### ISSUE TITLE
Where can I find information on what aXe actually tests?

### ISSUE THREAD

**Issue by jongund** [dequelabs/axe-core#1]

**Comment by felixzapata** [comment]
There is a little more of information inside the docs folder. But my opinion is that it is still incomplete.

**Comment by loginx** [comment]
I was wondering the same thing yesterday and then noticed the rules engine resides in another repository: https://github.com/dequelabs/axe-rules

I'm guessing the idea is to provide decoupling so that one could consume the ruleset in their own system without the need for the loader.

**Comment by felixzapata** [comment]
ok thanks. I ´ve made some tests this morning. It is strange because the results only shows that your code is not valid but I do not see the detail for each error.

Regards.

**Comment by dsturley** [comment]
I've added [rule descriptions](https://github.com/dequelabs/axe-core/blob/master/doc/rule-descriptions.md) to doc/.  You can also get the ruleID and description from the core itself by calling `axe.getRules()`.  We will be adding a more detailed API documentation soon. 

The examples we've included are pretty bare-bones at the moment, but we will be releasing more integrations and plugins in the very near future.  In the meantime, you may want to take a look at the [chrome extension](https://chrome.google.com/webstore/detail/axe/lhdoppojpmngadmnindnejefpokejbdd) to see all the information that is available.

**Comment by dsturley** [comment]
[API docs are now available](https://github.com/dequelabs/axe-core/blob/master/doc/API.md).  Please do not hesitate if you have any further questions.

**Comment by felixzapata** [comment]
ok, thanks. I will try to make a Gulp plugin
