### ISSUE TITLE
Broken links in doc pages

### ISSUE THREAD

**Issue by seanforyou23** [dequelabs/axe-core#1010]
Hello, when browsing the docs I tried to navigate to the links in the footer and noticed I receive a 404 for each of them. Could be a stumbling block for someone getting up to speed with aXe so figured I'd mention it.

- Link to live demo: `https://axe-core.org/docs/`

<pre><code>
axe-core version: `^3.0.3`
axe-webdriver, extension or other integration version: `^2.0.1`

Browser and Assistive Technology versions

For Tooling issues:
- Node version: `8.11.2`
- Platform:  `macOS`
</code></pre>

<img width="842" alt="screen shot 2018-07-16 at 6 30 49 pm" src="https://user-images.githubusercontent.com/5942899/42787046-b7a0ac2a-8926-11e8-9184-df37820c9868.png">

<img width="1106" alt="screen shot 2018-07-16 at 6 31 02 pm" src="https://user-images.githubusercontent.com/5942899/42787047-b7b31568-8926-11e8-985a-d0e239bb1895.png">

**Comment by marcysutton** [comment]
This issue would normally be better off in [axe-website](https://github.com/dequelabs/axe-website), except that entire site is being redirected to deque.com very shortly. So because we won't be making any changes, I'm going to close this issue. But thanks so much for the heads up!
