### ISSUE TITLE
Getting Error- Error: The message port closed before a response was received.

### ISSUE THREAD

**Issue by Ishrat1401** [dequelabs/axe-core#1012]
- Link to live demo:

<pre><code>
axe-core version: X.Y.Z
axe-webdriver, extension or other integration version: X.Y.Z

Browser and Assistive Technology versions

For Tooling issues:
- Node version: XX  
- Platform:  
</code></pre>i have opened axe in developer tool, but everytime after clicking on analyse i am getting the below error and i am not able to check the accessibility of my application.
Error: The message port closed before a response was received.

**Comment by jkodu** [comment]
Hi @Ishrat1401 ,

Can you confirm the version number of aXe you are running?

This has been resolved in version the latest version of [aXe](https://chrome.google.com/webstore/detail/axe/lhdoppojpmngadmnindnejefpokejbdd)

Could you try, closing the developer tools, refreshing the page you wish to inspect, and reloading aXe to analyse and see if the issue persists?

**Comment by Ishrat1401** [comment]
Hey 
Thanks it is working now.
