### ISSUE TITLE
Assess feasibility to swap check for `aria-dpub-role-fallback` to `aria-allowed-role`

### ISSUE THREAD

**Issue by jkodu** [dequelabs/axe-core#1033]
- see comments: https://github.com/dequelabs/axe-core/pull/945/files#r198097140
- to swap the underlying checks used by `aria-dpub-role-fallback` rule, from `implicit-role-fallback` to `aria-allowed-role rule`.
- aim to deprecate `implicit-role-fallback`

**Comment by jeankaplansky** [comment]
Included in 3.5 release notes doc

**Comment by padmavemulapati** [comment]
Verified with the latest axe-coconut, seeing the "aria-dpub-role-fallback" rules in deprecated tag and moved to "aria role"
![image](https://user-images.githubusercontent.com/47409579/69849754-8e06c900-12a3-11ea-8364-5e33e67795da.png)

![image](https://user-images.githubusercontent.com/47409579/69849790-abd42e00-12a3-11ea-9d90-fb2291a4a9dc.png)
