### ISSUE TITLE
Error: The message port closed before a response was received. on Google.com

### ISSUE THREAD

**Issue by dlowy** [dequelabs/axe-core#1042]
Axe will not work on google.com, just for testing I inspected google.com.  I get Error: The message port closed before a response was received AND Chrome on macOS hangs.

**Comment by marcysutton** [comment]
It works for me, can you try these few things:
- Close and open the devools, refresh the page
- Disable and reenable the axe Chrome extension in chrome://extensions

I suspect the latter will work, as it is a known issue that has already been fixed. Just needs to get shipped.

**Comment by jkodu** [comment]
@dlowy 
Please ensure you have the latest version of the extension, see notes from this ticket - https://github.com/dequelabs/axe-core/issues/940
