### ISSUE TITLE
TypeError: window.axe is undefined

### ISSUE THREAD

**Issue by okeul** [dequelabs/axe-core#1044]
Hi !

Testing a fork of [gulp-axe-webdriver](https://github.com/okeul/gulp-axe-webdriver/tree/browsers) (using axe-core & axe-webdriverjs) and stuck on this error : 
`TypeError: window.axe is undefined`

<img width="1035" alt="capture d ecran 2018-08-03 a 18 04 23" src="https://user-images.githubusercontent.com/6248074/43653875-bdf1aada-9749-11e8-97ca-ef89ee5c49d6.png">

The strange thing is that everything works with one or two test files. But with 30, 40 or 50 no. For the test I'm just duplicating the same file.

Do you have any idea ? thank you in advance.

**gulpfile.js**
```js
var gulp = require('gulp');
var axe = require('gulp-axe-webdriver');

gulp.task('axe', function() {
  var options = {
    browser: 'firefox',
    browserArguments: ['--headless'],
    scriptTimeout: 600000,
    tags: ['wcag2aaa', 'wcag2aa', 'wcag2a', 'best-practice'],
    urls: ['src/**/*.html'], 
    verbose: true,
  };
  return axe(options);  
});
```

**package.json**
```js
{
  "dependencies": {
    "axe-core": "^3.0.3",
    "axe-webdriverjs": "^2.0.1",
    "chromedriver": "^2.41.0",
    "geckodriver": "^1.12.0",
    "gulp": "^3.9.1",
    "gulp-axe-webdriver": "^3.0.0",
    "selenium-webdriver": "^4.0.0-alpha.1"
  }
}
```

**test.html**
```html
<!doctype html>
<html>
<head>
  <title>Test</title>
</head>
<body>
  <div id="broken" role="main">
    <h1>Foobar tittle</h1>
    <p>Not a label</p>
    <input type="text" id="no-label">
    <p>Not an alt</p>
    <img src="foobar.gif">
  </div>
</body>
</html>
```

**Infos**
- Node version: v6.9.1
- Platform:  Mac OS X El Capitan (10.11.6)
</code></pre>

**Comment by marcysutton** [comment]
Sounds specific to gulp-axe-webdriver, which we don't maintain ourselves. Can you open an issue against that repo for @felixzapata to take a look?
