### ISSUE TITLE
Add axe-core specific eslint rules

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#1052]
Couple of things we should have rules for:

- Don't use node.matches()
- Don't use node.tagName, use node.nodeName instead
- Always follow node.nodeName with a .toUpperCase()

Adding Axe specific ESLint rules will help avoid common mistakes.

**Comment by mohanraj-r** [comment]
Hi @WilcoFiers Is this related to the [eslint-plugin-axe - npm](https://www.npmjs.com/package/eslint-plugin-axe) plugin? Can you please describe the intended goal of the reserved npm package? 

I am wondering if axe rules can be expressed as an eslint plugin? Guess axe needs a DOM to run? Can we do static code analysis with axe?

**Comment by jkodu** [comment]
Hi @mohanraj-r 	

To clarify this issue is related to enhancing the eslint rules within axe-core & not related to the package you have referred above.

**Comment by mohanraj-r** [comment]
Thanks @jkodu, I had thought so too. Do you know that the npm package is for ?
