### ISSUE TITLE
td-has-header not working outside of axe-Coconut (in browsers)

### ISSUE THREAD

**Issue by kensgists** [dequelabs/axe-core#1056]
Using axe-coconut, the td-has-header rule flags three tables on this page, appropriately, as violations:

https://butterpep.com/table-semantics-examples.html 

Tables with violations are examples 2a, 2b, and 2c.

Running the regular, non-coconut version, of aXe in Chrome, no table violations are caught, yet both instances of aXe Chrome are running the same version of devtools (3.4.0-alpha 2) and axe-core (3.0.3)

**Comment by marcysutton** [comment]
`td-has-header` is still an experimental rule, and those are enabled in axe Coconut only. Refer to the rule tags to see this distinction. Closing as this is behaving as designed.

**Comment by kensgists** [comment]
Thanks Marcy. Is documented somewhere? I was unaware experimental rules didn't run in the standard browser aXe. 

FYI, I typically look at https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md when hunting down rules. And everything in that table says "Enabled by Default: true"

**Comment by marcysutton** [comment]
Yes, it's documented in a few places.
- Look for "experimental" in rule-descriptions.md and you'll see all experimental rules
- It's in this blog post https://www.deque.com/blog/test-leading-edge-accessibility-axe-coconut-axe-core-3-0/
- It's written in the axe Coconut browser extension description https://chrome.google.com/webstore/detail/axe-coconut/iobddmbdndbbbfjopjdgadphaoihpojp?hl=en
- It's on Deque University https://dequeuniversity.com/guide/
