### ISSUE TITLE
Using aXe Chrome extension with a screen reader

### ISSUE THREAD

**Issue by jamalmazrui** [dequelabs/axe-core#1063]
- Link to live demo:

<pre><code>
axe-core version: X.Y.Z
axe-webdriver, extension or other integration version: X.Y.Z

Browser and Assistive Technology versions

For Tooling issues:
- Node version: XX  
- Platform:  
</code></pre>I have tried the latest JAWS and NVDA with the latest Chrome browser.  The aXe extension was easily to install from the Chrome web store, but using it is difficult with a screen reader, and I have not found any documentation on such use.  

When I activate the extension, it takes me to a web page about aXe but does not run an analysis on the current browser page.  Navigating the developer tools panel via the keyboard and screen reader output has been challenging.  I have not yet found a straightforward and reliable way of making the aXe panel active.

Let me suggest that the extension be configured with a default hotkey that runs aXe against the current page and then puts focus at the top of the results.

Any keyboard or screen reader tips for using aXe would be appreciated.

**Comment by marcysutton** [comment]
Hi Jamal,

Thanks for your report! We are already working on an axe extension guide for screen reader use, so your message is timely. We've got one for our WorldSpace Attest extension but we hadn't yet created one for axe. Stay tuned for a new resource!
 
For some things our hands are tied with regards to the Chrome extensions interface and APIs. The web page you mentioned is a browser toolbar feature dynamically added by Chrome, and it can't kick off an analysis in DevTools for security reasons–it would likely the same issue with a "default hotkey". Navigating to the axe extension through Chrome DevTools is required to do an analysis.

Here's how I've gotten it to work with NVDA on Windows:

- Open the developer tools with `Control + Shift + i`
- Navigate through the DevTools extensions with `Control + }`. By default, axe should be the 10th one.
- Hit the ENTER key to activate the extension.
- TAB key to enter into the extension. The first tab stop is a version info button, and the second tab stop is the analysis button.

Let me know if you have any trouble with that. I didn't have to change modes or anything to get into axe with NVDA, but I did find a regression using the keyboard alone. NVDA seemed to work just fine.

**Comment by dpeschel** [comment]
Hi Marcy,

Thanks for the procedural steps. I work with Jamal and we have streamlined the Chrome procedure somewhat. This works with NVDA; I haven't tested JAWS yet. First change one of the developer tools settings:
- Press `F12` to open the developer tools.
- Press `F1` to open the developer tools preferences.
- Press `x` twice to get to the `Enable Ctrl + 1-9 shortcut to switch panels` checkbox and check it.
- If space or enter behave strangely when checking the checkbox, for example switching to the inspector panel, use `NVDA+numpad divide` followed by `numpad divide`, to simulate a mouse click on the checkbox.
Now to start the aXe analysis:
- Open the dev tools.
- Press `ctrl+9` followed by `ctrl+]` or instead `ctrl+1` followed by `ctrl+[`.
- Follow your steps for navigating within the panel.

We also tested Firefox 57. I turned off as many dev tools panels and toolbar buttons as I could, using the dev tools preferences. As a relaiable way to get to the aXe tab:
- Press `ctrl+shift+S` which opens the dev tools and selects the debugger tab.
- Press `ctrl+]` to move to the aXe tab.
- Press `b` until you get to the Analyze button. (This won't work with JAWS; it puts the focus on the group of dev tools tabs, while NVDA puts the focus inside the aXe panel.)

Even though Chrome and Firefox limit the capabilities of dev tools extensions, I wonder if there's a way to speed up any part of this process. Keyboard shortcuts for part of the process (like switching to the aXe tab or moving the focus to certain places inside the aXe tab) would help if possible. Checking item labels, and screen reader output in general, would also help.

Thanks again for your time.

**Comment by cyns** [comment]
Any updates or ETA on this documentation?

**Comment by marcysutton** [comment]
@cyns there is an NVDA and Firefox guide on the Deque website: https://www.deque.com/axe/documentation/

**Comment by jeankaplansky** [comment]
Note @marcysutton provided a link to relevant documentation on Jan 28, 2019
