### ISSUE TITLE
Update documentation for checks that are preload dependent

### ISSUE THREAD

**Issue by jkodu** [dequelabs/axe-core#1077]
Based on the thread of comments here - https://github.com/dequelabs/axe-core/pull/1000#discussion_r210572820

Agreement has been made that for checks that will involve preloading assets, it is still uncertain whether we should fail, or incomplete a check if preload has failed.

What to return will solely be dependent on the type of check being implemented. This mandates an improvement in documentation for authoring checks.

**Comment by straker** [comment]
Passing `undefined` as the assets if the preload fails and letting the check handle it is good enough.

**Comment by jeankaplansky** [comment]
axe-core docs, no release notes.
