### ISSUE TITLE
Link of repository still goes to old website

### ISSUE THREAD

**Issue by jancborchardt** [dequelabs/axe-core#1079]
This is not about the software (thanks a lot for it!) but only a minor thing in this repository. The link next to the description is still to the old site:
![screenshot from 2018-08-20 15-36-02](https://user-images.githubusercontent.com/925062/44343689-f060ff00-a48e-11e8-8f63-b4a14e2fa4a5.png)

Would be better to directly link ot https://www.deque.com/axe/ :)

**Comment by WilcoFiers** [comment]
Indeed, good point. We changed that last week.
