### ISSUE TITLE
New Rule: Link Color Contrast

### ISSUE THREAD

**Issue by dsturley** [dequelabs/axe-core#108]
Color alone MUST NOT be used to distinguish links from surrounding text unless the color contrast between the link and the surrounding text is at least 3:1 and an additional differentiation is provided when the link is hovered or receives focus.

WCAG 2 Level AA 1.4.1 Use of Color

Checking for additional differentiation on focus and hover might be problematic to get working in all supported browsers.

**Comment by WilcoFiers** [comment]
We have implemented this rule and will be making it available during the next major release of Axe-core.
