### ISSUE TITLE
Refactor: audit.run perhaps should not split rules to run

### ISSUE THREAD

**Issue by jkodu** [dequelabs/axe-core#1085]
- Currently with in `audit.run` rules are run in a before and after fashion, for those that are dependent on assets that need to be preloaded.

Solution:
- Pass a preload callback to each rule, to ascertain when each should run, after a given asset dependency is resolved.
- Enhance rule spec to not just a boolean, but also an array of assets, to allow for the rule to run as soon as the asset type is resolved.

**Comment by straker** [comment]
We may not need this any more with `axe._cache` so you can save things in between check runs.
