### ISSUE TITLE
devlop branch has a future version of enzyme-adapter-react-16

### ISSUE THREAD

**Issue by RashelleKosib** [dequelabs/axe-core#1090]
Hey,
when cloning your project, by default it takes me to devlop. When doing npm install it fails because of a versioning problem for enzyme-adapter-react-16 (^1.5.0 instead of ^1.1.0).
The version in the package.json for both branches is different. 
 

- Link to live demo:

<pre><code>
axe-core version: X.Y.Z
axe-webdriver, extension or other integration version: X.Y.Z

Browser and Assistive Technology versions

For Tooling issues:
- Node version: XX  
- Platform:  
</code></pre>

**Comment by WilcoFiers** [comment]
specifically, the jest example has this... I have no idea how that happened. Greenkeeper keeps those dependencies up to date. It seems like greenkeeper has installed a dependency that doesn't exist? :-/
