### ISSUE TITLE
axe-core 3.1.0 does not have main entry point `axe.js`

### ISSUE THREAD

**Issue by ttdmayshark** [dequelabs/axe-core#1104]
Some of our builds which leverage axe/axe-core started failing this morning with an error loading `axe-core`. This appears to be fallout of having moved from 3.0.3 to 3.1.0 once it was published.

- Link to live demo:
3.0.1: https://unpkg.com/axe-core@3.0.1/axe.js
3.1.0: https://unpkg.com/axe-core@3.1.0/axe.js
3.1.0 still uses `axe.js` as entry point in package.json: https://unpkg.com/axe-core@3.1.0/package.json

- Node version: 8.9.4
- Platform:  OSX & Linux

**Comment by calinoracation** [comment]
Ours is failing as well now, but on the missing `axe-core/axe.min.js` file.

**Comment by ljharb** [comment]
(Please note that removing any entry point is a breaking change)

**Comment by WilcoFiers** [comment]
Hey all. Apologies for the problematic release. We are working on a fix and will have it up available within a few hours.

**Comment by WilcoFiers** [comment]
Hey all. Quick update. Axe-core 3.1.1 just landed on NPM. We should be all set to move forward again.
