### ISSUE TITLE
Incompatibility in https://github.com/dequelabs/axe-core/commit/c40a1529c0bb4d1bd9cf65783af92af13dd06621

### ISSUE THREAD

**Issue by jeankaplansky** [dequelabs/axe-core#1114]
Note the incompatibility:
{
  "id": "**image-redundant-alt**",
  "selector": "button, [role=\"button\"], a[href], p, li, td, th",
  "tags": [
    "cat.text-alternatives",
    "best-practice"
  ],
  "metadata": {
    "description": "Ensure button and link text is not repeated as image alternative",
    "help": "Text of buttons and links should not be repeated in the image alternative"
  },
  "all": [],
  "any": [],
  "none": [
    "**duplicate-img-label**"
  ]
}

The name of the rule in axe rules is image-redundant-alt (and that's what the rule help is using as an ID).

**Comment by marcysutton** [comment]
I'm not sure I follow. The id here is referencing a rule, while the `none` entry is for the `duplicate-img-label` check. https://github.com/dequelabs/axe-core/blob/develop/lib/checks/label/duplicate-img-label.json

**Comment by jeankaplansky** [comment]
My bad... I misread the brackets.
