### ISSUE TITLE
Misleading documentation on axe.run options key `resultTypes`

### ISSUE THREAD

**Issue by kospl** [dequelabs/axe-core#1126]
Documentation link: https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#options-parameter

paragraph `6. Only process certain types of results`

It gives example and explanation of expected results:

> ```
> {
>   resultTypes: ['violations', 'incomplete', 'inapplicable']
> }
> ```
> 
> This example will process all of the "violations", "incomplete", and "inapplicable" result types. Since "passes" was not specified, it will only process the first pass for each rule, if one exists. **As a result, the results object's `passes` array will have a length of either `0` or `1`.** On a series of extremely large pages, this would improve performance considerably.

Misleading part is bolded:

> **As a result, the results object's `passes` array will have a length of either `0` or `1`.**

Unfortunately, when tested with given `resultTypes` option, aXe results object has `passes` array length equal to passed rules count, and not just limited to `0` or `1`. 

For example, `https://www.google.com/` with aXe option set to `resultTypes: ['violations', 'incomplete', 'inapplicable']` has `passes` array with length `28`.

**Comment by jkodu** [comment]
@kospl 

Thanks for reporting this. We will do some tests internally to ensure the same & come back to you with a fix or updates accordingly.

**Comment by jeankaplansky** [comment]
doc fix confirmed: "This example will return all the nodes for all rules that fall under the "violations", "incomplete", and "inapplicable" result types. Since the "passes" type was not specified, **it will return at most one node for each rule that passes.**"
