### ISSUE TITLE
TypeError: Cannot read property 'querySelectorAll' of undefined

### ISSUE THREAD

**Issue by stephenmathieson** [dequelabs/axe-core#1136]
Injecting `axe-core` and calling `axe.run()` on http://speedtest.att.com/speedtest/ produces an uncaught exception:

```
VM367:1 Uncaught (in promise) TypeError: Cannot read property 'querySelectorAll' of undefined
    at t (<anonymous>:1:62019)
    at Object.axe.utils.getSelectorData (<anonymous>:1:62440)
    at Object.x [as _runRules] (<anonymous>:1:35739)
    at Object.axe.run (<anonymous>:1:37950)
    at <anonymous>:1:5
```

This is an issue with 3.0.3 and 3.1.1 (and probably other versions, but I haven't tested them).

I have only just begun debugging this, and will update if/when I find any more information.

**Comment by stephenmathieson** [comment]
It's [this line](https://github.com/dequelabs/axe-core/blob/v3.0.3/lib/core/utils/get-selector.js#L81) which is throwing when `current` is the `<body>` element. Still not sure why, but will continue to investigate.

**Comment by stephenmathieson** [comment]
It appears that the `domTree` used in `axe.utils.getSelectorData` has elements with the wrong shape. On a "working" page (google.com, for example), the `domTree` resembles something like:

```js
[
  {
    shadowId: String | undefined,
    actualNode: HTMLElement,
    children: [
      {
        shadowId: String | undefined,
        actualNode: HTMLElement,
        children: [
          {
            shadowId: String | undefined,
            actualNode: HTMLElement,
            children: [
              ...
            ]
          },
          {
            shadowId: String | undefined,
            actualNode: HTMLElement,
            children: [
              ...
            ]
          },
          ...
        ]
      },
      ...
    ]
  }
]
```

However, on the "broken" page (listed above), the `domTree` resembles:

```js
[
  {
    shadowId: String | undefined,
    actualNode: HTMLElement,
    children: [
      HTMLElement, // <head>
      HTMLElement, // #text
      HTMLElement // <body>
    ]
  }
]
```

Because the `children` in the "broken" case do not have an `actualNode` property, we're unable to access `child.actualNode.querySelectorAll`, which causes the exception.

I am still unsure _why_ we're improperly generating the `domTree` here.

**Comment by stephenmathieson** [comment]
I've figured out why we're not building the `domTree` as expected. The page is overwriting `Array#reduce`, which prevents any usage of `Array#reduce` on our end from working properly.

To prove this, navigate to http://speedtest.att.com/speedtest/, open your DevTools console, and type `Array.prototype.reduce`.

In a "working" page, you'll see something like:

```
> Array.prototype.reduce
ƒ reduce() { [native code] }
```

However, on the page in question, you'll see:

```
> Array.prototype.reduce
ƒ () {
    return this.length > 1 ? this : this[0];
  }
```

I'm not sure how to continue here, since `axe-core` heavily relies on `Array#reduce`. Leaving this open for now.

**Comment by jkodu** [comment]
`Constructor.prototype.toString()` and checking for `[native code]` is not bulletproof.

Let's say I have a native override like below:
```
window.iamNative = {
  toString: () => '[native code]'
};
```

The above check would fail again. There are still 2 main things to solve for, to arrive at a fix.

1) Enumerate all the native methods, as against having a hand-written list of methods that needs to be checked for override.
2) A better way to compute if method is native and not overridden.

**Comment by stephenmathieson** [comment]
Sure, we could protect against that. But do we really need to? The idea here is just to provide more helpful error messages. If the user is making that intentionally difficult for us, they'll just not have "nice" error messages.

**Comment by stephenmathieson** [comment]
Alternatively, we could feature test the actual methods we need. For example:

```js
const hasArraySome = typeof [].some === 'function'
if (!hasArraySome) {
  throw new Error('axe-core requires Array#some')
}

const hasValidArraySome = [1,2,3].some((x,i) => x === i + 1)
if (!hasValidArraySome) {
  throw new Error('axe-core requires Array#some')
}
```

This however, requires us to write feature tests for every native method, and that does not sound fun.

**Comment by stephenmathieson** [comment]
Ended up writing a bunch of feature tests for this. See #1188.
