### ISSUE TITLE
AXE seems to fail a properly nested ordered list.

### ISSUE THREAD

**Issue by DavidMacDonald** [dequelabs/axe-core#1153]
```
<ol style="list-style-type: lower-alpha;">
    <li> a person is deemed by subsection 62 (1) of the Act to hold a certificate
    of qualification and registration, and </li>
    <li> such person has failed to:</li>
    <ol style="list-style-type: lower-roman;">
        <li> provide information to the Registrar which members are required by
        section 31 to provide </li>
        <li> pay the annual membership fee prescribed by the bylaws </li>
        <li> apply to the Registrar for the issuance of a certificate of qualification
        and registration in accordance with the regulations</li>
    </ol>
</ol>

```

https://www.oct.ca/about-the-college/what-we-do/legislation-regulations-and-bylaws/college-bylaws#9

Go to section
9.17 Pursuant to paragraph

**Comment by WilcoFiers** [comment]
Hey Dave. Lists aren't allowed to contain other lists directly. Your second `ol` is supposed to be a child of the second `li` element. This is the way it's [defined in HTML 5](https://www.w3.org/TR/html52/grouping-content.html#the-ol-element) and [in ARIA 1.1](https://www.w3.org/TR/wai-aria-1.1/#list). The only exception to that is that you're allowed to group `listitems` in ARIA.

The problem this creates is that the sublist is now treated as a third list item, where as the top list only really has two items. It confuses the hierarchy of the lists.

**Comment by WilcoFiers** [comment]
Closing the issue as no action seems necessary.
