### ISSUE TITLE
Discussion: Should we introduce the concept of a warning?

### ISSUE THREAD

**Issue by dylanb** [dequelabs/axe-core#116]
There are some situations where we are not able to correctly evaluate an element and we know we are not able to do this. The two scenarios that I know about are:

color contrast: when the background is not a flat CSS color (i.e. gradient or image) or the element is obscured by something (e.g. sticky headers)
iframes: the iframe does not have the axe library injected into it

In these situations, it would be nice to give the user some indication that things have been skipped/missed.

**Comment by preetykumar** [comment]
question is how do we give this warning without creating noise and give the user the handle to toggle on/off.

**Comment by dylanb** [comment]
It would be a separate structure that would only be used in a manual assessment tool. The problem is that any manual assessment tool will not know when elements are missed by the engine unless the engine tells them, or unless they duplicate the code in the engine.

**Comment by dsturley** [comment]
If they are not meant to be displayed then this already supported.  The `Check` could set something on `data` that the tool could then check for in `passes`.  Color contrast already does this with `contrastRatio`.

**Comment by dylanb** [comment]
@dsturley I don't think that quite meets the criterium that it not create noise because this means that we have to generate an issue for every node, just to send the information back that it could not be processed properly. We would have to put this into a separate structure in order to avoid noise/necessity to look into, and understand, this data being sent back.

**Comment by marcysutton** [comment]
I think we have this handled now with Incomplete/Needs Review.
