### ISSUE TITLE
Allow street-address autocomplete on text fields (PR #1217)

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#1161]
Even though the HTML 5 spec says street-address is a multiline control and shouldn't be on input[type=text] the spec also has a few examples that show it being used that way. This, plus the fact that street-address seems to be the only thing not allowed on text, suggests we should probably just allow it.

**Comment by jkodu** [comment]
@WilcoFiers 

Was this the fix you were thinking? - https://github.com/dequelabs/axe-core/commit/fc3e89869778ec2c3c7bf00d57f0ec92c5c6aa33#diff-c8be89ccd7cd8049ef39d04c207728cbR12

**Comment by WilcoFiers** [comment]
That should do, make sure you add tests :)

**Comment by jkodu** [comment]
PR merged. Closing issue.
