### ISSUE TITLE
Axe-core can return an invalid `selector` in some scenarios 

### ISSUE THREAD

**Issue by joelhsmith** [dequelabs/axe-core#1165]
On a valid html webpage using valid attributes, Axe-core returns an invalid item selector on Accessibility audits in the following scenario:

If two or more elements have:

1. identical selectors
2. identical attributes
3. one attribute's value (in this case content) is different.

__Example__
Example of two elements causing the problem from the example website linked below (note the content attributes are unique):

`
<span class="date-display-single" property="dc:date" datatype="xsd:dateTime" content="2018-09-26T15:30:00-04:00">Wednesday, September 26</span>
`

`
<span class="date-display-single" property="dc:date" datatype="xsd:dateTime" content="2018-10-01T11:30:00-04:00">Monday, October 1</span>
`

__Link to live demo__:
https://joelhsmith.github.io/debug-examples/date-selector-issue/date-selector-issue.html

Original Issue was reported to Lighthouse Issue Queue, but belongs here. https://github.com/GoogleChrome/lighthouse/issues/6115#issuecomment-424833246

I _speculate_ that Axe tries to return a unique-ish selector by latching onto the one attribute that has a unique value, the content attribute. Then returns it using a pseudo selector, but might be getting processed in Lighthouse

`span[content=\"\\32 018-09-26T15\\:30\\:00-04\\:00\"]`

It looks like it is getting encoded in some unusual way.  Note it turns "2018" to "\\32 018".

__Expected behavior__
_I think_ the expected behavior would be for it to not be encoded, but if it was intended to get escaped, it should be something valid that we can decode from.

__Edge case?__
Those unusual [DC](http://dublincore.org/documents/dcq-html/) attributes are often used on dates. Almost every Drupal website's date element has these attributes. So every list of events on the website will return a pile of invalid selectors. I suspect other CMS platforms also use these attributes, or it could also effect other attributes

- axe-core version: 3.0.0-beta.2
- running through Chrome Lighthouse: 3.0.3 but tested in Axe-core cli also.
- node: 8.9.1
- os: Mac OS 10.12.6

**Comment by WilcoFiers** [comment]
Thanks for reporting. Are you interested in working on a fix for this? If not I'll see what I can figure out.

**Comment by joelhsmith** [comment]
Its way out of my league as a dev :-) But I would, if I could.

**Comment by joelhsmith** [comment]
That helps a lot.  Thanks @jkodu for looking into this so thoroughly. That was super informative.

Exactly said, when I use the selector in question (that is shown in the Chrome aXe extension under “Element location”) it returns:

`span[content="\32 018-09-26T15\:30\:00-04\:00”]`

That works in both FF and Chrome as a selector.

But when I run Chrome Lighthouse and look at the “selector” attribute it returns in the [json format](https://gist.github.com/joelhsmith/e000462ec4cb3ba323447a81771aa76e#file-joelhsmith-github-io-20181010t093804-json-L114) it something different after processing in Lighthouse:

`span[content=\"\\32 018-09-26T15\\:30\\:00-04\\:00\”]` (note the extra `\`s)

Which does not work in both FF and Chrome as a selector.

Would you concur that this is not an aXe issue, and should go back downstream to the Lighthouse Issue queue?  As a bug? And we should close it here?

**Comment by marcysutton** [comment]
Sounds like a Lighthouse issue to me, especially if you can't repro it in axe-core or the axe extension.

**Comment by joelhsmith** [comment]
Sounds good.
