### ISSUE TITLE
postinstall script should not run for users of axe-core

### ISSUE THREAD

**Issue by thibaudcolas** [dequelabs/axe-core#1169]
At the moment, installing `axe-core` in a project runs its `postinstall` script:

```
# 13:13:36:playground/axe-test via ⬢ v8.6.0
$ npm install --save axe-core@latest

> axe-core@3.1.2 postinstall [...]/node_modules/axe-core
> node build/utils/postinstall.js

+ axe-core@3.1.2
added 1 package in 2.466s
```

This postinstall script seems to only be intended for development of `axe-core`, not users of the package, so it shouldn't run in those circumstances.

I would suggest switching to the [`prepare`](https://docs.npmjs.com/misc/scripts) script, which runs in local installs only:

> prepare: Run both BEFORE the package is packed and published, and on local npm install without any arguments (See below). This is run AFTER prepublish, but BEFORE prepublishOnly.

<pre><code>
axe-core version: 3.1.2

For Tooling issues:
- Node version: 8.6.0, 10.7.0
- Platform:  macOS 10.13
</code></pre>

**Comment by WilcoFiers** [comment]
Thanks for the suggestions. That's a good idea.

**Comment by marcysutton** [comment]
`prepare` didn't exist when that script was written, so I'm glad there is a suitable replacement now!
