### ISSUE TITLE
Discussion: Self inject into same domain iframes

### ISSUE THREAD

**Issue by dylanb** [dequelabs/axe-core#117]
If we have same domain iframes, we could simplify the use of the library by self-injecting into these iframes if the library is not present.

Pros: easier to use
Cons: would not be able to "easily" exclude iframes by choosing not to inject into them

**Comment by WilcoFiers** [comment]
I don't think there's a need for this. Axe-core behaves more consistently if it is required to be injected into every frame, rather than have it be required in some but not in others.
