### ISSUE TITLE
Browser extension: usability suggestions for screen reader users

### ISSUE THREAD

**Issue by Neurrone** [dequelabs/axe-core#1173]
Some usability suggestions for the extension:

* Besides the next/previous issue buttons that allow you to go to the next/previous occurance of the currently selected issue, there should be another set of buttons that let you go to the previous/next different issue. I suggest renaming the current buttons to next/previous occurance, and repurpose next/previous issue to do what I describe. Its pretty annoying to have to arrow through the list of different issues to find the one after your current one.
* When the filter options dialog is open, it does not prevent focus from moving outside it. I was trying to switch issues with the filter options expanded, and was confused as to why it wouldn't work, until I closed it.

**Comment by WilcoFiers** [comment]
We are exploring solutions to this. There is an issue open in the extension repo (not public). Closing this one.
