### ISSUE TITLE
axe chrome extension won't install

### ISSUE THREAD

**Issue by lifeiscontent** [dequelabs/axe-core#1180]
Hi, I'm using the latest stable chrome and trying to install axe, but I keep getting an error about an icon missing. Is this the right repo to be posting about this extension?

**Comment by WilcoFiers** [comment]
Thanks for reporting. We're working on a fix. This should be resolved within the next few hours.

**Comment by WilcoFiers** [comment]
A fix has been published. Thank you for your patience.
