### ISSUE TITLE
aXe chrome extension: highlight not working

### ISSUE THREAD

**Issue by chrisdemars** [dequelabs/axe-core#1190]
As I was trying to highlight the element in the chrome extension, nothing happens. Same with the aXe Coconut extension.

**Comment by robcorto** [comment]
Same issue for me using the Chrome extension. It works fine with Firefox extension.

**Comment by WilcoFiers** [comment]
We've worked out a fix, an update has been sent to QA today. We'll try to get it out some time early next week.

**Comment by marcysutton** [comment]
This should be fixed with the latest extension update (3.6.0). Please let us know if it persists!
