### ISSUE TITLE
Confusing wording for 'none' in api.md

### ISSUE THREAD

**Issue by ghost** [dequelabs/axe-core#1198]
In the API docs, the description for 'none' should perhaps instead say that any passing checks will lead to a failure. The current wording is a bit confusing, as it implies that if none of the checks pass, a violation will be generated.

> This is a list of the checks that, if none "pass", will generate a violation.

https://github.com/dequelabs/axe-core/blob/develop/doc/API.md

**Comment by karansin-ms** [comment]
This is also true of "any": 

> any - array(optional, default []). This is the list of checks that must all "pass" or else there is a violation.

**Comment by WilcoFiers** [comment]
That's a fair point. Thank you for reporting. Would you be willing to propose a pull request to resolve the issue?

**Comment by RussellJQA** [comment]
I saw the same thing in the "Parameters -> rules" section of https://github.com/dequelabs/axe-core/blob/master/doc/API.md#api-name-axeconfigure, and so just submitted a proposed pull request to resolve the issue.

Sorry for some of the extra steps shown above. (This was my first pull request anywhere,)

**Comment by straker** [comment]
Closed by #1262
