### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by patrickhulce** [dequelabs/axe-core#1203]
### Link to problem page: http://silvertipgold.ca/

Lots of problems with axe on this page, but running just `color-contrast` has axe never completing (it runs for several minutes before crashing on my machine) and two errors being spammed to the console. Originally discovered in https://github.com/GoogleChrome/lighthouse/issues/6272

### TypeError: Cannot read property 'length' of undefined

https://github.com/dequelabs/axe-core/blob/320e63380189f507a32c99fd19619f3c6a161764/lib/core/utils/merge-results.js#L109

<details>
<summary>Stack Trace</summary>

```
axe.js:3096 Uncaught TypeError: Cannot read property 'length' of undefined
    at axe.js:3096
    at Array.forEach (<anonymous>)
    at axe.js:3088
    at Array.forEach (<anonymous>)
    at Object.mergeResults (axe.js:3083)
    at axe.js:1662
    at axe.js:3716
    at axe.js:1651
    at axe.js:1624
    at axe.js:3902
```
</details>

### Error: Expect axe._selectorData to be set up
https://github.com/dequelabs/axe-core/blob/9f9b15be23ebc330ff2feb8bd06b5964237d0feb/lib/core/utils/get-selector.js#L334-L336

<details>
<summary>Stack Trace</summary>

```
axe.js:2840 Uncaught Error: Expect axe._selectorData to be set up
    at generateSelector (axe.js:2840)
    at Object.createUniqueSelector [as getSelector] (axe.js:2896)
    at axe.js:1654
    at axe.js:1624
    at axe.js:3902
```
</details>

### Environment Details

<pre><code>
axe-core version: 3.0.2
axe-webdriver, extension or other integration version: N/A

Chrome 69.0.3497.100
Mac 10.12.6
</code></pre>

**Comment by WilcoFiers** [comment]
Thanks for reporting the issue. I'm not entirely sure what it might be... this looks like it is going to need a deep dive.

**Comment by straker** [comment]
Latest versions of Lighthouse (v4.0.0), axe (v3.2.2), and the axe extension (v3.1.2) don't seem to be throwing the errors anymore for that page.

**Comment by straker** [comment]
Please reopen the issue if this is still a problem.
