### ISSUE TITLE
False Positive: Angular skiplink using routerLink & fragment

### ISSUE THREAD

**Issue by MrGrigri** [dequelabs/axe-core#1204]
When utilizing the Angular router module as a skip-link, the Axe browser extension for Chrome creates a false positive claiming: "All page content must be contained by landmarks". I believe this might be an issue due to the fact that there is no `href` attribute on the link itself. There are a couple of Angular directives (routerLink and fragment) as well as a click event binding that controls what happens when the user clicks or interacts with the link. 

- Link to live demo: https://angular-4opnbd.stackblitz.io

<pre><code>
axe extension version: 3.5.2
axe extension on: Chrome (69)

Browser and Assistive Technology versions

For Tooling issues:
- Node version: 8.11.1
- Platform:  Windows (10/1709)
</code></pre>

**Comment by marcysutton** [comment]
@MrGrigri the example won't load for me, can you check to make sure your demo works without authenticating on stackblitz?

**Comment by MrGrigri** [comment]
Yeah, I opened it in an 'incognito' window in chrome and it works fine.

**Comment by MrGrigri** [comment]
My guess is your local network is blocking it.

**Comment by marcysutton** [comment]
It was something weird with Chrome–I can get it to load in Firefox.

The link does render an href, but I think it's being thrown off by the clientside routing. If you remove the `/` from `/#main-content` in the skip link href, it passes. Sounds related to the fix that was added in #824, except this is the other way around (routing for skip links, which was excluded). Any thoughts on this @WilcoFiers? Seems like we can't really have it both ways...?

**Comment by MrGrigri** [comment]
Yeah, Angular adds the `href` attribute...there's no way of changing that (as far as I know)

**Comment by marcysutton** [comment]
It wouldn't be a focusable skip link without the href, so that part seems necessary.

**Comment by WilcoFiers** [comment]
Any update on this? Can you maybe provide a codepen that we could use instead @MrGrigri?

**Comment by jkodu** [comment]
I was able to get the example running.

Based on inspecting the DOM, it is clear that the skip link perhaps needs a landmark region (just as axe reports).

![image](https://user-images.githubusercontent.com/20978252/47914480-c4eb8f00-de97-11e8-9448-1b68778529d9.png)

![image](https://user-images.githubusercontent.com/20978252/47914619-2ad81680-de98-11e8-86ba-a0616ee3631a.png)


@MrGrigri 
Could you try surrounding the `a` with `nav` or specifying a `role=navigation` on the parent div of the anchor?

**Comment by MrGrigri** [comment]
That div is only there to push the rest of the content down. That `a` element is the top-level element. [Here](https://stackblitz.com/edit/angular-4opnbd) is the link to the code. It's all in angular.

**Comment by WilcoFiers** [comment]
After some research, I think I've figured it out. What's happening is that the skip to content link is has a `/` at the beginning of the href: `/#main-content` instead of `#main-content`. Axe isn't expecting you to use the `/` first.

This is a false positive, clearly this is a skiplink and axe is misidentifying it. We'll have to fix it. Thank you for reporting!

**Comment by MrGrigri** [comment]
Thanks for y'all's help.
