### ISSUE TITLE
aXe Coconut issue for rule: Elements must have sufficient color contrast

### ISSUE THREAD

**Issue by spatel111** [dequelabs/axe-core#1206]
I m not able to locate the section when I click Highlight button.

**Comment by marcysutton** [comment]
@spatel111 we need more details to debug your issue. Is it just about the highlighter being broken, or is this actually related to the color contrast rule? There is already an issue open for the highlighter: #1190

**Comment by marcysutton** [comment]
I'm going to close this issue for inactivity, but you're welcome to reply with more details and we can reopen it.
