### ISSUE TITLE
Discussion: Tools changes

### ISSUE THREAD

**Issue by dylanb** [dequelabs/axe-core#121]
Tools concept is under flux. This issue is to discuss the diverse requirements and arrive at some specific changes that will result in additional issues

The tools are supposed to help with manual testing. There are the following list of needs:

1) Perform a specific action on a specific node, that is directed by the caller. Two examples are: "highlight" an element, and "pick" an element. In this mode, the target/return value is a JSON object with data about the object and a selector array identifying the address of the element in the document and child iframes. Lets call this "act";
2) Perform an action on a selector (that may evaluate to zero, one or multiple elements in each iframe). An example of this is to highlight the information for a particular class of elements (e.g. showing the headers). The target is a set of selectors and a set of attributes to display. The return value is (potentially) a serialized representation of the matching nodes. The selector would be executed in each frame identically. The return values would contain arrays of addresses. This is similar in concept to the way that a11yCheck runs, except we are passing back slightly different data. Lets call this "find";

These two operations may be performed in series to achieve the results desired by the caller. For example:

1) Perform a find with the selector of "table" to return a list of all the tables in the page;
2) Perform an act to select all the table header associations and other table data; and
3) Perform an act to highlight specific elements that have missing or non-conforming data

The current `runTool` in `master` is partially designed to be an "act", the `runTool` in the `exp` branch is designed to be more of a "find".

Thoughts?

**Comment by dsturley** [comment]
Internal.
