### ISSUE TITLE
Explain JDK, JRE?

### ISSUE THREAD

**Issue by riyabhat** [dequelabs/axe-core#1212]
[Java Development Kit](http://exltech.in/java-training.html):
1.Java  stands for Java Development Kit.
2.It is the tool  use  to to compile, document and package Java programs.

[Java Runtime Environment](http://exltech.in/).
1.It stands for Java Runtime Environment.
2.JRE refers to a runtime environment in which java bytecode can be executed.

Visit Us:
[http://exltech.in/java-training.html
](http://exltech.in/java-training.html
)

**Comment by jkodu** [comment]
Unrelated to axe-core issue. Closing.
