### ISSUE TITLE
broken link - selenium using javascript

### ISSUE THREAD

**Issue by trabulmonkee** [dequelabs/axe-core#1215]
inside of the api documentation here: https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#section-3-example-reference the selenium using javascript link goes to a 404 page.  Looking at the examples repo here: https://github.com/dequelabs/axe-core/tree/develop/doc/examples selenium using javascript is missing.

**Comment by trabulmonkee** [comment]
As in correcting the link path?  Sure, does someone have the original source of the examples for selenium or do examples need to be made and then the link updated?

**Comment by marcysutton** [comment]
I believe we removed that example in favor of axe-webdriverjs. The link for that repo is https://github.com/dequelabs/axe-webdriverjs

**Comment by trabulmonkee** [comment]
See PR: https://github.com/dequelabs/axe-core/pull/1242

**Comment by straker** [comment]
Closed by #1242
