### ISSUE TITLE
Downgrade impact of autocomplete rule

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#1218]
I've heard some concerns about giving the autocomplete rule an impact of "serious". Instead, I propose we downgrade it to moderate until we've seen wider adoption of autocomplete as a way to personalise forms.

**Comment by jkodu** [comment]
+1 for `moderate`.

**Comment by dylanb** [comment]
This is not the way we make decisions about impact. We make decisions about impact based on the effect of the issue on a person with a disability that is impacted by the issue.

This violation affects a person with a cognitive disability, making it difficult to fill out a form. If the form is a critical business form, then this affects critical business functionality.

Is the impact critical, serious, moderate or minor? Please make an argument.
