### ISSUE TITLE
Revisit `<object>` rule

### ISSUE THREAD

**Issue by dylanb** [dequelabs/axe-core#124]
The `<object>` tag is complex and we need to look at all the different uses to see whether there are false positives that we need to eliminate. See https://github.com/dequelabs/axe-firefox-devtools/issues/24

**Comment by WilcoFiers** [comment]
We've updated the rules for the object element. This will now be permitted to also have aria-label / aria-labelledby or a non-empty title.

**Comment by jkossis** [comment]
@WilcoFiers I am on the latest (4.2.0), and I am still getting the following error, even with `aria-label` being included on the `<object>` tag:

"Fix all of the following: ARIA attribute cannot be used: aria-label"

**Comment by dylanb** [comment]
@jkossis can you provide a codepen example?
