### ISSUE TITLE
Firefox tests skipped on CircleCI

### ISSUE THREAD

**Issue by marcysutton** [dequelabs/axe-core#1246]
The geckodriver executable is missing on Circle, and so the tests are therefore skipped. We need to fix this.

Why this is a problem? There's a failing test in Firefox that we haven't caught as a result of the tests being skipped in that browser: `aria-allowed-role` should `return true when MENU has type context`, but it's returning `undefined`. https://github.com/dequelabs/axe-core/blob/develop/test/checks/aria/aria-allowed-role.js#L150

**Comment by jkodu** [comment]
Upon investigation, found that Firefox has a default user-agent style of `display: none` to `menu` element. Where as Chrome, Safari and Opera have `display: block`.

This causes the test to fail, as `dom.isVisible` computation within the check returns conflicting values between browsers.

![image](https://user-images.githubusercontent.com/20978252/48761578-df4ba800-eca0-11e8-8241-17c1a71adb91.png)

![image](https://user-images.githubusercontent.com/20978252/48761594-ed99c400-eca0-11e8-9a62-f43f45db887a.png)

Enforcing a `display: block` in the test case is not ideal. 😒

**Comment by jkodu** [comment]
Upon further investigation, support for `menu` and `contextmenu` is experimental and it looks like Firefox has got it right over other browsers.

See - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu#Browser_compatibility

Best case scenario, is to remove this this case, which I have done in this PR - https://github.com/dequelabs/axe-core/pull/1249
