### ISSUE TITLE
False Positive: Ensures DT and DD elements are contained by a DL

### ISSUE THREAD

**Issue by sethkane** [dequelabs/axe-core#1265]
Expectation: 
According to WHATWG wrapping child elements of a DL should be allowed without errors. 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl#Wrapping_name-value_groups_in_%3Cdiv%3E_elements

Actual: 
When using a DL list and all of the necessary child elements axe chrome extension is throwing an error if you wrap the DT and DD with a DIV for styling purposes.  The error that it reports "Ensures DT and DD  elements are contained by a DL Impact: serious"

Motivation: 
The W3C validator and WHATWG allow for wrapping child elements of a DL with a DIV acceptable.

Code Tested: 
`<dl><div><dt>Name</dt><dd>Godzilla</dd></div><div><dt>Born</dt>  <dd>1952</dd></div><div><dt>Birthplace</dt><dd>Japan</dd></div><div>  <dt>Color</dt>  <dd>Green</dd></div></dl>`

<pre><code>axe-devtools 3.6.0
axe-core 3.1.1

Browser and Assistive Technology versions

For Tooling issues:
axe chrome extension
</code></pre>

**Comment by nicklemmon** [comment]
I ran in to the same issue! Thanks for filing this. Hoping for a fix at some point.
