### ISSUE TITLE
axe-corejs vs axe-core chrome extension, massively different results?

### ISSUE THREAD

**Issue by karl0ss** [dequelabs/axe-core#1275]
I wonder if someone could tell me why, using the axe-core chrome extension, and using axe-corejs module, with the default rules, would produce different results? with the chrome extension finding violations and the js module not finding any violations on the page built with webpack?

My module implementation seems to be working though, and is also using chrome as the browser, if I point them both at www.google.com, they both report the same violations..

**Comment by marcysutton** [comment]
@karl0ss how are you running axe-core against google.com? The script has to be injected into the browser to pick it up as a context.

**Comment by karl0ss** [comment]
I am using webdriveio, and have implemented a step, like i said, i know its working, as it works fine with google.com in both the module and the extension, but when i point at our webpack app, they give different results

**Comment by marcysutton** [comment]
That could happen for any number of reasons: viewport size, scripts loading differently, etc. Can you give us more detail on what the differences are? This isn't enough detail for us to take action.

**Comment by WilcoFiers** [comment]
Closing due to lack of a response. Feel free to raise a new issue if you are able to provide further details.

**Comment by Vanals** [comment]
Any news on this? In my team, we are finding it necessary to use the Chrome extensions to find issues rather than the axe-core package. Are they supposed to be equally good or... not?

**Comment by straker** [comment]
@Vanals The defaults for the Chrome extension and axe-core or the apis are different so you will likely get different results depending on settings. See https://github.com/dequelabs/axe-core/issues/3984#issuecomment-1505469280 for a more detailed answer.

That said, may I ask why you find it necessary to use the extension over axe-core?

**Comment by Vanals** [comment]
> @Vanals The defaults for the Chrome extension and axe-core or the apis are different so you will likely get different results depending on settings. See [#3984 (comment)](https://github.com/dequelabs/axe-core/issues/3984#issuecomment-1505469280) for a more detailed answer.
> 
> That said, may I ask why you find it necessary to use the extension over axe-core?

Because we can automate it in our flow, we can add id in a CI/CD pipeline and remove the need for human intervention for checking errors.
Let me know if I am missing something.
If they would be equally good we would not need to use the extension ourselves every time we make changes but we could automate the check.

**Comment by straker** [comment]
@Vanals What issues are found depends a lot on what you're using. For example, if you run axe-core on a webpage that has iframes, it will not run in those iframes (thus not find any issues). You'd have to inject axe-core into the main page and every iframe in order for axe-core to find issues in them. However, the axe-core apis and extension both run in iframes by default, so those will detect issues there.

Iframes aside, axe-core should find the exact same issues as the apis, and should find the same issues as the extension so long as both are configured the same.
