### ISSUE TITLE
invalid "int" attribute values not picked up (aria-posinset, aria-level, aria-colindex, aria-colspan, and aria-rowindex)

### ISSUE THREAD

**Issue by schne324** [dequelabs/axe-core#1288]
Expectation: axe raises issue for attribute values less than 1 for the following attributes:

- aria-posinset
- aria-level
- aria-colindex
- aria-colspan
- aria-rowindex

Actual: no issues are raised for the above attributes whose values are less than 1

Motivation: came across `<div role="heading" aria-level="0" />`

*test page*: https://xzoqr636po.codesandbox.io/
*spec*: for each of the above attributes the spec states:
> The value for {attr name} is an integer greater than or equal to 1.

*related files*:
- https://github.com/dequelabs/axe-core/blob/89d18d08ed72ba944dfce71c72d5887f4ca26cc1/lib/commons/aria/validate-attr-value.js
- https://github.com/dequelabs/axe-core/blob/51a18a8048a3edd3312400ce8495a6047fcaaa8d/lib/commons/aria/index.js

<pre><code>
axe-core version: 3.1.1
axe-webdriver, extension or other integration version: 3.6.0
</code></pre>

**Comment by schne324** [comment]
I am happy to implement this if this is something everyone agrees should be added 😄

**Comment by WilcoFiers** [comment]
I think this is a good idea. Feel free to create a PR.

**Comment by padmavemulapati** [comment]
Verified with the latest axe-core develop branch code:
validated for valid and invalid minValue for the following aria-attributes:

aria-posinset - minValue set as "1" , validated for 0,1
aria-posinset="0"
![image](https://user-images.githubusercontent.com/47409579/103662520-102ceb00-4f96-11eb-9f44-46fe420495a5.png)
aria-posinset="1"
![image](https://user-images.githubusercontent.com/47409579/103662627-2dfa5000-4f96-11eb-84ec-4f8f6845aa87.png)

aria-level - minValue set as "1" , validated for 0,1
Pass criteria:(aria-level="1"
![image](https://user-images.githubusercontent.com/47409579/103661564-e0311800-4f94-11eb-98ff-3b8aaad18877.png)
Fail criteria:(aria-level="0")
![image](https://user-images.githubusercontent.com/47409579/103662151-9b59b100-4f95-11eb-90d7-2f2696ecd485.png)
When aria-level=-1
![image](https://user-images.githubusercontent.com/47409579/103662233-b4626200-4f95-11eb-9b7c-c40da39c72bd.png)
