### ISSUE TITLE
New rule: Avoid inline spacing

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#1301]
This is a rule for https://www.w3.org/TR/WCAG21/#text-spacing. Fail any element with a style attribute that sets line-height, letter-spacing or word-spacing using `!important`. Since this is the highest priority, custom stylesheets can't override these styles, meaning that SC1.4.12 fails.

TODO: Write up a proper proposal.

**Comment by jkodu** [comment]
# avoid-inline-spacing

The rule should fail any element with a style attribute that sets `line-height`, `letter-spacing` or `word-spacing` using `!important`.

**Tags:** wcag21, wcag1412

## Matcher

Element(s) to be tested is deciphered at run-time based on CSSOM and or styles applied.

## Checks

Check that no `!important` style overrides are specified for `line-height`, `letter-spacing` or `word-spacing` properties.

**Pass**
If there are no `!important` styles applied for `line-height`, `letter-spacing` or `word-spacing`.

**Fail**
If there are `!important` styles applied for `line-height`, `letter-spacing` or `word-spacing`.

**Needs Review**
??

**Comment by jeankaplansky** [comment]
documented in INR - 6/17/2019

**Comment by jeankaplansky** [comment]
https://dequeuniversity.com/rules/axe/3.3/avoid-inline-spacing

**Comment by jeankaplansky** [comment]
DQU and Other resources added for MVP.

**Comment by chandana7393** [comment]
Tested, only in Axe extension able to see the violations related to inline spacing but in Attest and Axe-coconut unable to see the violations related to the inline spacing rule.
![no_violations_inline_Attest](https://user-images.githubusercontent.com/45285854/62291429-911eb380-b481-11e9-9a4b-fba59a66eb0d.PNG)
![no_violations_inline_axe_coconut](https://user-images.githubusercontent.com/45285854/62291434-92e87700-b481-11e9-94cb-52e60f838e97.PNG)
**Tested Environment:**
Attest - 2.5.1.21115v
Axe - 3.8.1.21115v
Axe-coconut - 3.8.1.21304v
Chrome - 76.0.3809.87v
Firefox - 68.0.1v
OS - Windows 10 64 bit.

**Comment by jeankaplansky** [comment]
Closing - See #1698.
