### ISSUE TITLE
Consider adding WCAG tags with dots "wcag4.1.2" instead of "wcag412"

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#1309]
Add duplicate labels that have dots as separators to ensure that this is a non-breaking change

**Comment by straker** [comment]
A simple but tedious change. Just need to go through each [rule metadata file](https://github.com/dequelabs/axe-core/tree/develop/lib/rules) and add a matching WCAG tag with dot separated numbers to each rule's [`tag` array](https://github.com/dequelabs/axe-core/blob/develop/lib/rules/area-alt.json#L7-L8).

**Comment by jkodu** [comment]
PR merged. Closing issue.

**Comment by WilcoFiers** [comment]
Closing this issue. This is unlikely to ever be necessary. The most likely SC where this could become ambiguous is if a 2.11.1 and a 2.1.11 ever get released. This is unlikely, as Principle 2 only has 5 guidelines (we would nave to get 6 new guidelines) and guideline 2.1 only has 4 success criterion. We'd need 6 new guidelines on 2.1, and 7 new success criteria on 2.1 for this to become an issue. Since there is already talk of WCAG 3.0, this is unlikely to be an issue for WCAG 2.
