### ISSUE TITLE
Expose the element that is tested when a rule throws

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#1317]
When an error occurs while running a rule, axe-core catches that error and puts it in incomplete. What it doesn't do is expose which element it was testing when that error happened. Exposing this will help with debugging.

**Comment by stephenmathieson** [comment]
Taking a look at this. Seems like all we'll need to do is add `.node` [here](https://github.com/dequelabs/axe-core/blob/v3.1.2/lib/core/base/audit.js#L407-L408).
