### ISSUE TITLE
[Feature Request] Export Accessibility issues

### ISSUE THREAD

**Issue by pdgo** [dequelabs/axe-core#1336]
It would be nice if there were a way to export the results of a test to a nicely formatted file like a PDF or Word Document or such, maybe there is a way and I'm just missing it?

**Comment by WilcoFiers** [comment]
@pdgo Thank you for posting. Axe does not come with advanced reporting capabilities. It is intended to be used during development, and issues are expected to be resolved before they ever make it into the end product.

If you are looking for remediation / reporting capabilities, these are included in WorldSpace Attest, which is axe-core's commercial big brother. WorldSpace Attest is one of the reasons we are able to give away axe-core for free. You can learn more about it: https://www.deque.com/tools/worldspace-attest/
