### ISSUE TITLE
False positive: label rule fails for input having explicit label with role presentation

### ISSUE THREAD

**Issue by iamrafan** [dequelabs/axe-core#1337]
- Link to live demo: https://codepen.io/iamrafan/pen/GzqOZp

-  AT test results:

  | AT/Browser | Announced as
-- | -- | --
1 | Edge/Narrator | Name-case-1   editing
2 | Edge/JAWS | Name-case-1 Edit
3 | Edge/NVDA | Name-case-1  edit
4 | Chrome/NVDA | Name-case-1  edit
5 | Chrome/JAWS | Name-case-1  edit
6 | IE/JAWS | Name-case-1  edit
7 | IE/NVDA | Name-case-1  edit
8 | Firefox/NVDA | edit  has auto complete

<pre><code>axe-core version: 3.1.2
axe-Coconut version: 3.7.0</code></pre>

**Comment by WilcoFiers** [comment]
Hey Guru. Right you are. This looks like a problem in the accessible name computation. Fortunately, I already have a fix in a PR for this! Thank you for reporting.
