### ISSUE TITLE
Minor typo in docs

### ISSUE THREAD

**Issue by isner** [dequelabs/axe-core#134]
In `axe-core/doc/API.md`

![axe-docs](https://cloud.githubusercontent.com/assets/5174819/10222193/b591e2f2-6820-11e5-9737-62bd7ba0525a.PNG)

References to `ruleId1` and `ruleId2` in the final paragraph are misleading because those keys don't exists in the example.

**Comment by dylanb** [comment]
@isner do you want to submit a PR?

**Comment by WilcoFiers** [comment]
We have this issue fixed in the next major release.
