### ISSUE TITLE
Add role matches methods

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#1349]
In axe-core we do a lot of role matching. Instead of writing that code over and over, we should add this role matching capability to `axe.commons.matches()`.

I think there are three variations:

- `matches(node, { semanticRole: 'listitem' })`
- `matches(node, { explicitRole: ['presentation', 'none'] })`
- `matches(node, { implicitRole: 'img' })`

The semantic role is the default of `aria.getRole(node)`, the explicitRole is `aria.getRole(node, { noImplicit: true })`, and implicitRole is `aria.implicitRole(node)`.

The reason for calling it `semanticRole` rather than `role` is to avoid confusion with the `role` attribute.

**Comment by padmavemulapati** [comment]
devTask
