### ISSUE TITLE
axe-core vs chrome extension (color-contrast)

### ISSUE THREAD

**Issue by gaddes** [dequelabs/axe-core#1355]
**Expectation**: axe-core (injected into Cypress through cypress-axe) should report the same number of color-contrast issues as the aXe Chrome extension.

**Actual**: aXe Chrome extension picks up five color-contrast issues, axe-core only reports two.

**Motivation**: We want to incorporate axe-core (via Cypress) into our automated testing workflow.

Possibly related to issues [#1275](https://github.com/dequelabs/axe-core/issues/1275), [#1185](https://github.com/dequelabs/axe-core/issues/1185), [#1196](https://github.com/dequelabs/axe-core/issues/1196), [#226](https://github.com/dequelabs/axe-core/issues/226), and [#608](https://github.com/dequelabs/axe-core/issues/608)

**Notes**: Gherkin syntax below utilises the cucumber-preprocessor. Tested on w3.org example page.

<pre><code>
import { Given, Then } from "cypress-cucumber-preprocessor/steps";

Given('I visit the specified webpage', () => {
  cy.visit('https://www.w3.org/WAI/demos/bad/before/home.html')
  cy.injectAxe()
})

Then('I check for a11y violations', () => {
  cy.checkA11y()
})
</code></pre>

**Versions etc.**
<pre><code>
axe-core version: 3.1.2
aXe Chrome extension version: 3.7.0

For Tooling issues:
- Node version: 8.2.1
- Platform:  MacOS Mojave 10.14
</code></pre>

**Screenshots**:
![aXe Chrome Extension](https://user-images.githubusercontent.com/12231379/52401270-2fc0ed80-2ab9-11e9-93da-8f29b1d5ae95.png)
<img width="1441" alt="axe-core" src="https://user-images.githubusercontent.com/12231379/52401338-55e68d80-2ab9-11e9-8399-4bd88d5eb322.png">

**Comment by WilcoFiers** [comment]
Hey Matthew. Thank you for reporting. What I'm seeing is that the extension finds 2 violations, and 3 items that need to be manually reviewed. I think that explains the difference.
