### ISSUE TITLE
Integrate axe-core with angularjs 1.5.8

### ISSUE THREAD

**Issue by tkserver** [dequelabs/axe-core#1357]
I apologize for not using the exact issue template, but that doesn't apply to this question and I see no other place to inquire for this answer.

I'm tasked with trying to get axe-core working in an angularjs 1.5.8 application which currently uses phantomjs, karma, chai etc for automated tessting.

Expectation: Use axe-core in angularjs 1.5.8 with phantomjs

I have searched for hours looking for implementations or examples to achieve this and have not found anything.  So first off is this possible, and if so, how?

**Comment by WilcoFiers** [comment]
@tkserver I'm not aware of any open source Karma integrations for axe-core. It shouldn't be difficult to create one though. The only thing you'd need to do is to load axe.js into the page. If I remember right, Karma has an API for loading in additional scripts. This will make the `axe` global object available to your tests. From there you can call `axe.run()` for each test you want to run. You can pass an element into `results = await axe.run(myNode)` to scope it.

You can find the `axe.run` docs here:
https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#api-name-axerun

Alternatively, Deque Systems, the company behind axe-core, has a product called [WorldSpace Attest](https://www.deque.com/tools/worldspace-attest/), which does have a Karma plugin, which has a few more features if you are looking to go beyond a straight forward "pass all the rules" type of thing.
