### ISSUE TITLE
Scroll position in shadow DOM is not restored after axe.run

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#1358]
Like the title says. I found this while looking through `getElmScrollRecursive`. It only looks at the light tree, which means any scrollable regions in shadow trees will not be restored to their original scroll position after axe.run() completes.

**Comment by jeankaplansky** [comment]
https://docs.google.com/document/d/14PI0e3X9g6CBWtl86HReHrRxl-_zapZBE8HaKoOHrmE/edit#heading=h.cy2pxqhzo2cm

**Comment by padmavemulapati** [comment]
@steven for the testfile below:
`<div id="fail1" style="height: 5px; overflow: auto;">
	<input type="text" tabindex="-1" />
</div>

<div id="fail2" style="height: 5px; overflow: auto;">
	<input type="text" tabindex="-1" />
	<select tabindex="-1"></select>
	<textarea tabindex="-1"></textarea>
</div>


<section id="inapplicable1">This element is not scrollable</section>

<div id="inapplicable2" style="height: 200px; width: 200px; overflow: auto;">
	<div style="height: 10px; width: 100x;">Content</div>
</div>`

I am seeing the below behaviour..(attached screenshot), it is no longer scrolls the contents. Is this what we are expecting?

![image](https://user-images.githubusercontent.com/47409579/73812040-6121e580-4801-11ea-944a-6f8e1d26d62e.png)

**Comment by straker** [comment]
Yes the page should no longer scroll, but it doesn't look like there's a shadow DOM element in the test that has a scroll region.
