### ISSUE TITLE
Iframe fails with role presentation

### ISSUE THREAD

**Issue by pvmanoj** [dequelabs/axe-core#1360]
Expectation: The following code should not identify it as a best practice
<code><iframe role="presentation"></iframe></code>
Providing an role presentation on iframe is allowed

Actual: aXe extension throws best practice violation aganist an iframe with role presentation

<pre><code>
axe-core version: 3.1.2
</code></pre>

**Comment by jkodu** [comment]
PR in place - https://github.com/dequelabs/axe-core/pull/1361
