### ISSUE TITLE
Allow users to change test level (A, AA, AAA)

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core#1363]
We should allow users to change the test level (A, AA, AAA [when added]) when the run axe-core.

**Comment by WilcoFiers** [comment]
In axe-core, you can use the runOnly option with tags to set level A and AA. That should be enough. The extensions do not let users configure what rules they run though.

**Comment by Filip-from-Genesys** [comment]
Having AAA and being able to switch between levels would be a great improvement
