### ISSUE TITLE
Do you have any example using Protractor to run e2e and accessibility testing?

### ISSUE THREAD

**Issue by FJLopezGarcia** [dequelabs/axe-core#137]
Do you have any example using Protractor to run e2e and accessibility testing?

**Comment by dylanb** [comment]
@FJLopezGarcia we do not yet have an example - however, if you have a project with Protractor tests that you can give us access to, maybe we can help you create an example

**Comment by FJLopezGarcia** [comment]
Hi Dylan,
Hope you are doing well, thanks a lot for your quick response.
I have uploaded an example to the following Git
https://github.com/FJLopezGarcia/UITestingFramework
Please take a look, i would be very grateful if you can help me.
Thanks in advance
Javi

**Comment by dylanb** [comment]
@FJLopezGarcia I have forked, cloned and done npm install etc. The gulpfile does not seem to include a target for running tests. How do I run the tests?

**Comment by FJLopezGarcia** [comment]
Hi Dylan,
I am using Grunt insted of Gulp

Please run "npm install" from "../test/resources" it will install all
dependences needed
Next run the tasks from the Grunt file located under .../test/resources
folder

Let me know if you have problems

**Comment by dylanb** [comment]
ok, when I change line 56 of `./UITestFW/test/javascript/unit/controllers/controllers.spec.js` to

```
expect(result.violations.length).not.toBe(0);
```

Then the aXe tests run and pass. There are other failures but I don't think they are due to aXe.

**Comment by dylanb** [comment]
ok, I have everything running including the two "unit tests" I mentioned above. Where would you like to insert a call to aXe?

**Comment by FJLopezGarcia** [comment]
Hi Dylan,
I was able to run the two "Unit Tests" you are mentioning with Karma
without issues. What I would like to run is the e2e script (or integration
test) adding AXE verifications using Protractor, but i am not able to do
it... I need help here. (Please add a verification where you consider
necessary, this is just an example to learn).

The e2e script i created as example is located in the following path:
"...\test\javascript\e2e\home.spec.js" and to run Protractor I am running
the following Grunt task --> "grunt test:e2e-chrome" (please run the grunt
task from "...\test\resources" as well).
Previously you need to run npm install (i think you already did it) and
later update the Webdriver running from nodejs --> node
node_modules/protractor/bin/webdriver-manager update (I included the
instructions in protractor.conf.js)

Thanks and best regards
Javi

**Comment by dylanb** [comment]
ok, if you implement this patch in your test directory, you will have a single working accessibility test

```
diff --git a/UITestFW/test/javascript/e2e/home.spec.js b/UITestFW/test/javascript/e2e/home.spec.js
index f498f1f..dfcf0e4 100644
--- a/UITestFW/test/javascript/e2e/home.spec.js
+++ b/UITestFW/test/javascript/e2e/home.spec.js
@@ -1,3 +1,4 @@
+var AxeBuilder = require('../../resources/node_modules/axe-webdriverjs');
 'use strict';
 
 describe('E2E Test - Home:', function(){
@@ -43,4 +44,11 @@ describe('E2E Test - Home:', function(){
         });
     });
 
+    it('Should be accessible', function () {
+        AxeBuilder(browser.driver)
+            .analyze(function (results) {
+                expect(results.violations.length).toBe(0);
+            });
+    });
+
 });
\ No newline at end of file
diff --git a/UITestFW/test/javascript/unit/controllers/controllers.spec.js b/UITestFW/test/javascript/unit/controllers/controllers.spec.js
index 33b931c..5e14b05 100644
--- a/UITestFW/test/javascript/unit/controllers/controllers.spec.js
+++ b/UITestFW/test/javascript/unit/controllers/controllers.spec.js
@@ -53,7 +53,7 @@ describe('Suite 2) AXE - Accessibility Engine plugin', function () {
     it('AXE - Accessibility Engine plugin: Should report that bad HTML is bad', function (done) {
         var n = document.getElementById('broken');
         axe.a11yCheck(n, null, function (result) {
-            expect(result.violations.length).toBe(0);
+            expect(result.violations.length).not.toBe(0);
             done();
         });
     });
diff --git a/UITestFW/test/resources/package.json b/UITestFW/test/resources/package.json
index fb4ad98..b0c27c1 100644
--- a/UITestFW/test/resources/package.json
+++ b/UITestFW/test/resources/package.json
@@ -4,15 +4,12 @@
   "version": "1.0.0",
   "description": "UITesting Framework",
   "dependencies": {
-    "phantomjs": "^1.9.18",
+    "axe-webdriverjs": "^0.2.0",
     "grunt": "^0.4.5",
     "grunt-concurrent": "^2.0.3",
     "grunt-contrib-jshint": "^0.11.3",
     "grunt-karma": "^0.12.1",
     "grunt-protractor-runner": "^1.2.1",
-    "protractor": "^1.8.0",
-    "protractor-html-screenshot-reporter": "^0.0.21",
-    "protractor-screenshot-reporter": "^0.0.5",
     "jasmine-core": "^2.3.4",
     "jshint-junit-reporter": "^0.2.2",
     "jshint-stylish": "^2.0.1",
@@ -27,7 +24,12 @@
     "karma-junit-reporter": "^0.3.7",
     "karma-safari-launcher": "^0.1.1",
     "load-grunt-tasks": "^3.3.0",
-    "selenium-standalone": "^4.7.0",
+    "phantomjs": "^1.9.18",
+    "protractor": "^1.8.0",
+    "protractor-html-screenshot-reporter": "^0.0.21",
+    "protractor-screenshot-reporter": "^0.0.5",
+    "selenium-standalone": "^4.7.1",
+    "selenium-webdriver": "^2.48.0",
     "time-grunt": "^1.2.1"
   }
-}
\ No newline at end of file
+}
```

**Comment by FJLopezGarcia** [comment]
Hi Dylan,
This is working fine!! This is great!!! Thanks you very much!!!
is there any way to generate a reporting with the details of the
accessibility vulnerabilities?

**Comment by dylanb** [comment]
@FJLopezGarcia glad it is now working for you!! Send me an email at dylan.barrell@deque.com and I'll give you some options regarding regporting

**Comment by casybaby** [comment]
@dylanb thanks for the example. I have the same question regarding reporting. Can you please share your answer here?
