### ISSUE TITLE
'Form element has explicit <label> that is hidden' issue when using standard CSS hiding methods

### ISSUE THREAD

**Issue by fredboyle** [dequelabs/axe-core#1372]
Sample markup and CSS can be found at: https://gist.github.com/fredboyle/66091c37f2d2231930b8f19a51058bd6

`assistive-text.css` includes only the CSS selector and rules that appear to be the root cause.
Removing `clip` and `margin: -1px` resolves nearly all of our aXe test failures but that is likely due to the fact that the label is now detectable as visible.

Expectation:
Check/test to pass.

Actual:
Check/test fails with error 'Form element has explicit <label> that is hidden'.

Motivation:
False positive.

<pre><code>
axe-core version: 3.1.2
axe-webdriverjs: 2.1.0

Browser and Assistive Technology versions

For Tooling issues:
- Node version: 8.9.4
- Platform:  Mac
</code></pre>

**Comment by WilcoFiers** [comment]
Hey Fred. Thank you for reporting. This is a known issue. A fix for this is already in the prerelease. It will be included in axe-core 3.2, which should be available in a few weeks.
