### ISSUE TITLE
rowspan rule should be more discriminating

### ISSUE THREAD

**Issue by dylanb** [dequelabs/axe-core#138]
We currently flag all uses of rowspan. Screen readers have improved and some uses of rowspan now work well everywhere. We should make this rule discriminate between the pathological use cases and the ones that are well supported. Currently this rule generates some false positives on the following page

https://dequeuniversity.com/testsuite/tables/colgroup-rowgroup/

**Comment by WilcoFiers** [comment]
Resolved in the internal repo. Will be available in the next major release of axe-core.
