### ISSUE TITLE
Failing Safari tests

### ISSUE THREAD

**Issue by jkodu** [dequelabs/axe-core#1385]
The below tests are failing in Safari, on develop branch. Our CI does not test on safari

![image](https://user-images.githubusercontent.com/20978252/53123027-05a70b00-3550-11e9-914d-d55371868a6e.png)

![image](https://user-images.githubusercontent.com/20978252/53123047-135c9080-3550-11e9-863e-f53f7263915c.png)

**Comment by straker** [comment]
Turns out Safari has a bug where `<main>` does not support `attachShadow` even though it's a valid `attachShadow` target https://bugs.webkit.org/show_bug.cgi?id=197726
