### ISSUE TITLE
Allow ARIA grids without giving a table error

### ISSUE THREAD

**Issue by jnurthen** [dequelabs/axe-core#141]
Currently when an ARIA grid is used we get table errors from aXe (layout tables must not use data table elements). This is because the table elements have role=presentation on them and still contain th elements which have role=columnheader/rowheader which serve as the headers for the parent grid.

See http://jdevadf.oracle.com/adf-richclient-demo/faces/components/table.jspx for a code sample.

**Comment by WilcoFiers** [comment]
Hi Jnurthen. There is indeed a problem of not detecting such relationships correctly. However, do have a look at managing the ownership. A grid must own groups or rows, and rows must own cells.

**Comment by jnurthen** [comment]
@WilcoFiers As far as I can tell the ownership is correct in the grid in this example. Can you tell me what you think isn't correct?

**Comment by dylanb** [comment]
@jnurthen one problem is there is a row with a bunch of rows as direct children. They way I interpret the ARIA spec, rows are only allowed to have gridcell, rowheader and columnheader children. Also, the row must be owned by a grid, rowgroup or treegrid and having an interim row owner does not qualify IMO.

Also. there are some very questionable practices in the markup including

1. overriding default table semantics,
2. having structures without an explicit role

These last two items are, not, I believe, strict violations, but are likely to make this table only work in the strictest implementation.

**Comment by dylanb** [comment]
@jnurthen are you sure it is because of the ths? I think it might be because of the use of a summary attribute on the presentational table.

**Comment by dylanb** [comment]
@jnurthen I think I should close this but want you to confirm the above reason first

**Comment by jnurthen** [comment]
Why would having a summary on a presentation table be an issue. The
role="presentation" should override that so it is as if the summary does
not exist. (not saying we shouldn't remove the summary - but I don't think
it is an error)

**Comment by jnurthen** [comment]
Even once I remove summary (which I just did as a test) there is still an error that there is a TH in a layout table.... This is not a problem when you have marked the table using role="presentation". The role="presentation" on the <table> nullifies the semantics of the <th>. This is the whole point of role=presentation - it allows us to modify the semantic of elements without having to modify the DOM structure.
Now - if these tables wern't explicitly marked as being presentational then I would agree with these rules but you should not use the same logic for explicitly marked presentational tables as implicit ones.

**Comment by WilcoFiers** [comment]
Hi @jnurthen. We've been looking at the table rules more closely. We're going to split them up and redo a few parts as we are not satisfied with their results. This will give us the opportunity to consider the scenario you've posed here, where a representational table is mixed with a grid. This is quite an interesting case you've presented.

**Comment by marcysutton** [comment]
@WilcoFiers sounds like this might be addressed with the cantTell table rule.

**Comment by marcysutton** [comment]
Hi @jnurthen, the link in your issue no longer works. Can you provide us with another sample since we're picking up old issues?

**Comment by jnurthen** [comment]
@marcysutton its possible the server needed restarting. The link works now.

**Comment by WilcoFiers** [comment]
Issue is outdated. Suspect this has been resolved, table rules were completely overhauled.
