### ISSUE TITLE
role="banner" on header triggers empty heading violation

### ISSUE THREAD

**Issue by stonehippo** [dequelabs/axe-core#142]
I have a case where an H1 element triggers the "Headings must not be empty" violation, despite having non-empty, discernible text. The attached screenshot shows the violation warning. The page in question can be tested at https://stonehippo.com.

Removing the ARIA `role="banner"` attribute from the H1 element clears the violation. Given that the content is both visible and reachable by screen readers, this seems like a bug.

![screen shot 2015-11-25 at 4 32 51 pm](https://cloud.githubusercontent.com/assets/43452/11410061/6d763156-9392-11e5-8575-04a78f3bea0c.png)

**Comment by dylanb** [comment]
An element cannot be both a heading and a banner at the same time. The library is working correctly.

What you should do is wrap a div around your h1 and give that a role of banner.

However, on this page, a banner role does not look appropriate, so I suggest you simply remove it.
