### ISSUE TITLE
axe-Coconut Chrome extension not using latest axe-core API version

### ISSUE THREAD

**Issue by bjankord** [dequelabs/axe-core#1429]
Based on the description of [axe-Coconut Chrome extension](https://chrome.google.com/webstore/detail/axe-coconut/iobddmbdndbbbfjopjdgadphaoihpojp?hl=en), my assumption was that the Chrome extension would use the latest stable release of axe-core, (currently at v3.2.2), or possibly a beta release ahead of the latest stable release.

> The axe Coconut extension, created in the same vein as a Chrome Canary or Firefox Nightly, will allow you to try out our latest APIs and rules before they are released to more stable channels, such as our regular axe Chrome Extension.

Expectation: axe-Coconut Chrome extension uses latest axe-core version
Actual: axe-Coconut Chrome extension uses axe-core API version: 3.1.2

Motivation: I'd like to do quick spot testing with latest axe-core APIs.

<pre><code>
axe-core version: 3.1.2
Browser and Assistive Technology versions: Chrome 72
</code></pre>

**Comment by luarmr** [comment]
Will be great to update the Chrome extension and get rid of the bug related with `class="sr-only"`.

**Comment by WilcoFiers** [comment]
Howdy guys. Yup, this one is a little later than usual. We've updated all extensions yesterday, so you should be good to go again! Thanks for reporting.

**Comment by bjankord** [comment]
I'm seeing that the extension was last updated in January on the Chrome extension page for axe-coconut. Does it take a while for those updates to be picked up by the Chrome web store?

<img width="917" alt="Screen Shot 2019-03-26 at 7 04 05 PM" src="https://user-images.githubusercontent.com/633148/55041216-1a1c6e80-4ffa-11e9-8bee-1770c73d948c.png">
