### ISSUE TITLE
Table headers and col/row span 

### ISSUE THREAD

**Issue by shanderson** [dequelabs/axe-core#144]
What is the reasoning behind this requirement from axe?
"<th> elements should only be used when there is a single row and single column of headers"

In the documentation there is no reference that I can see that discusses <th> with a col or row span being a violation.

**Comment by dylanb** [comment]
This is to ensure that tables work properly on all platforms. Multiple column and row headers do not work on iOS

**Comment by dylanb** [comment]
@shanderson if you have an example that does work on iOS, please post the code here so I can validate it. If this has in fact been fixed by iOS, I would recommend removing this rule.

**Comment by thecristen** [comment]
I'm guessing you're talking about Safari on iOS. I just used that to look at http://webaim.org/techniques/tables/data and I can see the final table with its multiple headers just fine, FYI

**Comment by dylanb** [comment]
when I go to that final table in iOS with VoiceOver, it reads the table as follows

Shelley's Daughters (table start)
Age, By birth, name
Birthday, Age
Birthday
Name, Beth, by birth
Age, Jackie
Birthday, 5
The 5th of April
Age, by marriage, Beth
Birthday, 8
The 14th of January
Name, by marriage
Age, Beth
Birthday 8
the 14th of January, (table end)

This is totally wrong and confusing!

**Comment by WilcoFiers** [comment]
Hi Shanderson! Thanks for sharing this issue. We've had a few comments about the way tables were tested. We've done a complete rewrite of the axe rules for tables. This will become available in the next major release.

**Comment by dylanb** [comment]
@WilcoFiers can you test that the new rules still flag this broken table
