### ISSUE TITLE
New Rule: aria-form-field-label

### ISSUE THREAD

**Issue by jkodu** [dequelabs/axe-core#1449]
**Some Context:**
This is a composite rule that will use some pre-existing checks, to extend the current `label` rule for a larger set of semantic roles (checkbox, combobox, listbox, menuitemcheckbox, menuitemradio, radio, searchbox, slider, spinbutton, switch, textbox)

# aria-form-field-label

Ensures every element with semantic roles of a form field (checkbox, combobox (select elements), listbox, menuitemcheckbox, menuitemradio, radio, searchbox, slider, spinbutton, switch, textbox) has a label.

**Tags:** wcag2a, wcag412

## Matches
- all of the above semantic roles excluding ones covered by `label` rule & or any overlapping rules like `area-alt`, `button-name`, `image-alt`.

## Checks

**any:** 
- `aria-label` (Already exists) 
- `aria-labelledby`(Already exists) 
- `non-empty-title` (Already exists) 

**none:**
- `no-implicit-explicit-label`
	- "fail": "Element with ARIA role ... must have label",
	- "incomplete": "Element with ARIA role ... cannot have implicit or explicit label"

### Related issues
- https://github.com/dequelabs/axe-core/issues/1148
- https://github.com/dequelabs/axe-core/issues/1157

**Comment by dylanb** [comment]
we should call this `aria-input-field-name`

**Comment by jkodu** [comment]
@dylanb 

This got split into 2 rules
- `aria-toggle-field-label` and
- `aria-input-field-label`

Do you want to change both of them to below?
- `aria-toggle-field-name`
- `aria-input-field-name`

@WilcoFiers - what do you think?

**Comment by dylanb** [comment]
yes, name and this should probably happen before we ship 3.3

**Comment by jkodu** [comment]
@dylanb - as the PR's (https://github.com/dequelabs/axe-core/pull/1450 & https://github.com/dequelabs/axe-core/pull/1610) have been merged, I am closing this issue. If you believe the rules have to be renamed, please reopen the issue & notify.

**Comment by dylanb** [comment]
Yes, i think we should rename these before releasing 3.3
