### ISSUE TITLE
Offscreen Text <label for="p1" class="sr-only> reported as error

### ISSUE THREAD

**Issue by DavidMacDonald** [dequelabs/axe-core#1454]
Expectation: Don't fail offscreen label, or provide warning, or ignore it if the label string contains "search"
```<label class="sr-only" for="p1" >search</label><input type="text" id="p1">```

Actual: fails offscreen label 

Motivation: sometimes the visual label is obvious such as a search input with a magnifying glass button next to it. If aria-label is used it passes but offscreen explicitly associated label is not. this seems inconsistent.

<pre><code>
axe-core version: 3.1.2
axe-webdriver, extension or other integration version: X.Y.Z

Browser and Assistive Technology versions

For Tooling issues:
- Node version: XX  
- Platform:  
</code></pre>

**Comment by luarmr** [comment]
Axe-core 3.2.2 (current version) doesn't have this issue.

**Comment by WilcoFiers** [comment]
Jup, thanks Raul. This is fixed in 3.2.
