### ISSUE TITLE
False positive: Color-contrast rule fails when partially opaque overlay div is placed on top of content

### ISSUE THREAD

**Issue by iamrafan** [dequelabs/axe-core#1459]
Expectation: Not fail the color-contrast rule when partially opaque overlay div is placed on top of a section of view port

Actual: Fails color-contrast rule

Motivation: Once the side panel opens, the blurred out content need not be accessible to the user.

Demo link: https://developer.microsoft.com/en-us/fabric#/components/panel

![image](https://user-images.githubusercontent.com/22068434/54966314-1c66c600-4f31-11e9-92ed-3ee8ebbe87b0.png)

![image](https://user-images.githubusercontent.com/22068434/54966342-32748680-4f31-11e9-8195-6c55aad9bc26.png)

<pre><code>axe-core version: 3.1.2
axe-Coconut version: 3.7.0</code></pre>

**Comment by WilcoFiers** [comment]
Interesting. I reran this page with 3.2.2, 3.1.2 and 3.0.3, none of them report it. Is it possible this page has changed since?

**Comment by iamrafan** [comment]
@WilcoFiers No, I can still repro the issue using axe-core 3.1.2.

**Comment by roman-II** [comment]
@iamrafan Can you shed a little light on how this page is handling trapping the focus within the pop out panel? This will help with debugging. Thanks!

**Comment by iamrafan** [comment]
@roman-II I am not on the same team, I am not sure how the focus is being handled here

**Comment by cnamal** [comment]
Pinged folks from OUFR to provide assistance.

**Comment by dzearing** [comment]
@kkjeer can you help take a look?

**Comment by kkjeer** [comment]
Panel uses a [FocusTrapZone](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Panel/Panel.base.tsx#L167) for focus management. @JasonGore is more familiar with the FocusTrapZone component.

**Comment by JasonGore** [comment]
This issue is reporting a contrast issue with Overlay. I'm not sure what to do here from a FocusTrapZone perspective. FocusTrapZone does not apply any styling. If there is a FocusTrapZone focus issue to look into, I'd recommend creating a new issue.

**Comment by jeankaplansky** [comment]
No docs required.

**Comment by chandana7393** [comment]
Tested, still reproducible.
![overlap_needs_review](https://user-images.githubusercontent.com/45285854/61215030-379b5280-a727-11e9-9f0b-0fc6ac6668f8.PNG)
**Tested Environment:**
Axe-coconut - 3.8.1.19604v
Chrome -75v
OS - Windows 10 64 bit.

**Comment by roman-II** [comment]
@chandana7393 That screenshot is expected behavior. We still raise an issue, just under needs review and "Element is overlapped by another element." Also took a peek at this myself and the current element being looked at is actually behind the panel on the right side.

**Comment by chandana7393** [comment]
@roman-II This behaviour is observed in the previous axe-core version, then what are the changes in this rule and what is the expected output of this ticket would you please let me know.

**Comment by roman-II** [comment]
@chandana7393 The main change is moving those color-contrast violations to needs review. The screenshot you provided is the expected output, as the element is behind the panel.

**Comment by chandana7393** [comment]
Thank you @roman-II 
Tested, Working as expected.
![under_needs_review](https://user-images.githubusercontent.com/45285854/62109669-60e0e480-b2ca-11e9-8851-a20929e4621d.PNG)
**Tested Environment:**
Axe-coconut - 3.8.1.19721v
Chrome - 75.0.3770.142v
OS - Windows 10 64 bit.
