### ISSUE TITLE
Slow rules should turn themselves off on large pages

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#1464]
Testing a page with 70k DOM nodes, axe was unable to complete. Turning off just a few rules known to be particularly slow solves this problem. I created this configuration, which enables axe to complete in 26s.

```json
{
  "rules": [{
     "id": "color-contrast",
     "enabled": false
   }, {
     "id": "duplicate-id-active",
     "enabled": false
   }, {
     "id": "duplicate-id-aria",
     "enabled": false
   }, {
     "id": "duplicate-id",
     "enabled": false
  }],
  "checks": []
}
```

One possible solution would be to provide a "slow" flag, which when running on very large pages turns those rules off, returning a single "incomplete" result. We can add an option to axe that will force to alway run slow rules. But having this feature will help axe-core complete even on very large pages. We could consider different thresholds for different rules based on the number of DOM nodes.

**Comment by AutoSponge** [comment]
If you're looking for a benchmark, I can suggest https://js.tensorflow.org/api/latest/

**Comment by mohanraj-r** [comment]
A way to label and exclude slow rules seems like a good idea 👍 @WilcoFiers 

Btw in my tests I have found that oddly `link-name` rule also takes almost the same amount of time as `color-contrast`

**Comment by dylanb** [comment]
@WilcoFiers perhaps we could use the AOM to speed up the calculation of accessible name for situations that are simple (i.e. do not fall into the "lowest common denominator" category) - thoughts?
