### ISSUE TITLE
Axe-Core 3.2.0 added an ES6 Promise polyfill that overwrites native promise behavior

### ISSUE THREAD

**Issue by cscrosati** [dequelabs/axe-core#1468]
After updating to 3.2.0/3.2.2 of axe-core, I noticed a lot of our QUnit test suite failed in interesting ways, where Promise resolution was involved.

After debugging, it turned out when loading axe-core, a promise polyfill was loaded that overrides the native promise behavior. Not only that, it overrides our own polyfill implementation when we use one ourselves.

Can the polyfill only be used if window.Promise doesn't exist? Right now, it overwrites what is in place.

**Comment by WilcoFiers** [comment]
@cscrosati Thanks for reporting. That definitely wasn't the intent. @straker can you create a fix for this?

**Comment by cscrosati** [comment]
BTW, thanks for fixing so promptly! :) Which official release should I expect this to be in?
