### ISSUE TITLE
Axe analysis not working

### ISSUE THREAD

**Issue by Grapefruiteis** [dequelabs/axe-core#1485]
Expectation: << Describe what you expect the product to do >>

Actual: << Describe what the product actually does >>

Motivation: << Describe why you want the behavior to be changed >>

<pre><code>
axe-core version: X.Y.Z
axe-webdriver, extension or other integration version: X.Y.Z

Browser and Assistive Technology versions

For Tooling issues:
- Node version: XX  
- Platform:  
</code></pre>

**Comment by WilcoFiers** [comment]
@Grapefruiteis I'm closing this issue as it has no details on how to reproduce. If you can provide us with this information, feel free to reopen the issue.
