### ISSUE TITLE
New Rule: identical-links-same-purpose

### ISSUE THREAD

**Issue by jkodu** [dequelabs/axe-core#1505]
# identical-links-same-purpose

This rule checks that links with identical accessible names resolve to the same resource or equivalent resources.

## Tags
- wcag2
- wcag249

## Matches

- semantic role of `link`, or roles that inherit from `link` role.
- is not `aria-hidden`.
- has `accessible name`.

## Checks

**all:**
- identical-links-same-purpose
	- `incomplete` : `Links with identical names that do not serve same purpose`.
	- `pass`: `Links with identical names serve equivalent purpose`
	
- identical-links-same-purpose-after
	- all matching nodes in the results are processed to find any identical nodes (same accessible name) and verified if they resolve to the same resource. Nodes which do not satisfy to the same resource are marked as `incomplete`.

### References:
- [ACT Rule - Links with identical accessible names serve equivalent purpose](https://act-rules.github.io/rules/b20e66)

**Comment by jkodu** [comment]
@WilcoFiers - Please see proposal above, feedback welcome.

**Comment by jeankaplansky** [comment]
framework in place in github and DQU 1/27/2020

**Comment by jeankaplansky** [comment]
Release notes and rule content populated as of 2/03/2020

**Comment by padmavemulapati** [comment]
@jkodu , I am  seeing the voilations instead incomplete for this new rule, identical-links-same-purpose. used test file specified in the `https://github.com/dequelabs/axe-core/blob/develop/test/integration/rules/identical-links-same-purpose/identical-links-same-purpose.html` 
![image](https://user-images.githubusercontent.com/47409579/74122867-ae7fc780-4bf2-11ea-8abc-4f6c0679e2a6.png)
suspecting whether the changes in the axe version updated properly or not.

**Comment by padmavemulapati** [comment]
Working for axe-core's axe.run(), will verify the same with axe and attest extensions once axe-core3.5 deployed in devTools.
