### ISSUE TITLE
New Rule: no-autoplay-audio

### ISSUE THREAD

**Issue by jkodu** [dequelabs/axe-core#1506]
# no-autoplay-audio

- Description: `This rule checks that `autoplay` audio does not last for more than 3 seconds, or it has a control mechanism`
- Help: `<video> or <audio> elements does not autoplay audio`

## Tags
- wcag2
- wcag142

## Matches

- `"selector": "audio[autoplay], video[autoplay]"`
- `"excludeHidden": false`, because some user agents hide media elements when controls attribute is missing.
- exclude nodes that are either `paused` or `muted`.

### Check 1:
  - name: `no-autoplay-audio-below-allowed-duration`
    - impact: serious
    - messages: 
      - pass: `<video> or <audio> does not output audio for more than allowed duration`
      - fail: `<video> or <audio> outputs audio for more than allowed duration`
      - incomplete: `Check that the <video> or <audio> does not output audio for more than allowed duration`

### Check 2: 
  - name: `no-autoplay-audio-has-controls`
    - impact: serious
    - messages: 
      - pass: `<video> or <audio> has controls mechanism`
      - fail: `<video> or <audio> does not have controls mechanism`
      - incomplete: `Check that the <video> or <audio> has controls mechanism`

## ACT Rule Reference:
- [Video or audio has no auto-play audio](https://act-rules.github.io/rules/80f0bf)

**Comment by jkodu** [comment]
@WilcoFiers - Please see proposal above, feedback welcome.

**Comment by jeankaplansky** [comment]
rule help infrastructure created 1/27/2020

**Comment by jeankaplansky** [comment]
New rule help created, captured in release notes 2/03/2020

**Comment by padmavemulapati** [comment]
Verified with 'no-autoplay-audio.html' test file, getting 'needs review' issues.
![image](https://user-images.githubusercontent.com/47409579/74039925-b8ce7580-49e8-11ea-9733-67f2ac029b5e.png)

**Comment by padmavemulapati** [comment]
Verified with axe-coconut , 
![image](https://user-images.githubusercontent.com/47409579/74312162-2981e300-4d97-11ea-8e82-af0cee39bb07.png)
