### ISSUE TITLE
Portability for axe.js files

### ISSUE THREAD

**Issue by scottizu** [dequelabs/axe-core#1509]
We have two rule sets we run:

1. wa11y
 (eBay's ruleset written in 2014)
2. aXe (Deque's ruleset)

We run accessibility testing many different ways:

1. Java Test NG wrapper for ruleset javascript files
2. Copy and paste ruleset javascript files into Chrome Browser console and then execute various commands to run
3. aXe Chrome Extension (uses aXe)
4. eBay's Go Quickly Chrome Extension (uses aXe and wa11y)
5. Python
6. Node
7. Node Mocha Chai ChromeDriver

https://marcysutton.com/angular-protractor-accessibility-plugin referenced the method we use for 7, which will use the fs package to read the javascript, then run it

```
driver.executeAsyncScript(aXe+'axe.run(document, {runOnly: {type: "rule", values: '+JSON.stringify(rulesToRun)+'}}, arguments[arguments.length - 1]);', 'aXe 3.2.0 ruleset')
```

In aXe.2.3.1 this worked because the callback had results as its first argument. However, it aXe.3.2.0, we must change the javascript file replacing "callback(null,results)" with "callback(results)" in the axe.run function. To be more portable, it would be good if aXe.run's callback only used one variable (that could potentially include the error).

**Comment by dylanb** [comment]
@scottizu Why can you not simply change the code call ing axe-core? This seems like "some other code's problem" to me. Would this fix your problem https://github.com/angular/protractor-accessibility-plugin/issues/36

**Comment by WilcoFiers** [comment]
You can work around this problem by doing this:

```java
driver.executeAsyncScript(
  (
    aXe + 
    ';axe.run({runOnly: {type: "rule", values: ' + 
    JSON.stringify(rulesToRun) +
    '}}, function (err, results) { ' +
    '  arguments[arguments.length - 1](err || results);' +
    '});'
  ),
  'aXe 3.2.0 ruleset')
```

Error first callbacks is idiomatic JavaScript thanks to NodeJS. We shouldn't change that.

**Comment by scottizu** [comment]
This is interesting.  Thanks for the feedback and I think this fixes the issue.
