### ISSUE TITLE
Ignore iframes with display: none and no contents?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [dequelabs/axe-core#1516]
Suppose you have following iframe element gets on a page:

```html
<iframe name="__cmpLocator" style="display: none;"></iframe>
```

...which gets interpreted by Chrome in dev tools as:

```html
<iframe name="__cmpLocator" style="display: none;">
    #document
        <html>
            <head></head>
            <body></body>
        </html>
</iframe>
```

Expectation: There are no accessibility violations, right? This frame doesn't have any contents and doesn't get shown to the user.

Actual: Three accessibility complaints:
* Frames must have title attribute
* <html> element must have a lang attribute
* All page content must be contained by landmarks

Motivation: This is what's added when using https://github.com/appnexus/cmp as an en-US user.

<pre><code>
axe-devtools version: 3.8.0
axe-core version: 3.2.2

Browser and Assistive Technology versions

- Chrome: 73
- Platform:  Mac
</code></pre>

**Comment by WilcoFiers** [comment]
Thanks for reporting. The lang attribute one has been fixed. We'll have to look at the other two, but I agree with you that doesn't seem correct.

**Comment by straker** [comment]
I'm unable to reproduce the errors with just the iframe on the page using axe 3.2.2 https://codepen.io/straker/pen/vwwXMK. @JoshuaKGoldberg is this still an issue you're seeing?

**Comment by WilcoFiers** [comment]
We were unable to reproduce the issue. If you can provide more information, feel free to reopen the issue.
