### ISSUE TITLE
incompleteFallbackMessage incorrect translation?

### ISSUE THREAD

**Issue by danielweck** [dequelabs/axe-core#1518]
Ace v3.2.2

English (default):
https://github.com/dequelabs/axe-core/blob/v3.2.2/lib/misc/incomplete-fallback.json
```json
{
	"incompleteFallbackMessage": "aXe couldn't tell the reason. Time to break out the element inspector!"
}
```

French (I have not checked other languages):
https://github.com/dequelabs/axe-core/blob/v3.2.2/locales/fr.json#L664
```json
	"incompleteFallbackMessage": {
		"undefined": {
			"failureMessage": "Corriger tous les éléments suivants : {{~it:value}}\n  {{=value.split('\\n').join('\\n  ')}}{{~}}"
		}
}
```

This looks like a bad copy/paste of `failureSummaries.none.failureMessage`:
https://github.com/dequelabs/axe-core/blob/9556393cab10e2836b1cd6cd0c59bb4c1f231222/locales/fr.json#L654-L661

**Comment by jeankaplansky** [comment]
No docs required.
