### ISSUE TITLE
Poor performing rules causes certain pages large performance issues

### ISSUE THREAD

**Issue by bfulco** [dequelabs/axe-core#1521]
Expectation: Axe will scan the page: https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/faqs#PrescriptionRefill and return the results in a timely fashion

Actual: Axe takes 55 seconds to scan the page: https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/faqs#PrescriptionRefill

Motivation: Improved performance

<pre><code>
axe-core version: 3.1.2
axe-webdriver, extension or other integration version: Attest extension 2.0.0 and Comply application 6.3.0

Browser and Assistive Technology versions

For Tooling issues:
- Node version: NA
- Platform:  Mac, Linux
</code></pre>

**Comment by WilcoFiers** [comment]
This is related to #1464.

**Comment by WilcoFiers** [comment]
This should be resolved with #1503.
