### ISSUE TITLE
Document axe-core's required globals

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#1531]
To run, axe-core requires a number of globals to be set up. This isn't properly described in the documentation, so we need to add this.

The required globals are tested in a jsdom example here:
https://github.com/dequelabs/axe-core/pull/1530/files#diff-bdce4c640c93affd7131cd773f65ba2fR35

**Comment by jeankaplansky** [comment]
@straker: The docs are present, but the markdown for the table of contents is missing entries (for more things than just the required globals). I don't want a TOC to hold up a release though so if it's something you're not comfortable updating for July 1, please make a new ticket "update TOC for axe-core/docs/api.md" as a docs ticket and put it in the sprint ready bucket. I'll grab it when I get back.

If @aellsey and @straker are cool with this, I'll move the ticket to the Ready for QA column. Please advise. Thanks!

**Comment by jeankaplansky** [comment]
@straker - please see the last message above. Are we good to go with moving this to "Ready for QA"? Thanks!

**Comment by straker** [comment]
Sorry, forgot about this. Created a pr for this https://github.com/dequelabs/axe-core/pull/1682

**Comment by jeankaplansky** [comment]
TOC fixed.
