### ISSUE TITLE
Error during analyse of  Website - should report

### ISSUE THREAD

**Issue by FunThomas424242** [dequelabs/axe-core#1532]
Details following in the text:

Testobject: https://funthomas424242.github.io/honey-toggle-button/
wich contains this webcomponent
https://funthomas424242.github.io/honey-toggle-button/src/components/toggle-button/toggle-button.js

Expectation: I expect a list of accessibillity errors of my webcomponent.

Actual: There is a stacktrace of axe-cocounut addon

Motivation: The stacktrace write i should create an issue

<pre><code>
An error occurred
Please try again. If the error persists, pleasereport the issue  to Deque Systems

TypeError: Cannot read property 'nodeMap' of undefined
    at G (chrome-extension://iobddmbdndbbbfjopjdgadphaoihpojp/adapter.bundle.js:97:74309)
    at Object.utils.getFlattenedTree (chrome-extension://iobddmbdndbbbfjopjdgadphaoihpojp/adapter.bundle.js:97:81423)
    at Object.j [as cleanup] (chrome-extension://iobddmbdndbbbfjopjdgadphaoihpojp/adapter.bundle.js:97:51377)
    at chrome-extension://iobddmbdndbbbfjopjdgadphaoihpojp/adapter.bundle.js:109:321777
    at new Promise (<anonymous>)
    at Object.u [as highlight] (chrome-extension://iobddmbdndbbbfjopjdgadphaoihpojp/adapter.bundle.js:109:321749)
    at chrome-extension://iobddmbdndbbbfjopjdgadphaoihpojp/adapter.bundle.js:85:171163
    at onMessage (chrome-extension://iobddmbdndbbbfjopjdgadphaoihpojp/browser-polyfill.js:1056:22)
    at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26)

Following the chrome extension details site: 

Erweiterungssymbol axe-Coconut An

Beschreibung
Accessibility testing in Chrome Developer Tools
Version
3.8.0.12104 build 50d7d54b96
Größe
3,1 MB
Berechtigungen
Alle Ihre Daten auf von Ihnen besuchten Websites lesen und ändern
Dieser Erweiterung erlauben, alle Ihre Daten auf von Ihnen besuchten Websites zu lesen und zu ändern:
Weitere Informationen zum Websitezugriff

Im Inkognitomodus zulassen
Warnung: Google Chrome kann nicht verhindern, dass Ihr Suchverlauf von Erweiterungen protokolliert wird. Sie können diese Erweiterung für den Inkognitomodus deaktivieren, indem Sie das Häkchen aus dem Kästchen entfernen.

Zugriff auf Datei-URLs zulassen

Im Chrome Web Store ansehen

Browser and Assistive Technology versions

Chrome-Logo
Google Chrome
Version 71.0.3578.98 (Offizieller Build) (64-Bit)
Hilfe für Chrome aufrufen

For Tooling issues:
- Platform:   Linux https://antergos.com/
</code></pre>

**Comment by anuvenkatesh1** [comment]
I have been getting the same error as well. 
TypeError: Cannot read property 'nodeMap' of undefined
    at G (chrome-extension://iobddmbdndbbbfjopjdgadphaoihpojp/adapter.bundle.js:97:74309)
    at Object.utils.getFlattenedTree (chrome-extension://iobddmbdndbbbfjopjdgadphaoihpojp/adapter.bundle.js:97:81423)
    at Object.j [as cleanup] (chrome-extension://iobddmbdndbbbfjopjdgadphaoihpojp/adapter.bundle.js:97:51377)
    at chrome-extension://iobddmbdndbbbfjopjdgadphaoihpojp/adapter.bundle.js:109:321777
    at new Promise (<anonymous>)
    at Object.u [as highlight] (chrome-extension://iobddmbdndbbbfjopjdgadphaoihpojp/adapter.bundle.js:109:321749)
    at chrome-extension://iobddmbdndbbbfjopjdgadphaoihpojp/adapter.bundle.js:85:171163
    at onMessage (chrome-extension://iobddmbdndbbbfjopjdgadphaoihpojp/browser-polyfill.js:1056:22)

is what I'm getting

**Comment by straker** [comment]
Thanks for the report. I've narrowed down the problem and should be getting a fix in soon.

**Comment by anuvenkatesh1** [comment]
Hi any ETA on this? We greatly rely on aXe-coconut for our testing :)

**Comment by straker** [comment]
Yep. I have a fix ready, just need to tweak it a bit and should have it in within a day or two.

**Comment by bjankord** [comment]
Leaving a comment so I can track this issue. There are some rules in the newer versions of axe-core that I want to test with the axe-coconut chrome add-on once it is working again.

**Comment by straker** [comment]
The fixed was just merged so after a deploy axe-coconut should be working again. Please let us know if you run into any other problems.

**Comment by FunThomas424242** [comment]
In my case the fix seems not working. I have today deinstalled and new installed the chrome extension. Following the current screenshots:

![20190511-screenshot](https://user-images.githubusercontent.com/1297475/57570621-5a964700-7404-11e9-859d-9b60e7e87f0d.png)
![20190511-CocounutVersion](https://user-images.githubusercontent.com/1297475/57570622-5a964700-7404-11e9-8e3d-c606e54bca8d.png)

**Comment by bjankord** [comment]
I'm continuing to see an error as well on fresh install of axe-coconut from chrome web store.
<img width="1438" alt="Screen Shot 2019-05-12 at 4 55 50 AM" src="https://user-images.githubusercontent.com/633148/57580693-5c96ef00-7472-11e9-8a92-9ea23ba829b2.png">

**Comment by metalhaze** [comment]
I am continuing to see this error as well. Fails when I run it. 

![chrome_2019-05-13_10-56-00](https://user-images.githubusercontent.com/514812/57631588-c47e3000-756d-11e9-8d5c-143af283aac3.png)

**Comment by straker** [comment]
Thanks for letting us know that the extension is still having problems and for your continual patience while we work to resolve it. It turned out that we had a problem with our nightly deploys. We are working on a fix which should go out soon.

**Comment by straker** [comment]
We just deployed the latest version axe-coconut to the Google Chrome store. It seems to be working correctly. Please let us know if you still are experiencing any problems.

**Comment by bjankord** [comment]
It is working great for me now. Thanks for all the awesome work you all put into this tool!

**Comment by FunThomas424242** [comment]
works fine for me too :)
