### ISSUE TITLE
Rule frame-title-unique yields different results for below tests

### ISSUE THREAD

**Issue by jkodu** [dequelabs/axe-core#1542]
There is disparity between the expected results (of ACT Rules) and the actual outcome (of Axe) for the below testcases.

  - ACT Rule: Iframes with identical accessible names serve equivalent purpose
  - ACT Rule Url: https://act-rules.github.io/rules/4b1c6c
  - Axe Rule: `frame-title-unique`

  Results:

  | ACT Testcase Url                                                                           | ACT Expected | Axe Outcome  |
| ------------------------------------------------------------------------------------------ | ------------ | ------------ |
| https://act-rules.github.io/testcases/4b1c6c/6bcfa4db9634c6b44581c92c4446f3b9aafcbb4c.html | passed       | failed       |
| https://act-rules.github.io/testcases/4b1c6c/1f2804a732faaa1a675568a343ac5944b4f3eac0.html | passed       | inapplicable |
| https://act-rules.github.io/testcases/4b1c6c/1bb03a134c142663291d243f0508d81314b74a13.html | passed       | failed       |
| https://act-rules.github.io/testcases/4b1c6c/13d30fff7d78841ed311d95352aa86c66835f50a.html | passed       | failed       |
| https://act-rules.github.io/testcases/4b1c6c/427d0610d76e46beef047a676c186d8b3002e0e4.html | passed       | failed       |
| https://act-rules.github.io/testcases/4b1c6c/ac944ff6f5809543b393f77a3d3eaabcc0e33abe.html | passed       | failed       |
| https://act-rules.github.io/testcases/4b1c6c/5db3a461ed9373bf000c541402d3bd2c6a5b81fb.html | passed       | failed       |
| https://act-rules.github.io/testcases/4b1c6c/516ca61c5ce975305f1b37c87b5f237301070a7f.html | failed       | inapplicable |
| https://act-rules.github.io/testcases/4b1c6c/6cc8bb6758556ddcba11e89976f8040b62dcd651.html | failed       | passed       |
| https://act-rules.github.io/testcases/4b1c6c/a7a304e11088b6482329a6db6951a0a786085586.html | inapplicable | passed       |
| https://act-rules.github.io/testcases/4b1c6c/ed51fa0ad018a0d0c3a108b0a41b0edb9d564d80.html | inapplicable | passed       |
| https://act-rules.github.io/testcases/4b1c6c/99671a0c36e00e56fdfdb74a8967066cbc350606.html | inapplicable | passed       |
| https://act-rules.github.io/testcases/4b1c6c/8bedea37dd212bca4a10369cf3bab21d3eda69eb.html | inapplicable | passed       |

**Comment by dylanb** [comment]
@jkodu The links to the two failed cases result in 404s

Besides that though, I am having trouble thinking of an example that is real where two iframes could possibly have the exact identical purpose!?

**Comment by jkodu** [comment]
@dylanb it was for this rule - https://act-rules.github.io/rules/4b1c6c

I will close this and reopen after testing again.
