### ISSUE TITLE
Add all reporters to doc/API.md

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#1560]
Expectation: All available reporters in axe-core are listed in the API docs.

Actual: only v1 and v2 are documented.

**Comment by straker** [comment]
None of the reporters describe what they do exactly. Do you have a summary of them? Looking at the code this is my best guess:

- `raw` to return the raw result data without formating: `axe.configure({ reporter: "raw" });`
- `raw-env` to return the raw result data with environment data without formating: `axe.configure({ reporter: "raw-env" });`
- `no-passes` to return only violation results: `axe.configure({ reporter: "no-passes" });`
 - `na` (no idea what this reporter does)

**Comment by jeankaplansky** [comment]
Doc is present and accounted for, but no one specifically validated @straker's best guess. @WilcoFiers, @jkodu? Did he guess right? I'm moving this ticket to QA in the meantime. Please make a new sprint-ready ticket for any required corrections for 7/1. Thanks!

**Comment by somaalapati** [comment]
Now rest of the 3 reporting types have been added to doc/API.md file. So, closing this ticket. (will close this after getting confirmation on expected details from @WilcoFiers.

![image](https://user-images.githubusercontent.com/40261789/61725392-589a1e00-ad8d-11e9-9bd5-64aeaa47f6d0.png)
