### ISSUE TITLE
Why not put navigation role on ‘ul’?

### ISSUE THREAD

**Issue by lkmorlan** [dequelabs/axe-core#1574]
```
<ul role="navigation" aria-label="...">
<li><a href="...">...</a></li>
<li><a href="...">...</a></li>
<li><a href="...">...</a></li>
</ul>
```
The above code triggers the issue "ARIA role must be appropriate for the element". I don't see anything wrong with this. I could wrap the `ul` in a `div` and put the `role` attribute there, but how does that actually make it any better? It looks like cruft to me.

**Comment by stephenmathieson** [comment]
I suggest wrapping your `<ul>` with a `<nav>` element for that, since a [`<ul>` should have an implicit role of "list"](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/List_role).

**Comment by lkmorlan** [comment]
Thanks. I had thought that `<ul role="navigation" ...>` would end up with semantics of "a list of navigation items". I've done some more reading and I think the longer answer is that a it can't have two meanings at the same time, so it has to be a list inside a navigation element. So, your suggestion is a good one.
