### ISSUE TITLE
getFlattenedTree fails on firefox in pages with <content> elements

### ISSUE THREAD

**Issue by AdnoC** [dequelabs/axe-core#1576]
Expectation: It shouldn't error.

Actual: It errors with `TypeError: "e.getDistributedNodes is not a function"`.

Motivation: Crashing on `axe.run` isn't good.

Expected to occur on any page developed with shadow DOM v0.

Error occurs on line 110 of `lib/core/utils/flattened-tree.js`. It calls `getDistributedNodes()` when the node is a `<content>` element. The issue is that `getDistributedNodes()` [is deprecated](https://developer.mozilla.org/en-US/docs/Web/API/HTMLContentElement/getDistributedNodes) and removed from Firefox.

Minimal page that triggers the bug (taken from this [MDN page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/content)) ([this page as well](https://www.fabasoft.com/de/loesungen/produktmanagement)):

```html
<html>
  <head></head>
  <body>
  <!-- The original content accessed by <content> -->
  <div>
    <h4>My Content Heading</h4>
    <p>My content text</p>
  </div>

  <script>
  // Get the <div> above.
  var myContent = document.querySelector('div');
  // Create a shadow DOM on the <div>
  var shadowroot = myContent.createShadowRoot();
  // Insert into the shadow DOM a new heading and 
  // part of the original content: the <p> tag.
  shadowroot.innerHTML =
   '<h2>Inserted Heading</h2> <content select="p"></content>';
  </script>

  </body>
</html>


```

<pre><code>
axe-core version: 3.2.2
axe-webdriver, extension or other integration version: Extension version: HEAD (afc711a52806daf79a226e6fb8b55d56408a3255)

Browser and Assistive Technology versions

For Tooling issues:
- Platform:  Firefox 66.0.5, Mac
</code></pre>

Cause of https://github.com/dequelabs/axe-core/issues/1512

**Comment by AutoSponge** [comment]
For Docs: Not sure if we need to document this or not, but since `<content>` was deprecated, we're just following up. Anytime the element isn't supported (currently FF) we treat it like a `<div>`, the same way the engine will treat it as an unrecognized element.

**Comment by jeankaplansky** [comment]
The point that "anytime an element isn't supported (currently FF) we treat it like a `&lt;div&gt;,` the same way the engine will treat it as an unrecognized element" isn't something that we diverge from normal FF functionality...

I don't think we're on the hook for documenting that we match FF functionality over a deprecated shadow DOM element.

@WilcoFiers : Opinion?

**Comment by jeankaplansky** [comment]
Wilco agrees this is not a documentation issue.

**Comment by chandana7393** [comment]
Tested with the above code violations are not displayed.
![content_no_violations](https://user-images.githubusercontent.com/45285854/59428311-81c4a780-8dfa-11e9-9290-a03ef037e99b.PNG)
**Tested Environment:**
Axe-coconut - 3.8.0.16404v
Chrome - 75v
OS- Windows 10 64 bit.

**Comment by chandana7393** [comment]
Tested, "Inserted Heading" was not displayed on Firefox browser because of that unable to see the issues on Axe/Attest Firefox.
![No_content_violations](https://user-images.githubusercontent.com/45285854/60242289-f60b4a80-98d2-11e9-8236-ca2a8d4fe1ae.PNG)
**Tested Environment:**
Axe - 3.8.0.15616v
Attest - 2.5.0.15616v
Firefox - 66v
OS - Windows 10 64 bit.
