### ISSUE TITLE
aria-required="true" not allowed for checkboxes or radios

### ISSUE THREAD

**Issue by asparaguscat** [dequelabs/axe-core#158]
```<input type="checkbox" id="id" name="checkbox" aria-required="true">```
```<input type="radio" name="radio" value="male" aria-required="true">```

ARIA attribute is not allowed: aria-required="true"

**Comment by WilcoFiers** [comment]
Hi Asparaguscat. This is the correct implementation of ARIA 1.1. In ARIA, checkboxes and radiobuttons can not be required. Elements with the role of radiogroup can be required, but not the radiobuttons themselves. As for checkboxes, in a way these element always provide a value (checked or unchecked). I'm guessing that when you mean to make such an element 'required' you intend for it to be checked. This is a common enough use case. The aria-required attribute does not permit a 'null' result. But a checkbox never gives null, it only gives a true or false value.

**Comment by asparaguscat** [comment]
So I should apply aria-required to the fieldset containing the checkboxes or radios?
