### ISSUE TITLE
scrollable-region-focusable rule causing false positives

### ISSUE THREAD

**Issue by kensgists** [dequelabs/axe-core#1582]
This new rule is causing standard accessible text clipping techniques to fail. For example, this CSS:

`
.accessible-text { 
    position: absolute !important;
    clip: rect(0.0625rem 0.0625rem 0.0625rem 0.0625rem);
    clip: rect(0.0625rem, 0.0625rem, 0.0625rem, 0.0625rem);
    padding: 0 !important;
    border: 0 !important;
    height: 0.0625rem !important;
    width: 0.0625rem !important;
    overflow: hidden;
}
`

is marked as a violation in axe-coconut.

@WilcoFiers pointed out above that elements with overflow:hidden might be exempted. I think this is a good idea.

We use axe-coconut for testing because of some of the useful experimental rules. But now we are getting vast numbers of false positives due to this new rule.

Note: I put this same text mistakenly on the PR for this rule....

**Comment by WilcoFiers** [comment]
Yikes! Good find. Thanks Ken! I'll make sure we fix it before the 3.3 release.

**Comment by chandana7393** [comment]
Working as expected.
![conatiner_scrollable](https://user-images.githubusercontent.com/45285854/58782410-245f7800-85fc-11e9-8c10-88fec327f50d.PNG)
**Tested Environment:**
Axe-coconut - 3.8.0.15404v
Chrome - 74v
OS - Windows 10 64 bit.

**Comment by backwardok** [comment]
@WilcoFiers noticed this issue is happening again. Using the axe-core 4.3.5, a clipped overflow region is getting flagged as a scrollable region

I made a really [simple codepen with overflow examples](https://cdpn.io/backwardok/debug/bGrxdMO) where axe is flagging the page as having an issue for the clipped content.

**Comment by straker** [comment]
@backwardok I see what's going on. Could you open a new issue so we can track it? Thanks.

**Comment by backwardok** [comment]
@straker sounds good! I'll create a new ticket
