### ISSUE TITLE
[BUG] - Cannot read property 'getRootNode' of undefined

### ISSUE THREAD

**Issue by GianlucaGuarini** [dequelabs/axe-core#1589]
Expectation: it should generate the audits

Actual: it throws an exception error
```
TypeError: Cannot read property 'getRootNode' of undefined
    at Object.$.utils.getSelector (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/adapter.bundle.js:93:83969)
    at W.get selector [as selector] (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/adapter.bundle.js:93:74973)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/adapter.bundle.js:93:66962
    at Array.map (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/adapter.bundle.js:93:66781
    at Array.map (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/adapter.bundle.js:93:66677
    at Array.forEach (<anonymous>)
    at Object.f.processAggregate (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/adapter.bundle.js:93:66500)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/adapter.bundle.js:93:68664
```

Motivation: it's a bug, may I help you to fix it?

<pre><code>
axe-core version: 3.2.2
axe-webdriver, extension or other integration version: 3.8.0 

Browser and Assistive Technology versions
Chrome

For Tooling issues:
- Platform:  Mac
</code></pre>

**Comment by GianlucaGuarini** [comment]
The issue is reproducible analyzing the size: https://www.dreipol.ch/

**Comment by straker** [comment]
Thanks for the issue. I can reproduce it on the site. The problem seems to be that there's an element that starts in the DOM when the page is at the top, but after we scroll the page down to the bottom the element is removed from the DOM.

**Comment by GianlucaGuarini** [comment]
@straker If you want I could look into this and make a PR at least to avoid hard failures in such cases.

**Comment by straker** [comment]
Thanks! PRs are always welcome. Let me know if you have any questions.

**Comment by GianlucaGuarini** [comment]
I have tried hard to create a test to reproduce the issue and submit a patch for it but until now I wasn't able to recreate the conditions that throw the error.
The code should be patched [here](https://github.com/dequelabs/axe-core/blob/develop/lib/core/utils/get-selector.js#L386-L406) but I need some help with the unit test.

**Comment by straker** [comment]
Sure. I think a test that just removes the element from the DOM (or ensures it doesn't have a `getRootNode`) before calling `getSelector` should suffice. Something like

```js
  var fragment = document.createDocumentFragment();
  var node = document.createElement('div');
  fragment.appendChild(node)
  fixtureSetup(fragment);
  axe.utils.getSelector(fragment);
```

**Comment by straker** [comment]
@GianlucaGuarini how goes the pr? still need help?

**Comment by GianlucaGuarini** [comment]
@straker thank you for the reminder but I don't think I will have time to set up a PR in the near future. I a too busy at moment sorry. Let me want me to close this issue because in the end I was able to fix the bug on my side.

**Comment by jeankaplansky** [comment]
No new docs required.

**Comment by chandana7393** [comment]
@straker what needs to be QA here?? Can you please provide the required information.

**Comment by straker** [comment]
@chandana7393 the site seems to have removed the problem since it was reported, so I'm not sure of a good way to test this now without recreating the test case (a page with a large vertical scroll and a fragment element on the page that removes itself on scroll).

**Comment by chandana7393** [comment]
Dev Task.
