### ISSUE TITLE
axe overwriting window variable when using minified JS

### ISSUE THREAD

**Issue by bcstodds** [dequelabs/axe-core#1593]
Expectation: Axe works on a page that is running minified JS.

Actual: Axe overwrites the minified variable `window.axe` when injected. The variable later gets over-written by the process that originally set up `window.axe`, and then tests fail with `axe.run is not a function`.

Motivation: Axe should be injected onto the window on a variable that is less likely to be have a collision with minified variable names. My suggestion would be `window.__axe`.

axe-core version: 2.5.1 & 3.1.2. Problem should be version agnostic.

**Comment by bcstodds** [comment]
I've started a pull request here:
http://go/gh/dequelabs/axe-core/pull/1592

I acknowledge that this could cause issues with other tooling that expects axe to be injected as `window.axe` and would like any thoughts from the package maintainers.

**Comment by straker** [comment]
Thanks for bringing this to our attention. Unfortunately renaming the global object would cause too many breaking changes to tooling and our own extensions. 

Could you provide an example of the problem? From what I understand a minifier won't mangle global variable names unless you specifically tell it to, so I'm curious what is overriding the global namespace.

**Comment by bcstodds** [comment]
I'll see if I can create something shareable that demonstrates it, but at least so far it's looked like something coming from the Angular app we're testing is setting `window.axe` after (and possibly before) axe is being injected.

I'm not surprised that this would break a lot of tooling... I was just hopeful it might not :)

**Comment by bcstodds** [comment]
So in our case I was able to find a place to plug in `axe` as a reserved name so that it wouldn't be used by the compiled/minified JS. That should solve our issue, and is probably the correct path forward for anyone else hitting something like this.
