### ISSUE TITLE
documentation update: Clarification on rule-descriptions for audio-captiion

### ISSUE THREAD

**Issue by justmedude** [dequelabs/axe-core#1600]
Hello,

When I read through rule-descriptions.md, I see the following for the audio-caption:

Rule ID | Description | Impact | Tags | Enabled by default
--------| ----------- | ---- | ----- |------------------- | 
audio-caption |  Ensures \<audio\> elements have captions | Critical | cat.time-and-media, wcag2a, wcag121, section508, section508.22.a | false

However, as I read through the WCAG specifications, this seems as if it matches the tag of wcag122

Motivation: Just want to be sure the documentation is accurate. I'm happy to submit a pull request if my concern is valid.

**Comment by dylanb** [comment]
@goodwitch I think this is better - wdyt?

**Comment by WilcoFiers** [comment]
This issue is incorrect. The `audio` element is `audio-only`, which is tested by 1.2.1. SC 1.2.2 is for synchronised media, which is video with audio, not just audio.

**Comment by dylanb** [comment]
There could be other alternatives for pre-recorded audio that are not captions and one could still meet 1.2.1
