### ISSUE TITLE
"ARIA role slider is not allowed for given element" violation is displayed under best practices.

### ISSUE THREAD

**Issue by chandana7393** [dequelabs/axe-core#1608]
The following should fail
![input_line](https://user-images.githubusercontent.com/45285854/58950951-94f9c680-87ad-11e9-8ce7-ac94a5ffa8c8.PNG)

![violation_under_best_practice](https://user-images.githubusercontent.com/45285854/58950507-97a7ec00-87ac-11e9-81f2-3fa1a2fe3d4c.PNG)

![input_slider](https://user-images.githubusercontent.com/45285854/58950025-72ff4480-87ab-11e9-9a6a-0a19ffb4b2eb.PNG)
Above code is rendered as text box in the page but as role="slider" is used for the input tag the NVDA is announcing it as a Slider which is not appropriate for visual users.

**Environment:**
Axe-coconut - 3.8.0.15604v
Chrome - 74v
OS - Windows 10 64 bit.

CC: @padmavemulapati

**Comment by straker** [comment]
I don't believe this is a problem as these are two separate checks. The aria-valuenow check is valid for `<input type="text" role="slider">` as it has a `value` property. The aria-role check is also correct as it flags `<input role="slider">` as not a valid role for the input type.
