### ISSUE TITLE
Test the checks as part of integration tests

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#1609]
Axe-core's integration tests only test the outcome, but not if we get the results from the checks the way we'd expect them to. Because of this, we're not testing that the remediation advise we want to give is actually set up the way we want it to.

This has caused a number of bugs:
- https://github.com/dequelabs/axe-core/issues/1326
- https://github.com/dequelabs/axe-core/issues/1192
- https://github.com/dequelabs/axe-core/pull/683

We need to add capabilities to our integration tests so that we can verify that the remediation advise makes sense.

**Comment by dylanb** [comment]
#1326 is just a plain-old bad implementation - it is one of the oldest checks and simply did not get enough proper scrutiny at the time
#1192 is a case of the remediation suggestion being incomplete, it should be more specific about where an `alt` attribute can be applied
#683 is an edge case of accessibility supported, or it is just the same as #1192 

Are we overcomplicating things here?

**Comment by straker** [comment]
We are catching this through reviews these days, haven't seen it as a problem for awhile.
