### ISSUE TITLE
Improve error handling in aXe

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#161]
Much of axe runs async through the queue. Because of this, errors that are thrown can't be caught in the method that initiated the failing function. The callback system in axe doesn't use errors. We could use Promises to get manage failing async actions.

**Comment by dylanb** [comment]
We should implement this as a "node style" callback function in a backwards compatible way. We can then easily wrap this in a promise. Internally we can use the deque deferred object to manage the async calls.

**Comment by WilcoFiers** [comment]
Resolved in the next release
