### ISSUE TITLE
has-visible-text check not working as expected

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#1611]
The way `has-visible-text` is set up suggests it looks at visible text content. This isn't true though. Instead, it looks at the accessible name. Instead of calling `text.accessibleText` this needs to run `text.subtreeText`. We'll have to look carefully about what the impact of that change is though.

**Comment by dylanb** [comment]
This seems to me to be a bug, so it just needs to be fixed

**Comment by straker** [comment]
Rename to `has-accessible-text`.

**Comment by straker** [comment]
Should be part of #1006

**Comment by straker** [comment]
Closed via https://github.com/dequelabs/axe-core/pull/2234
