### ISSUE TITLE
Help reading results?

### ISSUE THREAD

**Issue by asparaguscat** [dequelabs/axe-core#162]
Violations have nodes, which can contain lists of elements in a property called 'any' or a property called 'none'. What is the significance of which list violation elements appear in?

**Comment by dylanb** [comment]
Here is some code that turns this structure into readable text. this should help you understand the structure better. If you'd like to contribute to the docs to make this more understandable, please do!!

https://github.com/dequelabs/axe-core/blob/master/doc/examples/html-handlebars.md
