### ISSUE TITLE
color-contrast message: prevent "pt" vs "px" misreadings

### ISSUE THREAD

**Issue by dbjorge** [dequelabs/axe-core#1628]
The color-contrast check includes the computed font size of the element being checked in its failure message in format "13.5pt". Recently, we've seen multiple false false-positive reports due to misreading this as "13.5px". We think it would be much harder to misread if it were instead formatted like "13.5pt (18px)" or "13.5pt / 18px" or similar - `color-contrast.js` already computes both anyway, so this should be a relatively minor change to the check implementation.

**Expectation**: A color-contrast check fail message like *"Element has insufficient color contrast of 4.21 (foreground color: #00809d, background color: #f5f5f5, font size: **13.5pt (18px)**, font weight: bold). Expected contrast ratio of 4.5:1"*

**Actual**: The color-contrast check's fail message currently looks like *"Element has insufficient color contrast of 4.21 (foreground color: #00809d, background color: #f5f5f5, font size: **13.5pt**, font weight: bold). Expected contrast ratio of 4.5:1"*

**Motivation**: We recently had a false report of an Accessibility Insights for Web false positive that turned out to be because a customer (and then a few of our engineers) misread the color-contrast check message's description of font-size in "pt" as "px" instead. A quick glance through similar axe-core issues suggests that a different user had a similar bit of confusion recently in #1585 - if multiple users are reporting similar confusion, we think it's probably worth making the minor update to alleviate it :)

<pre><code>
axe-core version: 3.2.2
Accessibility Insights for Web: 2.4.1
Chrome: 74.0.3729.169
</code></pre>

**Comment by straker** [comment]
That's a good idea. I'll see what it will take to implement.

**Comment by jeankaplansky** [comment]
The rule help is very explicit re: pts and the CSS pixel translations. No further rule help documentation required.

**Comment by chandana7393** [comment]
Tested, appearing as expected.
![axe_coconut_px](https://user-images.githubusercontent.com/45285854/61215202-bbedd580-a727-11e9-88a2-e6eb847244ca.PNG)
**Tested Environment:**
Axe-coconut - 3.8.1.19604v
Chrome - 75v
OS - Windows 10 64 bit.
