### ISSUE TITLE
Outdated relative luminance threshold

### ISSUE THREAD

**Issue by SashimiEthan** [dequelabs/axe-core#1629]
Expectation: << Describe what you expect the product to do >>
Use the correct relative luminance threshold: 0.04045 

Actual: << Describe what the product actually does >>
[The current threshold 0.03928](https://github.com/dequelabs/axe-core/blob/1bac69e21c2dfd7734f97b3adde5392688957bc4/lib/commons/color/contrast.js#L102-L106) used in the sRGB definition is [outdated](https://www.w3.org/Graphics/Color/sRGB.html).

There is already a bug filed against this issue in the wcag repo: https://github.com/w3c/wcag/issues/360

Motivation: << Describe why you want the behavior to be changed >>
Although there will be no visible difference in calculated contrast ratio from using the draft or the final standard threshold values, please refer to the discussions in the [wcag repo](https://github.com/w3c/wcag/issues/360) for the detailed justification. I'm not an expert in color spaces. Our company Microsoft's accessibility tool is using this library, so just wanted to bring this to your attention. 

<pre><code>
axe-core version: current
</code></pre>

**Comment by straker** [comment]
Thanks for letting us know about the outdated threshold. I'll bring this up and see if we're ready to update the threshold before the wcag issue is accepted and all the specs are updated.

**Comment by Myndex** [comment]
I am the W3C member who is working on these issues in the WCAG. The correct threshold for the reverse transform (going to linear) is 0.04045 and this should be used, not 0.03928 as incorrectly listed in the WCAG Understanding document. Also, the sRGB working draft from 1996 is not the standard, IEC 61966-2-1:1999 is the relevant international standard for sRGB.

There is no real reason to use the incorrect threshold. In terms of the WCAG contrast measurement, it functionally make no difference, but it can make a difference if you are using the equation for image processing. As a matter of best practices, the correct math should be used for converting sRGB to linear RGB.

For background, the reason for the change from the original sRGB draft has to do with a discontinuity at the intercept between the power curve and the linearized segment. 

There are some color transform libraries that use a more accurate (more decimal places) method which is advisable if you are doing multiple round trips for image processing applications. In the case of the reverse transform  This is discussed to some degree in the [Wikipedia page on the subject.](https://en.wikipedia.org/wiki/SRGB)

Nevertheless the **_DEFINED STANDARD_** is **0.04045**

**Comment by WilcoFiers** [comment]
I'm going to close this issue. I think staying consistent with the normative requirements from WCAG is very important for the work, even if the math is wrong. The place to fix this is in the WCAG standard. W3C can publish an errata to WCAG. We'll update it if/when this happens.
