### ISSUE TITLE
axecore is not recognizing the iframe inside elements

### ISSUE THREAD

**Issue by prabusundararaj** [dequelabs/axe-core#1631]
Summary: I am using axe-core npm module into our automation repository to run the accessibility rules, but there is a iframe inside the webpage which is not recognizing by axe.  There is no error throws, but it ignored the iframe web elements.

Expectation: axe.run function should work inside iframe webElements and finds out the accessibility issues.

Actual: its not running the accessibility stuff.

Motivation: << Describe why you want the behavior to be changed >>

<pre><code>
axe-core version:3.2.2
axe-webdriver, extension or other integration version: Using WebDriverIO

Browser and Assistive Technology versions

For Tooling issues:
- Node version: v8.11.1
- Platform:  MAC
</code></pre>

**Comment by dylanb** [comment]
@prabusundararaj are you injecting axe-core into the iframes?

**Comment by prabusundararaj** [comment]
Yes, I am injecting, but it is reactJS frame

**Comment by Kwon11** [comment]
Hi, I am having the same problem.

I load the iframe inside of a react component, and pass in a function to the iframe.onLoad

It fires, and I can see in the inspector that inside the iframe > document > head that the script is in there.

My webpack-dev-server is serving the script, and when I right click the element and "Reveal in sources panel" I am taken to the axe.min.js.

Yet when I run axe-core (and run it again just in case it ran before the script was appended to the iframe.head) I still get the "frames must be tested with axe core" error.

I cannot find another issue documenting this error, @dylanb any insight would be appreciated.

**Comment by dylanb** [comment]
@Kwon11 can you create a Codepen with an example?

**Comment by HectorLS** [comment]
Adding to the recognizing iframe issue i think we should add side issues. 
example case:  Axe return an error about **Page must contain a level-one heading** by having more than one `<html>` tag, but the other html tags are the one from the iframe so..

**Comment by straker** [comment]
I believe I have a [reproducible test case](https://codepen.io/straker/pen/xxxBqyj). The frame is injected with axe, but for some reason the outside axe does not see it.

**Comment by straker** [comment]
Nevermind, turns out I wasn't waiting for the frame to load before running axe. My test case now shows that it is working as intended. As this issue is 5 months old I'm going to close for now. @prabusundararaj if you are still getting this error and can provide a reproducible test case we can reopen.

@HectorLS Please feel free to open a new issue for your request.
