### ISSUE TITLE
typings: optional property 'xpath' missing from NodeResult

### ISSUE THREAD

**Issue by lisli1** [dequelabs/axe-core#1636]
Expectation: The documentation (https://www.deque.com/axe/axe-for-web/documentation/api-documentation/#options-parameter) lists `xpath` as an option that "returns xpath selectors for elements", so `NodeResult` should have the optional parameter `xpath`.

Actual: `xpath` is not an optional parameter of `NodeResult` in `axe.d.ts`

Motivation: This causes type-checking errors in our [project](https://github.com/microsoft/axe-sarif-converter) 

<pre><code>
axe-core version: 3.2.2
axe-webdriver, extension or other integration version: N/A

Browser and Assistive Technology versions

For Tooling issues:
- Node version: 10.15.3
- Typescript version: 3.4.5
- Platform:  Windows
</code></pre>

**Comment by jeankaplansky** [comment]
@straker - we can fix the documentation here: https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#options-parameter

It's up to marketing to update the content on deque.com though. This is something you can fix yourself in the api.md file, yes? Please advise. Thanks!

**Comment by straker** [comment]
@jeankaplansky there's no doc update needed. This was just a Typescript file that needed updating.

**Comment by jeankaplansky** [comment]
@straker: So we don't need to remove:

"xpath	false	Return xpath selectors for elements"

from the options table? Please confirm and I'll move this one along.

**Comment by straker** [comment]
Correct, this was just updating the TypeScript file. No docs needed

**Comment by somaalapati** [comment]
@straker Please close this issue if it cannot be testable by QA.
