### ISSUE TITLE
Manifest error on axe-firefox  extension installation

### ISSUE THREAD

**Issue by padmavemulapati** [dequelabs/axe-core#1647]
axe version -3.8.1.17023 and Firefox - 66v

![axe_firefox_manifest](https://user-images.githubusercontent.com/47409579/59861449-734c3200-939e-11e9-978e-48be63ad2b98.PNG)

**Comment by chandana7393** [comment]
Still reproducible.
![Manifest_error](https://user-images.githubusercontent.com/45285854/59909523-7d694180-942d-11e9-882f-4a27d30587aa.PNG)
**Tested Environment:**
Axe - 3.8.1.17117v
Firefox - 66v
OS - Windows 10 64 bit.

**Comment by straker** [comment]
Thanks for reporting the issue. We're working on a fix and should have it out soon.

**Comment by chandana7393** [comment]
Tested, no more manifest error is existing.
![axe_firefox_manifest](https://user-images.githubusercontent.com/45285854/59996171-3c646d80-9677-11e9-8eba-87aa4d41e351.PNG)
**Tested Environment:**
Axe - 3.8.1.17323v
Firefox - 66v
OS - Windows 10 64 bit.
