### ISSUE TITLE
"explicit-label" check should look at all labels

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core#1654]
@WilcoFiers noticed this while looking into a different bug, but the `explicit-label` check only looks at the first label associated with the input but it should look at all labels associated with the input.

**Comment by straker** [comment]
@WilcoFiers how should the check handle multiple labels? Should it return true if at least one label is visible and has text?

**Comment by WilcoFiers** [comment]
use querySelectorAll and loop to find if any label is visible.

**Comment by padmavemulapati** [comment]
Verified with the latest axe-core(v4.0.2) dated 22/10/2020 - 
test source snippet - ` <label for="target"></label><label for="target">Text</label><input type="text" id="target">`
Even multiple labels , explicit label check is passing and returning true if input and label are in the same shadow root
![image](https://user-images.githubusercontent.com/47409579/96880801-395fd400-149b-11eb-8004-a8dbb0731a4c.png)

Reproducible with axe-core3.5.4: here it is failing for `<input>` labels
![image](https://user-images.githubusercontent.com/47409579/96881640-1d106700-149c-11eb-85f4-23d435ef36c5.png)
