### ISSUE TITLE
Form <input> elements must have labels   - documentation example missing

### ISSUE THREAD

**Issue by newschapmj1** [dequelabs/axe-core#1661]
Form <input> elements must have labels
https://dequeuniversity.com/rules/axe/3.2/label

Expectation: Valid example provided, preferably >1 example

Actual: Example telling you **not** what to do
"When adding labels, be sure to avoid the following:

`First name: <input type="text" name="fname"> "`

Motivation: 'Don't make me think'  - help people to fix their code.

**Comment by straker** [comment]
Thanks for the suggestion. I'll pass the information along to the documentation team.

**Comment by jeankaplansky** [comment]
Addressed for 4.0 release. Added https://www.w3.org/WAI/tutorials/forms/labels/ to 3.5 release to provide more specific how-to information.

**Comment by newschapmj1** [comment]
Nice work, thanks
