### ISSUE TITLE
Should muted videos require caption?

### ISSUE THREAD

**Issue by Antonio-Laguna** [dequelabs/axe-core#1674]
Expectation: `muted` videos should not be flagged as need track.

Actual: `muted` videos should are flagged as need track.

Motivation: While I understand tracks for hearing impairment, background videos with no sound and that are specifically marked as muted, and usually autoplay, should not be flagged as critically?

Seen #249 and #285 but this is still around.

**Comment by straker** [comment]
The caption rule should return `Needs Review` for videos without a track. So even though the video is muted we will flag it for manual review. 

Just so there's no misunderstanding, you'd like that videos with the `muted` attribute not be flagged as `Needs Review`?

**Comment by Antonio-Laguna** [comment]
I think needs review would be fair but as far as I can remember was critical.

**Comment by straker** [comment]
Ah, I see. Yes, the `video-caption` rule is marked as `impact: critical`. Unfortunately, there's not much we can do about changing the impact level based on the attributes of the element. It's all based on the rule itself.

**Comment by WilcoFiers** [comment]
Conversation has gone stale, closing it.
