### ISSUE TITLE
Axe conflicts with Bluebird Promise

### ISSUE THREAD

**Issue by dhart3** [dequelabs/axe-core#1678]
Expectation: aXe does not overwrite a Bluebird Promise already defined in the existing page.

Actual: For example: getting ".bind is not a function" when trying to access the bind function of the Promise.

Motivation: Axe overwrites the Bluebird Promise with a local version, because the Bluebird Promise evaluates to [object Object] so the evaluation at line 2171: <code>if (promiseToString === '[object Promise]' && !P.cast)
</code> is not satisfied.

We commented out line 2175 (<code>local.Promise = Promise$1;</code>) and it fixed the problem.

<pre><code>
axe-core version: v3.2.2
axe-webdriver, extension or other integration version: axe-selenium version 3.0

Browser and Assistive Technology versions

For Tooling issues:
- Node version: v8.11.2
- Platform:  Linux, Windows
</code></pre>

**Comment by straker** [comment]
Interesting. We should only be adding the polyfill if `Promise` isn't on the window object. https://github.com/dequelabs/axe-core/blob/develop/lib/core/imports/index.js#L13-L15

I'm unfamiliar with how Bluebird works, but does not add the Promise to the window object?

**Comment by dhart3** [comment]
Hi, 

It does. We did not test this yet, but we think the above would work for us.

Thanks,
Diana

**Comment by WilcoFiers** [comment]
@dhart3 can you check with axe-core@latest if this has been solved for you?

**Comment by dhart3** [comment]
This issue is solved when testing with axe-core 3.3.0.
