### ISSUE TITLE
v3.3.0 appears to be missing a changelog entry

### ISSUE THREAD

**Issue by bjankord** [dequelabs/axe-core#1681]
When going to view what's in v3.3.0 in [the changelog](https://github.com/dequelabs/axe-core/blob/develop/CHANGELOG.md), I didn't notice any entry for that release.

<img width="1318" alt="Screen Shot 2019-07-08 at 2 13 11 PM" src="https://user-images.githubusercontent.com/633148/60836145-94789500-a18a-11e9-93af-00457b9c9a73.png">

I checked the release notes page for 3.3.0 and didn't find much info on new items in this release there either. https://github.com/dequelabs/axe-core/releases/tag/v3.3.0

**Comment by straker** [comment]
Thanks for letting this know. We should have the changelog and release tags updated shortly.

**Comment by straker** [comment]
Changelog entry has been added.
