### ISSUE TITLE
False positive on page title and language 

### ISSUE THREAD

**Issue by paulbohman** [dequelabs/axe-core#169]
aXe reports a missing page &lt;title&gt; and missing lang attribute on the page for the BBC web site http://www.bbc.com/ but both are present. FireEyes doesn't have this false positive (neither does WAVE). The code snippet in aXe gives the impression that aXe thinks the page is completely empty. The code snippet in aXe is simply:

&lt;html&gt;&lt;head&gt;&lt;/head&gt;&lt;body&gt;&lt;/body&gt;&lt;/html&gt;

The real code shows:
&lt;html class=" b-pw-1280" lang="en" &gt;
and 
&lt;title&gt;BBC - Homepage&lt;/title&gt;

I can't reproduce this bug on other web sites, only on BBC, so there must be something about the BBC site causing the problem, but I can't see what it would be.

**Comment by paulbohman** [comment]
Another site that causes a false positive for me on page title is amazon.com

**Comment by paulbohman** [comment]
Ok, it's got to be the iframes causing the error to show up. So this is a feature, not a bug... sort of. We need to be able to distinguish between errors in the main page versus errors in iframes. Put a flag or label on iframe errors to let people know where to look for the issue. It's confusing as it is now. It seems like it's reporting false positives, even though it's not.

**Comment by trav-is** [comment]
thank you paul,
based on our earlier conversation re: this issue I would suggest it be closed and the discussion about iframes be continued elsewhere.
You are right that this is a feature and not a bug, many tools do not look into iframes.

**Comment by dylanb** [comment]
Interesting thing about that iframe on that site is that it seems to be temporary and disappears later.

**Comment by dylanb** [comment]
What you will also notice is that there are other iframes on that page without titles, but that are display:none or otherwise hidden and aXe does not complain about them. So this one is definitely a violation and an example of how aXe is better than WAVE at handling iframes and single page apps.

**Comment by WW3** [comment]
Happens here as well (not iframe) https://www.metropoline.com/Pages/Questions.aspx?p=RavKavHashron
