### ISSUE TITLE
Violations related to "Avoid inline spacing" rule of Axe-core 3.3 are not displayed.

### ISSUE THREAD

**Issue by chandana7393** [dequelabs/axe-core#1698]
**Steps to reproduce:**
1. Launch "Avoid inline spacing" rule related test file on the Chrome browser.
2. Launch Axe coconut extension.
3. Click on "Analyze" button.
**Actual:**
Issues related to Avoid inline spacing are not displayed.
![avoid_inline_spacing_violation](https://user-images.githubusercontent.com/45285854/61029750-5ae99900-a3d9-11e9-8933-b2bf8798712a.PNG)
**Expected:**
Issues related to Avoid inline spacing must be displayed.
**Tested Environment:**
Attest-v2.5.1.20021
Axe-coconut - 3.8.1.19204v
Chrome - 75v
OS - Windows 10 64 bit.

CC: @padmavemulapati

**Comment by chandana7393** [comment]
Test file 
| <!DOCTYPE html>
-- | --
  | <html lang="en-US">
  | <head>
  | <title>avoid inline spacing</title>
  | </head>
  | <body>
  | <main>
  | <h1>Avoid inline spacing</h1>
  | <strong>Failing scenarios</strong>
  | 
  | <p id="fail1" style="line-height: 1.5 !important;">Banana error</p>
  | 
  | <p id="fail2" style="letter-spacing: 100em !important;">We need more cheeeeeeessseeeee!!!</p>
  | 
  | <p id="fail3" style="word-spacing: -.4ch !important;">
  | The cheese grater is in the way!</p>
  | 
  | <p id="fail4" style="word-spacing: 200%; letter-spacing: 50rem !important; line-height: 3;">Yo, Darth Vader</p>
  | <strong>Passing scenarios</strong>
  | 
  | <p id="pass1" style="font-size: 200%">I stepped on a Corn Flake, now I'm a Cereal Killer...</p>
  | 
  | <p id="pass2" style="line-height: 1.5;">
  | On a scale from one to ten, what is your favorite color of the alphabet.</p>
  | 
  | <p id="pass3" style="letter-spacing: 50px;">
  | The quick brown fox jumped over the lazy dog</p>
  | 
  | <p id="pass4" style="word-spacing: 10px;">A group of 24 Caterpillars has 694 legs</p>
  | 
  | <p id="pass5"
  | style="word-spacing: 20ch; letter-spacing: 50rem; line-height: 3;">Look, a distraction!</p>
  | </main>
  | </body>
  | </html>

**Comment by chandana7393** [comment]
`
<!DOCTYPE html>
<html lang="en-US">
<head>
	<title>avoid inline spacing</title>
</head>
<body>
<main>
	<h1>Avoid inline spacing</h1>
	<strong>Failing scenarios</strong>
	 
<p id="fail1" style="line-height: 1.5 !important;">Banana error</p>

<p id="fail2" style="letter-spacing: 100em !important;">We need more cheeeeeeessseeeee!!!</p>

<p id="fail3" style="word-spacing: -.4ch !important;">
	The cheese grater is in the way!</p>

<p id="fail4" style="word-spacing: 200%; letter-spacing: 50rem !important; line-height: 3;">Yo, Darth Vader</p>
<strong>Passing scenarios</strong>

<p id="pass1" style="font-size: 200%">I stepped on a Corn Flake, now I'm a Cereal Killer...</p>
 
<p id="pass2" style="line-height: 1.5;">
	On a scale from one to ten, what is your favorite color of the alphabet.</p>
 
<p id="pass3" style="letter-spacing: 50px;">
	The quick brown fox jumped over the lazy dog</p>

<p id="pass4" style="word-spacing: 10px;">A group of 24 Caterpillars has 694 legs</p>
 
<p id="pass5" 
style="word-spacing: 20ch; letter-spacing: 50rem; line-height: 3;">Look, a distraction!</p>
</main>
</body>
</html>`

**Comment by WilcoFiers** [comment]
This is quite weird. When I inject axe-core into the page directly it gives me the expected results, but then when I run axe-coconut it fails 1 thing it shouldn't, and ignores the rest (see Chandana's screenshot).

**Comment by straker** [comment]
I believe the issue is that the `avoid-inline-spacing` rule does not use a proper wcag tag to mark which level it is. At least for Attest, when we select which ruleset to use, it uses the tags of the rule to determine if it's active. Without the proper wcag tag, the rule is always disabled.

https://github.com/dequelabs/axe-core/blob/develop/lib/rules/avoid-inline-spacing.json#L4

**Comment by straker** [comment]
@jeankaplansky no docs needed

**Comment by chandana7393** [comment]
Tested, working fine in axe extension but in Attest and axe-coconut unable to see the violations related to avoid inline spacing.
![avoid_inline_spacing_axe](https://user-images.githubusercontent.com/45285854/62769418-9352c480-bab6-11e9-9fee-60e1d8860b80.PNG)
![avoid_inline_spacing_attest](https://user-images.githubusercontent.com/45285854/62769419-951c8800-bab6-11e9-9ee4-500b7f116b88.PNG)
![avoid_inline_spacing_axe_coconut](https://user-images.githubusercontent.com/45285854/62769431-98b00f00-bab6-11e9-8a67-f6c90e7566d3.PNG)
**Tested Environment:**
Axe - 3.8.1.22021v
Attest - 2.5.1.22021v
Axe-coconut - 3.8.1.22021v
Chrome - 76.0.3809.100v
Firefox - 68.0.1v
OS - Windows 10 64 bit.

**Comment by jeankaplansky** [comment]
See last QA note on #1301 for further information about behavior in axe-coconut and attest extensions.

**Comment by chandana7393** [comment]
Tested working as expected in Attest, but in axe-coconut unable to see the violation.
![axe_coconut_inline_space](https://user-images.githubusercontent.com/45285854/67270944-44be9f00-f4d7-11e9-87c8-ddbb6e0cd721.PNG)

**Tested Environment:**
Attest - 2.6.1.29416v
Axe-coconut - 4.0.0.29504v
Chrome - 77.0.3865.120v
Firefox - 69.0.3v
OS - Windows 10 64 bit.

**Comment by straker** [comment]
Axe-coconut was not running any wcag21 rules, have a fix pending

**Comment by padmavemulapati** [comment]
As per the @straker , axe-coconut fix not yet available, shall we keep this ticket open?

**Comment by padmavemulapati** [comment]
we should have a fix for axe-coconut,  with https://github.com/dequelabs/attest-browser-extensions/pull/1282, so will keep this ticket , not to close. Once the fix available , verify and will close.
