### ISSUE TITLE
Use static pages rather than actual websites in our examples

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#1699]
Since CI runs our examples, we need pages that are reliably available and have known results.

**Comment by straker** [comment]
Do we have a list of static pages that don't change we can test against, or is this something I'd need to create just for testing?

**Comment by straker** [comment]
https://github.com/dequelabs/axe-fixtures

**Comment by straker** [comment]
Looks like these 3 example tests use and actual website (`http://www.deque.com`):
- phantomjs
- puppetter
- chrome-debugging-protocol (however it's `test` command noops so doesn't actually run the tests)
