### ISSUE TITLE
False positive: 'scrollable-region-focusable' failure for a scrollable region containing focusable content positioned using CSS

### ISSUE THREAD

**Issue by iamrafan** [dequelabs/axe-core#1701]
Expectation: Not fail the 'scrollable-region-focusable' rule

Actual: There is a 'scrollable-region-focusable' failure here

Motivation: The scrollable region contains focusable elements, hence should pass this rule

Demo: https://www.bing.com/

<pre><code>axe-core version: 3.3.0-canary.5b05eb5
axe-Coconut version: 3.8.1</code></pre>

**Comment by straker** [comment]
I'm unable to reproduce this on the bing page using axe-core v3.3.0 nor axe-coconut v3.8.1 (axe-core 3.3.0-canary.e9f9c18).

**Comment by iamrafan** [comment]
@straker I am still able to reproduce this bug, please re-try
![image](https://user-images.githubusercontent.com/22068434/61327227-42a8be00-a7cd-11e9-92a1-761f8d7b3d91.png)

**Comment by straker** [comment]
![image](https://user-images.githubusercontent.com/2433219/61331519-64ab3c00-a7df-11e9-92b9-3272435bcdc7.png)

**Comment by dylanb** [comment]
I am seeing it, did you scroll down?

![image](https://user-images.githubusercontent.com/79245/61378464-72120600-a873-11e9-8131-90667e7a011d.png)

**Comment by straker** [comment]
I did. I also tried to change the window size and still am not getting it.

The difficulty is that Bing seems to be sending different markup based on unknown factors. I'm getting completely different violations. Are either of you logged into Bing? Maybe language settings or location is determining it?

![image](https://user-images.githubusercontent.com/2433219/61382583-4c343380-a86a-11e9-8d04-72aa74578263.png)

**Comment by WilcoFiers** [comment]
I'm having the same issues as Steve. @iamrafan can you put together something so we can reliably reproduce the issue?

**Comment by iamrafan** [comment]
@iamrafan I have created an example similar to the one on bing. Please let me know if it helps

https://codepen.io/iamrafan/pen/LwbPvz

**Comment by straker** [comment]
@iamrafan  I'm still not seeing the error. I even forked your code and set it up in debug mode just to make sure. Running `axe.run` manually shows that `scrollable-region-focus` is in the `inapplicable` section of the results. 

![image](https://user-images.githubusercontent.com/2433219/62572615-589c2280-b851-11e9-9a5c-c8c8f1cdf624.png)

![image](https://user-images.githubusercontent.com/2433219/62572528-2db1ce80-b851-11e9-8c40-4df5fa052cff.png)

**Comment by iamrafan** [comment]
@straker , can you please try once again on the same codepen (https://codepen.io/iamrafan/pen/LwbPvz). I increased the height of the ```div#hp_scroll_listen_pad```  to ```100000px```

**Comment by straker** [comment]
Still nothing, even at different screen sizes (axe extension upgraded to axe version 3.3.1, don't know if that's contributing or not).

![image](https://user-images.githubusercontent.com/2433219/62951326-0609bb80-bda7-11e9-8e2e-feed46ee7c6b.png)
![image](https://user-images.githubusercontent.com/2433219/62951350-11f57d80-bda7-11e9-8ac0-6c488f4d3c38.png)
![image](https://user-images.githubusercontent.com/2433219/62951396-25a0e400-bda7-11e9-89c7-7d197ed48e49.png)

**Comment by straker** [comment]
I can reliably reproduce it on bing.com using the window size of 770x540 and using axe v3.3.1 (either extension or through script injection).

**Comment by straker** [comment]
After looking into this, the scroll region in question has no content inside of it. It's just an empty div with a single empty child div. We should probably exclude empty scroll regions from the check.

**Comment by chandana7393** [comment]
Tested, working fine. Unable to see the "scrollable region focusable" violations for empty scroll regions.
![Attest_empty_div](https://user-images.githubusercontent.com/45285854/63999690-a8ed6400-cb21-11e9-8acc-f601d16350c2.PNG)
**Tested Environment:**
Attest - 2.6.1.24122v
Axe - 3.9.0.24122v
Axe-coconut - 3.9.0.24122v
Chrome - 76.0.3809.132v
Firefox - 68.0.2v
OS - Windows 10 64 bit.
