### ISSUE TITLE
tabindex rule throws error when it shouldn't 

### ISSUE THREAD

**Issue by jarrodek** [dequelabs/axe-core#1714]
I hope you could help me understand an error I am getting while performing a test.
I have the following test result:

```json
{
  "id": "tabindex",
  "impact": "serious",
  "tags": [
    "cat.keyboard",
    "best-practice"
  ],
  "description": "Ensures tabindex attribute values are not greater than 0",
  "help": "Elements should not have tabindex greater than zero",
  "helpUrl": "https://dequeuniversity.com/rules/axe/3.3/tabindex?application=axeAPI",
  "nodes": [
    {
      "any": [
        {
          "id": "tabindex",
          "data": null,
          "relatedNodes": [],
          "impact": "serious",
          "message": "Element has a tabindex greater than 0"
        }
      ],
      "all": [],
      "none": [],
      "impact": "serious",
      "html": "<paper-input role=\"textbox\" title=\"Search for a file\" label=\"Search\" no-label-float=\"\" id=\"search\" type=\"search\" tabindex=\"0\" aria-disabled=\"false\"></paper-input>",
      "target": [
        [
          "google-drive-list-view",
          "#search"
        ]
      ]
    }
  ]
}
```

The test is performed on a web component that uses `paper-input` from Google's web components collection. 
The error message says `Ensures tabindex attribute values are not greater than 0` but the element has no such attribute. I am not sure if I am doing something wrong or is it an issue with the library. I would be grateful for an advice.

**Comment by WilcoFiers** [comment]
Can you provide us with a test page for this issue? From the looks of it, that indeed does seem like it shouldn't fail. The rule is fairly straight forward, so I don't really see why it would give a false result either...

**Comment by jarrodek** [comment]
So I have this module to test my web components: https://github.com/advanced-rest-client/a11y-suite/blob/master/index.js#L88

I am using this module like this:

```javascript
await a11ySuite('Normal state for google-drive-list-view',
  `<google-drive-list-view></google-drive-list-view>`, {
  ignoredRules: ['tabindex']
});
```
https://github.com/advanced-rest-client/google-drive-browser/blob/stage/test/google-drive-list-view.test.js#L13

The element I am testing is here: https://github.com/advanced-rest-client/google-drive-browser/blob/stage/google-drive-list-view.js#L190

There's nothing special in this template. The `tabindex` on `paper-input` is added by this component when it is initialised. Not sure how more I can be a help here.

**Comment by straker** [comment]
Would you be able to get a live page up with the component that shows the issue, maybe in a CodePen? That would let us look at the output and figure out what's going on.

**Comment by jarrodek** [comment]
Hi,
I cannot reproduce this anymore. This must have been on my end...
