### ISSUE TITLE
Documentation: `axe.configure` is not shared with iframes

### ISSUE THREAD

**Issue by AutoSponge** [dequelabs/axe-core#1736]
Expectation: The `axe.configure` method (`/doc/API.md#api-name-axeconfigure`) shares information with iframes or explicitly states that it does not.

Actual: configuration is not shared and the docs do not make it clear.

Motivation: assumptions about the way `axe.run` works may lead some to believe that `configure` also communicates with iframes and that the same config is used across frames when executing `axe.run`.

<pre><code>
axe-core version: 3.x

Browser and Assistive Technology versions: NA

For Tooling issues:
- Node version: NA
- Platform:  NA
</code></pre>

**Comment by straker** [comment]
Closed via https://github.com/dequelabs/axe-core/pull/2392
