### ISSUE TITLE
Add furter details about messages which should be translated

### ISSUE THREAD

**Issue by nvdaes** [dequelabs/axe-core#1743]
In the localization section of the readme, "de" is used for an example. But there just help is shown, and in locales/de.json descriptions have an empty value:
```
"description": "",
```

However, descriptions are translated in other <langcode>.json files.
I'm making a translation into Spanish:

Should be "description" translated?

In case descriptions need a translation, please provide a different language as an example in the localization section, or furter clarification about the messages which should be localized.

Thanks

**Comment by nvdaes** [comment]
@danielweck may be interested in this issue too, due to his [suggestion about translating axe-core](https://github.com/daisy/ace/pull/261#issuecomment-516840958).

**Comment by straker** [comment]
Thanks for being willing to submit translations for axe! Yes, any empty values should have translations. The only up-to-date translations file that I'm aware of is the [Japanese](https://github.com/dequelabs/axe-core/blob/develop/locales/ja.json) one. All others were user submitted but not kept up to date.

**Comment by nvdaes** [comment]
I will continue the spanish translation and send a PR when this is ready, may be at the end of the next week or  in the last week of August.
Thanks for clarification.
