### ISSUE TITLE
Confusing message (caption-faked)

### ISSUE THREAD

**Issue by thiagoeec** [dequelabs/axe-core#1749]
The following rule has a confusing message:

https://github.com/dequelabs/axe-core/blob/05e4f8254c53f3f97d1432b838c2a94edee8ab66/lib/checks/tables/caption-faked.json#L7-L8

Maybe it would be better to rephrase it:
> The first **_child_** of the table should be a caption instead of a table cell

In case I'm understanding this the wrong way, I would appreciate a clarification.

**Comment by WilcoFiers** [comment]
I like the suggestion. Would you like to put together a pull request?

**Comment by thiagoeec** [comment]
Sure. I'll just wait my last PR to merge. I accidentally pushed this to the same branch.

**Comment by thiagoeec** [comment]
Fixed in PR: #1755

**Comment by straker** [comment]
Closed via #1755
