### ISSUE TITLE
`main` index.js is missing

### ISSUE THREAD

**Issue by jasonkarns** [dequelabs/axe-core#175]
I assumed this file was generated as part of the `npm run build` (which I assumed would be run in npm's prepublish hook), but it seems that neither are the case.

Without the correct `main` property, axe-core can't be loaded from a git clone or `npm-link`'d.

I'm not sure what the build process is, but I would expect `npm run build` to put the package into a stable, require-able state.

**Comment by marcysutton** [comment]
Isn't that file built with `grunt build`? That's how I generate it.

**Comment by jasonkarns** [comment]
`npm run build` (which runs grunt) generates a whole structure into `dist`. It generates axe.js, axe.min.js, and index.js (and for some reason, copies readme, license, bower.json and package.json into dist).

Is there some rationale for copying the entire root of the package into dist instead of just making `package.json` point to `dist/index.js`? There seems to be an awful lot of build script stuff happening for no reason?

This still leaves axe-core root with a package.json that is invalid even after running the build.

**Comment by jasonkarns** [comment]
Typically, I'd submit a pull request that simplified all this, but since there is no npm prepublish hook, then the publish/release process is either being done manually or out-of-band from typical npm-scripts.

**Comment by dylanb** [comment]
@jasonkarns I believe the rationale is that we publish from dist so that there are no extra directories in the npm package. Is there a better way to do that? If so, please submit a PR or enlighten us so we can fix it.

**Comment by jasonkarns** [comment]
Ah, I see! Yeah, there are other ways (either with .npmignore or the
`files` property in package.json).

I'll see if I can craft up a PR sometime. Thanks for the clarification!

**Comment by marcysutton** [comment]
I just ran into this as well, looking into fixes.

**Comment by jasonkarns** [comment]
I've started a branch. Hopefully I can get it pr ready soon

**Comment by marcysutton** [comment]
Hey @jasonkarns how is that PR coming? I keep running into this problem. Curious if you or @dylanb have any thoughts on it.

**Comment by jasonkarns** [comment]
@marcysutton opened #187 

There's still an issue with the PR, however. At some point, master was updated so that `dist/index.js` is no longer generated at all! Is dist/axe.js node require-able? I'm assuming this was a result of #177. But I'm getting really confused by this entire build process at this point. Typically, the 'source' is the node entry-point and browserify et. al. are used to make the browser distributable. But I guess this isn't the case?

**Comment by marcysutton** [comment]
`npm run build` creates axe.js now, and `main` in package.json points to it. Are you still having issues?

**Comment by marcysutton** [comment]
I'm going to close this issue due to inactivity, please let us know if you want to discuss it further!
