### ISSUE TITLE
Localization: when possible, avoid "interpolations" enforzing particular grammar rules

### ISSUE THREAD

**Issue by nvdaes** [dequelabs/axe-core#1751]
Expectation: << Describe what you expect the product to do >>
Translatable strings should be formatted so that non English grammar is supported.
Actual: << Describe what the product actually does >>
Interpolated strings checking if certain words should end with "s" to build the plural in English, also following English syntax, are included as translatable strings, for example (this translated into Spanish):
> "incomplete": "Esperando que se añada rol en ARIA para {{=it.data && it.data.length > 1 ? 'hijos' : 'hijo'}}:{{~it.data:value}} {{=value}}{{~}}"

Motivation: << Describe why you want the behavior to be changed >>
I'm translating Axe-core into Spanish, and sometimes the formatted strings, including plural checks, is difficult or cannot be translated properly. For example, some verbs which the same form in English have different words for plural in Spanish, or names and adjectives are located in different positions, etc.
When possible, sentences should be complete themselves, and replacements included inside {} symbols should be placed at the end or begining of sentences.

**Comment by WilcoFiers** [comment]
@nvdaes the templating language allows you to put in different code. You don't need to keep the `{{ ... }}` stuff if you don't need it, and you can update them for different language needs. If you have any specific things you need help with, please ask.

Also, very exciting to have this localisation added to axe-core! Thank you for putting this together.

**Comment by nvdaes** [comment]
Thanks for your help! My intention is to translate messages as exactly as possible, trying to respect Spanish grammar, though sometimes I leave words in English, used in user or specific guides about computing, also addressing that axe-core requires knowledge about certain kind of terms, like role/roles, etc, which may stand in English since it's how they should be used. But when possible I try to use spanish terms and rules.
This maybe ready tomorrow or on Thursday. I'm reviewing and fixing errors comparing with an original en.json file created for this.
Anyway, when you merge the future pull request, if something needs to be fixed or updated, hope I can do it.
The en.json file has about 777 lines.
Kind regards.

**Comment by WilcoFiers** [comment]
Think this can be closed.
