### ISSUE TITLE
For "ARIA attribute must conform to valid attributes" rule unable to see the ARIA attribute value instead some condition is displayed.

### ISSUE THREAD

**Issue by chandana7393** [dequelabs/axe-core#1761]
**Steps to reproduce:**
1. Open the below-attached Test file.
2. Launch the Attest extension.
3. Click on the 'ANALYZE' button.
**Actual:**
Under "We are not sure this is an issue, because:" observed that for ARIA attribute unable to see the value instead some condition is displayed.
![check_if_ref_attest](https://user-images.githubusercontent.com/45285854/62764738-33572080-baac-11e9-965f-0b85c2584193.PNG)
**Expected:**
ARIA attribute value must be displayed instead of some condition.

CC: @padmavemulapati 
**Tested Environment:**
Test file:

&lt;!DOCTYPE html&gt;
&lt;html lang="en-US"&gt;
&lt;head&gt;
	&lt;title&gt;Checking ID reference&lt;/title&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;main&gt;
	&lt;h1&gt;Checking ID reference&lt;/h1&gt;
	&lt;input id="giftCard_0" aria-describedby="giftCard_0Error" aria-invalid="false"/&gt;
	&lt;span id="giftCard_0Error" aria-live="polite"&gt;[nothing here yet]&lt;/span&gt;
&lt;/main&gt;
&lt;/body&gt;
&lt;/html&gt;

Attest - 2.5.1.21421v
Axe - 3.8.1.21421v
Chrome - 76.0.3809.100v
Firefox - 68.0.1v
OS - Windows 10 64 bit.

**Comment by WilcoFiers** [comment]
Should check that this isn't in other locals as well.

**Comment by straker** [comment]
This was fixed in #1739 and released in [3.3.1](https://github.com/dequelabs/axe-core/releases/tag/v3.3.1). Once the extensions use the latest axe-core version it should be fixed.

**Comment by chandana7393** [comment]
Tested, appearing fine.
![attest_valid_values](https://user-images.githubusercontent.com/45285854/66902824-fa44aa80-f01e-11e9-97ce-0e969f835692.PNG)
![axe_valid_values](https://user-images.githubusercontent.com/45285854/66902842-029ce580-f01f-11e9-8716-557cbac80fd3.PNG)
**Tested Environment:**
Attest - 2.6.1.28822v
Axe- 4.0.0.28822v
Axe-coconut - 4.0.0.28904v
Chrome - 77.0.3865.120v
Firefox - 69.0.3v
OS  - Windows 10 64 bit.
