### ISSUE TITLE
Safari 11.1 fails to run for 3.3.1

### ISSUE THREAD

**Issue by rikbrowning** [dequelabs/axe-core#1764]
Expectation: Tests that run in Safari 11.1 with version 3.2.2 through WDIOshould run in version 3.3.1

Actual: Tests fail to run  with errors  below
```
safari 11.1 macOS 10.13 #2-0] A JavaScript exception occured: undefined is not an object (evaluating '__magic__.globalThis = __magic__') (WARNING: The server did not provide any stacktrace information)
[19:40:26] :		 [npm test] Command duration or timeout: 107 milliseconds
[19:40:26] :		 [npm test] Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
[19:40:26] :		 [npm test] Driver info: org.openqa.selenium.safari.SafariDriver
[19:40:26] :		 [npm test] Capabilities [{applicationCacheEnabled=true, rotatable=false, databaseEnabled=true, handlesAlerts=true, version=13605.3.8, cleanSession=true, platform=MAC, nativeEvents=true, locationContextEnabled=false, webStorageEnabled=true, browserName=safari, javascriptEnabled=true, platformName=macOS, cssSelectorsEnabled=true}]
[19:40:26] :		 [npm test] [safari 11.1 macOS 10.13 #2-0] Error: An error occurred while executing user supplied JavaScript.
```

My code for running axe in WDIO
```javascript
browser.execute(axe.source);
  // eslint-disable-next-line
  const results = browser.executeAsync(function(axeConfig, done) {
    //run axe on page
    // eslint-disable-next-line
    axe.run(axeConfig, function(err, res) {
      if (err) {
        done(err);
      }
      done(res);
    });
  }, runConfig).value;
```

Motivation: These tests successfully run in Safari 12.1. Not sure what has changed that has caused this error to occur.

<pre><code>
axe-core version: 3.3.1
</code></pre>

**Comment by straker** [comment]
Thanks for letting us know, we'll take a look.

**Comment by jeankaplansky** [comment]
Specific user documentation not required.

**Comment by padmavemulapati** [comment]
Ran the script for latest axe version and running on the Safari 12.1 successfully

**Comment by rikbrowning** [comment]
Why was this closed? 3.4.0 still does not run in Safari 11.1, I just testing this and it failed to execute any tests.

**Comment by straker** [comment]
Shoot. Seems I forgot to update the package.json to include the fix from https://www.npmjs.com/package/@deque/dot. Sorry this won't be in the release but will be available in axe-coconut or the latest develop branch for axe-core once I do so.

**Comment by joscha** [comment]
is this released in a usable package by any chance?

**Comment by straker** [comment]
It should be usable in the `develop` branch until 3.5 is released.

**Comment by joscha** [comment]
> it should be usable in the `develop` branch until 3.5 is released.

Hi @straker - I looked at that, however to get a proper package it seems `build` needs to be invoked? I guess I can pin axe-core to 3.3.0 for now (which doesn't have this issue; confirmed).

**Comment by motss** [comment]
Why closing this issue when this is not yet resolved.
