### ISSUE TITLE
Error: Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by bsklar** [dequelabs/axe-core#1769]
Expectation: Axe to run
Actual: I just get the message of Error: Could not establish connection. Receiving end does not exist.

Motivation: 

<pre><code>
axe-core version: 3.9.0
axe-webdriver, extension or other integration version: X.Y.Z

Browser and Assistive Technology versions

For Tooling issues:
- Node version: XX  
- Platform:  
</code></pre>

**Comment by straker** [comment]
Thanks for the issue. Could you please provide a bit more details as to the problem? Does this happen on every page or just to a single page? Does this happen while using the axe Chrome or Firefox extension, or when you're running axe-core on a site directly through a `<script>` tag? Does the error message list any files and/or line numbers?

**Comment by bsklar** [comment]
I fixed it by restarting the Chrome browser.  Thank you for your response.
