### ISSUE TITLE
hi，I have two questions about the wallet.

### ISSUE THREAD

**Issue by mon1y** [dequelabs/axe-core#1772]
First: Why does the light wallet still have node synchronization speed?
 Second: Why is the address of the axe wallet different from the address generated by the bip you submitted? Currently, all the wallets that support axe generate different addresses, using the same mnemonic.

**Comment by straker** [comment]
@mon1y I'm not sure you have the correct repo for those questions. This is the axe accessibility testing tool. Did you want the AXE cryptocurrency?
