### ISSUE TITLE
Check the "axeVersion" property for axe.configure for compatibility

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#1780]
When calling `axe.configure()` with a "axeVersion" property, axe-core should check if that version of the custom rule is compatible with the axe-core version that's used. Custom rules are compatible with all patch and minor updates that are the same as, or newer than those in "axeVersion". So:

```js
axe.configure({
  rulesetVersion: '2.5.1',
  rules,
  checks
})
```

- 2.5.1 is compatible with 2.5.1
- 2.5.1 is compatible with 2.6.2
- 2.5.1 is compatible with 2.5.1-canary.2664bae
- 2.5.1-canary.2664bae is compatible with 2.5.2
- 2.5.1 is not compatible with 2.5.0
- 2.5.1 is not compatible with 2.4.3
- 2.5.1 is not compatible with 3.x.x
- 2.5.1-canary.2664bae is not compatible with 2.5.1
- 2.5.1-canary.2664bae is not compatible with 2.5.1-canary.a5d727c (since we can't tell which was released first, canary versions are only compatible with themselves, and any future stable release).

If axe.configure is called with an incompatible version, axe-core should throw a **meaningful** error.

**Edit**: The `ver` property has been renamed to `axeVersion`. We will add support for `ver`, but have it only be available as a deprecated feature, that will be removed as of the next major release.

**Comment by aellsey** [comment]
@WilcoFiers @awpearlm will we need design for the "meaningful error"? How do you see this change impacting the user experience?

**Comment by stephenmathieson** [comment]
Why "ver"? It's not a word.

**Comment by WilcoFiers** [comment]
See update above, renamed `ver` to `rulesetVersion`.

**Comment by isner** [comment]
Corresponding Comply ticket to accommodate this change:

**Accommodate axe 3.4 version-compatibility checking**
https://dequesrc.atlassian.net/browse/COM-1865

**Comment by WilcoFiers** [comment]
I've updated the above example to include canary versions.

**Comment by chandana7393** [comment]
@straker what needs to be QA here?? Can you please provide the required steps.

**Comment by straker** [comment]
Just that setting different `axeVersion` values of against the used version of axe either throws an error or doesn't in accordance with @WilcoFiers description.

**Comment by somaalapati** [comment]
@chandana7393 steps to verify this ticket:

1. Launch Attest extension.
2. Navigate to Rules panel.
3. Select axe-version '3.0.3' from axe versions dropdown.
4. Create a custom rule by setting 'rulesetVersion' as 2.5.1
5. Analyse a page using this custom rule.

Expected: You should see an 


@WilcoFiers Can you please make sure these steps are correct and provide an example custom rule that contains axe.configure

**Comment by somaalapati** [comment]
Comment from @WilcoFiers : You can’t verify this with the Attest extension. You’ll need to download axe-core@next from NPM, include it in any of the Attest APIs, (or axe-cli) and try to pass it a custom ruleset with an axeVersion set that’s incompatible.

@padmavemulapati See if you can verify this ticket.

**Comment by somaalapati** [comment]
@padmavemulapati This ticket is in "ReadyForQA" for a long time. Please verify asap.

**Comment by padmavemulapati** [comment]
Installed different axe versions with Node's get() , and apply in the APIs 'configure - obviously lower versions are incompatible and higher versions are compatible.
