### ISSUE TITLE
td-headers-attr docs mostly about using [scope]

### ISSUE THREAD

**Issue by paulirish** [dequelabs/axe-core#1782]
the https://dequeuniversity.com/rules/axe/3.3/td-headers-attr doc is quite confusing to me.

there is no example of a table using `[headers]` attribute (either incorrectly or correctly).. only a correct example using `scope`.

**Comment by straker** [comment]
cc @jeankaplansky

**Comment by jeankaplansky** [comment]
Added link to https://www.w3.org/TR/WCAG20-TECHS/H43.html in the How to Fix section - this example demonstrates associating IDs with `headers` attribute values on specific table cells.

**Comment by chandana7393** [comment]
Tested, there is no https://www.w3.org/TR/WCAG20-TECHS/H43.html link in the Fix the following,
![table-ref_same_cell](https://user-images.githubusercontent.com/45285854/67204014-2f3f6b80-f42a-11e9-94a7-c5521e1dca5e.PNG)

**Tested Environment:**
Axe-coconut - 4.0.0.29404v
Chrome -  77.0.3865.120v
OS - Windows 10 64 bit.

**Comment by jeankaplansky** [comment]
@chandana7393 : Not sure what you mean. There's no https://www.w3.org/WAI/*WCAG21*/Techniques/html/H43 in the UI, or in the rule help? Because the link is definitely in the rule help in the "Other Resources" section at the bottom of the page.

**Comment by jeankaplansky** [comment]
More new content added with examples demonstrating the use of `scope="colgroup"`, `scope="rowgroup"`, and IDs and headers attribute values in addition to the original example.

**Comment by chandana7393** [comment]
@jeankaplansky Thanks for the clarification.
Verified accordingly, there are headers examples updated in the Learn more link and also "https://www.w3.org/WAI/*WCAG21*/Techniques/html/H43" link is present under the other resources of deque University 'Learn More' link.

**Tested Environment:**
Axe-coconut - 4.0.0.29504v
Chrome - 77.0.3865.120v
OS - Windows 10 64 bit.
