### ISSUE TITLE
Allow serialisable DOM representations for virtualNodes

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#1783]
I'd like to be able to do the following, as an alternative to passing in a virtual node:

```js
const { violations } = axe.runVirtualRule('autocomplete-valid', {
  nodeName: 'input',
  attributes: {
    type: 'email',
    autocomplete: 'given-name'
  }
});
```

**Comment by straker** [comment]
Would it just create the virtual node for you behind the scenes?

**Comment by WilcoFiers** [comment]
Jup, that's the idea

**Comment by jeankaplansky** [comment]
Documentation required.

**Comment by chandana7393** [comment]
Dev Task.

**Comment by padmavemulapati** [comment]
As per the developers confirmation, there is no QA  here and can close this ticket, closing it.
