### ISSUE TITLE
Add lang query string to help URLs

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#1784]
To support DQU's localisation, axe-core's help URLs should include a language code, for example:

```
https://dequeuniversity.com/rules/axe/3.3/html-has-lang?lang=jp
```

This can be set when `axe.configure()` is called with a new locale.

**Comment by jeankaplansky** [comment]
@straker: This isn't a new rule, but is it something we should include in the release notes?

**Comment by jeankaplansky** [comment]
Added to release notes 10/14/2019

**Comment by padmavemulapati** [comment]
Verified this ticket, I am seeing the help URL, for language attribute is:  https://dequeuniversity.com/rules/axe/3.3/html-has-lang?lang=ja (not lang=jp) 
@WilcoFiers , can you please confirm that we are expecting "japanese" language , is n't it?

**Comment by straker** [comment]
Opened a separate issue #1861.

**Comment by padmavemulapati** [comment]
As this issue is tracking in #1861, closing this ticket
