### ISSUE TITLE
Rules options CSS selector ignored

### ISSUE THREAD

**Issue by fredboyle** [dequelabs/axe-core#1785]
Expectation:
Only run rule against elements matching value of `selector` key.
In sample config code below 'scrollable-region-focusable' is where the issue occurs.

Actual:
`selector` key of rule options is ignored.

Motivation:
Broken functionality. Looking to limit which elements are tested on a per rule basis.

<pre><code>
axe-core version: 3.3.1
axe-webdriver, extension or other integration version: 2.3.0

Browser and Assistive Technology versions

For Tooling issues:
- Node version: 10.16.2
- Platform:  Mac
</code></pre>

```
rules: {
        bypass: { enabled: false },
        'landmark-one-main': { enabled: false },
        region: { enabled: false },
        'page-has-heading-one': { enabled: false },
        'html-has-lang': { enabled: false },
        'scrollable-region-focusable': {
          'selector': ":not([class*='dropdown_length-'])"
        }
      }
```

**Comment by WilcoFiers** [comment]
@fredboyle Having custom include / exclude options for specific rules is not a thing axe-core supports today. Can you explain the use case for this? I haven't seen this from other users, so I'd like to understand it a little better.

One thing you could try is to run axe multiple times. Once for all rules with normal scope, and additional times with different scopes, and then turn the rules off in one run and on in the other.

**Comment by fredboyle** [comment]
@WilcoFiers Primarily it is to help us avoid invalid failures for tests that are buggy in certain scenarios. So until overly aggressive tests are fixed in axe-core we would like to avoid testing in key places.

We can investigate the multiple runs but would prefer a single report.

**Comment by fredboyle** [comment]
@WilcoFiers Doing some testing and using multiple passes is unfortunately impractical in our scenario. We're testing a design system with a very large number of individual examples. This increases the testing time for each rule we need to test in additional passes. Having exclusions per rule would be much simpler and timely.

Are there alternatives to running multiple passes (general scope, and specific scopes)?

**Comment by fredboyle** [comment]
Any input on this? It's become a bit of a blocker in our automated process and validation.

**Comment by damianpoole** [comment]
This would be really handy for us working with Salesforce's lightning web components. We have this scenario which I'm trying to resolve.

_Our component template_
```html
<button class='slds-button'>
    <lightning-icon alternative-text="close"></lightning-icon>
</button>
```

The `lightning-icon` component renders something along the lines of.
_lightning-icon_
```
<svg ...>
<span class="slds-assistive-text">Close</span>
```

This means my templates `button` does have discernible text and I have validated that using the axe extension in a live environment.

Now when it comes to running the tests in Jest, all the `lightning-...` components are stubs. This means the DOM that axe is looking at is not the same and the test will fail because it doesn't contain that span of assistive text.

Using the none stub versions of the `lightning` components is not an option as they are not ours and the source for them is not available outside a Salesforce environment

**Comment by straker** [comment]
It looks like you are trying to pass this config in through `axe.run`, is that correct? The `axe.run` config only supports enabling/disabling rules. If you wish to configure more about a particular rule, you will need to go through `axe.configure` and override the rules selector there:

```js
axe.configure({
  rules: [
      {
         id: 'scrollable-region-focusable',
         selector: ":not([class*='dropdown_length-'])"
      }
  ]
});
```

If doing this for automated testing, you can configure the rule before the test and then reset the config afterwards using `axe.reset()`.

**Comment by straker** [comment]
@fredboyle @damianpoole does the above address your issue?

**Comment by damianpoole** [comment]
I haven't had chance to check but it does look like this will address our issues.

**Comment by WilcoFiers** [comment]
I think we have a sufficient solution. Going to close the issue.
