### ISSUE TITLE
Add option to aria.getRole to ignore presentation and none roles

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core#1792]
We do a lot of `!['presentation', 'none'].includes(role)` in the code. It would be nice to add an option to [aria.getRole](https://github.com/dequelabs/axe-core/blob/develop/lib/commons/aria/get-role.js) to ignore these roles. An option named `noPresentational` should suffice. If the option is set, the function should return `null` if the role is either `presentation` or `none`.

Please also [create a test](https://github.com/dequelabs/axe-core/blob/develop/test/commons/aria/get-role.js) to show that the new option works.

**Comment by Loganras** [comment]
If it's not already being worked on, I think I'll give this one a shot.

**Comment by straker** [comment]
All yours. Let me know if you need anything.
