### ISSUE TITLE
Description of title attribute in "Buttons must have discernible text" rule

### ISSUE THREAD

**Issue by mikhin** [dequelabs/axe-core#1800]
Hello. Is the title attribute correct as legit accessible value for interactive elements like buttons? Is there a contradiction between axe-core and HTML specs?

> Relying on the title attribute is currently discouraged as many user agents do not expose the attribute in an accessible manner as required by this specification (e.g., requiring a pointing device such as a mouse to cause a tooltip to appear, which excludes keyboard-only users and touch-only users, such as anyone with a modern phone or tablet).

Source: https://html.spec.whatwg.org/multipage/dom.html#the-title-attribute
https://www.w3.org/TR/html52/dom.html#the-title-attribute

The description in axe-core doesn't say anything special about `title` attribute, but has it in example of correct markup solution.

Source: https://dequeuniversity.com/rules/axe/3.3/button-name

<pre><code>
axe-core version: 3.3
</code></pre>

**Comment by straker** [comment]
The `title` attribute is a valid property for the [accessible name computation](https://www.w3.org/TR/accname-1.1/#mapping_additional_nd_te). It's not the preferred way to generate an accessible name as some assistive technologies may not pick it up and the value won't be visible without a mouse hover.
