### ISSUE TITLE
Error: Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by klblackburn286** [dequelabs/axe-core#1801]
aXe tool in dev tools doesn't work on our existing site: https://www.oge.gov/web/oge.nsf

I'd like to use aXe in combination with a new accessibility software we're running. I prefer the aXe interface more, and trust in the tool. I plan on using it at the page level while our other tool will be used to remediate at the site level.

Hoping to get an answer soon to this issue so we can use for our redesign.

**Comment by straker** [comment]
We had someone open a similar issue a bit ago #1769. Have you tried restarting the chrome browser? There's also a new permission agreement you need to accept in order to run the latest version of axe.
