### ISSUE TITLE
role=presentation not recognized as valid

### ISSUE THREAD

**Issue by mStudios** [dequelabs/axe-core#1803]
Expectation: Using role=presentation (or role=none) in img passes. Example:

Actual: If no ALT is being used, the error returns "Ensures <img> elements have alternate text or a role of none or presentation" - if role=presentation is used, the error returns "ARIA role must be appropriate for the element". The same happens, when role=none is being used. Example code = `<img src="https://dummyimage.com/340x160/444/888" role="presentation">`

Motivation: I do not want to use alt="" in each presentational img and use its proper role.

<pre><code>
axe-core version: 3.3.1
axe-extension (Chrome) version: 3.9.0

Browser and Assistive Technology versions 
Browser : Chrome version: 76.0.3809.100
System : Mac OSX version: 10.13.6
</code></pre>

**Comment by WilcoFiers** [comment]
This looks like a gap in the ARIA in HTML spec. It considers img elements with a non-empty alt, and with an empty alt, but not without one:
https://www.w3.org/TR/html-aria/#img-alt

I agree we should treat no alt equivalent to having an empty alt.

**Comment by mStudios** [comment]
Thank you, this will be helpful.

**Comment by chivesrs** [comment]
I also ran into this issue, in `axe-core: 3.3.2` and `HeadlessChrome 77.0.3865`.

Per the WAI spec in https://www.w3.org/WAI/PF/aria/roles#presentation, anything with `role="presentation"` should simply be ignored for accessibility, so Axe should skip over the element in testing, and not even consider it. I think that is a better fix than dealing with `alt` attributes. This way, the fix will be for every use case, not just `img` tags.

**Comment by AutoSponge** [comment]
[Per spec](https://www.w3.org/TR/html-aria/#allowed-aria-roles-states-and-properties)

```
img with no alt=""	role=img	
Any role

Global aria-* attributes and any aria-* attributes applicable to the allowed roles and implied role (if any).
```

I'm reading this as the "missing" spec per Wilco's comment.

**Comment by chandana7393** [comment]
Tested, working as expected.
![role_presentation_best_practice](https://user-images.githubusercontent.com/45285854/67274710-a20a1e80-f4de-11e9-97b9-409ed268d8cc.PNG)

**Tested Environment:**
Axe-coconut - 4.0.0.29504v
Chrome - 77.0.3865.120v
OS - Windows 10 64 bit.
