### ISSUE TITLE
Spanish localization done and merged, but not published to NPM registry? (missing package contents?)

### ISSUE THREAD

**Issue by danielweck** [dequelabs/axe-core#1811]
Merged PR:
https://github.com/dequelabs/axe-core/pull/1758

Spanish locale exists in codebase at release tag`3.3.2`:
https://github.com/dequelabs/axe-core/tree/v3.3.2/locales

...but does not exist in published NPM package:
https://unpkg.com/browse/axe-core@3.3.2/locales/

CC @nvdaes

**Comment by nvdaes** [comment]
Spanish localization is now published in npm. So, I will close this issue.
Thanks for your work!

**Comment by nvdaes** [comment]
@danielweck , you can close the issue and use this release for ACE.
