### ISSUE TITLE
Docs: preload option default value inconsistency

### ISSUE THREAD

**Issue by sergei-startsev** [dequelabs/axe-core#1817]
There're contradictions regarding `preload` default value:

- https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#options-parameter
 > performanceTimer | **false** | Log rule performance metrics to the console

- https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#preload-configuration-details
 > The preload attribute **(defaults to true)** in options parameter...

Preload option was set to `true` value by default in 6643dc391dcfaeafd8eb6d85f5ee7da775b2b0e9.

Expectation: Preload option was set to `true` value by default

Actual: Preload option was set to `false` value by default

<pre><code>
axe-core version: >3.2
</code></pre>

**Comment by straker** [comment]
@jeankaplansky `preload` value should default to `true`

**Comment by jeankaplansky** [comment]
release notes fix.

**Comment by chandana7393** [comment]
Tested appearing fine on https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#options-parameter.
![preload_true](https://user-images.githubusercontent.com/45285854/66823150-45998300-ef63-11e9-9b50-1cc687fa5187.PNG)
