### ISSUE TITLE
False positive for aria-readonly on role="listbox"

### ISSUE THREAD

**Issue by smhigley** [dequelabs/axe-core#1821]
The following example throws an aria-allowed-attrs error for `aria-readonly` on a `role="listbox"` element: https://jsfiddle.net/rotL5v89/1/show

This seems like a straightforward error, since `aria-readonly` is one of the supported states for listbox: https://www.w3.org/TR/wai-aria-1.1/#listbox

<pre><code>
axe-core version: 3.2.2 and 3.3.2-canary.1aa567c
</code></pre>

**Comment by chandana7393** [comment]
Tested, working fine.
![aria-read-only](https://user-images.githubusercontent.com/45285854/66906144-bf457580-f024-11e9-878f-a5b5eb8d8493.PNG)

CC: @somaalapati 
**Tested Environment:**
Axe-coconut - 4.0.0.28904v
Chrome -  77.0.3865.120v
OS - Windows 10 64 bit.
