### ISSUE TITLE
region flags for svg sprite

### ISSUE THREAD

**Issue by badtant** [dequelabs/axe-core#1832]
When I run axe on https://www.svt.se/recept I get that the region rule says "All page content must be contained by landmarks" and points to my SVG symbol sprite that lives directly in body.

Is this a bug or is there a good way for me to fix to that my SVG sprite passes the test? Preferably I don't want to move it elsewhere in the dom. Maybe wrap it in some element or set some attribute? Any suggestions? My first take is this:
`<div aria-hidden="true"><svg /></div>`

Thanks

**Comment by straker** [comment]
Thanks for the issue. We'll look into ignoring non-content elements from this rule.

**Comment by straker** [comment]
@badtant are you still seeing this error? With axe@3.4.1 I get no violations on the page

**Comment by badtant** [comment]
thats because I've placed the svg sprite inside a div like this
`<div aria-hidden="true"><svg /></div>`

I did that to not get the issue but I think the rule should be able to detect that its a non-content element like you said earlier.

**Comment by padmavemulapati** [comment]
Verified in the latest code-
Observations:
Initially was unable to reproduce the issue, as it mentioned in the test page they have added <svg> inside <div>. So tried to reproduce the issue by removing svg sprite and yes reproduced:
![image (23)](https://user-images.githubusercontent.com/47409579/97836663-ca884380-1d02-11eb-944b-a98b4b250a39.png)

and then verified with the fix, even svg sprite deleted (no need to add it separately to get rid from the failure) from the source no issues found , as  per the fix .
![Uploading image.png…]()

**Comment by badtant** [comment]
@straker what was the reason for closing this?

**Comment by straker** [comment]
It's been fixed in the latest develop branch (tested and verified). We are planning to release axe-core v4.2 on the 16th.
