### ISSUE TITLE
tabindex rule throws error when it shouldn't

### ISSUE THREAD

**Issue by corrieann** [dequelabs/axe-core#1834]
Seems to be a recurrence of https://github.com/dequelabs/axe-core/issues/1714

Snippet of HTML of the Element | &lt;paper-input class="colab-replace-input" type="text" label="Replace with" tabindex="0" aria-disabled="false"&gt;
-- | --
Impact | serious
Targets | .colab-replace-row > paper-input.colab-replace-input
FailureSummary | Fix any of the following: Element has a tabindex greater than 0
At least one check must have passed | CheckResult ID: tabindexImpact: seriousMessage: Element has a tabindex greater than 0

Can view the element in question on 
https://colab.research.google.com by opening Edit -> Find and replace...
although if I do that and run axe via a Chrome extension, it's not triggering this error.  It only seems to from axe-webdriver.

<pre><code>
axe-core version: 2.5
axe-webdriver, extension or other integration version: 2.0

For Tooling issues:
- Platform:  Linux
</code></pre>

**Comment by straker** [comment]
The bug is that `paper-input` redefines the `tabIndex` property of the element, so when we check for `node.tabIndex <= 0`, it returns `undefined` instead of a value. I'm not sure if this is a Polymer bug or something we have to start accounting for (custom elements overriding native properties of the HTMLElement).

**Comment by WilcoFiers** [comment]
Conclusion. This is a bug in paper-input, which does not allow accessing .tabIndex. That said, to avoid this type of issue, I do think we should drop using properties to get at attribute values. Using `getAttribute()` is more reliable, we've been burned by this before, so let's just solve it.

**Comment by straker** [comment]
Fix this problem, then work it in over time for the rest of the code base.

**Comment by padmavemulapati** [comment]
Not seeing the now, as we have done fix. Closing the ticket as issue not replicating
