### ISSUE TITLE
meta-refresh.json uses cat.time

### ISSUE THREAD

**Issue by damien-git** [dequelabs/axe-core#1835]
`lib/rules/meta-refresh.json` uses `cat.time`. Shouldn't that be `cat.time-and-media`, as listed in https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#parameters ?

**Comment by straker** [comment]
You are correct. Thanks for pointing that out to us

**Comment by jkodu** [comment]
PR for this is merged. Closing issue.
