### ISSUE TITLE
What is the purpose of <walnut-highlight-tool> from Axe Chrome extension?

### ISSUE THREAD

**Issue by zelliott** [dequelabs/axe-core#1840]
It appears near the bottom of the DOM and appears to only hold an empty shadow root node. There's no information on Google about it and I was curious what it is used for.

**Comment by notiv-nt** [comment]
?

**Comment by straker** [comment]
The walnut highlight tool is injected into the page by the axe extension. It allows us to highlight the element of an issue (if you have selected to do so).

**Comment by notiv-nt** [comment]
@straker yes, but this element appears even if I do not touch the axe extension
Why?

**Comment by straker** [comment]
We currently do not lazy load the tool, so it's there even without the extension loaded. We have plans to fix this in a later version.
