### ISSUE TITLE
Need to document whether rules generate needs review items

### ISSUE THREAD

**Issue by dylanb** [dequelabs/axe-core#1855]
Current rules documentation does not make it clear which rule can generate needs review items. Some rules can only generate needs review (audio-caption) whereas other can generate both issues and needs review (color-contrast) and yet others only generate issues.

Documentation should make this clear

**Comment by WilcoFiers** [comment]
Do you have a suggestion on how to document this? I've been thinking of adding a tag to rules that only produce false positives, to make it easy to turn them off when you're running it in automated tests. Would that be sufficient?

**Comment by dylanb** [comment]
Could we add a column to the rule-description document that lists the types of issues each rule generates. We could generate this off an attribute in the rule `.json` file but I would suggest that we allow indication of "only issues", "only needs review" and "both" - I don't have a strong opinion about tag versus some other attribute but I have a slight preference for a separate attribute.

**Comment by robdodson** [comment]
> Could we add a column to the rule-description document that lists the types of issues each rule generates. 

+1 for this suggestion. We refer to that table a lot for Lighthouse related stuff since it also contains the severity of the failure.

**Comment by WilcoFiers** [comment]
We can add two columns: "failures" and "needs review", with "true" or "false" in them. This can be gaged off of the messages on the checks.

**Comment by straker** [comment]
@jeankaplansky Please see the new format for the [rule-description file](https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md)

**Comment by jeankaplansky** [comment]
This is great stuff! Will add to release notes for next axe-core release

**Comment by padmavemulapati** [comment]
Documentation ticket:

I think this documentation not yet done apart from release notes. @WilcoFiers who is taking care of updating the axe-core docs. Please update the comments here, I will take care on this ticket once documentation done. For now moving back to "Ready for Docs" stack.

**Comment by jeankaplansky** [comment]
@padmavemulapati : the documentation is here: https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md

This table is automatically generated from a JSON file. The docs have a link to the file where required.

**Comment by padmavemulapati** [comment]
Verified the .md file with the changes mensioned.
