### ISSUE TITLE
Make `node` and `virtualNode` available in `after` function

### ISSUE THREAD

**Issue by jeeyyy** [dequelabs/axe-core#1858]
**Expectation:** 
Enhance the arguments in the `after` function for a check, to receive `node` and `virtualNode`.

**Actual:** 
Currently the `after` function for a check receives only the `results` and `options` as arguments, like so: `after: 'function (results, options) {\n<%=source%>\n}',`.

**Motivation:** 
It is essential in some after checks to have access to `node` and or `virtualNode` for computational purposes. Example see comment - https://github.com/dequelabs/axe-core/pull/1649#discussion_r335440989

Here, in order to pass a given `node` into its `after` callback, it was set as a `relatedNode`, but the relatedNode was curated later to remove the node/ thyself. This is a round about way of passing items to `after` function & is currently done in a few rules.

**Comment by straker** [comment]
Which `node` and `virtualNode` should be passed? It's not running against a single check context so I'm not sure which context you'd expect to have in an after method. Maybe each `CheckResult` has `node` and `virtualNode` attached to it?

**Comment by straker** [comment]
Closing via https://github.com/dequelabs/axe-core/pull/2608. Check results now have a `node` property (the DQElement) which you can get the virtual node from using `getNodeFromTree`.
