### ISSUE TITLE
test:rule-help-version script broken

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#1863]
This script which is supposed to prevent us from releasing while docs aren't updated doesn't work because the DQU pages it hits return an error page with status 200.

**Comment by straker** [comment]
This might have bee changed recently? The rules page is now returning a proper 404 on a page that doesn't exist https://dequeuniversity.com/rules/axe/3.5

**Comment by WilcoFiers** [comment]
Reopened. That page is definitely giving me a 200 message back.

**Comment by straker** [comment]
I'm getting 404s from it.

![image](https://user-images.githubusercontent.com/2433219/69979488-a36e3400-14eb-11ea-8797-33ffcd5f04da.png)

**Comment by straker** [comment]
QA, please verify a rule help page for a version of axe that does not yet exist returns a 404.

**Comment by somaalapati** [comment]
@padmavemulapati looks like a simple verification. Please close this.

**Comment by padmavemulapati** [comment]
for axe rule page, now it is the version available is 3.4, so for https://dequeuniversity.com/rules/axe/3.4 , status is 200. Where as otherthan the unavialble versions/ upgraded versions ex: https://dequeuniversity.com/rules/axe/3.5 or 3.8 or 4.0 it is givng status 400, shown like below. which is good to let the user those pages not found.

![image](https://user-images.githubusercontent.com/47409579/71670541-29ed8e00-2d96-11ea-92bd-8ebc269ed051.png)
