### ISSUE TITLE
Color contrast issue when testing during animations

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#1866]
Had an issue report to us of a page that scrolled content into view. In the initial state of the animation, the contrast was insufficient, but when it complete it was. Because axe-core scrolls content and immediately tests, it leave not time for the animation to complete.

Short of never testing content that's outside the visible viewport, I don't think there's much that can be done to avoid it. This issue is mostly just so we have a record of the problem.

**Comment by emilyrohrbough** [comment]
My team has experienced this issue and spent quite a while trying to work through it. Axe won't and shouldn't know if there are scss animation on the page but it would be nice if there was a way to pass in an optional 'waitForAnaimation'. This would slow down tests.

Have you given any thought into how this might be handled?

**Comment by andrewborstein** [comment]
+1 for a solution to this! 

In case it's helpful I created two reduced test cases to demonstrate the issue in action. Just  adding `scroll-behavior: smooth` to your CSS is enough to trigger the problem.

1. [Reduced Test Case: No Smooth Scroll](https://cdpn.io/andrewborstein/debug/ZEGyJKj)
2. [Reduced Test Case: With Smooth Scroll](https://cdpn.io/andrewborstein/debug/JjdJyrQ)

**Comment by nickcolley** [comment]
Hello @andrewborstein,

The team has release 3.5.0 which changes how the scroll behaviour works when running certain tests, could you confirm you're using axe-core version 3.5.0 and above and that you run into the same problems please?

**Comment by andrewborstein** [comment]
Fantastic! Everything works 💯 now. Thanks so much for the speedy response @nickcolley .

**Comment by straker** [comment]
Glad to hear. Closing as this ticket seems to be resolved by the color contrast changes.
