### ISSUE TITLE
"Expect axe._selectorData to be set up" console errors

### ISSUE THREAD

**Issue by chimericdream** [dequelabs/axe-core#1867]
I'm getting the following error in the browser console when running aXe in my React app:

![2019-10-22 08_27_28-Window](https://user-images.githubusercontent.com/198075/67290744-2db38900-f4a6-11e9-9b9d-eb83c05ed14b.png)

I saw this was [reported on the react-axe repository](https://github.com/dequelabs/react-axe/issues/116), but it appears the root issue is in axe-core. I saw that the selector code had minor changes in 3.4.0 released today, but they did not fix the issue for me.

I saw similar, possibly related issues here (#1041 and #1084), but I wasn't sure if they were true duplicates. If so, I'll throw my +1 into those tickets for a fix.

Versions and environment

* `axe-core@3.4.0` (also tested with 3.3.2)
* `react-axe@3.3.0`
* `react@16.10.2`
* Node 12
* Windows 10
* Chrome

Thanks!

**Comment by WilcoFiers** [comment]
This is very likely because axe is started a second time before it completed the first. Axe-core can't have multiple runs going at the same time. @straker and I discussed last week if we could put together some kind of queue, so that axe-core doesn't start a run while another is still going. I think that's the best way to solve this.

**Comment by mohanraj-r** [comment]
I am also seeing this error after upgrading to 3.4.0. Did not see this error with 3.3.1.

**Comment by WilcoFiers** [comment]
@mohanraj-r are you also using react-axe, or something else?

**Comment by mohanraj-r** [comment]
@WilcoFiers I am using it via https://github.com/nickcolley/jest-axe on some custom components (not react)

**Comment by WilcoFiers** [comment]
@mohanraj-r Are you kicking off multiple axe.run() calls at the same time? That's not supported. You need to await a run before you start the next. You can do that pretty easily just doing `await axe(html)` in jest-axe.

**Comment by mohanraj-r** [comment]
@WilcoFiers Yes the `axe.run()` calls are being triggered in parallel by jest as it runs tests in parallel. I thought jest had isolation between the parallel tests - e.g. by using a different instance of jsdom for each parallel run. Maybe I should try using [`jest.resetModules()`](https://jestjs.io/docs/en/configuration#jest-resetmodules)?

**Comment by mohanraj-r** [comment]
Btw do you know why this is happening only in recent versions of axe ?
Wondering if I can workaround this if I know what is causing this..

**Comment by straker** [comment]
@jeankaplansky docs needed about how `axe.run` will now throw an error for concurrent runs: "Axe is already running. Use `await axe.run()` to wait for the previous run to finish before starting a new run."

**Comment by padmavemulapati** [comment]
@jeankaplansky , is this documented? If yes , can you  please mension the link here, I will verify and close this ticket.
@straker , I am seeing the code changes.

**Comment by padmavemulapati** [comment]
Apart from release doc, there is no specific axe related documentation to verify, so closing this ticket
