### ISSUE TITLE
Firefox add-on prevents line-breaks in code highlighted with PrismJS

### ISSUE THREAD

**Issue by ffoodd** [dequelabs/axe-core#1868]
I don't know how, but right now using Firefox Nightly (72) and consulting technical contents with code blocks (eg [HTMHell](https://www.htmhell.dev/2-div-with-button-role/)), PrimsJS is unable to wrap content for line-breaks (trying to add a `<span class="highlight-line">` for each line, but not throwing any error nor message…).

After double checking every settings and add-ons, it seems that this is prevented by the aXe webextension: with my current profile and every settings, simply disabling aXe made PrismJS wrapping correctly again…

I have no idea what's doing this, but this sounds very curious!

**Comment by straker** [comment]
Can confirm. The moment I turned on the axe extension and went back to the open tab, the code no longer wrapped.

![image](https://user-images.githubusercontent.com/2433219/67412832-417dee80-f57d-11e9-8793-2a34d524604a.png)

**Comment by scurker** [comment]
We use prismjs for code highlighting within axe, so there's a possibility there's some conflicts there.

The only way I've been able to reproduce this is enabling the extension when the page is already loaded. Navigating to the page with the extension already enabled does not exhibit this behavior. Are you seeing this in other instances as well @ffoodd?

**Comment by ffoodd** [comment]
I have this issue whatever I do, while aXe extension is active (even without using it, simply having its tab in my dev tools breaks Prism JS wrapping). And it breaks on about every sites using PrismJS — I saw this for months, but had no luck with finding the cause. aXe was the last thing I tried!

I’m using Firefox Nightly so there might something else coming into this behaviour, but I don't think so.

I don't know how to help more, please tell me if there's a way.

**Comment by scurker** [comment]
I have verified that it's an issue with prismjs running the following snippet causes white spaces to collapse:

```javascript
const script = document.createElement('script')
script.src = 'https://unpkg.com/prismjs@1.17.1/prism.js'
script.type = 'text/javascript'
document.head.appendChild(script)
```

It looks like prism is attempting to run highlight again, but I don't have a good solution for the axe extension right now to help prevent this.

**Comment by straker** [comment]
@ffoodd is this still a problem with the latest Chrome axe? I can no longer reproduce the issue when turning on/off the extension.

**Comment by ffoodd** [comment]
@straker Indeed, it seems to work fine now :)

**Comment by 36degrees** [comment]
I'm still seeing this happening in Chrome 86 with v4.6.1 of the extension.

For example, on https://www.11ty.dev/ I see

![Text in inline code blocks collapsed onto a single line, with syntax highlighting removed](https://user-images.githubusercontent.com/121939/97299300-ab923900-184c-11eb-9e09-ae9d6ec3b153.png)

If I disable the axe extension, I see:

![Text in inline code blocks displayed correctly, with syntax highlighting](https://user-images.githubusercontent.com/121939/97299344-bc42af00-184c-11eb-8b64-8f1e0679b619.png)

It's also stomping classes in other syntax-highlighted code blocks, removing the styling – for example on https://design-system.service.gov.uk/get-started/extending-and-modifying-components/ the extension replaces:

```
<pre><code class="lang-css"><span class="hljs-selector-class">.app-</span>\!<span class="hljs-selector-tag">-reference-number-width</span> {
  <span class="hljs-attribute">width</span>: <span class="hljs-number">10ch</span> <span class="hljs-meta">!important</span>;
}
</code></pre>
```

with:

```
<pre class="  language-css"><code class="  language-css"><span class="token selector">.app-\!-reference-number-width</span> <span class="token punctuation">{</span>
  <span class="token property">width</span><span class="token punctuation">:</span> 10ch <span class="token important">!important</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre>
```

**Comment by ianjmacintosh** [comment]
I'm seeing this issue in Chrome also (and found it on the Eleventy docs pages like @36degrees  at first but have seen it other places too)

**Comment by darekkay** [comment]
@ffoodd Please at least re-open the issue. I've just noticed this on [my blog](https://darekkay.com/blog/copy-shell-commands/) with the Axe Chrome extension enabled.

**Comment by ffoodd** [comment]
Please open a new issue, this one was resolved and only concerned Firefox.

**Comment by scurker** [comment]
We're currently tracking an open issue here: #2686
