### ISSUE TITLE
webextension default locale detection does not seem to work

### ISSUE THREAD

**Issue by ffoodd** [dequelabs/axe-core#1869]
I just discovered that axe webextension had a setting for locale, which default value is to match browser default.

This doesn't seem to work properly since it always fallback to english, although **both Firefox and Chrome** are set to french in my case.

This is kinda bad since I translated aXe to french months ago and just discovered that I could actually use it :D

**Comment by straker** [comment]
Thanks for letting us know, we'll take a lot into it and see what the problem is.

**Comment by scurker** [comment]
@ffoodd default browser locales should be applied in the latest axe coconut release when you have _Use Browser Default_ chosen in settings. It should land in the axe `4.2.0` release, but no ETA on that yet.

**Comment by padmavemulapati** [comment]
Verified with the latest version axe(4.1.0.32418) and axe-coconut(4.1.0.32504) , I am seeing the locale changes for these web extensions.

![image](https://user-images.githubusercontent.com/47409579/69352197-8000e900-0ca2-11ea-9d1a-0d1330ea7aa9.png)
But we are not closing this ticket, since the ticket is on axe-core will keep it not to close until 4.2.0 is out.

**Comment by ffoodd** [comment]
Just tried in Chromium with 4.1.0, with a very weird behaviour: some strings got translated but not all of them.
Switching back to defining French as value, everything get translated.

I'll wait for the next release to try this again, thanks all for your attention :)

**Comment by padmavemulapati** [comment]
Tested with latest axe-coconut(4.2.0) still seeing the partial text in english, not with complete locale changes
Frensch results:
![image](https://user-images.githubusercontent.com/47409579/69851523-e5a73380-12a7-11ea-8114-6fa6384e76c8.png)
Japanese results:
![image](https://user-images.githubusercontent.com/47409579/69851583-040d2f00-12a8-11ea-9f8d-41582d475c63.png)

**Comment by scurker** [comment]
@padmavemulapati It looks like it's working to me. Our french locales in the extension aren't 100% up to date as we don't have a lot of updated translations for axe Pro changes.

**Comment by padmavemulapati** [comment]
> @padmavemulapati It looks like it's working to me. Our french locales in the extension aren't 100% up to date as we don't have a lot of updated translations for axe Pro changes.

Yes @scurker , agree with you, I just kept the observations and also requesting the clarification to close the ticket, shall I

**Comment by scurker** [comment]
> Yes @scurker , agree with you, I just kept the observations and also requesting the clarification to close the ticket, shall I

👍Ah, my misunderstanding. We probably need to find out who helps maintain the extension French locale and get some updates.

**Comment by ffoodd** [comment]
I did most of the French translation, and FWIW I don't use the Pro version. I'll try to update translations ASAP but as I explained, when choosing "French" in the select box every strings are translated, but not when selecting "browser default" — so there's definetely some kind of bug out there :')

**Comment by scurker** [comment]
Axe `4.2.0` was released a few days ago, so default translations should now be available in both coconut and our mainline branch.

@ffoodd I changed my browser's default to French, opened a new tab and ran the extension. This is what I see:

![axe extension with analyze results](https://user-images.githubusercontent.com/1062039/70065229-56a06100-15b0-11ea-8a78-e362398d96a4.png)

Aside from values that we do not have translated yet, like "Save Results" is this different from what you see in your extension?

**Comment by ffoodd** [comment]
@scurker Yes it is, I'll download `4.2.0` to give it a try. It seems really better :)

**Comment by jeankaplansky** [comment]
No user-facing documentation required.

**Comment by ffoodd** [comment]
I can confirm I now have the same result using browser locale or specifically selecting French — and I can see I have new strings to translate, indeed :D 

Thanks!
