### ISSUE TITLE
Error: Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by benlwilliams** [dequelabs/axe-core#1881]
Expectation: << Describe what you expect the product to do >>
When I push the analyze button, it should analyze the page I'm looking at. 

Actual: << Describe what the product actually does >>
The error "Error: Could not establish connection. Receiving end does not exist." appears.  Which doesn't make sense, because I'm looking at the page, so I know that I have access and that the receiving end does exist. 

Motivation: << Describe why you want the behavior to be changed >>
I can't see the scan results without it. 

<pre><code>
axe-core version: X.Y.Z
axe-webdriver, extension or other integration version: X.Y.Z

Chrome: Version 78.0.3904.87 (Official Build) (64-bit)

For Tooling issues:
- Node version: XX  
- Platform:  Mac
</code></pre>

**Comment by straker** [comment]
Hey @benlwilliams, we've found the issue to be either to restart chrome or ensure your permissions are up-to-date. See https://github.com/dequelabs/axe-core/issues/1769 for more information. Going to close this as a duplicate, but let me know it doesn't solve it for you.

**Comment by benlwilliams** [comment]
@straker I restarted chrome and got the same result.  I'm not sure what you mean by "make sure your permissions are up-to-date".  

The plugin works about 30% of the time on all websites or no websites.

**Comment by straker** [comment]
Interesting. The latest axe-core requires additional permissions to run so you should have gotten a prompt to accept them. You can also check to make sure the permissions for all sites. See https://github.com/dequelabs/axe-core/issues/1806#issuecomment-533118649
