### ISSUE TITLE
Deprecate doT.js

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#1896]
doT.js uses `new Function()` which has some security concerns. To fix this, will use a simpler format. DoT.js will be deprecated, but remain available until at least axe-core 4.0.

**Comment by jeankaplansky** [comment]
@straker updated documentation in axe-core project.

**Comment by padmavemulapati** [comment]
Need to verify few hadful things:
default config (english) works (test a few combinations of different rules that uses different styles of check messages)
color-contrast various failures (background-img, overlapping element, etc).
pass message for a rule
etc.
axe.configure() with a non-en locale works
grunt build --lang=<langcode> with a non-en locale works
grunt translate --lang=<langcode> output uses the newer structure...
For time  being will keep it in work in progress and verify it bit later.

**Comment by padmavemulapati** [comment]
Verified axe configure for different locale  (ja,de and fr..).
generated respective rule-drscription file.
with grunt build --land=ja(de, fr..) --force - build axe.ja.js (.de.js /.fr.js)
with grunt translate  - translated the respective locales newer structure. Everything looks good

**Comment by jeankaplansky** [comment]
in the release notes as of 2/3/2020
