### ISSUE TITLE
Release script tagging the wrong commit

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#1907]
For the axe-core 3.4 release the commit before the 3.4 release was tagged. Because of that, the changelog and the version bump weren't included in the release commit.

Actions:
- Figure out what caused this, and create a fix
- Check if other repos have the same problem, and if so create issues for those.

**Comment by straker** [comment]
I'm not sure what happened. According to the CircleCI build, it should have [released using the correct commit](https://circleci.com/gh/dequelabs/axe-core/9680) sha of [a699b62](https://github.com/dequelabs/axe-core/tree/a699b62e8191d818c4d448be21ae274d6adae6ab). The release has already been updated and fixed, so I can't see what it actually pinned to when it was released.

**Comment by straker** [comment]
The release script looks like it was working correctly, but I'm the one who creates the tags when running `npm run release`. So maybe somehow I messed something up and created the v3.4.0 tag pinned to the wrong commit. Hard to know at this point but will watch out for it for the next release.
