### ISSUE TITLE
Error: response from subscriber uses invalid format     at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/background.bundle.js:14:43744

### ISSUE THREAD

**Issue by kathfor** [dequelabs/axe-core#1911]
Issue: Error: response from subscriber uses invalid format
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/background.bundle.js:14:43744

Expectation: << Describe what you expect the product to do >>

Actual: << Describe what the product actually does >>

Motivation: << Describe why you want the behavior to be changed >>

<pre><code>
axe-core version: X.Y.Z
axe-webdriver, extension or other integration version: X.Y.Z

Browser and Assistive Technology versions

For Tooling issues:
- Node version: XX  
- Platform:  
</code></pre>

**Comment by straker** [comment]
Thanks for the issue. Could you provide more details? What page did you see this error on, what extension were you using (Chrome or Firefox). What version of axe-core was the issue, etc.

**Comment by stephenmathieson** [comment]
Relevant LOCs: https://github.com/dequelabs/attest-browser-extensions/blob/develop/src/dq-web-extension/action-handler.js#L127-L134

**Comment by kathfor** [comment]
I just installed the axe extension in chrome and was testing it on the google website and it stopped working. had to uninstall originally because i had malware on my chrome so i had to reset the browser.
-- 
Katie Forrest
University of Michigan Class of 2021
kathfor@umich.edu 
(650)-285-7505 | LinkedIn <https://www.linkedin.com/in/katie--forrest/>

**Comment by erik-deque** [comment]
Marking as closed.
