### ISSUE TITLE
When will 3.5 be released?

### ISSUE THREAD

**Issue by jacopotarantino** [dequelabs/axe-core#1918]
Just curious. My team is running into the bug that is fixed by https://github.com/dequelabs/axe-core/commit/3252a020ffd372e9583d39c989affd3d3b22957b frequently and it's disruptive. Would love to see a canonical release so I don't have to point to a particular commit hash. Thanks!

**Comment by straker** [comment]
3.5 is planned to be released on February 10, 2020.

**Comment by WilcoFiers** [comment]
I don't think #1914 would solve anything, it just throws an error earlier. You can use axe-core@next if you want to use stuff that hasn't been released yet.
