### ISSUE TITLE
Errors in commented code

### ISSUE THREAD

**Issue by kkmuffme** [dequelabs/axe-core#1933]
it seems that Axe flags errors in commented HTML code:

```
<!--
<a href="https://google.com"><a>
-->
```

Will report "Links do not have a discernible name" in lighthouse

**Comment by WilcoFiers** [comment]
I am unable to reproduce, or imagine how something like that might happen even. Can you provide some more details about this? Axe-core does not look at comments at all, nor does it look at inner / outerHTML anywhere.
