### ISSUE TITLE
dom.isFocusable returns true for the summary element

### ISSUE THREAD

**Issue by mitchellwills** [dequelabs/axe-core#1945]
Expectation: axe.commons.dom.isFocusable should return true for `<summary>` elements and false for `<details>` elements with `<summary>` elements inside of them

Actual: It always returns true for `<details>` elements and returns false for `<summary>` elements

Motivation: doesn't match browser behavior (tested in recent Chrome, Firefox & Safari)

A simple example (prints focused element to the console): https://next.plnkr.co/edit/5lxR5V2jJWa44oND?open=index.html&preview

<pre><code>
axe-core version: 3.1.2 (appears to be a problem in the current code too)
</code></pre>

**Comment by WilcoFiers** [comment]
Right you are. Thank you for reporting. We'll be sure to fix that!

**Comment by jeankaplansky** [comment]
in release notes as of 2/3/2020
