### ISSUE TITLE
Violation "ARIA hidden element must not contain focusable elements" should not be set when tabindex="-1"

### ISSUE THREAD

**Issue by rianrietveld** [dequelabs/axe-core#1952]
In the case of multiple links to the same link target in, for example a card (or tile), one way is to hide all but one of the link by ARIA hidden and tabindex="-1".
`<a href="your-url" aria-hidden="true" tabindex="-1">link text</a>`
This is done for screen reader and keyboard user usability.

Expectation: 
No validation error "ARIA hidden element must not contain focusable elements" when a link also has the tabindex="-1" added.

Actual: 
The violation "ARIA hidden element must not contain focusable elements" is reported in Axe on links with aria-hidden="true" and tabindex="-1".

Motivation: 
IMO this is not a viloation, but done for screen reader and keyboard user usability. This construction gives the developer a way to hide duplicate links form the screen reader and tab order, as a way to make the link list shorter and the amount of tab stops less. Without losing functionality, as this is a construction typically used with multiple links to the same link target.

I discussed this construction with @WilcoFiers and @julezrulez. They both saw this as a valid construction to hide duplicate links.

**More info about this:**
- [Explenation in the WordPress Accessibility Handbook](https://make.wordpress.org/accessibility/handbook/markup/post-excerpts-for-an-archive-template/)
- [What makes an accessible card? Tenon Webinar](https://www.youtube.com/watch?v=AH2NagMoYYE)

<pre><code>
axe-core version: 4.1.0 (axe-core 3.3.2)  FireFox 71.0
Browser and Assistive Technology versions
FireFox 71.0
For Tooling issues:
- Platform:  MACOS Cataline 10.15.2
</code></pre>

**Comment by WilcoFiers** [comment]
Hey Rian. Something else has got to be going on with this, because the code snippet you shared does not throw an issue in any version of axe-core that I can see. Do you have a link to the page where you saw this issue?

**Comment by rianrietveld** [comment]
@WilcoFiers sorry for the confusion. I took an extra hour puzzeling what was going on and the error was not on the a link but on a hidden focussalbe element inside the link. Actually, Axe did a good job here, it only was very hard for me to discover what threw the error.

I'll close the issue.
