### ISSUE TITLE
npm support

### ISSUE THREAD

**Issue by nodren** [dequelabs/axe-core#197]
According to recent commits, you guys are celebrating your 2.0.5 release.

your npm package is still back on the 1.1.1 release, with also no tags to indicate the 2.x version has been released.  can we see newest releases published on npm as well?

**Comment by dylanb** [comment]
@nodren Thank you for using axe-core :-)

These releases were not published to npm, the 2.0.5 release will be published in the next couple of days. Stay tuned.

--Dylan

**Comment by BrianSipple** [comment]
Thanks for the new update, @dylanb! I have a similar question regarding bower, which is still at 1.1. Does this suggest that NPM is the only/main channel for new releases going forward?

**Comment by dylanb** [comment]
no, we will update bower too

**Comment by marcysutton** [comment]
They are now updated so I am going to close this issue. Thanks for your input!
