### ISSUE TITLE
False positive for "Document must have one main landmark"

### ISSUE THREAD

**Issue by erik-deque** [dequelabs/axe-core#1973]
When running a scan with the axe extension, a false positive is generated for "Document must have one main landmark" when a second element with "role=main" has "display: none!important;"

Expectation: No issue is raised for "Document must have one main landmark"
Actual: Issue is raised for "Document must have one main landmark"

Motivation: When an element is set to hidden, it is not identified by assistive technologies and so when there are multiple elements with role=main but hidden, they shouldn't count against this best practice.

axe-core version: 4.3.1 (latest)
axe-webdriver, extension or other integration version: axe extension

Found on: [https://ellenlevinlawoffice.com/](https://ellenlevinlawoffice.com/)

![image.png](https://images.zenhubusercontent.com/5dc03f44fd98400001804529/9ded5f1c-a362-4ab1-9e49-798068a40199)

**Comment by jeankaplansky** [comment]
Added to release notes 2/03/2020

**Comment by padmavemulapati** [comment]
test file having `<div><main id="target"></main><main id="dup" style="display:none;"></main></div>`
getting - 
Document does not have a non-empty <title> element
