### ISSUE TITLE
Appveyor build often reports as failure

### ISSUE THREAD

**Issue by jkodu** [dequelabs/axe-core#1976]
Expectation: 
Test builds should be fast, stable and consistent on each runs.

Actual:
- Appveyor build runs are slow
- Fails arbitrarily when installing dependencies (like webdriver)
- And reports inconsistent results
 
Motivation: 
Provide a seamless and easier workflow to run tests in windows environment

<pre><code>
axe-core version: 3.4.1
For Tooling issues:
- Platform:  Windows/ Appveyor/ CI
</code></pre>

**Comment by padmavemulapati** [comment]
DevTask
