### ISSUE TITLE
Scrolling position for elements with `hidden` overflow style are no longer restored

### ISSUE THREAD

**Issue by benbcai** [dequelabs/axe-core#1979]
### Summary

Our application uses axe-core to run accessibly and visual regression on test pages. When running axe we set the `restoreScroll` option to `true` to restore the scrolling position. 

This is how our test page used to look when using axe-core 3.2.2.
<img width="296" alt="Screen Shot 2020-01-13 at 10 32 31 AM" src="https://user-images.githubusercontent.com/22618655/72273556-278a0000-35f0-11ea-9aa6-b869a6397387.png">

However, after upgrading to axe-core 3.3.0 or 3.4.0, our test page now looks like this:
<img width="292" alt="Screen Shot 2020-01-13 at 10 35 50 AM" src="https://user-images.githubusercontent.com/22618655/72273740-83548900-35f0-11ea-84a7-e8b0d0ae20d3.png">

The container element on this test page has an `overflow-x` and `overflow-y` style of `hidden`.  The changes made on #1599 (released on axe-core 3.3.0) appears to no longer restore hidden elements back to their original position using `elm.scrollTop`. 

See this [comment](https://github.com/dequelabs/axe-core/issues/1951#issuecomment-572120044) on #1951 for additional details.

### Expectation: 
To restore elements with an `overflow` style of `hidden`  back to their original position

### Actual: 
Elements with an `overflow` style of `hidden` are scrolled to a different position but are not restored.

<pre><code>
axe-core version: 3.4.0

Browser and Assistive Technology versions

For Tooling issues:
- Node version: v10.17.0
- Platform:  Mac
</code></pre>

**Comment by WilcoFiers** [comment]
Hmm, that's very odd. Thank you for reporting. For axe-core 3.5, which we're planning to release in a month, axe-core will no longer be scrolling at all. So this problem should go away soon.

**Comment by straker** [comment]
If you manually run axe using https://unpkg.com/axe-core@3.4.1-canary.6e4ed6b/axe.js, does it give you issues with the scroll?

**Comment by benbcai** [comment]
@WilcoFiers @straker I pulled down the develop branch that includes the changes from #1943 and this issue is resolved. I'll close this issue. I'm seeing other failures (unrelated to this issue) when using the develop branch but I'll investigate further.
