### ISSUE TITLE
[extension] "Error in event handler: TypeError: Cannot read property 'getCurrent' of undefined" when navigating

### ISSUE THREAD

**Issue by ivan-aksamentov** [dequelabs/axe-core#1981]
## Steps

1. Open chrome with axe installed
2. Open developer console
3. In console settings (cogwheel in console's top right corner)  check "Preserve log" checkbox (to make sure that the log is not overwritten on navigation)
4. Navigate to `https://www.google.com/`
5. Click on "I am feeling lucky" button, "How search works" link, or any other element that navigates to another page.

## Expectation

No console errors

## Actual

The following warning is emitted in dev tools console:

```
(index):1 Error in event handler: TypeError: Cannot read property 'getCurrent' of undefined
    at e (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/adapter.bundle.js:31:1210)

```

It does not happen on all pages. But if it happens once, after that point, every navigation will print that error.

## Notes

It's a convoluted usecase, but I thought it may help debugging. It may indicate the presence of some cryptic bugs too. The hypothesis is that axe may not handle navigation properly, when markup suddenly disappears and the event handlers are destroyed. The error is hidden because the console is being reset on navigation by default.

## Versions
Axe webextension: 4.2.0
Chromium: 81.0.4024.0 on Ubuntu

**Comment by erik-deque** [comment]
This issue has been resolved.

**Comment by whygithub7** [comment]
i call chrome.tabs.getCurrent() from content script , but i  get  "Cannot read property 'getCurrent' of undefined" from content. 
Where i can use this method ?  in content script and in background its not work
