### ISSUE TITLE
axe Chrome and Firefox extensions hang when attempting to analyze page

### ISSUE THREAD

**Issue by kensgists** [dequelabs/axe-core#1986]
Expectation: axe analysis completes on the following page: https://www.chase.com/business/small-business-resource-center

Actual: axe extensions hang indefinitely, with never-ending circular spinner

Browser and axe extension versions:
Firefox 72 (axe 4.2.1) and Chrome 79 (axe and axe-coconut extensions 4.2.0)

**Comment by OtisMyDog** [comment]
When I attempt to use the aXe utility on my site within Chrome if sits and does nothing except display this:
![axe error](https://user-images.githubusercontent.com/59936907/72469211-f276dc80-37ac-11ea-8e5b-36dfed0f7b78.png)

**Comment by straker** [comment]
Thanks for the issue. 

@kensgists we have a new version of axe which looks like it might fix the problem. Axe-coconut should be updated soon with the changes and we can test again when it does.

@OtisMyDog can you provide more details? What site are you testing on and what is the error details?

**Comment by OtisMyDog** [comment]
By going to the Pro Beta this issue seems to have gone away.

**Comment by erik-deque** [comment]
Closing
