### ISSUE TITLE
Color contrast calculation for #777777 on #FFFFFF say 4.48 Colour contrast tool for same is 4.5

### ISSUE THREAD

**Issue by DavidMacDonald** [dequelabs/axe-core#199]
Who's right?

:)

**Comment by dylanb** [comment]
axe-core is right - see here http://springmeier.org/www/contrastcalculator/index.php

**Comment by marcysutton** [comment]
The WebAim checker also says 4.48:1. http://webaim.org/resources/contrastchecker/

I don't think there's any action to be taken here, so I'm going to close the issue.
