### ISSUE TITLE
color contrast nonMbp charset isn't global and isn't sanitised

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#1993]
If I pass something like this into the color contrast rule, it is tested because only the first char is stripped out, and the spaces aren't removed:

```html
<div style="color: #ccc">
  &#x20A0;
  &#x20A1;
  &#x20A2;
  &#x20A3;
</div>
```

**Expected**: This element is incomplete for color-contrast
**Actual**: This element fails color-contrast

**Comment by jeankaplansky** [comment]
Added to release notes 2/04/2020;

https://docs.google.com/document/d/14PI0e3X9g6CBWtl86HReHrRxl-_zapZBE8HaKoOHrmE/edit#

**Comment by padmavemulapati** [comment]
non BMP chanrecter color-contrast test still seeing voilations, not needs review.

**Comment by straker** [comment]
Confirmed. The checks options are not be passed in due to a [misconfiguration of the check.json](https://github.com/dequelabs/axe-core/blob/develop/lib/checks/color/color-contrast.json#L6-L10).

**Comment by straker** [comment]
@padmavemulapati Should be fixed now in the latest axe-core

**Comment by padmavemulapati** [comment]
will verify the same with axe and attest extensions once axe-core3.5 deployed in devTools.
