### ISSUE TITLE
Avoid odd unicode chars in regexp

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#1994]
We've noticed some issues executing regex with odd unicode characters in them. These are used here:

https://github.com/dequelabs/axe-core/blob/develop/lib/commons/text/unicode.js

Instead of using regexp, what we could do is use `str.charCodeAt()` to figure out if the string has characters we want to strip / check for. That way we can keep these things as character codes and don't have to put characters in memory old javascript VMs can't deal with.

**Comment by straker** [comment]
@jeankaplansky no docs

**Comment by padmavemulapati** [comment]
DevTask
