### ISSUE TITLE
Release patches for 3.2, 3,3, 3.4 with unicode escape fix

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2004]
PR https://github.com/dequelabs/axe-core/pull/1997 has fixed some issues for older browsers. We've had requests to make this fix available for older versions of axe-core as well. That will require us to do releases for 3.2, 3,3 and 3.4, in addition to this fix getting released in axe-core 3.5.

**Comment by padmavemulapati** [comment]
No specific QA required at this point as it happened with the released versions
