### ISSUE TITLE
[QA] Update rule `label` to correct SC

### ISSUE THREAD

**Issue by jkodu** [dequelabs/axe-core#2014]
Expectation: 
Rule `label` should map to SC `4.1.2` instead of `3.3.2`

Actual:
See above

Motivation: 
Needed for implementation of rule - https://act-rules.github.io/rules/e086e5

<pre><code>
axe-core version: X.Y.Z
axe-webdriver, extension or other integration version: X.Y.Z

Browser and Assistive Technology versions

For Tooling issues:
- Node version: XX  
- Platform:  
</code></pre>

**Comment by jkodu** [comment]
@jkodu to verify if this fix completes the implementation for above ACT Rule

**Comment by jkodu** [comment]
@jeankaplansky reopening issue, to check if this needs to be documented

**Comment by padmavemulapati** [comment]
Verified with latest axe-coconut (v4.3.0.06000 ), seeing the change from wcag332 to wcag412. Attached the screenshots. 
(without update rule `label` - tag is wcag332)
![image](https://user-images.githubusercontent.com/47409579/75664419-74a55c80-5c98-11ea-8971-15f448052052.png)
(after updating rule `label` - tag is wcag412)
![image](https://user-images.githubusercontent.com/47409579/75664341-52abda00-5c98-11ea-8cac-d720a76d598d.png)

**Comment by jkodu** [comment]
> Worked with DQU to update tags respectively in DQU content
