### ISSUE TITLE
`grunt-contrib-uglify` does not treat unicode characters correctly

### ISSUE THREAD

**Issue by jkodu** [dequelabs/axe-core#2023]
Expectation: 
`grunt-contrib-uglify` should minify unicode characters correctly.

Actual: 
`grunt-contrib-uglify` converts unicode characters specified not as a literal into UTF-8 character code set.

Motivation: 
This minification fails when building axe under a windows ecosystem.
Also, this was identifed when executing attest-java selenium driver based tests.

<pre><code>
axe-core version: @next
axe-webdriver, extension or other integration version: attest-java@next

Browser and Assistive Technology versions

For Tooling issues:
- Node version: NA
- Platform:  Windows
</code></pre>

**Comment by AdnoC** [comment]
Unicode is converted to:
![axe-core unicode regex convertedpng](https://user-images.githubusercontent.com/4079454/73943290-80cb1380-48be-11ea-98a6-bcf7e384a87d.png)

Said unicode now causes error when creating regex:
![axe-core unicode regex stack](https://user-images.githubusercontent.com/4079454/73943320-8d4f6c00-48be-11ea-87f8-c14476702a5c.png)

**Comment by straker** [comment]
No docs required. Testing: test latest axe.min.js in IE11

**Comment by padmavemulapati** [comment]
On IE11, with the below script -
`var script = document.createElement('script');
script.src = 'https://unpkg.com/axe-core@3.5.0/axe.min.js';
document.body.appendChild(script)` 
able to load axe.min.js on testfile 
`<div style="background-color: #FFF;">
	<div id="canttell20" style="color:#DDD;">
		&#x20A0; &#x20A1; &#x20A2; &#x20A3;
	</div>
</div>` , 
below attached the screenshot
![image](https://user-images.githubusercontent.com/47409579/74639742-70efe100-5194-11ea-81ab-17dd08c13fc0.png)
@straker , please let me know anything else need to QAed here

**Comment by padmavemulapati** [comment]
ran axe on IE11 with the snippet :
`axe.run(function(err, result) {
  if (err) {
    console.log('err:', err);
  }
  console.log('result:', result);
}); `

![image](https://user-images.githubusercontent.com/47409579/74664030-f4c0c200-51c2-11ea-88cd-ce12562b62b9.png)
Which is expected.
