### ISSUE TITLE
possible false positive for 'Ensures `<audio>` elements have captions'

### ISSUE THREAD

**Issue by mfairchild365** [dequelabs/axe-core#203]
This might not actually be a false positive, but I couldn't find anything regarding the subject so I thought I would bring it up here. I'm leaning on it being a false postive.

Consider the following scenario

> An `<audio>` element exists on a page but is hidden from view (visibility: hidden, display:none or visually hidden with css). The audio element is only ever used to play a notification sound. Notifications are also displayed visually. 

It is my understanding that in the above scenario, it is okay for the `<audio>` element to not have a caption track.

**Comment by dylanb** [comment]
@mfairchild365 thanks for the feedback: how do you suggest that we change the algorithm to not flag these? Do we simply ignore all hidden `<audio>` elements?

**Comment by mfairchild365** [comment]
In order to adhere to the manifesto of the project, that might be the best decision. I can't think of a way to programmatically determine if an <audio> element already has an accessible alternative.

Another related issue is a presentational only video. Many sites have been adopting the `<video>` element to loop a muted and subtle video in the background. In these cases, the video is essentially just a moving image, and I don't see any rationale to require a captions track with it (because there is nothing to caption). An audio description might make sense here instead. But again, I can't think of a way to programmatically determine the intended purpose of a video.

**Comment by mfairchild365** [comment]
Reviewing this further, I think the best solution is to just use `aria-hidden="true"` on these elements.
