### ISSUE TITLE
3.5 on Chrome extension

### ISSUE THREAD

**Issue by jaimeiniesta** [dequelabs/axe-core#2063]
Hi! The Chrome extension is still using axe-core 3.4 - is there a plan to upgrade it to the latest release?

**Comment by straker** [comment]
Yep. We should be releasing updated builds soon.

**Comment by straker** [comment]
Firefox and Chrome have both been released using axe-core 3.5.1.

**Comment by jaimeiniesta** [comment]
That's great but why not 3.5.2 to get the latest bug fixes?

**Comment by straker** [comment]
Releasing the extensions and publishing to the stores takes some time, so it'll be bit before we can publish 3.5.2 in them.
