### ISSUE TITLE
Feature Request: Allow Export into WCAG-EM Report Tool & Similar

### ISSUE THREAD

**Issue by mgifford** [dequelabs/axe-core#2070]
Coming from this Accessibility Insights request https://github.com/microsoft/accessibility-insights-web/issues/653

I added this request to the WCAG-EM Report Tool  https://github.com/w3c/wcag-em-report-tool/issues/326

But figured I should make it here too.  Wouldn't it be nice if errors produce could easily feed into a standardized reporting structure?

**Comment by WilcoFiers** [comment]
@mgifford. I haven't personally tested importing axe-core results into the WCAG-EM Report Tool, but my understanding is that it should work if you use [axe-reporter-earl](https://github.com/dequelabs/axe-reporter-earl). Have you tried using this?

**Comment by mgifford** [comment]
Thanks @WilcoFiers I definitely hadn't heard of this.  Thanks!

**Comment by WilcoFiers** [comment]
Cool. In that case closing the issue. Feel free to open an issue if this doesn't end up working for you.
