### ISSUE TITLE
Update check `invalidrole` to fail when all given roles are invalid

### ISSUE THREAD

**Issue by jkodu** [dequelabs/axe-core#2073]
**Expectation:** 
Check `invalidrole` should only fail when all given roles are invalid.

**Actual:** 
Currently `invalidrole` fails when even one role is invalid.

**Motivation:** 
Noticed wrong outcomes when validating ACT rule against this example - https://act-rules.github.io/rules/674b10#passed-example-3

**Comment by padmavemulapati** [comment]
Added one invalid aria role and two pass/valid roles and tested. 
Invalid role only failing , not all the roles if invalid role is there in the test file. Working as expected.
Verified with axe-4.3.0.06416 with chrome
![image](https://user-images.githubusercontent.com/47409579/75980673-fac7da00-5f08-11ea-9a25-aa0e5d252608.png)

**Comment by jkodu** [comment]
Nothing to document here. Closing issue.
