### ISSUE TITLE
[Enhancement]Message should be 'xml:lang is not valid ' for non xhtml having [xml:lang] 

### ISSUE THREAD

**Issue by padmavemulapati** [dequelabs/axe-core#2080]
`<html>` element with `xml:lang` attribute , is giving a voilation , which is expected.
But that fail message , probably like -  'xml:lang is not valid ' instead 'The <html> element does not have a lang attribute'. Can we take it up as an update or enhancement in this case. (Can observe from the below screenshot)

![ticket_xhtmlMsg](https://user-images.githubusercontent.com/47409579/75786930-ffb34f00-5d8b-11ea-8783-72e0714e95dc.png)

**Comment by padmavemulapati** [comment]
Verified in the latest axe-coconut(v4. )
Seeing the meesage description for the xml:lang as appropriate. (attached the screenshot)
![image](https://user-images.githubusercontent.com/47409579/76740638-388ff280-6794-11ea-9ca7-032a8c2819d6.png)

**Comment by straker** [comment]
No docs needed
