### ISSUE TITLE
scrollable-region-focusable [contenteditable="true"] false positive

### ISSUE THREAD

**Issue by AutoSponge** [dequelabs/axe-core#2091]
Expectation: axe-core does not raise a `scrollable-region-focusable` violation for a container with content exceeding its dimensions and does not have `tabindex=0` when it has `contenteditable="true"`.

Actual: axe raises `scrollable-region-focusable` violation

Motivation: editable content will "scroll into view" as needed using standard keyboard navigation based on cursor movement.

<pre><code>
axe-core version: 3.5.1

Browser and Assistive Technology versions: Chrome
</code></pre>

**Comment by WilcoFiers** [comment]
Hey, I know this guy! Thanks for the issue Paul. We'll be sure to pick it up.

**Comment by padmavemulapati** [comment]
Verified with latest axe-coconut(v4.4.1.09219), not seeing voilations for scrollable-region-focusible, when content has no tabindex=0 and has contenteditable=true. (here is the screenshot)
![image](https://user-images.githubusercontent.com/47409579/78259216-02839a00-751a-11ea-95cc-2e71cb5b8d8b.png)
