### ISSUE TITLE
Allow autocomplete="tel-national" on input[type=tel]

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2097]
HTML spec doesn't allow it, but this seems more like an error in the spec. As part of this fix, be sure to look at other things that make sense for type=tel too.

**Comment by padmavemulapati** [comment]
auto-complete - `tel-*` allowing and showing in Passes. (verified in latest axe-core3.5.5)
![image](https://user-images.githubusercontent.com/47409579/85282841-0b955f00-b4aa-11ea-81b9-b100864a725e.png)

**Comment by jeankaplansky** [comment]
no user-facing docs required.
