### ISSUE TITLE
Color contrast checking of unicode private use characters

### ISSUE THREAD

**Issue by ahuth** [dequelabs/axe-core#2101]
Axe version: 3.5.2
OS: MacOS and Linux
Browsers: Firefox and Chrome

My company uses a custom font to render various icons for certain unicode characters. It looks like #2005 fixed the color-contrast rule for non-BMP characters, and now I'm getting color-contrast failures that I don't expect.

I believe this is caused by the non-BMP regex not matching characters in Supplementary Private Use Area-A

Changing this would solve our issue, and I'd be happy contribute fixes for either or both of them, if this seem reasonable.

## Our setup

We use a custom font to show icons for unicode characters in Supplementary Private Use Area-A. For example:

<img width="368" alt="airmoji" src="https://user-images.githubusercontent.com/2503289/77013257-eb935400-692c-11ea-8fe0-505df492a75f.png">

The red star, checkmark, and medal icons are the characters in question, and are now failing color-contrast checks. I believe they meet the "incidental" exception to the minimum contrast success criteria.

## Possible fix

The characters in question are in the range F0000–FFFFD, and outside the Basic Multilingual Plane range. We could add this range to the [regex for testing non-BMP characters](https://github.com/dequelabs/axe-core/blob/7952a377b960c2403c8d4758a9f35ebe525549fe/lib/commons/text/unicode.js#L100).

Let me know if this makes sense, and I'd be happy to contribute a fix.

**Comment by ahuth** [comment]
Also, thanks for all your work on axe-core!

We use it extensively at Airbnb. For example, we've ran axe on around 16,840 CI builds so far this year. It's been instrumental to helping scale our accessibility efforts.

**Comment by ahuth** [comment]
Yikes. Updating the regex and testing it is turning out to be harder than anticipated in #2102 😞 . Not sure if there are any other potential solutions.

**Comment by pieralexandreb** [comment]
Hi, it looks like my team is also having an issue here because of the nonBmp rule. We are also using a custom font to render icons and some of our tests are broken. Is there a way to turn off the rule or to modify the rule?

**Comment by straker** [comment]
You can disable color-contrast completely, buy I don't think there's a way to modify the rule to flag icons. Would you be able to provide an example of the problem? Would love to see what's going on and maybe we can look into fixing it.

**Comment by pieralexandreb** [comment]
Yes, of course. We are using FluentUI's IconButton to build our UI and therefore we render non-text only on our buttons. FluentUI provides also some mecanisms to provide a custom icon font. We don't want to disable all the color contrast rules because they are important, but only this particular rule.
