### ISSUE TITLE
bypass blocks - heading verbiage

### ISSUE THREAD

**Issue by weboverhauls** [dequelabs/axe-core#2104]
When "Page must have means to bypass repeated blocks" is reported, under the "To solve this..." section, verbiage says "header" instead of "heading".

Expectation: "Page does not have a heading"

Actual: "Page does not have a header"

Motivation: "heading" is the correct term for solution

References:
https://dequeuniversity.com/class/wcag-conformance/interpreting/wcag/a/2.4.1/2.4.1.a
https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-skip.html

![image](https://user-images.githubusercontent.com/473400/77089018-a712c180-69db-11ea-87bc-da0383a94cab.png)

**Comment by WilcoFiers** [comment]
Fair enough. Thanks Dennis!

**Comment by padmavemulapati** [comment]
Verified with the latest devTools , and seeing the fix 
![image](https://user-images.githubusercontent.com/47409579/79881512-ea16e900-840e-11ea-932e-0eec058392d8.png)
