### ISSUE TITLE
False positive: page must have means to bypass...

### ISSUE THREAD

**Issue by dylanb** [dequelabs/axe-core#2105]
Expectation: Not raise the "page must have a means to bypass repeated blocks" violation on a page with an iframe with a heading level 1 inside the iframe

Actual: False positive violation is raised

Motivation: False positive goes against the axe manifesto

Page that exhibits the behavior https://lion-web-components.netlify.com/?path=/docs/forms-form-examples--default-story

<pre><code>
axe-core version: 3.5.1

Browser and Assistive Technology versions

For Tooling issues:
Chrome extension v4.4.1, Mac OS X
</code></pre>

**Comment by WilcoFiers** [comment]
It shouldn't matter what heading level it is, other than that, I agree.

**Comment by padmavemulapati** [comment]
Verified with the iframe ` <!doctype html>
<html lang="bob">
<head>
	<title>Hello</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
  <p>metaviewport</p>
</div>
</head>
</html>` and calling this into another iframe -- not throwing voilations or incomplete

**Comment by jeankaplansky** [comment]
comment in release notes 7/28/2020
