### ISSUE TITLE
Analysis errors out when trying to scan a page

### ISSUE THREAD

**Issue by erik-deque** [dequelabs/axe-core#2127]
Expectation: Analysis should complete without an error (page and login infor cannot be shared publicly, contact @erik-deque for this info)

Actual: The analysis errors out with the following:

`Error: Result for unknown rule. You may be running mismatch axe-core versions
    at chrome-extension://lfmcehohgifnaodaogknapedjiaoebgo/vendor.bundle.js:41:149915
    at Array.map (<anonymous>)
    at g.after (chrome-extension://lfmcehohgifnaodaogknapedjiaoebgo/vendor.bundle.js:41:149852)
    at chrome-extension://lfmcehohgifnaodaogknapedjiaoebgo/vendor.bundle.js:41:170548
    at chrome-extension://lfmcehohgifnaodaogknapedjiaoebgo/vendor.bundle.js:41:216623
    at chrome-extension://lfmcehohgifnaodaogknapedjiaoebgo/vendor.bundle.js:41:184772
    at chrome-extension://lfmcehohgifnaodaogknapedjiaoebgo/vendor.bundle.js:41:216623
    at chrome-extension://lfmcehohgifnaodaogknapedjiaoebgo/vendor.bundle.js:41:184677
    at chrome-extension://lfmcehohgifnaodaogknapedjiaoebgo/vendor.bundle.js:41:184331
    at chrome-extension://lfmcehohgifnaodaogknapedjiaoebgo/vendor.bundle.js:41:218701`

Motivation: N/A

<pre><code>
axe-core version: 3.5.1
Latest Attest and axe extensions
Chrome and Firefox

For Tooling issues:
- Platform:  Mac and Windows
</code></pre>

Note: This appears to be related to #1754

**Comment by padmavemulapati** [comment]
Verified in the latest axe (4.4.1.09019), with axe-core v 3.5.1, getting the analysed results properly. 
Verified on a site , which involves more iframes - https://revel.pearson.com/#/start
Credentials to login into this site - Student3.AQA.AXE@mailinator.com /Axeqa123
 click on the single available course (Devito_AXEtest_AQA). 
Then click "contents" and navigate to chapter 1.3.
Then Launch the axe extension , Analyze it , seeing the analysed results properly.
![image](https://user-images.githubusercontent.com/47409579/78035671-09c66e80-7387-11ea-980f-9ae684c9651a.png)

**Comment by straker** [comment]
No docs needed
