### ISSUE TITLE
Convert most APIs to accept a virtual node and return a virtual node

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core#2144]
To help simplify the API, most functions should accept a virtual node and return a virtual node (as opposed to a DOM node). This deprecates functions like `findUp` which just get passed a DOM node and find the virtual node for it and continue to `findUpVirtual`. It also avoids problems such as `findUpVirtual` accepting a virtual node but returning a DOM node.

Most `commons` functions can probably do this, but functions in `utils` might not be able to (such as `getFlattenedTree` which creates the virtual tree). But as a general rule of thumb, a function should only take and return virtual nodes.

**Comment by dylanb** [comment]
@straker is this still valid

**Comment by straker** [comment]
We've been doing a lot of this work in https://github.com/dequelabs/axe-core/issues/2734, so we can close this one.
