### ISSUE TITLE
Add superclass role to ARIA lookup table

### ISSUE THREAD

**Issue by NickAb** [dequelabs/axe-core#2151]
Incorrect role type is returned for the role of dialog: [lookup-table.js#L492](https://github.com/dequelabs/axe-core/blob/86e3324ef4c9188f164e153f0b800d26ecaad4ad/lib/commons/aria/lookup-table.js#L492).

Expectation: `axe.commons.aria.getRoleType('dialog')` returns `'window'`.

Actual: `axe.commons.aria.getRoleType('dialog')` returns `'widget'`.

Reference: https://www.w3.org/TR/wai-aria-1.1/#dialog

Motivation: I want `getRoleType` to return role types according to aria spec. This is so that we can use returned role type in a custom rule to run keyboard reachability checks.

<pre><code>
axe-core version: 3.5.2
</code></pre>

Wider issue https://github.com/dequelabs/axe-core/issues/672 was closed with suggestion to open role specific ones.

**Comment by straker** [comment]
Thanks for the issues. @WilcoFiers will have a better idea of if this is intended or not.

**Comment by WilcoFiers** [comment]
@NickAb the "type" is not intended to be an accurate representation of the element's superclass. Admittedly, it looks way too much like the superclass, so I understand the confusion. getRoleType() === 'widget' does is tell us if the thing can be focusable. You can see that for example in the focus-order-semantics rule.

To be honest, I'd like this "type" property to get deprecated and be replaced by proper superclass, and maybe have a prop that says whether or not the thing "may" or "should" be focusable. 

I think the proper solve here is to add a "superclass" property to the lookup table. Would you be open to putting in a pull request for this? Fair warning, it'll likely take 3 to 5 months before we can do another release with new features in it, so if you're in a hurry with the rule, you may want to bake a solution into the rule in the mean time.

**Comment by straker** [comment]
Link to #1677

**Comment by redgardner** [comment]
Could I take a stab at this issue if no one else is working on it?

**Comment by straker** [comment]
All yours. Let us know if you need anything.

**Comment by redgardner** [comment]
I've added the `superclassRole` property per the linked standards. Do I need to add any additional functionality around fetching this property to `getRoleType` ?

**Comment by straker** [comment]
Nope. Just adding the property to the standards file should be enough. We can take care of incorporating it into the `getRole` stuff. We still need to figure out what we want to do with it exactly.

**Comment by redgardner** [comment]
Thanks! I've created the PR: https://github.com/dequelabs/axe-core/pull/2600

I've signed the CLA but I'm still getting a note saying that I haven't signed it yet in the PR

**Comment by straker** [comment]
Thanks! I'll take a look. Sometimes the CLA can be finicky so I'll see what's going.

**Comment by padmavemulapati** [comment]
As this is code based, marking it as devTask. Please let me know if anything needs from QA.
