### ISSUE TITLE
Merge all ESLint config into a single file

### ISSUE THREAD

**Issue by stephenmathieson** [dequelabs/axe-core#2156]
Our ESLint setup frequently confuses me. I often forget to look at nested `.eslintrc` files, and as result, I end up with unexpected lint violations in my patches.

As discussed in the [ES Modules proposal](https://github.com/dequelabs/html-team-proposals/blob/master/axe-core-migration-es-modules.md), it'd be nice to just use ESLint `overrides` rather than nested/duplicated files, so there's only a single source of "lint truth".

**Comment by straker** [comment]
Dev task
