### ISSUE TITLE
Add an "ACT" tag for rules published by the W3C

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2165]
When the W3C publishes new ACT rules, we should tag the corresponding rules in axe-core with an "ACT" tag.

**Comment by padmavemulapati** [comment]
Verified with the latest axe-core-3.5.5 develop code, 
For the following rules seeing the "ACT" tag
1. `document-title` - testfile - `<html lang="en">
	<title> A brief, clear, informative, and unique title</title>
		 

	<div class="foo" id="foo">foo</div> </html>`
![image](https://user-images.githubusercontent.com/47409579/87697946-6cb20900-c7b0-11ea-8c8a-5dd65a388d62.png)
2. `html-has-lang`  & `html-lang-valid` - testfile - `<html lang="en"> ...</html>`
![image](https://user-images.githubusercontent.com/47409579/87698314-e813ba80-c7b0-11ea-800d-4abb3a2ae0b4.png)
3. `html-xml-lang-mismatch` - testfile - `<html xml:lang="en">
<body>helloo</body>
</html>`

![image](https://user-images.githubusercontent.com/47409579/87699693-daf7cb00-c7b2-11ea-8eac-4ad743293e18.png)

4.`input-image-alt` - testfile - `<input type="image" src="submit.png" name="submit"
		height="36" width="113" alt="Submit">` 
![image](https://user-images.githubusercontent.com/47409579/87698987-d67ee280-c7b1-11ea-8d7f-75d988ccc58b.png)

**Comment by jeankaplansky** [comment]
Captured in [release notes](https://docs.google.com/document/d/1BArQf-czemCkijUknsUxORdOmU5OKZK6rziL53E-HRs/edit#heading=h.hdex1llrrtxx): 3/20/2020
