### ISSUE TITLE
Every screen reader found Main inside a Section - why is landmark-main-is-top-level a best practice?

### ISSUE THREAD

**Issue by goodwitch** [dequelabs/axe-core#2166]
One of my clients is asking me why "landmark-main-is-top-level" is a best practice rule in axe?

We created this test page (http://www.glendathegood.com/a11y/landmarks.html ), where `<main>` is located inside a `<section>`.  Every screen reader we tested found `<main>` with no problem.  I've tested in the latest version of each of the following:

Desktop

- VoiceOver/Safari
- NVDA/Chrome
- JAWS/Chrome

Mobile

- VoiceOver/Safari
- Talkback/Chrome

**Expectation**: If having the Main Landmark at the top level is a best practice, I would expect an Axe failure of "main landmark is top-level" to have a real impact on users.  However, I cant see how having `<main>` inside `<section>` is having any real impact on any screen reader user.

**Actual**: Axe is throwing this error:  https://dequeuniversity.com/rules/axe/3.4/landmark-main-is-top-level?application=AxeFirefox

**Motivation**:  I want every ounce of energy used to fix a11y problems to actually have meaningful results that help real people with disabilities.  

I have a sneaking suspicion that this "best practice" is based on W3C validation (even though the validator does not throw any 4.1.1 errors).  And that this is about future-proofing (what if some future screen reader of AT can't handle <main> instead <section>. 

axe-core version: 3.5.1
axe extension version: 4.4.1

Browser and Assistive Technology versions
Firefox 75

**Comment by goodwitch** [comment]
Would y'all be willing to update the "Learn More" page to reference whatwg's quote:  "A hierarchically correct main element is one whose ancestor elements are limited to html, body, div, form without an accessible name, and autonomous custom elements. Each main element must be a hierarchically correct main element."  source: https://html.spec.whatwg.org/#the-main-element:the-main-element

**Comment by straker** [comment]
@jkodu would you be able to update the docs for `landmark-main-is-top` with the note?

**Comment by jeankaplansky** [comment]
Glenda and Paul approved.
