### ISSUE TITLE
Language handling for testing output

### ISSUE THREAD

**Issue by pgalle** [dequelabs/axe-core#2172]
Hello guys and girls,

I'm new to using axe-core and I'm using it inside of a apify crawler using puppeteer. I'm just trying to change the output language for example to german. As far as I could understand the documentation and the code it should look like the following:

``` js
const language = fs.readFileSync('path to axe locale file', 'utf8')
const handle = await page.evaluateHandle(`
  // inject axe source code
  ${AxeCore.source}
  //run axe
  axe.run({
  options: {
    locale: ${language}
  }
})

const results = await handle.jsonValue()
await handle.dispose()
```

For the default language, english, it works great. For other languages I choose nothing changes. I don't get an error.

I'm using the version 3.5.3 of axe-core, installed via npm, Ubuntu Bionic Beaver and node version 12.16.2. Npm ist on version 6.14.4 

Is my configuration wrong, if so what would be correct, or is this a real issue?

Kind regards
Pascal

**Comment by pgalle** [comment]
Well it works like I showed in my code. However what created the issue wasnt related to axe itself, but to my apify app not reloading the configuration.

Wouldn't it be more convenient to just input the language code like "de" or "jp"?

**Comment by straker** [comment]
It would be more convenient to just be able to just say `axe.locale = 'es'`, however that would mean we would need to bundle all languages into axe to do that. That would make the bundle unnecessarily too large. For example, [Momentjs](https://momentjs.com/) with all the locale data is 50K more gizzped, and their locale data per locale is much smaller than ours.
