### ISSUE TITLE
Cannot read property 'querySelectorAll' of undefined #1136

### ISSUE THREAD

**Issue by dythebs** [dequelabs/axe-core#2177]
Test website [http://movie.mtime.com/](http://movie.mtime.com/) and produces an uncaught exception: `AxeRuntimeException: Cannot read property 'querySelectorAll' of undefined`

I entered `Array.prototype.reduce` on console and get
```
Array.prototype.reduce
ƒ (){return this.length>1?this:this[0]}
```
which is same as [http://speedtest.att.com/speedtest/](http://speedtest.att.com/speedtest/)
but my code can get the correct result on the latter.
So it seems that the [issue#1136](https://github.com/dequelabs/axe-core/issues/1136) is not completely solved.

<pre><code>
axe-core version: 3.5.3

Browser and Assistive Technology versions
chrome verison: 78.0.3892.0

For Tooling issues:
- axe-selenium-java version: 3.0  
- Platform:  Windows
</code></pre>

**Comment by straker** [comment]
Unfortunately there's nothing we can really do if the website provides an incorrect override/polyfill to a native functions. Thus we added a [note to the readme](https://github.com/dequelabs/axe-core#supported-browsers):

> We can only support environments where features are either natively supported or polyfilled correctly.
