### ISSUE TITLE
Add generic matches-definition evaluate method

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2185]
This evaluate method would test if an element matches some configuration of axe.commons.matches().

It would look something like this:

```js
function matchesDefinition(_, options, virtualNode) {
  return axe.commons.matches(virtualNode, options.matcher)
}
```

A number of existing evaluate methods will be replaced by this more generic solution. As part of resolving this ticket we'll have to look at which evaluate functions this can replace, and replace them.

**Comment by WilcoFiers** [comment]
Navigation/header-present can be replaced with this.

**Comment by padmavemulapati** [comment]
devTask

**Comment by jeankaplansky** [comment]
no rule help required.
