### ISSUE TITLE
Pull out deprecated commons, checks and rules for axe-core 4.0

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2189]
Anything that has been marked as deprecated in 3.5.0 or before then should be removed from axe-core 4.0.

Make sure to also pull out support for `ver` in axe.configure.

**Comment by straker** [comment]
https://github.com/search?q=deprecated+repo%3Adequelabs%2Faxe-core+created%3A%3C2020-02-10&type=Code&ref=advsearch&l=&l=

**Comment by padmavemulapati** [comment]
devTask

**Comment by jeankaplansky** [comment]
@straker: Is this up-to-date?: https://github.com/dequelabs/axe-core/blob/master/doc/rule-descriptions.md#deprecated-rules

**Comment by straker** [comment]
Develop has the most up-to-date list https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md#deprecated-rules

**Comment by jeankaplansky** [comment]
@straker: Include the list of deprecated rules that were removed in the release notes? Seems like a very good place for this type of information...

**Comment by jeankaplansky** [comment]
captured in [release notes](https://docs.google.com/document/d/1BArQf-czemCkijUknsUxORdOmU5OKZK6rziL53E-HRs/edit#) 7/20/2020
