### ISSUE TITLE
Ensure check options is always an object

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2191]
Currently check options can be any type. Axe-core currently has arrays and objects here. It would be better if all of these were objects, making the API more predictable and easier to document.

We'll have to make this backward compatible though, so that if someone passes an array as an option, checks that support array options in axe-core 3.5 know how to handle it for the new object structure. For example, we could give it a key, so that `['foo']` is passed as `{ value: ['foo'] }` into the evaluate function.

**Comment by padmavemulapati** [comment]
devTask

**Comment by jeankaplansky** [comment]
no user-facing rule help docs required.
