### ISSUE TITLE
Add generic matches-descendants evaluate method

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2193]
There are a few evaluate methods that can be made more generic, as they just run QSA on the virtual node. This more generic evaluate method would replace them. It'd look something like this:

```js
const selector = options.selector
return axe.utils.querySelectorAll(virtualNode, selector).length > 0;
```

We'd replace all evaluate methods that follow this pattern with the generic version of it.

**Comment by WilcoFiers** [comment]
Can replace "caption" and "description" checks, for starters.

**Comment by padmavemulapati** [comment]
devTask

**Comment by jeankaplansky** [comment]
behind the scenes stuff; no user-facing rule help docs required.
