### ISSUE TITLE
Provide more options for non-generic check evaluate functions

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2195]
Adding these options will make it easier to configure these checks in custom rules:

* [x] Label/duplicate-img-label
    * Options for parent selector
* [x] Language/has-lang
    * Options for which attributes to look at
* [x] Language/valid-lang
    * Options for which attributes to look at
* [x] Navigation/region
    * Option for what elements are considered regions using a matcher
* [x] Shared/avoid-inline-spacing
    * Option for inline spacing css props
* [x] Tables/scope-value
    * Option for invalid values of scope

Other checks either already have options, they will be replaced with more general checks, or they will be configurable through commons.

**Comment by straker** [comment]
QA: you'll need to look at each of the individual prs listed here to know what the options for each check is called.

**Comment by padmavemulapati** [comment]
Seeing the changes on all Options (Options.value) and instead normal methods, observed getter methods and call funtions. Please let me know is there any specific impacts on tests/test results.
