### ISSUE TITLE
Heading-order rule does not flag multiple H1's

### ISSUE THREAD

**Issue by devarshipant** [dequelabs/axe-core#220]
When I run the rule "heading-order": { enabled: true } on a webpage with semantically incorrect headings - heading level 1 followed by heading level 2 and then two heading level 1, the enabled rule does not catch the error. 
![2 violations do not include heading order](https://cloud.githubusercontent.com/assets/7377040/18126618/fccc9ff0-6f49-11e6-8dd3-9d7f0634e169.png)

**Comment by marcysutton** [comment]
To capture what we've discussed about this issue:

> Multiple h1s does not cause any accessibility issue, but it might cause blind users to stop searching after reaching the first h1. But many screen readers have ways to jump between headings of certain levels, look at the structure etc. So if someone does not know the site, they probably would explore the entire heading structure and it would not cause problems. If someone does know the site, they would know there are multiple h1s.

> So the biggest problem is if the site otherwise does not use multiple h1s and suddenly, 1 page does:  this is where an automated best practice rule can be useful.

> We should separate out the multiple h1s from other structure problems with heading such as missed levels even though they are both best practices.

So the TODO is to create another best practice rule for multiple h1's independent missed levels.

**Comment by WilcoFiers** [comment]
Based on some discussion we've come to conclude that there are valid cases for using multiple H1 elements. Which means it isn't a best practice, and so it doesn't fit within aXe. I suggest if you're looking to do this, you can add a custom rule using `axe.configure()`.

**Comment by zelliott** [comment]
What are the valid use cases for including multiple h1 elements? I'd imagine one valid use case is a page that (1) has an h1 heading and (2) has a dialog that additionally has its own h1 heading. Thus, the page has two h1 headings, but only one is visible at any given point in time.

Is it true to say then that a page should only ever have a single h1 heading that is accessible to a screen reader *at any single point in time*?

**Comment by dylanb** [comment]
As pointed out in #1544 this could be a needs review best practice...
