### ISSUE TITLE
Add "ancestry" property to nodes

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2209]
Currently, axe-core has the "selector" property, which gives a CSS selector that is designed to be easy for developers to read, and understand the element from. This selector is helpful, but costly to compute and somewhat prone to change.

A selector that is more stable across axe-core versions could be an "ancestry" selector, which just lists all the node names down to the root, including only which child was selected. The ancestry selector would look something like this:

```
['html > body > iframe', 'html > body > main > div:nth-child(2) > p > img']
```

The "ancestry" property would be in addition to the existing "selector" property.

**Comment by WilcoFiers** [comment]
We should check for performance, if this adds a significant amount of time, make this an option that's off by default.

**Comment by padmavemulapati** [comment]
devTask

**Comment by jeankaplansky** [comment]
Added to internal release notes 7/27/2020
