### ISSUE TITLE
Custom Rules

### ISSUE THREAD

**Issue by sbollu** [dequelabs/axe-core#221]
Hi, 
I am planning to add or modify with some custom rules in JSON file. 
I would like to know how to create axe.min.js file from custom rules. 

If any one have idea or how to create custom axe.min.js file please let me know. 

At present axe.min.js file creating from npm install axe-core, I think it will create package from axe-core from github.

To create package from local github clone , how to create ? 

Thanks,
Sri.

**Comment by marcysutton** [comment]
I would advise against modifying the source code. Instead, use `axe.configure()` and pass in your JSON string. Here is the API documentation for that: https://github.com/dequelabs/axe-core/blob/master/doc/API.md#api-name-axeconfigure
