### ISSUE TITLE
Zooming and scaling must not be disabled on iframed page

### ISSUE THREAD

**Issue by thedamon** [dequelabs/axe-core#2210]
Is it truly an accessibility issue if a page exists only for being iframed and it has user-scaling disabled? We are getting that issue, and do not have access to the source page, and I'm just trying to figure out how I would scale an iframe if I wanted to.

**Comment by WilcoFiers** [comment]
We're doing some testing. I suspect you are right, and that user-scalable only impacts resize if it's on the top window, not when it is used in iframes. If so we'll fix it. Thanks for reporting!
