### ISSUE TITLE
<ul> with role presentation being flagged by <li> rule

### ISSUE THREAD

**Issue by Brynman** [dequelabs/axe-core#2217]
Expectation: << <li> elements must be contained in a `<ul>` or `<ol>`, should not flag elements with role `presentation` >>

Actual: << `<li>` elements nested in in parent `<ul>` with `role="presentation"` are failing the above check onhttps://www.waitrose.com/ecom/products/essential-waitrose-semi-skimmed-milk/053457-26759-26760

![image](https://user-images.githubusercontent.com/60389544/81285974-42c5c300-9058-11ea-9171-b06d58cbd5f5.png)
>>

Motivation: << Unless I am missing something this element is not exposed to AT and so it doesn't matter that the `<ul>` doesn't have a list role>>

<pre><code>
axe-core version: 4.4.1 (Plan: Professional axe-core 3.5.1)
axe-webdriver, extension or other integration version: NA

Browser and Assistive Technology versions: Safari 13.1.1 + VoiceOver

**Comment by straker** [comment]
Thanks for the issue. It seems that we do not take into account `role=presentation | none` when determining the parent of an `<li>`.

**Comment by padmavemulapati** [comment]
Verified with the fix - Not seeing Parent- children failures for `ui` `li` elements even with `role=presentation | none ` 
![image](https://user-images.githubusercontent.com/47409579/82628339-2f932580-9c0a-11ea-895f-0856f133e774.png)

**Comment by jeankaplansky** [comment]
No user-facing rule help docs required.
