### ISSUE TITLE
"Frame-title" rule has misleading description and help text

### ISSUE THREAD

**Issue by iamrafan** [dequelabs/axe-core#2223]
The ```frame-title``` rule does more than just look for the presence of ```title``` attribute on the iframes, hence the current description, help text and help page content for this rule need to be changed

Expectation: Have appropriate help and description text

Actual: 
> "description": "Ensures <iframe> and <frame> elements contain a non-empty title attribute"
>"help": "Frames must have title attribute"

Motivation: ```frame-title``` rule checks for the presence of any of the following

	"aria-label",
	"aria-labelledby",
	"non-empty-title",
	"role-presentation",
	"role-none"

<pre><code>axe-core version: 3.5.2-canary.37be85f
axe-Coconut version: 4.4.1</code></pre>

**Comment by WilcoFiers** [comment]
I'm actually considering pulling the aria-label(ledby) checks off this. For some reason those don't seem to work in Safari.

**Comment by WilcoFiers** [comment]
Changed my mind on the above. I think we'll keep the rule the way it is. I do think the help / description needs to be updaed.

**Comment by padmavemulapati** [comment]
Verified with the latest develop branch code of axe-core(dated 15th jan 2021)
Seeing the description updated for the rule `frame-title' 
from: `description: "Ensures <iframe> and <frame> elements contain a non-empty title attribute"
help: "Frames must have title attribute"`
to: `description: "Ensures <iframe> and <frame> elements have an accessible name" `
`help: "Frames must have an accessible name"`
![image](https://user-images.githubusercontent.com/47409579/104745884-930f2c00-5774-11eb-851c-43bfb2860555.png)
