### ISSUE TITLE
aXe Coconut issue for rule: Elements in the focus order need a role appropriate for interactive content

### ISSUE THREAD

**Issue by Mottie** [dequelabs/axe-core#2227]
While performing some testing on a page with lots of hidden content (dropdown menus), I encountered an issue where axe is reporting a focus error with it's own highlight tool.

![Screen Shot 2020-05-11 at 10 06 50 AM](https://user-images.githubusercontent.com/136959/81577654-53837b00-936f-11ea-9458-210457c939a2.png)

**Comment by erik-deque** [comment]
Thanks for reporting this issue @Mottie. Do you have any steps or instructions to help us reproduce the error?

**Comment by Mottie** [comment]
Unfortunately, I didn't see how the issue occurred, but I was testing a multi-step form built using [react-jsonschema-form](https://github.com/rjsf-team/react-jsonschema-form). So that highlight box may have be located in the footer content that did not update while I switched between page forms.

**Comment by erik-deque** [comment]
This issue will be resolved in the 4.5.1 release of the extension.
