### ISSUE TITLE
Confidential Privacy Question

### ISSUE THREAD

**Issue by kellyannmcnamara01** [dequelabs/axe-core#2228]
### Question: 
I am working on a confidential site that only has access through a portal. I want to use your AXE tools locally/on the staging env to test accessibility but I need written confirmation that you don't pull the content of the sites. When I say content I mean the actual text people would read when they are viewing the site. The privacy policy isn't very clear about the actual content of the sites running your tools. 

Can you please confirm you do not collect the written content? 

_P.S I reached out to the helpdesk and they said I had to issue a ticket for this yes-no question. Sorry for any inconvenience this might cause._

**Comment by erik-deque** [comment]
When you say "AXE tools" are you referring to the free axe Chrome extension? No data is collected with the base analysis functionality.

Information may be collected when using advanced functionality that is part of axe beta.

**Comment by kellyannmcnamara01** [comment]
Yes, Thank you

Cheers,
Kelly

**Comment by erik-deque** [comment]
Question answered.

**Comment by tomaszwojciechowski** [comment]
How about collecting data during usage of https://www.npmjs.com/package/axe-core?
