### ISSUE TITLE
Create local min.js file

### ISSUE THREAD

**Issue by sbollu** [dequelabs/axe-core#223]
I am trying to create axe.min.js file from local repository.  Please let me know how to run npm install for local repository to create axe.min.js file
1. I have downloaded git axe-core package 
2. Modified some of the rules 
3. trying to create new axe.min.js file from local modified project 

I am trying to add some custom rules and build new axe.min.js file to run pages with custom rules.

Please let me know how to create axe.min.js file from local project.

**Comment by marcysutton** [comment]
Hi, I answered the same question from you here: https://github.com/dequelabs/axe-core/issues/221

You should not modify source code to add custom rules. Rather, you should use the API as I illustrated in the other issue. Is there a specific reason why you need a single file?
