### ISSUE TITLE
Document correction: API Name: axe.getRules section need correction

### ISSUE THREAD

**Issue by padmavemulapati** [dequelabs/axe-core#2248]
https://github.com/dequelabs/axe-core/blob/master/doc/API.md
API document. wcag2a should not be mapped with WCAG2.1 Level A. Same issue with other tag wcag2aa
![image (30)](https://user-images.githubusercontent.com/47409579/82689757-9e0ecc80-9c78-11ea-98a4-a2ce3062cd74.png)

**Comment by jeankaplansky** [comment]
@padmavemulapati assigned me, but this is axe-core docs; @straker is the right person to fix this one.

**Comment by WilcoFiers** [comment]
This is incorrect. WCAG 2.0 level A success criteria are required for WCAG 2.1 level A as well.

**Comment by somaalapati** [comment]
Convinced, but the details look confusing.
