### ISSUE TITLE
role=presentation on <dl><dt><dl>  should be allowed

### ISSUE THREAD

**Issue by DavidMacDonald** [dequelabs/axe-core#2258]
Currently this is flagging an error in AxeCore 3.5.3.

**Comment by WilcoFiers** [comment]
Thanks for reporting. You're absolutely correct. We fixed this for ul / ol recently. Hasn't been released yet. I'll make sure we go back to check it also works for dl.

**Comment by padmavemulapati** [comment]
Verified in axe-core3.5.5 (with the test content ` <dl role="presentation"><dt id="target">My list item</dt></dl>` ) not seeing any error  but seeing the results in passes:
![image](https://user-images.githubusercontent.com/47409579/85303397-0c3cee00-b4c8-11ea-850e-c3a869c92b92.png)

**Comment by jeankaplansky** [comment]
no user-facing docs required.
