### ISSUE TITLE
Rule "color-contrast" does not include section508

### ISSUE THREAD

**Issue by devarshipant** [dequelabs/axe-core#226]
Refer to rule descriptions at https://github.com/dequelabs/axe-core/blob/master/doc/rule-descriptions.md and check rule "color-contrast." Shouldn't section508 tag be part of the rule besides wcag2aa, wcag143? Refer to 1194.21 (j) that says "When a product permits a user to adjust color and contrast settings, a variety of color selections capable of producing a range of contrast levels shall be provided."

**Comment by dylanb** [comment]
@devarshipant 1194.21 (j) just requires that IF there is the ability to select the colors in a UI, then there must be "a wide variety" of choices. There is no way we could test for that programmatically. There is as far as we know, no requirement in the current 508 for color contrast.

However, you can always turn on the rule through the API, or add it to your 508 rule set yourself through the API.

**Comment by devarshipant** [comment]
Correct - There is no requirement in the current 508 for color contrast, but wide variety of choices possibly imply ratios above and beyond standardized threshold ratios, and federal agencies, when testing, follow the 3:1 and 4.5:1 contrast ratio requirements - http://www.section508.va.gov/support/html/3_7.asp.

Including the contrast requirement within Section508 tag would mean running a single section508 test.

I tried to turn on the ‘color-contrast’ rule besides ‘section508’ but could not detect contrast issues.

  var config = {

  runOnly: {
      type: "tag",
      values: ["section508", "color-contrast"]
    },
}
axe.a11yCheck(document, config, function(results) {
  console.dir(results.violations);
});
