### ISSUE TITLE
"opacity: 0" elements are treated as visible

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core#2261]
`utils.isHidden` and `dom.isVisible` do not take into account opacity. As such, a node with `opacity: 0` is visible and not hidden according to axe.

```html
<h1 id="target" style="opacity: 0">Title</h1>

<script>
axe.utils.isHidden(target);  // false
axe.commons.dom.isVisible(target);  // true
</script>
```

This leads to some interesting results when a combox dropdown menu is "hidden" using opacity. 

```html
<div style="color: gray; background-color: white; font-size: 14pt; font-weight: 100;">
  <span id="target" style="font-weight:bolder; opacity: 0;">My text</span>
</div>
```

Color contrast runs on the nodes and reports incomplete for nodes that are not visible on screen.

**Comment by padmavemulapati** [comment]
Verified with the test file - 
`<div style="color: gray; background-color: white; font-size: 14pt; font-weight: 100;">
  <span id="target" style="font-weight:bolder; opacity: 0;">My text</span>
</div>`
when a combox dropdown menu is "hidden" using opacity. Color contrast runs on the nodes and reports incomplete for nodes that are not visible on screen. (attached  screenshot)

![image](https://user-images.githubusercontent.com/47409579/84401547-05d58900-ac21-11ea-8eef-618d6fc9f5e2.png)
