### ISSUE TITLE
children of scroll regions with 0 height are considered visbile

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core#2262]
A scroll region with 0 height will not display any of the contents, but all children (and the scroll region itself) are considered visible and so all rules run against those nodes even when not visible on screen (especially color contrast).

```html
<div style="color: gray; background-color: white; font-size: 14pt; font-weight: 100; overflow: scroll; height: 0">
  <span id="target" style="font-weight:bolder">My text</span>
</div>
```

This throws an error in color-contrast and returns as incomplete.

**Comment by padmavemulapati** [comment]
Verified with the test file -
` <div style="color: gray; background-color: white; font-size: 14pt; font-weight: 100; overflow: scroll; height: 0">
  <span id="target" style="font-weight:bolder">My text</span>
</div> `
This throws an error in color-contrast and returns as incomplete.
![image](https://user-images.githubusercontent.com/47409579/84402105-ad52bb80-ac21-11ea-8816-e516d99052eb.png)
