### ISSUE TITLE
JR

### ISSUE THREAD

**Issue by snv0** [dequelabs/axe-core#2265]
Expectation: << Describe what you expect the product to do >>

Actual: << Describe what the product actually does >>

Motivation: << Describe why you want the behavior to be changed >>

<pre><code>
axe-core version: X.Y.Z
axe-webdriver, extension or other integration version: X.Y.Z

Browser and Assistive Technology versions

For Tooling issues:
- Node version: XX  
- Platform:  
</code></pre>

**Comment by straker** [comment]
@snv0 did you mean to open an issue here? Your comment is just the issue template.

**Comment by snv0** [comment]
> @ snv0 هل تقصد فتح مشكلة هنا؟ تعليقك هو مجرد قالب المشكلة.

مجرد خطاء
