### ISSUE TITLE
displaying different violations count on chrome plugin and axe API

### ISSUE THREAD

**Issue by Sathish406** [dequelabs/axe-core#2269]
1) I have installed axe-core plugin in my chrome machine.
2) Tested my live site URL with that chrome plugin it shows 0 violations.
3) I copied that URL Web site content and pasted inside a div in my angular application and tested the page in chrome plugin. Now it shows 4 violations.
4) I tested the above with axe-core API but now it shows only 3 violations.

P.S: for a confirmation i have done the same scenario for the following URL 'https://www.deque.com/company/contact' 
But now all the above(2, 3, 4) shows same result which is violations are 0.

Can you please help me to solve this.

**Comment by straker** [comment]
It's hard to say what the issue could be without seeing the page in question, but adding another pages web contents to a `div` of another page might cause some violations with DOM structure.

**Comment by straker** [comment]
I'd have to be able to see the final DOM structure of your angular app to be able to say what's going on. Would it be possible to put it up in codepen or something similar for me to look at?

**Comment by straker** [comment]
@Sathish406 any update on this?

**Comment by Sathish406** [comment]
yes i resolved this issue. i cleared dom elements then added that html content inside to div then loaded via axe it works fine now. thanks
