### ISSUE TITLE
Ship one more v3.5.x release?

### ISSUE THREAD

**Issue by paulirish** [dequelabs/axe-core#2280]
https://github.com/dequelabs/axe-core/pull/2238 is a fairly high priority fix for Lighthouse.

Would you be willing to make a release?

If it helps, I took some time and made a `v3.5x` branch which contains every bugfix that's landed in `develop` post-3.5.3. I manually resolved a bunch of conflicts and ensured the tests are passing.

https://github.com/paulirish/axe-core/commits/v3.5.x  

Admittedly, I excluded [one commit](https://github.com/dequelabs/axe-core/commit/e9dd2598b469fcbf936517aba33f983191301ff9) as that complexity of porting that one was ... not very alluring. :)

------

All this said, what's your expectation with #2261 and #2262? Ideally I'd like to get those fixes back into Lighthouse asap. TBH i'd personally be quite content with false negatives rather than throwing, but obviously, that's your call. :)

**Comment by dylanb** [comment]
@WilcoFiers I think we should put out another release ASAP with the fix mentioned

**Comment by WilcoFiers** [comment]
Makes sense. There are a few other things I'd like to get released before 4.0. Aiming for a release next week.

**Comment by WilcoFiers** [comment]
Update, yeah we're going to try to get fixes done for #2261 and 2262. Once those are fixed we'll do a patch release.

**Comment by straker** [comment]
Release pr for 3.5.5 #2297

**Comment by straker** [comment]
Axe 3.5.5 has been released https://www.npmjs.com/package/axe-core/v/3.5.5
