### ISSUE TITLE
role="presentation" on <hr> tag

### ISSUE THREAD

**Issue by andyricchuiti** [dequelabs/axe-core#2288]
when adding a role="presentation" it's showing a violation even though mdn and aria say that an hr tag is [allowed to have that role](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hr)

Expectation: adding a role="presentation" does not trigger a semantic violation

Actual: It currently does

<img width="938" alt="Screen Shot 2020-06-12 at 1 06 36 PM" src="https://user-images.githubusercontent.com/7213108/84533555-f6e8e800-acad-11ea-978f-ee76abeacbf3.png">

Motivation: My accessibility team has tagged our code with a violation because our hr tag does not have a role="presentation"

<pre><code>
"axe-core": "3.5.3"
"@deque/attest-puppeteer": "^2.10.5"

Browser and Assistive Technology versions

For Tooling issues:
- Node version: 12.13.1 
- Platform: mac 10.15.4
</code></pre>

**Comment by habeebmh** [comment]
Having the same issue on `2.11.1`.

**Comment by andyricchuiti** [comment]
@WilcoFiers sorry for at-ting you, but would love guidance on this if there's something i'm missing. thanks for your time

**Comment by straker** [comment]
This seems to be an error on our part. Our list of [allowed elements for presentation](https://github.com/dequelabs/axe-core/blob/develop/lib/commons/aria/lookup-table.js#L1499-L1524) needs to include the `hr` element.

**Comment by andyricchuiti** [comment]
awesome! thanks so much for looking into it, @straker!

**Comment by WilcoFiers** [comment]
Thanks for reporting, yeah this is an error. Thank you for reporting!

**Comment by padmavemulapati** [comment]
tested with the test file ` ` and axe-core3.5.5 `aria-allowed-role` for `<hr role=presentaiton> is not throwing in voilations now, its in passes
Passes attachement:
![image](https://user-images.githubusercontent.com/47409579/85302144-6341c380-b4c6-11ea-9632-fefb71d89f75.png)
Voilatons attachement: ( `aria-allowed-role` node is there but not for <hr> )
![Uploading image.png…]()

**Comment by jeankaplansky** [comment]
no user-facing docs required.
