### ISSUE TITLE
Rule ID -- audio-caption: Ensures <audio> elements have captions 

### ISSUE THREAD

**Issue by devarshipant** [dequelabs/axe-core#229]
Hi,

Hoping I am wrong -- Just noticed that the rule 'audio-caption' does not run properly (code attached).

[audio.txt](https://github.com/dequelabs/axe-core/files/476762/audio.txt)
thanks!

**Comment by dylanb** [comment]
It works just fine, the attached file does not raise any violations

**Comment by devarshipant** [comment]
It works for me now. thanks!

**Comment by devarshipant** [comment]
ok, here is something I noticed - API does not raise any violation when there are two track elements with only one using the kind attribute. In the attached file, source with label "Svenska" has the caption, but not the English one. Should it raise a violation when either one is missing?
[aud.txt](https://github.com/dequelabs/axe-core/files/480316/aud.txt)

**Comment by dylanb** [comment]
no, we cannot tell what language the multimedia file is in, so we cannot tell when it needs a different, or multiple languages. We only flag those that have no captions at all.
