### ISSUE TITLE
Issue for language codes

### ISSUE THREAD

**Issue by umaar** [dequelabs/axe-core#2298]
Probably missing some context but in the [valid-langs.js](https://github.com/dequelabs/axe-core/blob/develop/lib/core/utils/valid-langs.js) file, is it correct that there are codes like `aaa, aab, aac` and different permutations like that? What is the reason?

I would've assumed language codes would be something like [this](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)

**Comment by WilcoFiers** [comment]
Jup, three-letter code are correct language codes. "aaa" is the code for Ghotuo, "aab" is Alumu-Tesu, and "aac" is "Ari". They are fairly obscure languages. I'm not sure if there are any assistive technologies that support them, that's not really something we can prove, so axe-core supports these.

All official language codes are in the IANA language subtag registry: https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

**Comment by umaar** [comment]
Woah, had no idea! Thanks for sharing that, useful to know 👍️

**Comment by WilcoFiers** [comment]
Yer welcome!
