### ISSUE TITLE
typescript: TagValue is missing many values

### ISSUE THREAD

**Issue by stephenmathieson** [dequelabs/axe-core#2312]
The [`TagValue`](https://github.com/dequelabs/axe-core/blob/develop/axe.d.ts#L8) type is missing _many_ values. This makes setting these tags impossible when using the TypeScript compiler (as most Attest products do).

<details>
<summary>
Tags that are not allowed by the definition, but are used in axe itself
</summary>

Each of these tags can be seen in the [`doc/rule-descriptions.md`](https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md) file.

- cat.aria
- cat.color
- cat.forms
- cat.keyboard
- cat.language
- cat.name-role-value
- cat.parsing
- cat.semantics
- cat.sensory-and-visual-cues
- cat.structure
- cat.tables
- cat.text-alternatives
- cat.time-and-media
- section508.22.a
- section508.22.f
- section508.22.g
- section508.22.i
- section508.22.j
- section508.22.n
- section508.22.o
- wcag111
- wcag121
- wcag122
- wcag131
- wcag143
- wcag211
- wcag221
- wcag224
- wcag241
- wcag242
- wcag244
- wcag2aaa
- wcag311
- wcag312
- wcag325
- wcag332
- wcag411
- wcag412
</details>

<details>
<summary>
Additional tags used by Attest, but are not seen in the rule-descriptions.md file
</summary>

Used by Attest, but not seen in `axe-core`:

- cat.time
- section508.22.b
- wcag125
- wcag125
- wcag144

</details>

---

I'm happy to update the `TagValue` type to include these tags, but this doesn't seem like a sustainable practice, as we're going to eventually add more tags (and forget to add them).

Thoughts on how to continue?

**Comment by stephenmathieson** [comment]
Related #2313

**Comment by straker** [comment]
Our type file continues to be out of date with our actual API. We should either convert our code to use TypeScript or develop a way to automate the types file. I vote on the former.
