### ISSUE TITLE
bug: axe not finding elements passed in to web component

### ISSUE THREAD

**Issue by liamdebeasi** [dequelabs/axe-core#2318]
Axe does not seem to find content that was passed into a web component.

Steps to reproduce:

1. Open this example: https://codepen.io/liamdebeasi/pen/vYLmOpm. It might be easier to fork this an open it in "Debug" mode/its own frame.
2. Open Dev tools.
3. Inspect the `ion-select` component. Notice is has `role="listbox"`.
4. Inspect any of the `ion-select-option` components inside of `ion-select`. Notice that they all have `role="option"`.
5. Run Axe.
6. You should get an issue that says `Certain ARIA roles must contain particular children`. In this case, it wants the children to have `role="option"`, which the `ion-select-option` components do.

Expectation: I would expect Axe to not issue this warning.

Actual: Axe is issuing a warning that child elements do not have a particular role.

Motivation: I am passing in select option components that do have `role="option"`.

Is it possible that Axe is only looking inside of the shadow root when it detects a shadow DOM component?

<pre><code>
axe-core version: 3.5.4
axe extension version: 4.5.2

Browser and Assistive Technology versions: Chrome 83.0.4103.106

For Tooling issues:
- Platform:  macOS 10.15.5
</code></pre>

**Comment by straker** [comment]
I must say, `ion-select` is an interesting component. The component opens the options as a modal and you select them as a checklist. However, the component doesn't appear to have a tab stop so I can't open it via the keyboard. If I turn on VoiceOver I can navigate by line to the button (which doesn't have an accessible name) and open the modal from there. However, my focus stays on the button and I'm unable to use the up/down arrow keys to select an option. I instead have to tab to the modal and each of the options. Enter does not select the option, but instead checks it and I have to confirm my choice with the OK button. Finally, after selecting a choice, the component does not tell me what choice is selected. For that I would have to reopen the modal and find the checked option myself.

However, none of that is about your question. The `listbox` role requires every owned element to be an `option`. The error is finding the option roles of `ion-select-option`. What it's failing on is the shadowroot elements of `ion-select` which are non-option elements, such as the `button`. So as far as I can tell, the code is working as expected.

**Comment by liamdebeasi** [comment]
Yes, `ion-select` certainly has plenty of accessibility issues we need to improve upon.

Is there a way to tell Axe to ignore the elements in the shadow root? Those elements are purely decorative, and what VoiceOver should see is the host `ion-select`.

**Comment by straker** [comment]
Unfortunately no. But the button isn't decorational as it's the only thing that can receive the keyboard focus, and the `placeholder` div is what is giving the ion-select its name as the `aria-labelledby` target element isn't in the DOM.

**Comment by liamdebeasi** [comment]
Thanks for clarifying 👍
