### ISSUE TITLE
Color Contrast issue on selected issue - list of issues panel (left)

### ISSUE THREAD

**Issue by srinivasuchakravarthula** [dequelabs/axe-core#232]
Description: When an issue is selected to view details, background changes to blue and text remains black. This causes difficulty for users with low vision (like me) to read that issue again. 

Steps to reproduce:
1. Open a web page (be sure to pick a page that ptotentially have accessibility problems)
2. Run aXe extension
3. Click on "Analyze" button
4. Select one of the issues from the list
5. Notice background of selected issue changes to Blue and text remains black.

Environment Noticed:
Browser: Firefox (latest)
OS; Windows 7
aXe version: 1.0.2

Screenshot: Attached
![axe-results-color-contrast-srini](https://cloud.githubusercontent.com/assets/5158620/18772868/ee39aa7a-8167-11e6-82f5-9972b1de6cca.PNG)

**Comment by dylanb** [comment]
@srinivasuchakravarthula This is an axe-firefox-devtools problem, not an axe-core problem, can you open the issue at that project https://github.com/dequelabs/axe-firefox-devtools
