### ISSUE TITLE
API docs for getRules/runOnly are misleading

### ISSUE THREAD

**Issue by jamime** [dequelabs/axe-core#2327]
Expectation:
The [documentation](https://www.deque.com/axe/axe-for-web/documentation/api-documentation/) should be consistent with the repo.
This was fixed in the repo in https://github.com/dequelabs/axe-core/pull/2169 but it is not reflected on the website.

Additionally both tables should be the same, or they should not be duplicated `runOnly` and `getRules` both accept the same tags AFAIK.

Actual: 
`getRules` says `wcag2a` and `wcag2aa` include both WCAG 2.0 and WCAG 2.1 rules (incorrect).
![image](https://user-images.githubusercontent.com/2328042/85731184-340f9a00-b6f2-11ea-945a-08e0902a57f5.png)

`runOnly` table does not say `wcag2a` and `wcag2aa` include both WCAG 2.0 and WCAG 2.1 rules (correct).

![image](https://user-images.githubusercontent.com/2328042/85738552-088fae00-b6f8-11ea-875c-e0b5628084fb.png)

![image](https://user-images.githubusercontent.com/2328042/85739448-b69b5800-b6f8-11ea-83b4-035556c21a2b.png)

- wcag2a has 52 rules
- wcag2aa has 3 rules
- wcag21a has 1 rule
- wcag21aa has 3 rules

![image](https://user-images.githubusercontent.com/2328042/85740215-58bb4000-b6f9-11ea-8630-cb8b07562dfb.png)

- wcag2a does not include wcag21a
- wcag2aa does not include wcag21aa
- wcag21a does not include wcag2a
- wcag21aa does not include wcag2aa

Motivation:
The documentation should match the behaviour.

<pre><code>
axe-core version: 3.5.5
@storybook/addon-a11y version:  5.3.18

Browser and Assistive Technology versions

For Tooling issues:
- Node version: v12.16.1
- Platform:  Mac
</code></pre>

**Comment by straker** [comment]
Sorry, I've seem to have missed this one. I've created a [ticket to go over all the docs](https://github.com/dequelabs/axe-core/issues/2277) to ensure they are up-to-date and correct. I'll be sure to look at this one as well.

**Comment by jeankaplansky** [comment]
This is a really big merge and it's all about https://www.deque.com/axe/axe-for-web/documentation/api-documentation/, which is technically owned by marketing. I've asked @straker to get in touch with Ryan Bateman to discuss next steps on this since I don't usually update docs on deque.com

**Comment by straker** [comment]
@jamime Alright, I was informed that those docs are synced with the master branch version. We are planning on releasing axe-core 4.0.0 on Monday, so once that goes live the docs on deque.com website should be updated.

**Comment by jeankaplansky** [comment]
Closed per Steve's comment above.
