### ISSUE TITLE
iframe giving "All page content must be contained by landmarks" when iframe itself is contained by a landmark

### ISSUE THREAD

**Issue by jnurthen** [dequelabs/axe-core#2330]
Expectation: This best practice should only occur when content isn't contained by a landmark

Actual: The best practice gets reported whenever an iframe contains content without landmarks even when the iframe itself is contained in a landmark.

Motivation: We use a UI shell around some pages. The shell will look at the included page and, if they do not provide landmarks, will add a main around the iframe. axe still reports this as an error and it is confusing to developers

Testcase: https://jnurthen.github.io/testcases/axe/iframeLandmarks/index.html

<pre><code>
axe-core version: 3.5.4
extension: 4.5.2

</code></pre>

**Comment by WilcoFiers** [comment]
Yeah I agree, that should pass. Thanks for reporting James.

**Comment by padmavemulapati** [comment]
Verified using Test File - on axe-coconut(v4.6.1.30800)
[landmark-unique-test.txt](https://github.com/dequelabs/axe-core/files/5494968/landmark-unique-test.txt)
Seeing the "region" rule for iframes:
![image](https://user-images.githubusercontent.com/47409579/98253658-55866980-1fa1-11eb-8fa5-edd313e46ae6.png)
