### ISSUE TITLE
is-valid-autocomplete should allow one-time-code as a standalone term

### ISSUE THREAD

**Issue by lencioni** [dequelabs/axe-core#2335]
Expectation: `<input type="text" autocomplete="one-time-code" />` should be allowed

Actual: It is flagged as invalid

Motivation:  This autocomplete value can be used by some browsers to automatically fill in the value after receiving a one-time-code for 2-factor authentication. More info:

- https://github.com/whatwg/html/pull/4573
- https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_an_html_input_element
- https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#Values
- https://www.twilio.com/blog/html-attributes-two-factor-authentication-autocomplete

<pre><code>
axe-core version: 3.5.5
axe-webdriver, extension or other integration version: eslint-plugin-jsx-a11y@6.3.0

Browser and Assistive Technology versions

For Tooling issues:
- Node version: 10.16.0  
- Platform: Mac 
</code></pre>

**Comment by padmavemulapati** [comment]
Verified with the changes,  `<input type="text" autocomplete="one-time-code" />` allowing me to enter the values in textbox, also its not failing with input type , but showing failure for there is no label defined for the input type 
used test code is : `<input type="text" autocomplete="one-time-code" />`
![image](https://user-images.githubusercontent.com/47409579/87294610-9f929d80-c521-11ea-9d72-40f967fdd56a.png)
