### ISSUE TITLE
aria-roledescription

### ISSUE THREAD

**Issue by WW3** [dequelabs/axe-core#234]
recognized as [critical] invalid aria attribute.
see https://www.w3.org/TR/wai-aria-1.1/#aria-roledescription

**Comment by marcysutton** [comment]
Thanks, we are starting to add support for ARIA 1.1 so we'll add this to the list.

**Comment by WilcoFiers** [comment]
I don't think we can support this until there is widespread adoption of this in assistive technologies. It seems to me that most use cases for this attribute would cause problems for users of AT that don't support it.

**Comment by WilcoFiers** [comment]
Closing the issue as aria-roledescription is currently unsupported in a number of popular screen readers. We are working on accessibility supported checks which will make it easier to configure this sort of stuff in the future, but we're not going to add it by default until assistive technologies support has improved.

**Comment by gnapse** [comment]
Hmmm, it seems weird to me that being valid and documented, an axe audit still flags it as an invalid attribute to code using this attribute. At the very least flag its uses and warn users running these audits that the attribute is not widely implemented in assistive technologies. But saying it's an incorrect attribute, when it [can be found in plain sight in aria documentation](https://www.w3.org/TR/wai-aria-1.1/#aria-roledescription), can be confusing.

**Comment by WilcoFiers** [comment]
@gnapse We are planning to improve the messaging around unsupported accessibility features. We've added one such feature for unsupported roles. unsupported attributes is next on the list. Stay tuned!

**Comment by attilavago** [comment]
Yeah, I'd like this to be supported as well. It's starting to be adopted more and more, so pretty please? :)

**Comment by padraig-ohiceadha** [comment]
I believe this is now supported by JAWS, and VoiceOver for Safari on the Mac, and Firefox with NVDA so supporting it, or at least changing the message returned from "Invalid ARIA attribute name" to a warning that it may cause issues with some screen readers would be very useful.

**Comment by iamrafan** [comment]
I tested for support across the current browser/ATs, here are the results


  | AT/Browser | Announced as | Is aria-roledescription announced?
-- | -- | -- | --
1 | Edge/Narrator | Here Split button | Yes
2 | Edge/JAWS | Here Button | **No**
3 | Edge/NVDA | Split button here | Yes
4 | Chrome/NVDA | Split button here | Yes
5 | Chrome/JAWS | Here Split button | Yes
6 | IE/JAWS | Here split button | Yes
7 | IE/NVDA | Split button here | Yes
8 | Firefox/NVDA | Split button here | Yes

#1216
