### ISSUE TITLE
Bug: running JSDOM (without setting globals) results in error

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core#2347]
```js
let dom = jsom('<div></div>');
axe.run(dom.window.document.documentElement);  // runs fine

dom = jsom('<div></div>');
axe.run(dom.window.document.documentElement);  // errors with "axe.run arguments are invlaid"
```

The issue is that axe-core now sets the global `document` and `window` but does not unset it after the run. JSDom apparently creates a new `window` and/or `document` every new instance, so they are no longer the same. When we check if the `context` is a context, we use the `window` element to determine things, which is what fails on the 2nd run.

**Comment by straker** [comment]
Pairing with @stephenmathieson  we discovered the problem only happens in jsdom v16 (v15 does not fail). The fix is to null `window` and `document` in the `cleanup` function of `run-rules.js` if we set the globals ourselves.

**Comment by stephenmathieson** [comment]
<details>
<summary>Failing test case</summary>

```js
const axe = require('axe-core'); // ^3.5.5-canary.67d2dca
const jsdom = require('jsdom'); // ^16

const test = async () => {
  const one = new jsdom.JSDOM(`
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
      </head>
      <body>
        Hello
      </body>
    </html>
  `);

  let r = await axe.run(one.window.document.documentElement, {
    rules: { 'color-contrast': { enabled: false } },
  });
  console.log('one: %d violations', r.violations.length);

  const two = new jsdom.JSDOM(`
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
      </head>
      <body>
        Hello
      </body>
    </html>
  `);

  r = await axe.run(two.window.document.documentElement, {
    rules: { 'color-contrast': { enabled: false } },
  });
  console.log('two: %d violations', r.violations.length);
};

test();
```
</details>

**Comment by padmavemulapati** [comment]
Installed "JSDOM" and ran 
1. without defining jsdom - `dom = jsom('<div></div>');
axe.run(dom.window.document.documentElement);` - got error - "Uncaught ReferenceError: jsom is not defined
    at playground.html:10"
and 
2. ran by defining the jsdom variable - `let dom = jsom('<div></div>');
axe.run(dom.window.document.documentElement); ` - running fine.
(Attached the screenshot in both scenarios.

![image](https://user-images.githubusercontent.com/47409579/88066038-eff5a500-cb8a-11ea-9b29-58b54fd84b7c.png)

**Comment by stephenmathieson** [comment]
@padmavemulapati try the [test case from above](https://github.com/dequelabs/axe-core/issues/2347#issuecomment-655063191).

Also note that this is run in a Node.js context, not a browser.

**Comment by jeankaplansky** [comment]
behind the scenes stuff; docs req'd in repo.

**Comment by ali-habibzadeh** [comment]
This method has flaws, such as no repotting at all on colour contrast issues
