### ISSUE TITLE
autocomplete-valid rule incorrectly fails for autocomplete="tel-*" values on input type=tel

### ISSUE THREAD

**Issue by kensgists** [dequelabs/axe-core#2355]
The autocomplete-valid rule fails all "tel-*" autocomplete values on input type="tel" fields. 

Expectation: <input autocomplete="tel-extension" type="tel"> passes autocomplete-valid rule

Actual: <input autocomplete="tel-extension" type="tel"> fails autocomplete-valid rule

axe-core version: 3.5.5

**Comment by straker** [comment]
Thanks for the issue. This should be fixed in develop with https://github.com/dequelabs/axe-core/pull/2307 and should be in the next release.

**Comment by kensgists** [comment]
Awesome! Thanks! This project is amazingly responsive. Much appreciated.
