### ISSUE TITLE
Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by malkeets1** [dequelabs/axe-core#2356]
Expectation: << Describe what you expect the product to do >>

Actual: << Describe what the product actually does >>

Motivation: << Describe why you want the behavior to be changed >>

<pre><code>
axe-core version: X.Y.Z
axe-webdriver, extension or other integration version: X.Y.Z

Browser and Assistive Technology versions

For Tooling issues:
- Node version: XX  
- Platform:  
</code></pre>

**Comment by straker** [comment]
Hey @malkeets1, we've found the solution to be either to restart chrome or ensure your permissions are up-to-date. See #1769 for more information. You can also check to make sure it has permissions for all sites. See https://github.com/dequelabs/axe-core/issues/1806#issuecomment-533118649

Going to close this as a duplicate, but let me know it doesn't solve it for you.
