### ISSUE TITLE
th-has-data-cells docs example is incorrect

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2364]
The bad example shows a table with empty data cells. This would not be flagged by the rule though. A better example would be if the scope is set incorrectly, have scope=row where it should be scope=col and visa versa.

https://dequeuniversity.com/rules/axe/3.5/th-has-data-cells?application=RuleDescription

We'll need to show code instead of an actual table to illustrate this point.

**Comment by jeankaplansky** [comment]
Submitted https://github.com/dequelabs/docs-axe/pull/6 7/28/2020
