### ISSUE TITLE
Type Definition missing 'version' - error TS2339: Property 'version' does not exist on type 'typeof axe'

### ISSUE THREAD

**Issue by mohanraj-r** [dequelabs/axe-core#2378]
Expectation: `axe.version` doesn't result in type error

Actual: Accessing version with `axe.version` results in `error TS2339: Property 'version' does not exist on type 'typeof axe'`

Motivation: Type definition should match runtime behavior where `axe.version` works directly in browser console or in code after suppressing the error 

<pre><code>
axe-core version: 3.5.5
axe-webdriver, extension or other integration version: NA

Browser and Assistive Technology versions

For Tooling issues:
- Node version: v12.18.2
- Platform:  Mac
</code></pre>

**Comment by straker** [comment]
Thanks for letting us know. I'll make sure to address this when i fix #2317

**Comment by mohanraj-r** [comment]
Thanks @straker 
Wondering if this is automated or hand-crafted ?
If automated and easy to do - could be something a person like me who isn't extremely familiar with axe internals could help as well.

**Comment by WilcoFiers** [comment]
@mohanraj-r It's maintained by hand, which is why there's an issue at all. Would you be interested in putting in a PR? The file to change is this one:

https://github.com/dequelabs/axe-core/blob/develop/axe.d.ts

**Comment by mohanraj-r** [comment]
Thanks @WilcoFiers I can take a stab at it.
Are there tests for the type-definitions ?

**Comment by straker** [comment]
@mohanraj-r our tests for the type file are located here https://github.com/dequelabs/axe-core/blob/develop/typings/axe-core/axe-core-tests.ts

**Comment by mohanraj-r** [comment]
Thanks @straker I will take a stab at it soon - btw if we were to hold a axe hackathon in our team as a way of contributing back is there a list of good first issues that we can use ? I noticed there isn't a corresponding github issue label.

**Comment by straker** [comment]
@mohanraj-r I can go find some issues and put the `help wanted` or `hacktoberfest` labels on them for you.

Also, we'll need the version fix in by end of day today (5pm MST) as we are putting a code freeze in place for our release next week. If you can't get it in by then I'll fix it so we have it for 4.0.

**Comment by straker** [comment]
`version` is now part of the types file for 4.0

**Comment by mohanraj-r** [comment]
Thanks @straker 
Sorry I wasn't able to get back in time - swamped with some other things right now.
Yes it would be great if you can label some issues to help the hackathon.

**Comment by straker** [comment]
@mohanraj-r no problem. I've gone through and put [the help wanted label](https://github.com/dequelabs/axe-core/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) on a handful of issues. Some of these issues are discussion points (not ready for prs), but most of them are able to receive a pr. Let us know if you have any questions about the issues and we'll be happy to help.

When are you planning the hackathon?

**Comment by mohanraj-r** [comment]
Thanks @straker 
We are planning it on Aug 26th - axe is one of the handful of projects that people can choose for the hackathon.
