### ISSUE TITLE
Rule ["layout-table"]

### ISSUE THREAD

**Issue by devarshipant** [dequelabs/axe-core#238]
I am parsing a table with captions but without the usual table headers. I think it should flag it as an issue as there can be instances where caption (usual suspect, besides table headers, that gets picked up by screen reader when interacting with layout tables) is solely used without table headers and other data table semantics. Refer to attached html markup.

thanks,
Devarshi

**Comment by marcysutton** [comment]
We will need the HTML markup to be able to debug. It looks like it didn't get posted

**Comment by devarshipant** [comment]
Attached.

thanks!
[layout table rule.txt](https://github.com/dequelabs/axe-core/files/518461/layout.table.rule.txt)

**Comment by WilcoFiers** [comment]
I propose we make a check flag this as cantTell.

**Comment by devarshipant** [comment]
That makes sense.

**Comment by devarshipant** [comment]
Another flag could be “CheckTableHeaders.”

**Comment by dylanb** [comment]
@WilcoFiers close?

**Comment by straker** [comment]
Based on what @WilcoFiers said in #3011, I'm going to close this issue for similar reasons. Not all tables need `th`, and the layout-table rule was deprecated due to too many false positives.
