### ISSUE TITLE
Remove "restoreScroll" option

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2388]
Because the color-contrast rule no longer scrolls, the restoreScroll option does nothing. This should be taken out of core and out of the docs. I don't think we need to deprecate it either, just as long as passing it doesn't cause axe-core to crash.

**Comment by padmavemulapati** [comment]
Seeing the changes for color-contrast issue , verified with latest axe-coconut
![image](https://user-images.githubusercontent.com/47409579/88541427-59196480-d032-11ea-9170-f50527efd077.png)

**Comment by jeankaplansky** [comment]
changelog still has references to restoreScroll from previous versions.
No user-facing docs required.
