### ISSUE TITLE
Grunt build issue

### ISSUE THREAD

**Issue by sbollu** [dequelabs/axe-core#241]
Trying to build internally with grunt, getting some issues. some of the files not loading getting error saying
Loading "configure.js" tasks...ERROR
>> Error: Cannot find module 'clone'
Loading "langs.js" tasks...ERROR
>> Error: Cannot find module 'promise'
Loading "test.js" tasks...ERROR
>> Error: Cannot find module 'promise'
Loading "validate.js" tasks...ERROR
>> Error: Cannot find module 'revalidator'

but we have modules - configure.js, langs.js, test.js, validate.js

the problem is all the grunt js files should start with -- module.exports 
but some js file started with global variables and then with - module.exports
i have commented global variables and kept inside function...now it build..

but axe.js and axe.min.js is empty just create 1 KB files.

Any idea how to build with grunt after getting the code from github ?

Thanks,
Srinivasa Bollu.

**Comment by dylanb** [comment]
Did you follow the instructions here https://github.com/dequelabs/axe-core/blob/master/doc/developer-guide.md

**Comment by marcysutton** [comment]
@sbollu can you provide more information? I'm going to close this issue for inactivity otherwise.

**Comment by sbollu** [comment]
Hi,
I am good now. please close the issue.

Thanks, 
Srinivasa Bollu.  
 
  On Tue, Oct 25, 2016 at 12:59 PM, Marcy Sutton<notifications@github.com> wrote:   
@sbollu can you provide more information? I'm going to close this issue for inactivity otherwise.
