### ISSUE TITLE
Not even starting the analyzation

### ISSUE THREAD

**Issue by tctanya** [dequelabs/axe-core#2416]
Expectation: << Describe what you expect the product to do >>

Actual: << Describe what the product actually does >>

Motivation: << Describe why you want the behavior to be changed >>

<pre><code>
axe-core version: X.Y.Z
axe-webdriver, extension or other integration version: X.Y.Z

Browser and Assistive Technology versions

For Tooling issues:
- Node version: XX  
- Platform:  
</code></pre>

**Comment by WilcoFiers** [comment]
Please provide details on how to reproduce the issue.
