### ISSUE TITLE
duplicate definition in axe.js

### ISSUE THREAD

**Issue by adob** [dequelabs/axe-core#2418]
`grunt` produces a `axe.js` file where the same function is defined multiple times. For example, `_typeof(obj)` is defined on line 16, and then again on line 305, with the same body. Same with `_defineProperty()`. The duplicate declarations are still there in the minified file, wasting bytes.

**Comment by straker** [comment]
Thanks for the issue. I believe this issue has been fixed in the latest develop version of the file. `function _typeof` is only defined twice now (an artifact of how we are doing this that can't be fixed yet).

**Comment by SkReD** [comment]
Is there realy no way to fix duplicating? It breaks compilation with swc
https://github.com/swc-project/swc/issues/3193

**Comment by straker** [comment]
At the moment no. We probably won't be able to fix it until v5.0.0 when we address https://github.com/dequelabs/axe-core/issues/2052

**Comment by bryanjtc** [comment]
It currently breaks compilation with esbuild@0.16.9

**Comment by bryanjtc** [comment]
@SkReD Did you find a workaround?

**Comment by SkReD** [comment]
> @SkReD Did you find a workaround?

in case of webpack - yes :) 
```
{
  test: /\.c?jsx?$/,
  exclude: [/node_modules[\\\/]axe-core/],
  use: [jsxLoader],
},
{
  test: /\.c?jsx?$/,
  // it has duplicated declaration of function that breaks swc
  // https://github.com/dequelabs/axe-core/issues/2418#issuecomment-1050884061
  include: [/node_modules[\\\/]axe-core/],
  use: ['babel-loader'],
},
```
