### ISSUE TITLE
Checkboxes that share the same name in different forms cause violations

### ISSUE THREAD

**Issue by GregJohnStewart** [dequelabs/axe-core#2420]
I have two nearly identical login forms on the same page (one for the navbar, one for the page content). They are nearly identical because I can use the same javascript/selenium code to implement and test both.

The issue with this is that I get the following violation from AXE:

```
1) Checkbox inputs with the same name attribute value must be part of a group: https://dequeuniversity.com/rules/axe/3.1/checkboxgroup?application=axeAPI
  a) ["#homeLoginStayLoggedIn"]
    Fix any of the following:
      All elements with the name "stayLoggedIn" do not reference the same element with aria-labelledby
      Element does not have a containing fieldset or ARIA group
```

Nav login:

```
<div class="form-group">
    <div class="form-check">
        <input type="checkbox" class="form-check-input loginStayLoggedIn" id="navbarLoginStayLoggedIn" name="stayLoggedIn" form="navbarLogin">
        <label class="form-check-label" for="navbarLoginStayLoggedIn">
            Remember me
        </label>
    </div>
</div>
```

Homepage Login:

```
<div class="form-group">
    <div class="form-check">
        <input type="checkbox" class="form-check-input loginStayLoggedIn" id="homeLoginStayLoggedIn" name="stayLoggedIn" form="homeLogin">
        <label class="form-check-label" for="homeLoginStayLoggedIn">
            Remember me
        </label>
    </div>
</div>
```

These are part of entirely different forms in different parts of the page. Am I missing something, or is it a bug that AXE associates these inputs?

**Comment by straker** [comment]
The checkbox group rule was [deprecated in version 3.4](https://github.com/dequelabs/axe-core/releases/tag/v3.4.0). If you upgrade to that version or later the issue should go away.

**Comment by GregJohnStewart** [comment]
I'm using `axe-core-java`, Is there a fix for that?

**Comment by stephenmathieson** [comment]
Hey @GregJohnStewart! It's been awhile since I've worked on that project, but it looks like `axe-selenium-java` expects you to bring your own version of `axe.js` based on these LOCs:

- https://github.com/dequelabs/axe-selenium-java/blob/master/src/main/java/com/deque/axe/AXE.java#L66
- https://github.com/dequelabs/axe-selenium-java/blob/master/src/main/java/com/deque/axe/AXE.java#L256

This said, you should be able to download a more recent version of `axe.js` and place it wherever you have it currently.

**Comment by GregJohnStewart** [comment]
Do you mean the js listed [here](https://github.com/dequelabs/axe-selenium-java/tree/master/src/test/resources)?

I'm currently using the `axe.min.js` listed here, pulled it sometime last week. Is there a better source? Honestly it's a little hard to find a real link it seems, there isn't clear direction as to where to find the axe js (it's a little easier if you use node, but I only found the link above through a Medium article)

**Comment by stephenmathieson** [comment]
Those are "fixtures" for the tests/example (which we should clearly update). I would recommend downloading a more recent version of axe from npm or a CDN like unpkg.

Also hi : wave:

**Comment by GregJohnStewart** [comment]
Thanks! For anyone else looking for the direct link, here it is: https://unpkg.com/browse/axe-core@3.5.5/axe.min.js

**Comment by stephenmathieson** [comment]
@GregJohnStewart great idea! Feel free to open an PR!
