### ISSUE TITLE
Add capability to support custom reporter

### ISSUE THREAD

**Issue by aldosuwandi** [dequelabs/axe-core#2428]
### User story
As a test author, I want to be able to intercept the `results` object right before the `axe.run()` returns the `result`

Currently, if we want to process the `results` we can already do it this way.
```
axe
	.run()
	.then(results => {
		new CustomReporter(results).process()
	})
```
However, with this approach the `new CustomReporter(results).process()` has to be called whenever `axe.run()` is invoked.

### Proposal
It'll be nice if we can add a custom reporter implementation into the axe instance.  Roughly, the workflow will be something like this:
1. Implement the custom reporter logic
```
// the skeleton is taken from https://github.com/dequelabs/axe-core/blob/develop/lib/core/reporters/v2.js
const customReporter = (results, options, callback) => {
      // custom reporter logic
};
```
2. register the reporter through axe.configure()
```
const config = {
      reporter: customReporter
}
axe.configure(config)
```
I haven't looked too deep into the possibilities of this idea, but I'm curious to know if it's something worth having, or it already can be done differently.

**Comment by WilcoFiers** [comment]
Well, do I have good news for you! This is already possible. It isn't well documented, definitely something we need to address. You can do the following in axe:

```js
axe.addReporter('my-reporter', function (results, options, callback) {
  // do stuff...
  callback(results)
}, true) // this boolean is optional, it sets it as the default reporter.
```

This gets you the raw results, before axe turns it into this nicely structured passes / violations structure. If you want to work on the output of axe-core's v1 reporter, a simple wrapper function could also work:

```js
const runAxe = async (...args) => myReporter(await axe.run(...args))

runAxe()
  .then(res => console.log(res))
```

**Comment by aldosuwandi** [comment]
Thanks for the response!
I see. I wonder if there is an enhancement that can be made to pass the custom reporter via [axe.configure()](https://www.deque.com/axe/axe-for-web/documentation/api-documentation/#api-name-axeconfigure)?

The reason that I'm asking is that the majority of axe integrated test frameworks, such as [axe-webdriverjs](https://github.com/dequelabs/axe-webdriverjs), [cypress-axe](https://github.com/avanslaars/cypress-axe), [jest-axe](https://github.com/nickcolley/jest-axe), etc only allow us to pass the configuration through [axe.configure()](https://www.deque.com/axe/axe-for-web/documentation/api-documentation/#api-name-axeconfigure).
Thus, if we can pass it as part of the [axe.configure()](https://www.deque.com/axe/axe-for-web/documentation/api-documentation/#api-name-axeconfigure), other frameworks can use it right away.

**Comment by straker** [comment]
It appears our docs our not correct and you can indeed pass a function to `axe.configure({ reporter })` and axe will use that reporter. I will make sure to add this to the docs.

**Comment by aldosuwandi** [comment]
I looked at the code a bit, and yes! It does enable us to pass a function! 

Currently, I'm working with axe-webdriverjs, and I tried to pass this custom reporter function through the provided configuration ([AxeBuilder.configure()](https://github.com/dequelabs/axe-webdriverjs#axebuilderconfigureconfigobject)). However, the framework doesn't let us pass a JS object into the configure() method since everything will be turned into a string. (code [link](https://github.com/dequelabs/axe-webdriverjs/blob/develop/lib/axe-injector.js#L7))

Looking into how this reporter is registered in the axe-core module, I wonder if it's possible to pass the custom reporter function implementation as a **_string_** instead of a **_function_**?

**Comment by straker** [comment]
Interesting. It would seem that even if `axe.configure` allows the feature, we have to stringify it to make it work with script injections into iframes. I'm not sure we could support configuration with functions if that's the case...

**Comment by padmavemulapati** [comment]
Verified with the latest axe-core -develop code (dated 22/10/2020) 
1. Verified with the `axe.configure({ reporter: "raw" });` 
![image](https://user-images.githubusercontent.com/47409579/96869412-0ca4c000-148d-11eb-8fe1-f92fae0b4429.png)

2. axe.configure({ reporter: "v2" });
![image](https://user-images.githubusercontent.com/47409579/96869486-25ad7100-148d-11eb-82b7-16909174c876.png)

3. axe.configure({ reporter: "no-passes" });
![image](https://user-images.githubusercontent.com/47409579/96869536-36f67d80-148d-11eb-8078-d0fd6364583a.png)
