### ISSUE TITLE
Difference in contrast errors between chrome and firefox extensions

### ISSUE THREAD

**Issue by mfairchild365** [dequelabs/axe-core#243]
I'm seeing some errors that only show up when analyzing a page with the chrome extension. Is the chrome extension up to date with axe-core or interact with the page differently?

It is a bit of an odd problem, so I will provide a concrete example. Go to http://wdn.unl.edu/ and run the chrome extension at a mobile width
- Chrome with extension: 19 contrast errors. It looks like it is checking contrast on links that are not in the viewport currently.
- Chrome with injected axe-core js - 2 contrast errors
- firefox - 2 contrast errors

Note, I'm opening this issue per the conversation on gitter.im

**Comment by marcysutton** [comment]
This has been fixed in the latest code and will be shipped with the next versions of axe-core and the extensions.

**Comment by marcysutton** [comment]
The latest axe-chrome is out, and axe-firefox-devtools should be out any day now. So I will close this issue!
