### ISSUE TITLE
Add "Narrator" in accessibility supported requirements

### ISSUE THREAD

**Issue by iamrafan** [dequelabs/axe-core#2430]
The [latest screen reader survey by WebAIM ](https://webaim.org/projects/screenreadersurvey8/)is out and 30.3% of the respondents said they use Narrator. 

![image](https://user-images.githubusercontent.com/22068434/88844171-2046d000-d197-11ea-9b12-82854225dbf6.png)

Considering this, please add Narrator and Microsoft Edge as one of the AT/Browser combinations to be tested for support in the [Accessibility supported](https://github.com/dequelabs/axe-core/blob/develop/doc/accessibility-supported.md#accessibility-supported) guidance

**Comment by straker** [comment]
Thanks for brining this to our attention. We'll start looking into Narrator to see what it would take to support it.

**Comment by WilcoFiers** [comment]
@iamrafan what would really help move this forward is an understanding of known bugs in Narrator.

**Comment by straker** [comment]
After discussion, we decided we won't add Narrator to be accessibility supported. Even though it has 30% usage on Windows, it's usage with a browser is < 1% [according to the same survey](https://webaim.org/projects/screenreadersurvey8/#browsercombos). We updated our [accessibility supported](https://github.com/dequelabs/axe-core/blob/develop/doc/accessibility-supported.md#accessibility-supported) requirements to include that it at least needs 1% browser market share to be considered.
