### ISSUE TITLE
unable to analyze the page, due to documentElement error

### ISSUE THREAD

**Issue by RCopeland** [dequelabs/axe-core#2439]
Expectation:  Analyze the page
Actual: Reports 'an error occured' with the following:

``` console
TypeError: Cannot read property 'documentElement' of null
TypeError: 
    at e (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:187615)
    at Object.utils.getFlattenedTree (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:188426)
    at U (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:165293)
    at G (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:166349)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:219634
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:219652
    at l (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:219145)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:46:219348
```
Motivation: Im trying to do some a11y analysis of pages.

<pre><code>
axe-core version: 3.5.5
axe-webdriver, extension or other integration version: 4.5.3
Browser and Assistive Technology versions
</code></pre>

Chrome 81
MacVO - Catalina 10.15.3
![Screen Shot 2020-08-05 at 11 13 33 AM](https://user-images.githubusercontent.com/412903/89431117-825e8280-d70d-11ea-9558-138243afa76b.png)

**Comment by WilcoFiers** [comment]
Hey @RCopeland, can you provide the page where this problem happened? This is going to be hard to debug otherwise.

**Comment by straker** [comment]
Running axe-core directly on the page from the image doesn't result in an error. Testing it with the extension results in the issue, so my guess is it's something to do with the iframes on the page.

**Comment by erik-deque** [comment]
Updates have been made to how we handle iFrames and this appears to be working as expected on both Chrome and Firefox.
