### ISSUE TITLE
aria-valid-attr-value: allow numbers with comma as decimal separator

### ISSUE THREAD

**Issue by placetobejohan** [dequelabs/axe-core#2450]
Numbers that use a comma as decimal separator - eg **aria-valuenow="68885,8"** - now trigger the [[aria-*] attributes do not have valid values](https://web.dev/aria-valid-attr-value/) error.

I wonder if it's possible to allow the comma as a decimal separator, perhaps based on the current UI culture?

**Comment by WilcoFiers** [comment]
Hey @placetobejohan, using comma as decimal separator doesn't work. Browsers will just ignore whatever comes after the comma. You have to use a dot, not a comma. The ARIA spec defers handling of numbers to HTML, which unfortunately doesn't have a definition of number, but browsers seem be consistent in using JavaScript's praseFloat method for this.

You can read the definition of it here: 
https://www.w3.org/TR/wai-aria-1.1/#state_property_processing

And here's the list of defined types for HTML:
https://infra.spec.whatwg.org/#index-defined-here

**Comment by placetobejohan** [comment]
Perhaps I should've been more specific or I came to the wrong conclusion. 

The issue I have is that elements like this one

`
<input type="text" class="k-formatted-value numeric k-input" title="0,3400 €" tabindex="0" role="spinbutton" aria-valuemin="0" autocomplete="off" aria-disabled="true" disabled="disabled" aria-valuenow="0,34" style="display: inline-block;">
`

are marked with 'invalid value'. What could be the reason for this?

Could be related to the use of a Kendo numeric textbox?

Thanks for your help.

**Comment by placetobejohan** [comment]
The issue seems to be with kendo here, they should generate a valid aria-valuenow independent of which culture is being used.
