### ISSUE TITLE
Clarify svg-non-empty-title fail message

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2452]
There are two things which will cause the `svg-non-empty-title` check to fail. Either the SVG does not have a title, or the title is empty. The fail message only describes the first case. This can be confusing. We can fix this by using `messageKey` and splitting the fail message into two.

Info on how to do this is described in a closely related issue #2451

**Comment by padmavemulapati** [comment]
Verified with the test file `<svg id="target" ></svg>` , which is having no titile , and also 
`<svg id="target"><title></title></svg>` , which has empty title, in both cases i am not seeing any failure message. 
@straker  / @WilcoFiers can anyone please provide inputs to reproduce the issue.

**Comment by straker** [comment]
No docs required
