### ISSUE TITLE
Update internal-link-present-evaluate to work with virtualNodes

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core#2466]
The [internal-link-present-evaluate](https://github.com/dequelabs/axe-core/blob/develop/lib/checks/navigation/internal-link-present-evaluate.js) function should work with `virtualNode` rather than `actualNode`. Update the regexp test to use [virtual-node](https://github.com/dequelabs/axe-core/blob/develop/lib/core/base/virtual-node/virtual-node.js) methods to get the attribute.

You'll also need to update the [tests](https://github.com/dequelabs/axe-core/blob/develop/test/checks/navigation/internal-link-present.js) to pass the virtual node rather than just the node.

See [non-empty-if-presenet-evaluate](https://github.com/dequelabs/axe-core/blob/develop/lib/checks/shared/non-empty-if-present-evaluate.js) and its [test file](https://github.com/dequelabs/axe-core/blob/develop/test/checks/shared/non-empty-if-present.js) as an example.

**Comment by straker** [comment]
Sure thing, all yours.

**Comment by straker** [comment]
@anuk79 any update on working on this? If not I'll probably pick it up.

**Comment by anuk79** [comment]
Hi @straker sorry I couldn't pick it up. You can reassign

**Comment by dan-tripp** [comment]
Hello.  I'm new here.  Figured I'd try this 'good first issue'.  I submitted a PR for it.  Is it useful?
