### ISSUE TITLE
Update unique-frame-title-evaluate to work with virtualNodes

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core#2468]
The [unique-frame-title-evaluate](https://github.com/dequelabs/axe-core/blob/develop/lib/checks/navigation/unique-frame-title-evaluate.js) function should work with `virtualNode` rather than `node`. Update the function call to use `virtualNode` and use [virtual-node](https://github.com/dequelabs/axe-core/blob/develop/lib/core/base/virtual-node/virtual-node.js) methods to get the attribute.

You'll also need to update the [tests](https://github.com/dequelabs/axe-core/blob/develop/test/checks/navigation/unique-frame-title.js) to pass a virtual node rather than a fake node.

See [non-empty-if-presenet-evaluate](https://github.com/dequelabs/axe-core/blob/develop/lib/checks/shared/non-empty-if-present-evaluate.js) as an example.

**Comment by shankarshastri** [comment]
@straker , I was taking a look at this one. But wasn't sure what should be done w.r.t virtual node in this case. as the title is passed as a JSON object.

**Comment by straker** [comment]
Are you talking about the tests? The tests shouldn't pass a fake "node" object but instead create actual virtual node (using `queryFixture` or something similar) and pass that as other tests have done. Probably use `iframes` as the element as that is what the check is suppose to be checking (even though it doesn't matter for the check what the element actually is).

**Comment by straker** [comment]
No qa/docs required.
