### ISSUE TITLE
Update caption-evaluate to work with virtualNodes

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core#2469]
The [caption-evaluate](https://github.com/dequelabs/axe-core/blob/develop/lib/checks/media/caption-evaluate.js) function should work with `virtualNode` rather than `node`. Update the `tracks.some` function to not use `actualNode` property and instead use `vNode` and use [virtual-node](https://github.com/dequelabs/axe-core/blob/develop/lib/core/base/virtual-node/virtual-node.js) methods  to get the attribute.

The tests should not need updating.

See [non-empty-if-presenet-evaluate](https://github.com/dequelabs/axe-core/blob/develop/lib/checks/shared/non-empty-if-present-evaluate.js) and its [test file](https://github.com/dequelabs/axe-core/blob/develop/test/checks/shared/non-empty-if-present.js) as an example.

**Comment by xyc** [comment]
hi @straker , is there a way to make `querySelectorAll` to return vNodes from a `vNode` input?

[captionEvaluate](https://github.com/dequelabs/axe-core/blob/develop/lib/checks/media/caption-evaluate.js) doesn't seem to use the `node` param, and `actualNode`s are returned from `querySelectorAll` on `virtualNode`.

**Comment by straker** [comment]
Correct. The change should just be to not use the `actualNode` property of the vNode returned from `querySelectorAll` and instead use the vNode directly and it's functions. Something like

```js
const hasCaptions = tracks.some(vNode => (vNode.attr('kind') || '').toLowerCase() === 'captions');
```

**Comment by xyc** [comment]
Gotcha, thanks for the explanation. I was somehow thinking that [`querySelectorAll`](https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#returns) was returning actual nodes when I looked at the API doc. Will make a PR from your suggestion.

**Comment by straker** [comment]
No qa/docs required.
