### ISSUE TITLE
Update duplicate-img-label-evaluate to use virtualNode

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core#2472]
The [duplicate-img-label-evaluate](https://github.com/dequelabs/axe-core/blob/develop/lib/checks/label/duplicate-img-label-evaluate.js) function should pass `virtualNode` to `getRole` rather than `node`.

The tests should not need updating.

**Comment by anuk79** [comment]
@straker can I work on this issue if no one else is working on it?

**Comment by straker** [comment]
It's yours.

**Comment by straker** [comment]
No qa/docs needed.
