### ISSUE TITLE
Update aria-hidden-body-evaluate to work with virtualNodes

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core#2475]
The [aria-hidden-body-evaluate](https://github.com/dequelabs/axe-core/blob/develop/lib/checks/aria/aria-hidden-body-evaluate.js) function should work with `virtualNode` rather than `node`. Update the function call to use `virtualNode` and use [virtual-node](https://github.com/dequelabs/axe-core/blob/develop/lib/core/base/virtual-node/virtual-node.js) methods to get the attribute.

You'll also need to update the [tests](https://github.com/dequelabs/axe-core/blob/develop/test/checks/aria/aria-hidden-body.js) to pass the virtual node rather than just the node.

See [non-empty-if-presenet-evaluate](https://github.com/dequelabs/axe-core/blob/develop/lib/checks/shared/non-empty-if-present-evaluate.js) and its [test file](https://github.com/dequelabs/axe-core/blob/develop/test/checks/shared/non-empty-if-present.js) as an example.

**Comment by shankarshastri** [comment]
@straker , I was trying to fix this.

**aria-hidden-body.js**
```javascript
describe("aria-hidden", function () {
  "use strict";

  var checkContext = axe.testUtils.MockCheckContext();
  var queryFixture = axe.testUtils.queryFixture;

  afterEach(function () {
    checkContext.reset();
  });

  it("should not be present on document.body", function () {
    var vNode = queryFixture('<body></body>');
    assert.isTrue(
      axe.testUtils
        .getCheckEvaluate("aria-hidden-body")
        .call(checkContext, null, {}, vNode)
    );
  });

  it("fails appropriately if aria-hidden=true on document.body", function () {
    var vNode = queryFixture('<body aria-hidden="true"></body>');
    assert.isFalse(
      axe.testUtils
        .getCheckEvaluate("aria-hidden-body")
        .call(checkContext, null, {}, vNode)
    );
  });

  it("passes if aria-hidden=false on document.body", function () {
    var vNode = queryFixture('<body aria-hidden="false"></body>');
    assert.isTrue(
      axe.testUtils
        .getCheckEvaluate("aria-hidden-body")
        .call(checkContext, null, {}, vNode)
    );
  });
});
```

**aria-hidden-body-evaluate.js**
```javascript
function ariaHiddenBodyEvaluate(node, options, virtualNode) {
	return virtualNode.hasAttr('aria-hidden') !== 'true';
}

export default ariaHiddenBodyEvaluate;
```

But when I run `npm run test`, I currently get 
```
 1) aria-hidden
       should not be present on document.body:
     TypeError: Cannot read property 'hasAttr' of undefined
      at Object.ariaHiddenBodyEvaluate (http://localhost:9876/axe.js:497:28)
      at Object.evaluateWrapper (http://localhost:9876/test/testutils.js:382:25)
      at Context.<anonymous> (aria/aria-hidden-body.js:17:10)

  2) aria-hidden
       fails appropriately if aria-hidden=true on document.body:
     TypeError: Cannot read property 'hasAttr' of undefined
      at Object.ariaHiddenBodyEvaluate (http://localhost:9876/axe.js:497:28)
      at Object.evaluateWrapper (http://localhost:9876/test/testutils.js:382:25)
      at Context.<anonymous> (aria/aria-hidden-body.js:26:10)

  3) aria-hidden
       passes if aria-hidden=false on document.body:
     TypeError: Cannot read property 'hasAttr' of undefined
      at Object.ariaHiddenBodyEvaluate (http://localhost:9876/axe.js:497:28)
      at Object.evaluateWrapper (http://localhost:9876/test/testutils.js:382:25)
      at Context.<anonymous> (aria/aria-hidden-body.js:35:10)

```
Can you please let me know how I can proceed?

**Comment by straker** [comment]
Awesome, thanks for taking this on. I believe the issue is that `queryFixture` returns the virtual node with the id of `target`, so all your DOM strings should just have to add `id=target` to them.

**Comment by shankarshastri** [comment]
@straker , Thanks will raise PR soon !!

**Comment by shankarshastri** [comment]
@straker , tried the same as well, still having the same error. Will push it to a branch. And then we can continue to discuss on the draft PR.

**Comment by straker** [comment]
No qa/docs needed.
