### ISSUE TITLE
Improve performance of color-contrast-matches

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core#2479]
The color contrast matches function took 30s on a page with 30,000 `<p>` tags. We should investigate ways to improve its performance.

See https://github.com/dequelabs/axe-core/issues/2445.

**Comment by michael-siek** [comment]
See: https://www.chase.com/content/dam/chaseonline/en/demos/cbo/launch.html slow due to queryselectorall for every element ancestor looking for arialabelledby id

**Comment by straker** [comment]
Dev task
