### ISSUE TITLE
For Layout table rule, deprecated tag is not displayed.

### ISSUE THREAD

**Issue by chandana7393** [dequelabs/axe-core#2481]
**Steps to reproduce:**
1. Launch "http://qateam.dequecloud.com/axecore4/table-layout.html" Url.
2. Launch axe-coconut extension.
3. Click on the "ANALYZE" button.

**Actual:**
For "Data or header cells should not be used to give caption to a data table." violation and "All th elements and elements with role=columnheader/rowheader must have data cells they describe" needs review, deprecated tag is not displaying.
![table-layout](https://user-images.githubusercontent.com/45285854/91126726-879e5580-e659-11ea-837a-8bbce94ad816.PNG)

**Expected:**
For "Data or header cells should not be used to give caption to a data table." violation and "All th elements and elements with role=columnheader/rowheader must have data cells they describe" needs review, deprecated tag should be displayed.

**NOTE:** Is this expected or is there any other rule for table layout, Please let me know.

**Tested Environment:**
Axe-coconut - 4.5.3.23216 v
Chrome -  84.0.4147.135v
OS - Windows 10 64 bit.

CC: @padmavemulapati

**Comment by straker** [comment]
I'm sorry, I don't quite follow. The rule that is failing `th-has-data-cells` is not deprecated. All deprecated rules/checks were removed in 4.0.

**Comment by padmavemulapati** [comment]
@chandana7393  - the rules you mensioned are not deprecated rules. what it is showing the results in axe-coconut are correct and those are not related to `layout-table` rule.

**Comment by chandana7393** [comment]
@straker Can you please provide me with the code snippet (or) any test file-related to layout table rule? that could help me a lot.

**Comment by straker** [comment]
We do not have a rule for layout-table https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md. What exactly are you trying to test?

**Comment by straker** [comment]
We removed the layout-table rule in axe-core 4.0.0 https://github.com/dequelabs/axe-core/releases/tag/v4.0.0

**Comment by chandana7393** [comment]
So, basically I am testing the breaking changes of axe-core 4.0 in that layout-table got deprecated, I just want to check what is this rule in the previous axe-core versions, For that I require a test file (or) code-snippet of layout-table.
![layout_table_axe_changelog](https://user-images.githubusercontent.com/45285854/91206829-a8e45d80-e6bc-11ea-81aa-06abfd37f419.PNG)

**Comment by chandana7393** [comment]
> We do not have a rule for layout-table https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md. What exactly are you trying to test?

@straker this link is helpful thank you

**Comment by straker** [comment]
Closing as I believe we resolved this.
