### ISSUE TITLE
Typos in french translations

### ISSUE THREAD

**Issue by AlainVagner** [dequelabs/axe-core#2484]
I have detected several issues in the french translations:

- basic typos: "assig**m**é" -> "assig**n**é"
- frequent usage of "S'assure que" which is not a correct imperative form (in french, the imperative form is only available for "tu", "nous", "vous") Here the infinitive form seems more appropriate. 
- use of subjunctive forms, which are here to be avoided
- typography: use of ' and ’ could be homogenized
- typography: space before : and !
- singular / plural, ex:  "un caractère**s**" -> "un caractère"
- gender, ex: "L'utilisation de l'écran est indépendant" -> "L'utilisation de l'écran est indépendant**e**"
- some elisions of vowels are missing, ex: "**le** intitulé" -> "l'intitulé"

<pre><code>
axe-core version: 4.0.1
</code></pre>

**Comment by straker** [comment]
No qa/docs required.
