### ISSUE TITLE
Axe-core releases are tagged incorrectly

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2486]
Instead of the commit where the version number is bumped, the parent of that commit is tagged as the release. This causes the download link in the Github releases to not be the actual version that was released. I'm not entirely sure what the cause of this is, but perhaps what we should do is not have standard-version tag the release, and instead have the github_release script create the tag if it finds none exists.

**Comment by straker** [comment]
@michael-siek and I paired and figured out that the github release script uses the default branch as the target of the tag if not specified: https://github.com/github-release/github-release/blob/master/github-release.go#L47

This explains why every one of our releases are the commit behind the release.

**Comment by straker** [comment]
4.1.0 release was correctly tagged https://github.com/dequelabs/axe-core/releases/tag/v4.1.0
