### ISSUE TITLE
Investigate chrome-mobile test failures

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core#2497]
Chrome-mobile started failing all of a sudden consistently on a [few color-contrast commons checks](https://app.circleci.com/pipelines/github/dequelabs/axe-core/1123/workflows/c31e2b00-b6e9-41fb-9f9a-b09eee5f842d/jobs/21485). We haven't changed anything in color-contrast and prs prior passed without issues. Locally testing chrome using mobile emulation with the [same dimensions as our test setup](https://github.com/dequelabs/axe-core/blob/develop/build/tasks/test-webdriver.js#L96-L112) does not reproduce the issues.

We disabled chrome-mobile for now, but we should investigate why it started failing.

**Comment by somaalapati** [comment]
Nothing to test, so closing this bug.
