### ISSUE TITLE
[aria-required-parent] invalid false positive

### ISSUE THREAD

**Issue by ljosberinn** [dequelabs/axe-core#2513]
Expectation: HTML [here](https://codesandbox.io/s/silly-sanderson-0ro1t?file=/index.html) passes just fine

Actual: does not pass `.toHaveNoVioliations` through `jest-axe`:

![image](https://user-images.githubusercontent.com/29307652/92662314-de18be80-f2fe-11ea-842c-b574108aa43e.png)

Motivation: 

[HTML spec](https://www.w3.org/WAI/PF/aria-1.1/roles#menuitemradio) says:
> Authors MUST ensure that menu item radios are owned by an element with role group, menu, or menubar in order to identify that they are related widgets. Authors MAY separate menu items into sets by use of a separator or an element with an equivalent role from the native markup language.
> If a menu or menubar contains more than one group of menuitemradio elements, or if the menu contains one group and other, unrelated menu items, authors SHOULD nest each set of related menuitemradio elements in an element using the group role, and authors SHOULD delimit the group from other menu items with an element using the separator role.

given html matches  the 2nd case:
- `menu` contains more than one group of `menuitemradio` elements
- (...) other, unrelated menu items, authors SHOULD nest each set of related menuitemradio elements in an element using the group role
- (...) and authors SHOULD delimit the group from other menu items with an element using the separator role

> - div role menu
>   - div role group
>     - button role menuitemradio
>     - button role menuitemradio
>     - hr, implicit role separator (making it explicit doesnt change anything fwiw)
>     - a role menuitem

- [minimum reproduction](https://codesandbox.io/s/headless-cache-bz3o2?file=/index.html)
- validates fine [here](https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2F0ro1t.csb.app%2F) as valid html, not sure if that checks for aria beyond redundancy though
- it worked fine before v4.0, so I presume something [in this commit here](https://github.com/dequelabs/axe-core/commit/782c0fd91497549cee4a7a5b7e0e01dd932b1cd5#diff-b1f434bd8f0b34466f35e2ca6d841036) broke
- removing `div role group` fixes it. adding a second group around the solo menuitem anchor on bottom also highlights this one as broken

<pre><code>
axe-core version: 4.0.2
~~axe-webdriver, extension or other integration version: X.Y.Z~~

Browser and Assistive Technology versions

For Tooling issues:
- Node version: 14.7.0XX  
- Platform:  Win10
</code></pre>

**Comment by straker** [comment]
Yep, seems our [standard object](https://github.com/dequelabs/axe-core/blob/develop/lib/standards/aria-roles.js#L278) is missing `group` from required context of [menuitemradio](https://www.w3.org/TR/wai-aria-1.1/#menuitemradio)

**Comment by straker** [comment]
@ljosberinn would you be interested in putting together a pr for this?

**Comment by ljosberinn** [comment]
Can do, got a full plate at the moment, sorry - is there more to this than literally just adding it to that array?

**Comment by straker** [comment]
That's it. Adding `'group` to the array is the entire pr.

**Comment by padmavemulapati** [comment]
with the change (along with menu, and menubar , group also added to role solved the false positive)
![image](https://user-images.githubusercontent.com/47409579/93750843-c5bb7480-fc19-11ea-844d-306df20e5084.png)

**Comment by straker** [comment]
No docs required
