### ISSUE TITLE
axe should be aware of input type default of text

### ISSUE THREAD

**Issue by schne324** [dequelabs/axe-core#2514]
regarding input type...

> If this attribute is not specified, the default type adopted is text.

_from https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input_

**example markup**: 

```html
<input ng-repeat="input in inputCtrl" ng-style="{'width': input.css + '%'}" class="input-md _1DEW order-number landing-input-1 sidebar-input-number ng-touched" ng-class="{ 'input-error': $ctrl.showError }" type="input.type" aria-label="Order Number" aria-describedby="loginErrorTooltip" data-test="input-number" placeholder="" ng-required="input.is_required" ng-model="$ctrl.modelObject[input.name]" ng-change="$ctrl.updateLandingForm(input.name, $ctrl.modelObject[input.name])" style="width: 98%;">
```
(from https://returns.narvar.com/reionline/returns)

Expectation: `getRole(document.querySelector('input'))` should return `textbox`

Actual: `getRole(document.querySelector('input'))` returns `null`

I can tell this is because the above input, has an invalid type of `input.type` 🤦 but it appears that all browsers treat that invalid `type` attribute value as the same as not having it present at all (which defaults to text). I've tested this [rei page](https://returns.narvar.com/reionline/returns) out with safari + vo and inspected a11y trees in the 3 major browsers.

Motivation: 🤷 

<pre><code>
axe-core version:4.0.2

Browser and Assistive Technology versions

For Tooling issues:
- Node version: XX  
- Platform:  
</code></pre>

**Comment by straker** [comment]
Should be an easy fix. Instead of looking at the [type attribute as we do now](https://github.com/dequelabs/axe-core/blob/develop/lib/commons/standards/implicit-html-roles.js#L112), we should look at the `vNode.props.type` property which is [already calculated to respect valid types and default to text](https://github.com/dequelabs/axe-core/blob/develop/lib/core/base/virtual-node/virtual-node.js#L33-L42)

**Comment by shankarshastri** [comment]
@straker , I can take a look at this one !!

**Comment by straker** [comment]
Awesome. Let me know if you need anything.

**Comment by shankarshastri** [comment]
I went ahead with the approach you suggested above, by changing 
```switch ((vNode.attr('type') || '').toLowerCase()) { ``` to 
```switch ((vNode.props.type || '').toLowerCase()) {```

@straker , Any thoughts on how I can test the change?

**Comment by straker** [comment]
Yep, we have a test file for [implicit roles](https://github.com/dequelabs/axe-core/blob/develop/test/commons/aria/implicit-role.js) that you can make sure an invalid input type returns as `textbox`
