### ISSUE TITLE
Github Linter "image-redundant-alt" rule not triggered

### ISSUE THREAD

**Issue by privatmamtora** [dequelabs/axe-core#2519]
I am playing around with the Github Axe-Linter but I can't seem to trigger the "**image-redundant-alt**" rule (Sample: https://github.com/privatmamtora/axe-test/pull/5)

I used the "bad" example from Deque University.

The rule is triggered when I use the Browser Addon to scan the page.
![image](https://user-images.githubusercontent.com/7475401/93261587-e5adec80-f770-11ea-9baa-79e3ceee6051.png)

Expectation: Catch the issue

Actual: Issue not reported

Motivation: The documentation says it is supposed to work

**Note: I added configuration to "enable" all the rules, since the documentation never listed what is the "Default Configuration"

**Comment by straker** [comment]
Sorry that's not working out for you. [The docs](https://axe-linter.deque.com/docs/ruleset/) is a bit misleading in that it fails to take into account which rules apply to which file types. So the image-redundant-alt rule only works in JSX at the moment and not for HTML files. This is a current limitation but we are working to increase the rules and types.

**Comment by privatmamtora** [comment]
Alright thanks, good to know.
Any chance the documentation could be made more accurate?
Something as simple as just adding `(JSX only)` after the rule.

OR a larger enhancement to [Axe-Linter](https://github.com/privatmamtora/axe-test/pull/5/checks?check_run_id=1119635395) report to list the rules/tests that were executed or skipped.

**Comment by WilcoFiers** [comment]
Yes, we will work on it in the coming sprint. Thank you for reporting.

**Comment by straker** [comment]
Closing as the `image-redundant-alt` rule was removed last year and is no longer listed in the docs as a valid rule.

**Comment by padmavemulapati** [comment]
No QA-required
