### ISSUE TITLE
Add an implicit role of "row" to the tr element

### ISSUE THREAD

**Issue by SiTaggart** [dequelabs/axe-core#252]
According to the [ARIA in HTML spec](https://www.w3.org/TR/html-aria/#tr), table rows come with an implicit role of "row".

Currently aXe causes false negatives on rows within an ARIA grid, that uses HTML table semantics. You shouldn't have to apply `<tr role="row">` to a table row element.

Yes, I agree it's strange that information is not supplied in the HTML 5 specification, so for good measure, I [filed an issue on the ARIA in HTML spec](https://github.com/w3c/html-aria/issues/47) too. 

I'm going to assume the implicit role is correct, but if it turns out it's a mistake in the ARIA in HTML spec then this issue can be closed.

**Comment by dylanb** [comment]
@SiTaggart can you supply a test HTML snippet for this issue?

**Comment by SiTaggart** [comment]
Is this useful @dylanb https://github.com/dequelabs/axe-core/pull/255 ?

**Comment by SiTaggart** [comment]
I should click on things before I submit a PR. I see it's covered in #253. I guess my test my be of some worth. Feel free to close otherwise.

Thanks for adding these so quickly! 👍

**Comment by dylanb** [comment]
Thanks, that test was useful

**Comment by marcysutton** [comment]
Is this still an issue, or did it get handled with #253?

**Comment by SiTaggart** [comment]
It's totally fixed as far as I can see in the latest release @marcysutton.

Thanks for being great at addressing these things! 🎉

**Comment by marcysutton** [comment]
That one was all @dylanb! I will go ahead and close this issue. Thanks for contributing!

**Comment by SiTaggart** [comment]
Well, just generally, as a team 👏
