### ISSUE TITLE
Objects should not allow fallback content

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2524]
The following should fail axe-core. Fallback content on objects is not used to compute an accessible name.

```html
<object data="...">
  Fallback content
</object>
```

For details, see the discussion about this in the WCAG issues: https://github.com/w3c/wcag/issues/1138

**Comment by padmavemulapati** [comment]
Verified with the test content
Pass criteria: 
 `<object id="pass1" title="This object has text"></object>` ,
`<object id="pass2" aria-label="this object has text"></object>` , 
and failure: 
	`<object id="violation1"></object>` , 
 `<object id="violation2"><div></div></object>` and 
	`<object id="violation3">This object has text.</object>`
not allowing fallback content on the data , properly pass and fail meeting the requirements
![image](https://user-images.githubusercontent.com/47409579/95086648-5d52b400-073e-11eb-97c9-664e5caa9a3c.png)

**Comment by yecril71pl** [comment]
Please change the summary to something less horrible, like *Object fallback content marks it accessible*.
