### ISSUE TITLE
rerun integration test is flakey

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2529]
See: https://app.circleci.com/pipelines/github/dequelabs/axe-core/1188/workflows/6974fd5e-aac0-4bf5-b058-412f52d5d8f8/jobs/22089

This test failed on develop. No idea yet why, but when I reran the test it passed.

**Comment by straker** [comment]
Another random failure https://app.circleci.com/pipelines/github/dequelabs/axe-core/1243/workflows/3b3bc4ca-a329-477b-8312-4290924ec4b6/jobs/22642

**Comment by straker** [comment]
https://app.circleci.com/pipelines/github/dequelabs/axe-core/1288/workflows/7fcf9926-857f-4705-9b76-63f83f835833/jobs/23106

**Comment by straker** [comment]
#2563 seems to be more stable (the IE11 link-in-block test no longer fails), but will leave this open for a bit to see how it goes.

**Comment by straker** [comment]
Closing as tests haven't been flakey anymore
