### ISSUE TITLE
axe.reset() does not reset branding

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core#2530]
If you configure axe with custom branding and then call `axe.reset()`, the custom branding is not reset.

```js
axe.configure({
  branding: {
    brand: 'foo',
    application: 'axe-jest'
  }
});

axe.reset();
console.log(axe._audit.brand);  // foo
```

**Comment by straker** [comment]
I think the best solution is to set the `brand`, `application`, and `tagExclude` (also doesn't get reset) in the [_init](https://github.com/dequelabs/axe-core/blob/develop/lib/core/base/audit.js#L294) function back to their [original values](https://github.com/dequelabs/axe-core/blob/develop/lib/core/base/audit.js#L153-L155).

We'll also need to add tests to the [resetRulesAndChecks](https://github.com/dequelabs/axe-core/blob/develop/test/core/base/audit.js#L374-L397) block to ensure they get reset properly.

**Comment by Bracciata** [comment]
I am working on this now. As a fan of Axe super excited to tackle this issue.

**Comment by padmavemulapati** [comment]
axe.reset() is resetting : Verified on latest axe-core 4.0.2.
![Uploading image.png…]()
