### ISSUE TITLE
Rule proposal: BP: Pages should not make scrolling UI inaccessible or difficult to use

### ISSUE THREAD

**Issue by Jehoel** [dequelabs/axe-core#2538]
(Ported over from https://github.com/GoogleChrome/lighthouse/issues/11292 )

(This rule proposal does not match the standard prescriptive format for other `act-rules` because I'm unfamiliar with Deque System's process for reviewing and approving rules, and I didn't want to spend a lot of time and effort into a proposal that might get rejected early - and because it's difficult for me to express this check simply in terms of "assumptions" and "outcomes" as mentioned in your W3C Standard Rules formatting spec, but I did use the template from [your `rule-proposal.md` file](https://github.com/dequelabs/axe-core/blob/develop/doc/rule-proposal.md)).

# Best practices: "Pages should not make scrolling UI inaccessible or difficult to use" (Alternative name: "Scrolling UI should not be customized by pages")

### Rule description

Ensures web-pages do not make browser-provided / native scrolling UI inaccessible or harder to use, especially for users of mouse-driven computers.

### Rule help

Elements _should not_ ("must not"?) override or customize how the browser will render scroll UI elements. Remove all custom styling of `::-webkit-scrollbar` psedoelements (for Chromium/Webkit browsers) and `scrollbar-*` properties (for MSHTML browsers).

----

(Alternatively, some styling should be permissible, but checks that ensure scrollbar UI meets certain minimum sizes (Fitts Law, etc) and have sufficient colour contrast would work)

**Tags:** `best-practice`, `cat.sensory-and-visual-cues`, `cat.mouse`, `experimental`

## Selector

No single selector exists. See each check below.

### There must be no customization of a browser's scrolling UI. `optional`, `none`

1. There must be no CSS rules with selectors matching any known scroll pseudoelement (e.g. `::-webkit-scrollbar-*`).
2. There must be no CSS rules with properties matching any known scrollbar style property (e.g. `scrollbar-3dlight-color`).

(Question: should this rule also prohibit use of [the non-proprietary `scrollbar-width: thin;` property](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width) and value?)

### There must be no elements with vertical scrollbar tracks and thumbs narrower than some minimum width `{minWidth}px` accessible to users of mouse-driven computers lacking scrolling hardware (e.g. scroll wheel, built-in touchpad, etc). `none`.

(Question: What should the minimum width be? It varies between systems. While WCAG 2.5.5 suggests _touch_ targets should be at least 44px long or wide at 96dpi that rule doesn't apply to mouse-driven UI)

1. There must be no CSS rules with selectors matching any known scroll pseudoelement (e.g. `::-webkit-scrollbar-*`) which caused a a `width:` or `height:` property's _computed-style_ value lower than `{minWidth}px`.

### There must be no elements with vertical scrollbar thumbs with insufficient visual contrast with their scrollbar tracks.

(Question: Should this rule require all scrollbars to have a solid and opaque background color, or just prevent any customization of color? What about UI where there isn't normally a track displayed at all, just a floating thumb? How do those browsers/systems handle cases where the thumb is a solid white or solid black but the page's background is an image or video with white or black regions that render the thumb entirely invisible?

**Comment by WilcoFiers** [comment]
@Jehoel Thank you for the suggestion. It is an interesting idea, but I'm not sure why customised scrollbars would cause accessibility issues. Can you elaborate on that? I've never heard this suggestion, so I'm a little skeptical about it; then again, I've been wrong before ;).

**Comment by WilcoFiers** [comment]
@Jehoel Any updates?

**Comment by WilcoFiers** [comment]
Closing the issue due to inactivity. Thanks for raising the suggestion though. If you'd like to revisit feel free to reopen.

**Comment by paulirish** [comment]
There's a little more I can add here.

[Flag websites with custom scrollbars that are very thin · #13112](https://github.com/GoogleChrome/lighthouse/issues/13112) is a more recent proposal, much in the same lines of this issue.

And this issue has also been raised in the csswg issue tracker.. suggesting there could be spec text (and presumably UA intervention?) to prevent inaccessible/low-contrast scrollbars:
https://github.com/w3c/csswg-drafts/issues/6675
https://github.com/w3c/csswg-drafts/issues/6710

**Comment by Jehoel** [comment]
@WilcoFiers  Sorry I dropped-the-ball on this.

From my position, the accessibility and usability issues with thin and poorly-designed scrolling UIs (often caused by web-designers on macOS forgetting that PC users even exist...) are immediately obvious and demonstrable, so when you wrote this (emphasis mine):

>  It is an interesting idea, but **I'm not sure why customised scrollbars would cause accessibility issues**

... I kinda gave-up and lost-interest because I had the impression you wouldn't be satisfied until I wrote an entire explainer, passed it around for comments from UI/accessibility research leaders, made a YouTube video and given a TED talk on the subject..

I jest, but I felt you were being dismissive.

**Comment by Jehoel** [comment]
@paulirish Yes, that Lighthouse issue is the exact problem I'm talking about. I didn't think to add screenshots to mine, though.

I see you closed that one as a dupe of this, so now I feel vindicated, thank you :)

**Comment by straker** [comment]
One potential problem I foresee about a rule such as this is the speed (it would probably be as slow if not slower than color-contrast). The algorithm would look something like this:

* get all nodes on the page
* see if node has a scroll region (defines overflow and the scrollsize is larger than the element size)
* get computed styles of all scrollbar pseudo selectors (which might not even exist for the element, but there's no way to tell). I think there's 4 or 5 we would need to look at. 
* get width/height or any property we care about. Because we can't know if the styles define a custom scrollbar we'd have to do the math for every scroll region just in case. Since we're looking at width/height of the scrollbar, that's likely to cause a style recalc or force layout for every call. 
* determine if there's a problem (probably not intensive math)

**Comment by Jehoel** [comment]
@straker 

> Because we can't know if the styles define a custom scrollbar

Checking for the use of all CSS properties that customize the browser's scrollbar appearance is straightforward - or are you referring to _truly_ custom scrolling implementations that don't use browser-provided scrollbars?

**Comment by straker** [comment]
I mean checking these styles:

```js
window.getComputedStyle(node, '::-webkit-scrollbar');
window.getComputedStyle(node, '::-webkit-scrollbar-thumb');
window.getComputedStyle(node, '::-webkit-scrollbar-track');
```

Without digging into it I'm not sure if the others apply or not, but these probably are the major ones. But we have to ask the browser for each one in tern for every scroll region, there's no way to know if the user actually defined any styles for these selectors without checking.

`getComputedStyles` can cause layout and recalc when [checking certain properties](https://gist.github.com/paulirish/5d52fb081b3570c81e3a#calling-getcomputedstyle). Since we need to know width/height properties, it's likely to cause recalf or layout.

**Comment by Jehoel** [comment]
@straker Using `getComputedStyle` shouldn't be necessary - A simple textual `grep` of source stylesheets and `style=""` attributes would catch 90% of offenders, and doing the same for strings in source JavaScript would then catch the remaining 5% - for the remaining cases the only explanation is a page trying to obfuscate or hide their style logic, which I don't think is worth the effort to try to catch.

That said, doesn't Chromium expose any way for Lighthouse to inspect the "final" rendered document at all?

**Comment by straker** [comment]
Axe-core only works on DOM nodes, we don't currently support scanning CSS files.

**Comment by Jehoel** [comment]
> Axe-core only works on DOM nodes, we don't currently support scanning CSS files.

CSS files are exposed via the DOM though.
