### ISSUE TITLE
Rename a saved test

### ISSUE THREAD

**Issue by emendezsolis** [dequelabs/axe-core#2540]
Hi,

I could not find a way to rename a saved test. I think it would be very useful to have this functionality as sometimes you need to reorganize your saved tests - and renaming them would be a way to accomplish this task.

Thanks.

Expectation: << Describe what you expect the product to do >>

Actual: << Describe what the product actually does >>

Motivation: << Describe why you want the behavior to be changed >>

<pre><code>
axe-core version: X.Y.Z
axe-webdriver, extension or other integration version: X.Y.Z

Browser and Assistive Technology versions

For Tooling issues:
- Node version: XX  
- Platform:  
</code></pre>

**Comment by WilcoFiers** [comment]
Thanks for reporting. I'm forwarding the request to the right person.

**Comment by erik-deque** [comment]
With the latest version you can rename your test (as shown below):

![image](https://user-images.githubusercontent.com/57361142/102511245-8ce33e00-4056-11eb-82d3-9ecd3c9e98a2.png)

**Comment by emendezsolis** [comment]
Thank you for answering my email.

I used the new Axe Beta version yesterday and it looks great! Congrats, it is way more stable than the previous one and with plenty of new features to disover!

Thank you,

Ernesto Mendez
UX Designer

Maximus Canada
716 Yates Street
6th Floor Cubicle - 621
Victoria, B.C. V8W 1L4
Office: 250.405.3829
ernesto.mendez@maximusbc.ca
CONFIDENTIALITY NOTICE: This electronic transmission, and any documents attached to it, may contain confidential information belonging to the sender. This information is intended solely for the use of the individual or entity named above. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution or the taking of any action in reliance upon the contents of this information is prohibited. If you have received this transmission in error, please notify the sender immediately and delete the message and all documents.
