### ISSUE TITLE
rule: document-title not detecting inside <head>

### ISSUE THREAD

**Issue by nova93** [dequelabs/axe-core#2543]
Expectation: rule ID document-title should detect <title></title> inside `<head></head>`

Actual: Throws a warning

Motivation: Align usage with MDN docs on title tag (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title) and Lighthouse (https://web.dev/document-title/), both say that <title> should be used inside `<head>`.

<pre><code>
@axe-core/react: 4.0.0

Browser and Assistive Technology versions
Chrome 85
</code></pre>

![image](https://user-images.githubusercontent.com/3315728/95337348-a8d5a100-08a9-11eb-8cd9-dd8a5457e0d9.png)

![image](https://user-images.githubusercontent.com/3315728/95337295-9ce9df00-08a9-11eb-9885-f5718efe4987.png)

**Comment by straker** [comment]
Interesting. Are you able to give me a link to the page that throws the error or maybe a code snippet that shows the error? The rule should detect the title element correctly.

**Comment by nova93** [comment]
Unfortunately, the project is behind a VPN. I'm trying to replicate this issue on a public repo, and will report back once successful.

**Comment by WilcoFiers** [comment]
@nova93 Browsers take the first `title` element in the page as the document title, irrespective of where it is in the page. Axe-core follows this behavior. You are correct that the HTML specification says it needs to be in the head, you're also only allowed to have one `title` element according, but neither of those are really accessibility issues, so it is not something axe-core flags.

**Comment by nova93** [comment]
I think I know what might be causing it.

The whole app is protected (behind a password), and every route has `withAuthentication` HOC, however, the metadata is added at the page level. Since adding `<Head>` from `next/head` doesn't cause a re-render, it's not being picked up. While playing around I've found a moment where <head> didn't have <title> tag, and axe-core warnings were visible. If I wait for everything to finish, the <title> tag is there, yet the warning still shows.

As mentioned above, I'm working on public repo which shows this.

**Comment by nova93** [comment]
Haven't been able to replicate... sorry for wasting your time
