### ISSUE TITLE
commons/table/to-grid does not account for rowspan=0

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core#2553]
Noticed this while working on https://github.com/dequelabs/axe-core/pull/2545. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/td#attr-rowspan), `rowspan=0` means the row spans to the end of the table (tested in Chrome).

> if its value is set to 0, it extends until the end of the table section (`<thead>`, `<tbody>`, `<tfoot>`, even if implicitly defined), that the cell belongs to

Our `get-headers` code will also need to be adjusted to handle rospawn of 0.

**Comment by padmavemulapati** [comment]
Verified in the axe-core latest develop code:
with the code snippet:
`<!-- rowspan=0 - headers-->`
 ` <table>`
  `  <tr><td rowspan="0"></td><th scope="col">1</th><th scope="col" id="t1">2</th></tr>`
   ` <tr><th scope="row" id="t2"></th><td id="target"></td></tr>`
   ` </table>`
![image](https://user-images.githubusercontent.com/47409579/103776724-dfac8600-5055-11eb-82ca-7349670f85d4.png)
