### ISSUE TITLE
Some rules are missing a category tag

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2554]
**Expectation**: All rules have a category (`cat:*`) tag

**Actual**: Some rules, such as aria-toggle-field-name do not

The easiest place to see missing tags is to look at the `docs/rule-description.md` file. In addition to adding these tags, we should add a test to `build/tasks/validate.js` to enforce that all rules have a category tag.

**Comment by mDalessandro** [comment]
I can take a look at this.

**Comment by padmavemulapati** [comment]
Verified in the latest axe-core latest develop ,
Added category - tag for the following rules/ids

aria-input-field-name: cat.aria
aria-toggle-field-name: cat.aria
aria-tooltip-name: cat.aria
avoid-inline-spacing: cat.structure
identical-links-same-purpose: cat.semantics
label-content-name-mismatch: cat.semantics
no-autoplay-audio: cat.time-and-media
scrollable-region-focusable: cat.keyboard
accesskeys: cat.keyboard
