### ISSUE TITLE
False positive: Axe "autocomplete attribute must be used correctly rule" flagging valid autocomplete values

### ISSUE THREAD

**Issue by dboshkoff** [dequelabs/axe-core#2557]
**Axe extension version:** 4.6.1
**Axe core version:** 4.0.2
**Browser version:** Google Chrome 85.0.4183.121
**Reproducible location:** https://codepen.io/braintree/full/mPgdPN

**Context**
My team is using hosted fields, custom input fields provided by the company Braintree for collecting a user's payment information. These fields load in iframes. Axe is flagging these fields as using the autocomplete attribute incorrectly in our custom custom component. I was also able to reproduce the behavior in Braintree's own example codepens (linked). However, unless I am misunderstanding the autocomplete rule there is no accessibility violation. So, this seems to be a problem with Axe rather than Braintree's hosted fields. 

**Steps to reproduce:**
1. Install the Axe extension in google chrome. 
2. Go to https://codepen.io/braintree/full/mPgdPN.
3. Scan the page with the Axe accessibility scanner. 

**Expected result:**
There should be no violation concerning autocomplete. 

**Actual result:**
All three hosted fields are flagged for invalid values of the autocomplete attribute including

- cc-number
- cc-csc
- cc-exp

According to these sources, https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete and https://www.w3.org/TR/WCAG21/#input-purposes the above are valid values for the autocomplete attribute. 

**Motivation:**
We are using Axe to test our component for accessibility, and it always flags these issues.

**Comment by WilcoFiers** [comment]
Thank you for reporting. We've looked into it and you are correct. This is something we're going to fix in the next release.

**Comment by padmavemulapati** [comment]
Reproducing in the old versions of (v4.6.1) - showing 3 autocomplete related issues.
![image](https://user-images.githubusercontent.com/47409579/97582409-b64ef880-1a1b-11eb-8b05-e48b6fabb007.png)

And validated with the latest fix version Axe-QA build  (v.4.6.1. 30220 ) , not seeing the `autocomplete` related issues
![image](https://user-images.githubusercontent.com/47409579/97582756-2198ca80-1a1c-11eb-9ec1-4325633d4d26.png)
