### ISSUE TITLE
Feature suggestion: include bounding rectangle of violation in Axe results

### ISSUE THREAD

**Issue by jamalmazrui** [dequelabs/axe-core#2560]
For tools that use the results.json from Axe in a non-interactive manner (e.g., not in an open browser), it would be helpful if bounding coordinates were included for the area of the page where a rule violation has been found.  For example, coordinates could be provided as x, y, width, and height, which might then be passed to the screenshot method of the Puppeteer API for saving a relevant image to disk.

**Comment by WilcoFiers** [comment]
Hey @jamalmazrui. Thank you for the suggestion. I think this is a little beyond the intended use of axe-core as an open source project. Axe-core is built to prevent accessibility issues. Users integrate it with their automated tests, and make sure all the tests pass before merging changes into their staging / production environment. What you are suggesting sounds more like using axe-core as an auditing tool to find and report on issues after they've already made it into production code.

This is not a use case axe-core is designed for, and to do it well would require quite a bit more than just including bounding rectangles on nodes. [Deque systems](https://deque.com/) has products that will help you with this use case. These are not free; they help us pay for the development of axe-core and its open source integrations. From the sound of it, you are getting a good deal of value out of axe-core, which I am happy to see. I do hope you'll contact us to see if some of our other products / services can help you out.

**Comment by jamalmazrui** [comment]
I understand and accept that this would be an enhancement that your 
company would reserve for commercial tools.


I do not understand the other points made though.  Axe provides specific 
CSS selector or XPath information to indicate where an accessibility 
violation has been detected.  The proposal is to add bounding rectangle 
information in addition to that within the JSON results (Axe is 
generally run with an automated browser with data available from a live 
DOM).  Secondly, this would, indeed, be useful in testing a prototype 
page before production -- it is just a way for Dev or QA to more easily 
identify the location of a problem, supplementing the textual path 
information.


Thanks for your response.

**Comment by WilcoFiers** [comment]
I would recommend to do this after the completion of an axe-core run then. The selector will help you find the element in the page.
