### ISSUE TITLE
Provide a Choice for Dark Theme / Light Theme

### ISSUE THREAD

**Issue by heidi-jungel** [dequelabs/axe-core#2564]
Expectation: On the plugin, an option for Dark Theme / Light Theme or base if off of the users OS

Actual: Forces user into dark theme

Motivation: I get Dark mode is all the rage; however Dark Theme is not readable to all users, particularly some users with low vision.  This, ironically, is what something Deque should be aware of.  Please provide a choice for the user.   For some users the plug in is now nearly impossible to read.

**Comment by straker** [comment]
Thanks for the suggestion. I'll pass it along to the appropriate team.

**Comment by scurker** [comment]
Thanks for the feedback @heidi-jungel! We're currently looking at this, and light mode is likely to return as a user selectable option in a future release of the extension.

**Comment by dylanb** [comment]
This is now implemented
