### ISSUE TITLE
Headings test - Finish/Next button gets permanently disabled

### ISSUE THREAD

**Issue by tgrushkasm** [dequelabs/axe-core#2565]
In the Chrome plugin, in the Headings test, on the step: **Does each heading accurately describe the content that immediately follows it?**

When I click and expand **Element selector**,

Then try to click **Finish** ...

Expectation: I should be able to finish/exit the test and return to the testing dashboard.

Actual: The **Finish** button is disabled. I try to click **Back** to go to the previous step. The **Next** button remains disabled. I then try to exit/save the test, and get the following error message:

**We were unable to load your test**

I then have to restart Developer Tools and start the testing process all over again (ALL TEST DATA IS LOST).

Motivation: This should NOT happen. At minimum, when a step in the wizard is changed, the state of the button should be re-evaluated/refreshed so that gets re-enabled. Better yet, the Finish button should never be disabled at all, because most users will be confused as to why it's getting disabled just because the user entered the element selector, which has nothing to do with whether the user can finish/go to the next step, does it?

<pre><code>
axe-core version: 4.0.2
axe-webdriver, extension or other integration version: 4.6.1

Browser and Assistive Technology versions

For Tooling issues:
- Node version: XX  
- Platform:  
</code></pre>

**Comment by straker** [comment]
Thanks for letting us know, I've passed on the issue to the appropriate team.

**Comment by erik-deque** [comment]
This is actively being worked on and a fix will be released soon.

**Comment by erik-deque** [comment]
This was fixed in 4.7.1
