### ISSUE TITLE
More detailed information nested and avalliable as tooltips on guided test questions

### ISSUE THREAD

**Issue by enewmanMN** [dequelabs/axe-core#2566]
Expectation: When running guided tests a tooltip for more information surrounding the questions would be helpful. EX. I ran a guided test on list and the first question asks whether I see any lists that should not be lists. I am not sure to be honest so I was hoping to see a little tooltip describing why a list would be acceptable or not.

Actual: There is no tooltip provided on at least some of the guided test questions (I think most)

Motivation: I know this is an issue with the user but I think it would be pretty simple to put in a little 'i' icon for more information next to some of the questions to help speed things up and make it more user friendly the first couple go arounds :)  

Just thought I'd throw it out there!

**Comment by straker** [comment]
Thanks for the suggestion.

**Comment by erik-deque** [comment]
Thank you for the feedback, will take this to the team.
