### ISSUE TITLE
Update the ACT tag

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2568]
A few more ACT rules were recently published by the W3C. Need to add tags for axe-core implementations of those rules.

**Comment by padmavemulapati** [comment]
Verified with the latest code (v4.0.2) dated 12/11/2020
Observed "ACT" tag for the following:
1. sv-img-alt: test-snippet: `<svg xmlns="http://www.w3.org/2000/svg" role="img" id="violation1">
		<circle cx="50" cy="50" r="40" fill="yellow"></circle>
	</svg>`
![image](https://user-images.githubusercontent.com/47409579/98948967-20d45e00-251d-11eb-96da-8a3cbc9e9fdc.png)

2.select-name: test-snippet: `<select id="fail2"></select>`
![image](https://user-images.githubusercontent.com/47409579/98947839-b66eee00-251b-11eb-84a1-47d12d311ae4.png)

3. role-img-alt: test-snippet: `<div role="img" aria-label="" id="violation2"></div>`
![image](https://user-images.githubusercontent.com/47409579/98947523-57a97480-251b-11eb-8ee2-ccc5e3d86c3f.png)

4.meta-viewport: test-snippet: `<meta
	name="viewport"
	id="mvp"
	content="User-Scalable= no;
										 maximum-scale=2;"
/>`
![image](https://user-images.githubusercontent.com/47409579/98947361-1add7d80-251b-11eb-9cca-cdcf5c2877b5.png)

5. link-name: test-snippet: `<a href="#" id="fail-linkname" role="presentation"></a>`
![image](https://user-images.githubusercontent.com/47409579/98947164-de118680-251a-11eb-8f2b-946df49260fa.png)

6. label: test-snippet: `<input type="text" id="fail27">`
![image](https://user-images.githubusercontent.com/47409579/98946995-a30f5300-251a-11eb-9a1f-1ee853c89737.png)

7. image-alt : test-snippet: `<img src="img.jpg" id="violation12" role="separator" tabindex="0">`
![image](https://user-images.githubusercontent.com/47409579/98946816-62173e80-251a-11eb-80aa-440a1451a03d.png)

8.button-name: - test-nippet: `<button id="fail-buttonname" role="presentation"></button>`
![image](https://user-images.githubusercontent.com/47409579/98946538-03ea5b80-251a-11eb-8b68-bd27f0529185.png)

9.aria-toggle-filed-name:  - test snippet: `<div id="failariatoogle" role="checkbox" aria-labelledby="does-not-exist"></div>`
![image](https://user-images.githubusercontent.com/47409579/98946340-c5ed3780-2519-11eb-90fb-36497fb1e769.png)

10.aria-input-feild-name - test snippet : `<div id="failariafield" aria-label=" " role="combobox">England</div>`
![image](https://user-images.githubusercontent.com/47409579/98946121-7ad32480-2519-11eb-99c4-06d3e63b4115.png)

11.area-alt: test-snippet:`<area href="#" id="violation2" aria-label="" />`
![image](https://user-images.githubusercontent.com/47409579/98949266-7d377d80-251d-11eb-82a9-e27e3eaf5269.png)
