### ISSUE TITLE
Ignore elements from name rules that don't need one

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2578]
**Espected**: When an element that natively needs an accessible name is given a role that does not require a role, axe-core ignores does not call these out as issues.

**Actual**: In some instances, axe-core will fail these. For example:

```html
<img role="separator" />
<button role="gridcell" disabled>
  <!-- debatable if this needs it or not, ARIA says it does -->
</button>
```

This exception should probably only apply to elements that can not be focused. I think we can implement this by adding a matcher to the image-alt, svg-img-alt, button-name, link-name ... rules.

**Comment by padmavemulapati** [comment]
Verified with the latest axe-core  develop code(v4.0.2)- 
For the following rules, axe-core ignoring the issue when needs an accessible name is given a role that does not require a role.
1.button-name
2. image-alt
3. input-button-name
4. input-img-alt
5. object-alt
for ex: button-name: test-snippet: '<button id="target" role="button"></button>'
![Uploading image.png…]()
