### ISSUE TITLE
Button with role="slider" flagged as not appropriate for the element

### ISSUE THREAD

**Issue by PeterCiuffetti** [dequelabs/axe-core#2599]
A button with the following markup raises the exception "ARIA role must be appropriate for the element"

```
<button
 aria-label="slider-button"
 class="rheostat-handle"
 aria-valuemax="2020"
 aria-valuemin="1999"
 aria-valuenow="1999"
 aria-disabled="false"
 data-handle-key="0"
 role="slider"
 tabindex="0"
>
</button>
```
![image](https://user-images.githubusercontent.com/1168204/97354624-0f782a00-186c-11eb-91dc-273109fede2d.png)

Expectation:
According to [WAI guidelines on role slider](https://www.w3.org/TR/wai-aria-1.1/#slider), the appropriate attributes are set, are numbers, and have values that are in the expected range.

Also [WAI examples for role slider](https://www.w3.org/TR/wai-aria-practices/examples/slider/slider-1.html) indicate a similar set of attributes.

The expectation is that this markup would pass.

axe-core version: 4.0.2
axe-webdriver, extension or other integration version: 4.6.1

Browser versions:
Chrome 86.0.4240.111

The following web page contains a year range slider that exhibits the problem.
https://mindscapecommons.net/search?q=%22vr%22

**Comment by straker** [comment]
Thanks for the issue.

The [ARIA in HTML spec](https://www.w3.org/TR/html-aria/) dictates which roles are allowed on elements. In this case, the [button element](https://www.w3.org/TR/html-aria/#el-button) is only allowed certain interactive roles, but `slider` is not allowed. Even though the attributes are all correct, the role is not appropriate for the button element.

**Comment by PeterCiuffetti** [comment]
Thanks for the feedback, we will address this issue in the markup.
