### ISSUE TITLE
Rule idea: flag empty table headers for review

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2604]
Fairly similar to the empty-headings rule. When a table header has no accessible name, axe-core should report it as *needs review**. This applies both to native `th` elements and to ARIA `rowheader` and `columnheader` roles.

**Comment by WilcoFiers** [comment]
Assigned to @ jlin95.

**Comment by padmavemulapati** [comment]
Verified with the latest axe-core code base, 
seeing the new rule "empty-table-header" failure where when a table header has no accessible name
![image](https://user-images.githubusercontent.com/47409579/111937675-40444e80-8aee-11eb-9a75-4c99ae48f564.png)
