### ISSUE TITLE
Integrating axe-core to Jasmine

### ISSUE THREAD

**Issue by Ankur289** [dequelabs/axe-core#263]
All the examples or tutorials available on web regarding axe-core with jasmine shows appending the small html and verify it with a11ycheck. However when we have an html template more than 100 lines what needs to be done to check accessibility. Please demonstrate any example that will be helpful.

**Comment by dylanb** [comment]
@Ankur289 there is no difference in how you use axe-core with a small snippet of HTML or with hundreds of lines.
