### ISSUE TITLE
Replace phrasingElements array in subtreeText

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2632]
We can remove the phrasingElements array in getSubtreeText, now that we have "phrasing" included in contentTypes on HTML elements in standards.

https://github.com/dequelabs/axe-core/blob/develop/lib/commons/text/subtree-text.js#L49

https://github.com/dequelabs/axe-core/blob/develop/lib/standards/html-elms.js#L14

**Comment by straker** [comment]
Dev task
