### ISSUE TITLE
"Content should be contained in a landmark region" violation on dialog element using axe chrome extension

### ISSUE THREAD

**Issue by shankarshastri** [dequelabs/axe-core#2633]
Axe chrome plugin reports failure for modal(dialog) opened on a page w.r.t rule All page content must be contained by landmarks. 

Issue similar to #991 

axe-core version: 4.0.2
axe-chrome-extension: 4.6.1

**Comment by straker** [comment]
Thanks for the issue. I believe we fixed this in the latest develop with https://github.com/dequelabs/axe-core/pull/2586. Would you be able to test the problem with the latest code and see if it still fails?

**Comment by shankarshastri** [comment]
@straker, I was actually using the chrome extension. If you can let me know how I can test from develop, I can try it out. Thanks for the reference.

**Comment by straker** [comment]
Sure. You can get the latest develop changes with [axe-coconut](https://chrome.google.com/webstore/detail/axe-coconut-web-accessibi/iobddmbdndbbbfjopjdgadphaoihpojp?hl=en)

**Comment by straker** [comment]
Wait sorry. I forgot we no longer auto-update axe-coconut with latest develop changes... So you can get the latest with `npm` using [axe-core@next](https://www.npmjs.com/package/axe-core/v/next).

**Comment by shankarshastri** [comment]
But any thoughts regarding latest chrome extension, apart from automation?

**Comment by straker** [comment]
@shankarshastri any update on this? The latest axe extension should have the latest code. Does it fix the issue?

**Comment by shankarshastri** [comment]
@straker , will check and come back on this one !!

**Comment by shankarshastri** [comment]
@straker , Looks like it's fixed.
