### ISSUE TITLE
"Content should be contained in a landmark region" violation on alertdialog element

### ISSUE THREAD

**Issue by aj-r** [dequelabs/axe-core#2638]
Expectation: no errors for a valid alert dialog

Actual: error: "Content should be contained in a landmark region"

Motivation: #991 exempts `role="dialog"` from the "Content should be contained in a landmark region" rule. I think `role="alertdialog"` should be exempt for the same reasons. Furthermore, adding a landmark around an alertdialog seems to cause screen readers to stop announcing the contents of the dialog, which is a big problem.

**Comment by WilcoFiers** [comment]
You are right. Not sure how we overlooked that, but we feel silly for having done so! We'll be sure to address it in the 4.1.1 patch.

**Comment by aj-r** [comment]
Amazing thank you!

**Comment by WilcoFiers** [comment]
Also, just as an FYI. We had to do an unplanned patch release, which ended up as 4.1.1. This bill be in the planned patch release, which is now numbered 4.1.2.

**Comment by padmavemulapati** [comment]
Verified with the latest axe-core(develop code) - dated 08/12/2020,
`role="alertdialog"` is exempting the "All page content must be contained by landmarks" - `region` rule


Tried to reproduce without `role="alertdialog"`
