### ISSUE TITLE
Flooded by 'No response from frame' logs

### ISSUE THREAD

**Issue by wyattdanger** [dequelabs/axe-core#264]
I have axe-core running in my development environment, and see a flood of 'No response from frame' logs. The `iframe` in question is from a third party service. Is there a way to disable the checking of `iframe`s or to disable checking within specific frames?

**Comment by dylanb** [comment]
I think you can set `axe.log = function () {};` and it will suppress all the messages

**Comment by wyattdanger** [comment]
Sounds good to me
