### ISSUE TITLE
add axe.getRule(id)

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core#2642]
Need a public way to return an individual rule so we don't have to keep doing `axe._audit.rules.find(ruleObj => ruleObj.id === ruleId)`

**Comment by WilcoFiers** [comment]
Here's another use for this method: https://github.com/dequelabs/axe-core/pull/2648/files#diff-6cb05ef5f40343f1168c634a0aaa0c15f5e9cde40d7775c131ef70f263a7bc7aR34

**Comment by padmavemulapati** [comment]
devTask

**Comment by padmavemulapati** [comment]
Validated with the latest axe-core code base - 
after run build, and latest `axe.js` built, run `await axe.utils.getRule('region')` , below is the details we can see:
![image](https://user-images.githubusercontent.com/47409579/116100978-107afe80-a6cb-11eb-8a99-16652b2a9db9.png)

also verified for few more rules:, `bypass`
![image](https://user-images.githubusercontent.com/47409579/116101241-4cae5f00-a6cb-11eb-8628-49aba7a11073.png)

for `color-contrast`
![image](https://user-images.githubusercontent.com/47409579/116101449-71a2d200-a6cb-11eb-8672-40316a319345.png)

**Comment by padmavemulapati** [comment]
Tested on axe-expert_v4.6.0.03923, we can see the `_audit` details by running - `utils.getRule('rule_id')`
![image](https://user-images.githubusercontent.com/47409579/230848253-e2ccaaa2-1e5a-43ab-9bb1-29ad3b32d560.png)
