### ISSUE TITLE
Add "impact" field to rules

### ISSUE THREAD

**Issue by connorjclark** [dequelabs/axe-core#2644]
The `doc/rule-descriptions.md` file marks each rule's impact. It'd be nice if this was also represented in the `lib/rules` json files. Lighthouse already uses `axe-core`'s impact / `tags` to determine how to [weigh](https://github.com/GoogleChrome/lighthouse/blob/bd5c03c51eef2c522aadc326bc26d832b7853aed/lighthouse-core/config/default-config.js#L493) each rule, and we're looking to automate it with a script to make it more concrete, so I figure this field would be a big help.

**Comment by straker** [comment]
Interesting suggestion. Right now a rules impact is determined at run time by looking through each of its checks and getting the highest impact, so it's not something we could manually add to the rules json file. And since rules and checks can be configured by the user, it's not something we could hard-code either.

**Comment by connorjclark** [comment]
Ah, I hadn't realized that. We could reference the checks of each rule then. Would it be accurate-enough to consider the impact of a rule by using all the checks listed in a rule's `all/any/none` fields with equal weighting?

**Comment by straker** [comment]
Not sure on the weighting part, but if you were to scan the rule file and get all it's checks, then scan each check JSON file looking at the impact, you could probably deduce the final impact and assign a weight to it.

**Comment by straker** [comment]
It's not the cleanest of code, but here's where we generate a rules impact for the rule description doc. You could probably do something similar to get the final impact level

https://github.com/dequelabs/axe-core/blob/develop/build/configure.js#L238-L263
