### ISSUE TITLE
locale specific axe.js not generating

### ISSUE THREAD

**Issue by padmavemulapati** [dequelabs/axe-core#2649]
When trying to run `npm run build --lang=ja` its not generating `axe.ja.js` file.
Expectation: Should generate specified locale axe.js file

Actual: Generating browser default axe.js file only 
![image](https://user-images.githubusercontent.com/47409579/99562855-9db87980-29ee-11eb-9395-7b39fb9560c2.png)

Verified axe-core: 4.1.0

**Comment by padmavemulapati** [comment]
Verified with the latest code base - axe-core, able to generate `axe.ja.js` for `npm run build -- --lang=ja`,
abs using this `axe.ja.js` analysed webdriverjs's analyse api and seeing the results in japanese language
![image](https://user-images.githubusercontent.com/47409579/103213748-a5940380-4934-11eb-851b-5d9325f83409.png)

**Comment by padmavemulapati** [comment]
Again this issue is reproducing - 
tried to generate ` --lang=de` file but still getting `axe.js` instead `axe.de.js`

@straker , can you please confirm this from your end

**Comment by clottman** [comment]
@padmavemulapati there's a difference in the command that works and the one that doesn't - the extra set of `--`. Those are necessary to actually pass through the option provided to the build script. 

This works for me: 
`npm run build -- --lang=ja`

This does not: 
`npm run build --lang=ja`

**Comment by padmavemulapati** [comment]
@clottman , tried with your suggestion and its working .
`npm run build -- --lang=ja`
![image](https://user-images.githubusercontent.com/47409579/124438322-ab601b00-dd95-11eb-9f04-92a2407975d5.png)
