### ISSUE TITLE
AxeResult results come as string values instead of json when uses prototype.js v1.6.1 script

### ISSUE THREAD

**Issue by TroyWalshProf** [dequelabs/axe-core#2657]
Expectation: The violations, passes, inapplicable and incomplete json nodes should contain a list of result nodes.

Actual: The violations, passes, inapplicable and incomplete json nodes have string values.
To repo run Axe Core against:
[PageTest.zip](https://github.com/dequelabs/axe-core/files/5580666/PageTest.zip)

More context -
**What your JSON looks like**
_violations: **"**[CONTENT]**"**_
**What your JSON should look like:**
_violations: [CONTENT]_

Motivation: This appears to break most tooling which uses Axe core

Effects:
axe-core version: 4.0.2 & 4.1.1
axe-webdriver, extension or other integration version: 
-Selenium. Axe  2.0.0
-axe (Chrome extension) v4.6.1

**Comment by straker** [comment]
Thanks for the issue. Due to security reasons we can't open a zip file. Would you be able to setup a test page on CodePen or something similar, or paste a code snippet that reproduces the issues?

**Comment by TroyWalshProf** [comment]
Here are the needed file:
[TestPage.html.txt](https://github.com/dequelabs/axe-core/files/5584025/TestPage.html.txt)
[v161prototype.js.download.txt](https://github.com/dequelabs/axe-core/files/5584026/v161prototype.js.download.txt)
[v173prototype.js.download.txt](https://github.com/dequelabs/axe-core/files/5584027/v173prototype.js.download.txt)

*Notes: 
1. You will need to remove the .txt extension to use them
2. This bug comes from: https://github.com/TroyWalshProf/SeleniumAxeDotnet/issues/102

**Comment by straker** [comment]
Thanks for the content. So I'm not able to reproduce this issue. I use both the v161 and v173 files but each time I run `results = await axe.run()` I get a properly structured JSON back, where violations, passes, etc. are all arrays of objects.

**Comment by TroyWalshProf** [comment]
The problem is really really small.
Here is what I get back when I have the prototype js:
[ResultBad.json.txt](https://github.com/dequelabs/axe-core/files/5584255/ResultBad.json.txt)
Here is what I get back when I remove the prototype js:
[ResultGood.json.txt](https://github.com/dequelabs/axe-core/files/5584256/ResultGood.json.txt)


Note the extra quote in the bad results:
Good:
```
  "violations": [
    {
```
vs 
Bad:
`  "violations": "[{`

**Comment by straker** [comment]
How are you saving the JSON results? By default axe-core outputs an JSON object, but your output looks like stringified JSON

**Comment by straker** [comment]
I'm going to guess this is an issue with the Prototype code. Without the code on the page it `JSON.stringify` works correctly. With v173 it works as well. But as soon as the other version is on the page the stringify function returns incorrectly even though the raw results aren't any different.

**Comment by straker** [comment]
A simple test case confirms this. Just doing `JSON.stringify({foo: [1,2,3]})` results in `"{"foo":"[1, 2, 3]"}"` (a string aray)

**Comment by straker** [comment]
Specifically I think [this file is the culprit](https://github.com/prototypejs/prototype/blob/1.6.1/src/lang/object.js). They are completely overriding the browser `Object` prototype (specifically `toJSON` which seems to be what `JSON.stringify` uses

**Comment by TroyWalshProf** [comment]
That is nasty.
So if I am understanding correctly this will not affect Axe Core, but anything using Axe Core with JSON.stringify will not work.

**Comment by straker** [comment]
Yep. Anything using `JSON.stringify` will be broken on arrays

**Comment by TroyWalshProf** [comment]
Closing this bug as the issue is in prototype.
*Or at least I assume you don't intend to workaround folks overriding such low level functionality.
