### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by sbollu** [dequelabs/axe-core#266]
I am trying to compare both label value and input title but I am unable to get the proper values.

var label = document.querySelector('label[for="' + axe.utils.escapeSelector(node.id) + '"]');
var label = axe.commons.dom.findUp(node, 'label');

which one is right one to get if nay row with label ? similarly looking for title also please let me know which one is right one ? 

var titleNode = document.querySelector('input[title="' + axe.utils.escapeSelector(node.title) + '"]');
var	titleNode = node.getAttribute('title');

If all the above wrong, please let me know how to get both label value and input title ?

**Comment by marcysutton** [comment]
Can you explain more about what is motivating your request? We already have label checking rules. Are you trying to write a custom rule?

**Comment by sbollu** [comment]
planning to write custom rule and test it. below var works for if label have "for" and "id" ..something like this  but below scenario its working...
<input type="checkbox" name="hobbySports" id="chk1" value="sports" title="Title: please select your hobbies: sports" />
<label for="chk1" id="lbl_chk1">Label: Sports</label>
var label = document.querySelector('label[for="' + axe.utils.escapeSelector(node.id) + '"]');

How to get label value for below scenario. I have to see label have value ?
<LABEL><SPAN class=bold>Sports</SPAN><BR><SPAN>$&nbsp;</SPAN></LABEL><INPUT type="text" title="please select your sports">

**Comment by dylanb** [comment]
@sbollu in your second example, the label is not associated with the input, so the "accessible name" for the input is "please select your sports".

The existing `label` rule should deal with both of those cases, so I am not sure what you are trying to have your custom rule do?

**Comment by sbollu** [comment]
Thanks for the info.
