### ISSUE TITLE
Axe-Core library showing different results for different language platforms

### ISSUE THREAD

**Issue by harimadusumilli** [dequelabs/axe-core#2678]
The results when run through Selenium-Dotnetcore and when run through the Taiko (Non-Selenium) do not match using the same version of Axe-Core library. Version 4.0.2

Expectation: The counts for violations, passes and incomplete should be the same.

Actual: The counts for violations , passes and incomplete are not matching when run through selenium and when run through taiko

Motivation: The results should be consistent across any language or platform that is used. We have different technology groups and when we use the AXE-Core library we would like to see the same result output for a site that is being audited.

axe-core version: 4.0.2
Selenium.Axe  - version 2.0 (Nuget package - Dotnetcore).

Taiko-accessibility plugin using axe-core 4.0.2

Browser and Assistive Technology versions 

Both being run on Windows 10 operating system

Url: http://puppies.herokuapp.com/
Orientation: landscape-primary
Size: 1280 x 565
Time: 12/7/2020 2:37:11 PM +00:00
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Using: axe-core (4.0.2)
Counts:
Violation: 11
Incomplete: 14
Pass: 191
Inapplicable: 53

When we use Taiko with Axe-Core against the same site and same page we get the following : Context:
Url : http://puppies.herokuapp.com/
Orientation : landscape-primary
Size : 1280 X 565
Time : 2020-12-07T14:53:17.757Z
User agent : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Using : axe-core 4.0.2
Counts:
score : 75
violations : 6
incomplete : 1

**Comment by dylanb** [comment]
Those packages are not maintained by Deque

Please contact the package maintainers 
https://www.nuget.org/packages/Selenium.Axe/
https://github.com/andreas-ku/taiko-accessibility

If you would like a supported C# integration please [contact us](https://www.deque.com/company/contact/)
