### ISSUE TITLE
Support graphics roles in the aria-roles rule

### ISSUE THREAD

**Issue by TwoLaid** [dequelabs/axe-core#2684]
Expectation: The `aria-roles` rule should pass on elements that use graphics roles such as `graphics-document` and `graphics-object`.

Actual: The rule fails when the website contains an element with `role="graphics-document"`

Motivation: As far as I can tell, these roles already have decent support, and are even used in some of the internal axe-core tests, such as https://github.com/dequelabs/axe-core/blob/f2f15377c917d0b6fc27d2181f64ebef26e5a9b0/test/integration/rules/svg-img-alt/svg-img-alt.html or the `svg-img-alt` rule.

<pre><code>
axe-core version: 3.5.5
axe-webdriver, extension or other integration version: n/a

Browser and Assistive Technology versions: macOS Catalina, VoiceOver and Safari

For Tooling issues:
- Node version: 12
- Platform:  macOS
</code></pre>

**Comment by straker** [comment]
Thanks for the issue. We've been [meaning to get them added](https://github.com/dequelabs/axe-core/issues/1189). Would that be something you'd be interested in opening a pr for?

If so, I'd be happy to walk you through it. You'd just add a new file in [lib/standards](https://github.com/dequelabs/axe-core/tree/develop/lib/standards) called `graphicRoles` and then add each [graphic role](https://www.w3.org/TR/graphics-aria-1.0/) as documented by the [aria-roles doc](https://github.com/dequelabs/axe-core/blob/develop/doc/standards-object.md#aria-roles).

**Comment by TwoLaid** [comment]
Yes, I'm interested in contributing! Thank you for the pointers.

**Comment by WilcoFiers** [comment]
Issue resolved, closing the ticket.
