### ISSUE TITLE
aXe Coconut issue for rule: Bold, italic text and font-size are not used to style p elements as a heading

### ISSUE THREAD

**Issue by ajitbubu** [dequelabs/axe-core#2688]
<< Please describe how you encountered this issue. Is it an experimental rule? Something not working in Shadow DOM? >>

**Comment by straker** [comment]
Thanks for submitting an issue. Could you describe the issue a bit more (like what's incorrect about the report, page, etc.) or link to the public page that this issue occurs on?

**Comment by straker** [comment]
Going to close this as no response
