### ISSUE TITLE
What to do with SHOULD in ARIA

### ISSUE THREAD

**Issue by dylanb** [dequelabs/axe-core#269]
The ARIA spec lists a lot of conditions for attribute use that are listed as SHOULD and not MUST. This means that they are strictly not required, however there are some that really don't make sense to not do.

For example, a [progressbar](https://www.w3.org/TR/wai-aria/roles#progressbar) that has a valuemax, valuemin without a valuenow does not really make sense. I suggest that we create specific rules for the conditions that fall into this category that are separate from the other ARIA rules.

Thoughts @marcysutton @WilcoFiers?

**Comment by marcysutton** [comment]
Could these be added as Best Practice rules?

**Comment by dylanb** [comment]
We could add them as best practice or we could add them as "cantTell". I kindof prefer cantTell because of the treatment those will receive in the new extension - WDYT?

**Comment by marcysutton** [comment]
Ooh, I like that idea.

**Comment by WilcoFiers** [comment]
This issue is a bit too vague to have an actual fix for it. The answer is; it depends, usually we'll want to use cantTell, but it'll depend on each individual case.
