### ISSUE TITLE
Is this Landmark Best Practice Issue accurate, or did axe make an overcall?

### ISSUE THREAD

**Issue by goodwitch** [dequelabs/axe-core#2690]
Issue:  I ran axe on this page http://test.austinfree.net/ (as a Judge for Knowbility's AIR competition).  
The following Best Practice issue is being thrown:  'All page content must be contained by landmarks"
on the video player that is within an iframe that is within `<main>`.

Expectation: I was wondering if the iframe inside main was enough to count this player as being within a landmark, or if additional landmark need to be added within the iframe. 

<pre><code>
axe-core version:4.0.2
axe-extension: version 4.6.0

Browser and Assistive Technology versions:
Firefox: 83.0

For Tooling issues:
- Platform:  Mac 11.0.1
</code></pre>

**Comment by WilcoFiers** [comment]
You are correct. That needs to be fixed. Looks like we didn't properly fix #2330 @straker. Sorry Glenda, we'll get it resolved ASAP.

**Comment by svinkle** [comment]
@WilcoFiers Any update to this? We're running into the same issue with YouTube embeds elsewhere. Thanks.

**Comment by padmavemulapati** [comment]
Validated on test page: `http://test.austinfree.net/`
able to reproduce using axe-expert, seeing `Best Practice` issue on `region` saying "All page content must be contained by landmarks"
![image](https://user-images.githubusercontent.com/47409579/125097909-358ce400-e0f4-11eb-97c5-c4caa13f3eaa.png)

and seeing the fix in the latest develop branch code- axe-core (9th July,2021)
not seeing any issue either `violation` or `Best-practice` on `region` within iframe that is within <main>.
![image](https://user-images.githubusercontent.com/47409579/125098368-94eaf400-e0f4-11eb-903f-d1f933230bcd.png)

**Comment by WilcoFiers** [comment]
This could have been closed some time ago.
