### ISSUE TITLE
Axe - Web Accessibility Testing Extension: Too many cookies created by Amplitude causing 400 bad request errors

### ISSUE THREAD

**Issue by pgrunewald** [dequelabs/axe-core#2698]
**Preamble:**
I recently noticed, that using the "Axe - Web Accessibility Testing Extension" I get several responses from servers saying *400 Bad Request* with the note, that the header size is too large.  I noticed that the header size is increased by the growing number of cookies beginning with "amp_cookie_test_".

In my research I stumbled on [this similar issue](https://github.com/amplitude/Amplitude-JavaScript/issues/326) where the cause seems to be related to the usage of [Amplitude](https://github.com/amplitude/Amplitude-JavaScript) by a browser extension with another extension uBlock origin. Upon further inspection I saw that Amplitude is as well used for this extension.

In my setup I run Adblock (version 4.25.1) instead, but the result is the very same. The current workaround is to either disable the extension entirely or delete the aforementioned cookies of the unreachable sites.

**Expectation:** The Axe extension creates no cookies for every site I visit.

**Actual:** The Axe extension creates cookies for every site I visit.

<pre><code>Extension version: 4.6.2
Browser: Chromium 87.0.4280.66
Platform: Linux Manjaro (Kernel: 5.9.11)
</code></pre>

Let me now if you need more information for solving this issue.

best, Paul

**Comment by erik-deque** [comment]
Thanks for posting this, we're investigating.

**Comment by erik-deque** [comment]
We've been trying to reproduce this and so far have been unsuccessful. Any chance we could hop on a zoom call and walk through it?

**Comment by jasikpark** [comment]
I may be having the same problem? *Something* is creating many cookies in the form: https://github.com/amplitude/Amplitude-JavaScript/search?q=COOKIE_TEST_PREFIX resulting in the same problem of a 400 when the number of cookies grows too big.

I've mostly encountered this when visiting https://duckduckgo.com and https://codepen.io

**Comment by rrix** [comment]
for the last few months i have been having issues making searches in Firefox; lately i have tracked the issue down to a big pile of cookies that expire in 2025 or later that i guess Axe is creating; i had 145 of them when I just wiped my duckduckgo cookies:

![image](https://user-images.githubusercontent.com/138102/108568267-a9059480-72be-11eb-93b3-f0ddbc704374.png)

making DDG searches from the Firefox URL bar handles this situation *terribly*, simply not performing the search without any error messages in the tab inspector or indiciation as to what's going on, much less a visible 400 page. It's taken me weeks to hunt this down, i figured i was being haunted... unfortunately i have 20 other addons enabled in my sync profile and tracking which is causing these cookies to not be cleared is beyond my limited free time at the moment.

**Comment by jasikpark** [comment]
exactly what I was experiencing. I removed the  extension, useful though it may be, and have not had any problems since.

**Comment by erik-deque** [comment]
We've got a fix for this that will be rolling out in next week's release.

**Comment by dylanb** [comment]
@jasikpark @rrix @pgrunewald can you upgrade to the latest version and see whether this problem is now fixed for you?

**Comment by jasikpark** [comment]
Reactivated now, will let y'all know if I run into this problem soon. It definitely was the culprit, since deactivating it removed the problem entirely. Hopefully the fix works 👍

**Comment by pgrunewald** [comment]
Just tested it: I'm not seeing any new random cookies just by visiting sites. The issue seems to be fixed! Thank you @erik-deque and everyone involved.
