### ISSUE TITLE
web extension: CSS classes are changed causing React to warn about hydration mismatches 

### ISSUE THREAD

**Issue by eps1lon** [dequelabs/axe-core#2699]
Live reproduction: https://codesandbox.io/s/pensive-snowflake-51gx2?file=/src/index.js

Expectation: No hydration mismatches reported by React

Actual: ``Warning: Prop `className` did not match. Server: "alanguage-sh language-none" Client: "alanguage-sh"``

Motivation: It does not seem like intended behavior. Once I disable the axe extension I don't get any warning from React.

<pre><code>
axe-core version: unknown
extension version: 4.6.2

Browser and Assistive Technology versions

For Tooling issues:
- Chrome version: 88
- Platform:  Ubuntu 20.04
</code></pre>

**Comment by julia-allyce** [comment]
+1 We are also seeing this issue trying to run axe-core/react in an app that uses SSR / hydrate

**Comment by dylanb** [comment]
@eps1lon @julia-allyce can you provide some test code that we can use to reproduce?

**Comment by eps1lon** [comment]
> @eps1lon @julia-allyce can you provide some test code that we can use to reproduce?

The live-reproduction mentioned in the issue: https://codesandbox.io/s/pensive-snowflake-51gx2?file=/src/index.js

However, I originally reproduced it with 4.6.2. With the latest 4.8.6 I can no longer reproduce. It was probably fixed unintentionally.

**Comment by dylanb** [comment]
closing as fixed/unreproducible
