### ISSUE TITLE
axe-core Error: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by buttinoni** [dequelabs/axe-core#2701]
![0902436E-776C-42C1-97F6-3750CD4BE68F](https://user-images.githubusercontent.com/76198497/102582879-cde55c00-4103-11eb-9eb7-11b0e1fe2ada.png)

Expectation: << Hi I have this error >>

Actual: << Describe what the product actually does >>

Motivation: << Describe why you want the behavior to be changed >>

<pre><code>
axe-core version: X.Y.Z
axe-webdriver, extension or other integration version: X.Y.Z

Browser and Assistive Technology versions

For Tooling issues:
- Node version: XX  
- Platform:  
</code></pre>

**Comment by WilcoFiers** [comment]
Thank you for reporting. Could you test this page with the latest version of the [axe Extension](https://chrome.google.com/webstore/detail/axe-web-accessibility-tes/lhdoppojpmngadmnindnejefpokejbdd). This looks very similar to an issue that we fixed recently, I don't believe has made it into Lighthouse just yet.

**Comment by WilcoFiers** [comment]
Since there are no actual details on what the problem might be here, I'm going to close the issue. As for when lighthouse updates axe-core. That decision is made by the lighthouse team, so if you'd like to see them update more frequently, that request should probably go into their repo.
