### ISSUE TITLE
Unused and inconsistent code in build

### ISSUE THREAD

**Issue by SandersAaronD** [dequelabs/axe-core#2714]
Expectation: Axe either accepts multiple locale arguments for building, or does not have code in the gruntfile to parse a list of multiple locale arguments.

Actual: Axe build fails if you provide multiple locales in a delimited list, but the gruntfile parses them out as if it were intended to accept them.

Motivation:
Right now the gruntfile appears to think that you can and should take multiple language arguments in comma and/or semicolon separated lists, but the aria-supported file chokes on this really badly because it doesn't perform the "parse in the list" step.

I'd be inclined to fix this but I'm unclear on what resolution would be desired; fully support passing in multiple languages in (something)-delimited lists, or remove the unused code that parses them out from the gruntfile?

**Comment by straker** [comment]
Thanks for letting us know. I'll bring this up internally and see what the answer should be. May take some time due to the holidays though.

**Comment by straker** [comment]
We'll look into this. If it's easy to fix we'll make it support multiple langs, otherwise we might just stick to supporting just one.

**Comment by padmavemulapati** [comment]
Validated with the latest develop branch code base,
When I tried to build multiple locales in a comma separated list , its allowing and creating the list at a time. (But not for all)
`npm run build -- --lang=ja,nl` resulting the below attachment and results as well
![image](https://user-images.githubusercontent.com/47409579/124437766-06ddd900-dd95-11eb-94b7-09818d4fefb8.png)

![image](https://user-images.githubusercontent.com/47409579/124437554-d0a05980-dd94-11eb-8ff0-c2b1ecdee6ca.png)
