### ISSUE TITLE
"aria-setsize" is not allowed in "treegrid"

### ISSUE THREAD

**Issue by DevChu** [dequelabs/axe-core#2720]
When I use axe chrome extension in the official aria practice (https://www.w3.org/TR/wai-aria-practices-1.1/examples/treegrid/treegrid-1.html), there are some "critical" issues.

Expectation:
No issues are announced in axe

Actual: 
"aria-setsize" is not allowed in "treegrid"

Motivation:
This should not be announced as an "issue"

<pre><code>
axe-core version: 4.1.1
axe-webdriver, extension or other integration version: axe chrome extension v4.6.2

- Platform:  Mac, Chrome v87.0.4280.88
</code></pre>

**Comment by straker** [comment]
Thanks for the issue.

**Comment by clottman** [comment]
Adding a note here from the ARIA Authoring Guide that might add clarity to why this was a false positive: 

> NOTE: Due to an error in the ARIA 1.1 specification, the aria-posinset and aria-setsize properties are not supported on row elements. This is being corrected in ARIA 1.2. Consequently, when validating the HTML in this example, errors are generated.
