### ISSUE TITLE
Axe reporting error for a angular tag

### ISSUE THREAD

**Issue by shankarshastri** [dequelabs/axe-core#2725]
Recently I was exploring the modal from ngx-bootstrap in angular. And I ran the axe tool and it reported **ARIA dialog and alertdialog nodes must have an accessible name** issue for an angular tag.

Should axe tool report errors only for HTML tags?

Modal URL:
https://ngx-modal.stackblitz.io/
https://stackblitz.com/edit/ngx-modal

Browser: Chrome
Axe version: v4.6.2
Axe Core Version: 4.1.1

Please find the below image for more details:

<img width="1293" alt="Screenshot 2020-12-28 at 7 19 58 PM" src="https://user-images.githubusercontent.com/10391044/103218791-14c42480-4942-11eb-8af1-5bc6d46822f2.png">

**Comment by WilcoFiers** [comment]
@shankarshastri Yes, this is an accessibility issue. The way that should have been implemented is by adding aria-labelledby to the model element, and have it reference the h4. This would make for a much better user experience for assistive technologies.
