### ISSUE TITLE
Using a custom ruleset with `axe.configure` yields reference errors

### ISSUE THREAD

**Issue by jeeyyy** [dequelabs/axe-core#2726]
**Expectation:**
Custom ruleset spec file configuration should run without errors.

**Actual:**
Using a custom ruleset file that follows the [axe.Spec](https://github.com/dequelabs/axe-core/blob/develop/axe.d.ts#L190) typings and passing it to `axe.configure` and then running `axe.run` yields a lot of reference errors to almost all functions defined and imported as ES modules.

> Note: This issue affects other integrations building on top of custom ruleset configuration.

Steps for replication:
- Create a custom ruleset file or use the [wcag2 ruleset file](https://github.com/dequelabs/axe-core/files/5748054/wcag2-ruleset.txt).
- Run `axe.configure(spec)`, where spec is the contents of the above file or custom ruleset file.
- Run `await axe.run()`

Errors (to show a few):
- "`ReferenceError: is_disabled_default is not defined` - feature unsupported in your environment. Skipping color-contrast rule."
- "`ReferenceError: get_node_attributes_default is not defined` - feature unsupported in your environment. Skipping aria-allowed-attr rule."
- "`ReferenceError: escape_selector_default is not defined` - feature unsupported in your environment. Skipping duplicate-id rule."
- "`ReferenceError: get_scroll_default is not defined` - feature unsupported in your environment. Skipping scrollable-region-focusable rule."
- "`ReferenceError: get_explicit_role_default is not defined` - feature unsupported in your environment. Skipping image-alt rule."

![image](https://user-images.githubusercontent.com/20978252/103229860-90e64a00-48f9-11eb-80f2-0450660a80cd.png)

**Motivation:**
Be able to configure and use custom rules.

<pre><code>
axe-core version: 4.1.1
</code></pre>

**Comment by WilcoFiers** [comment]
These are not errors within axe-core itself. Closing this ticket.
