### ISSUE TITLE
color contrast false positive in scrollable area

### ISSUE THREAD

**Issue by mfairchild365** [dequelabs/axe-core#2728]
Instructions:

1. Open Google Chrome and navigate to https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html
2. Run the axe browser extension
3. Observe that several color contrast issues are returned for elements in the side navigation. Each of these issues are for elements that are not currently visible. You need to scroll the navigation area to make them visible. The background color for these elements is not being correctly computed.

Expectation:

* using the 'Downloadable Documentation' link as an example (ensure that it is not visible when running axe, you might need to resize your viewport)
* foreground color should be `#d9d9d9`
* background color should be `#343131` (the background for `.wy-nav-side`)

Actual:

* foreground color is computed correctly
* background is incorrectly computed as `#fcfcfc` (the background for the body).

Motivation: I don't want false positives reported

Versions:
<pre><code>
axe-core version: 4.1.1
Google Chrome: 87
Platform: Mac
</code></pre>

**Comment by WilcoFiers** [comment]
Confirmed. We'll look into it. Thanks Michael!
