### ISSUE TITLE
Runtime issue: Cannot read property 'ownerDocument' of undefined

### ISSUE THREAD

**Issue by Keerthi-Penukonda** [dequelabs/axe-core#2733]
Unable to test scan part of the page with axe-beta
**Steps to reproduce:**
1. Open any web page
2. Launch axe-beta and login to the application
3. Select a component using scan part feature
4. Run automation

**Expected:** Automation should run successfully without any issues
**Actual:** Below error message is being displayed

axe-core version: `4.1.1`
axe-extension version: `4.7.0`

```
TypeError: Cannot read property 'ownerDocument' of undefined
    at Object.getFlattenedTree (chrome-extension://cnhapefnceeebgkbcjikpmgllgpbcaaj/content.bundle.js:33:25012)
    at chrome-extension://cnhapefnceeebgkbcjikpmgllgpbcaaj/content.bundle.js:33:6013
```

**Comment by WilcoFiers** [comment]
This is an issue in a beta version of the axe Extension. It is not related to axe-core. This issue is open in an internal repo, closing the ticket here.
