### ISSUE TITLE
How to get array of radio or check box group

### ISSUE THREAD

**Issue by sbollu** [dequelabs/axe-core#274]
Hi,

Looking for how to get array of radio or check box group. I am trying below (axe.commons.dom.idrefs) but always getting one and length getting always 1. 

Please help me to get array of 'aria-labelledby', 'aria-describedby';

var aby = axe.commons.dom.idrefs(node, 'aria-labelledby');
var dby = axe.commons.dom.idrefs(node, 'aria-describedby');

**Comment by marcysutton** [comment]
Custom rule support at this level of detail is mostly out of scope for axe-core open source. We do offer more support to customers of WorldSpace Attest: http://www.deque.com/products/worldspace-attest/
