### ISSUE TITLE
Incorrect reporting on role="treegrid" and it's owned children

### ISSUE THREAD

**Issue by SiTaggart** [dequelabs/axe-core#275]
Currently aXe will report that a `treegrid` requires a `treeitem` child. This is incorrect.

According to the ARIA Spec, [treegrid](https://www.w3.org/TR/wai-aria-1.1/#treegrid), similarly to a `grid`, requires a `row` or `rowgroup`. This means that [line 853](https://github.com/dequelabs/axe-core/blob/master/lib/commons/aria/index.js#L853) which declares that `treeitem` is `owned` by `treegrid`, should be closer to the `grid` rules on [line 341](https://github.com/dequelabs/axe-core/blob/master/lib/commons/aria/index.js#L341), which declares the role owns one of `row` or `rowgroup`.

Similarly it means that the required context for `treeitem` _should not_ include `treegrid` on [line 865](https://github.com/dequelabs/axe-core/blob/master/lib/commons/aria/index.js#L865), as per the ARIA 1.1 spec on `treeitem` https://www.w3.org/TR/wai-aria-1.1/#treeitem.

I can PR this if I get a spare moment, in the meantime just documenting it here.

**Comment by marcysutton** [comment]
Fixed with #479.
