### ISSUE TITLE
Deprecation of `doc-biblioentry` and `doc-endnotes` roles

### ISSUE THREAD

**Issue by Seirdy** [dequelabs/axe-core#2759]
DPUB-ARIA 1.1 [deprecates](https://github.com/w3c/dpub-aria/pull/22) the `doc-biblioentry` and `doc-endnote` roles. Using `<li>` or list/listitem is the preferred way to handle these endnotes.

Perhaps Axe could reduce the severity of its "missing children" checks wrt missing `doc-biblioentry` and `doc-endnote` roles, or eliminate them entirely.

**Comment by WilcoFiers** [comment]
I'm aware of the change in DPUB ARIA, but I don't really understand what you are suggesting to do. Can you provide an example of something that axe-core is currently failing, that you would like to see the severity changed on?

**Comment by Seirdy** [comment]
Currently failing:
- URL: https://seirdy.one/2021/01/12/password-strength.html
- Error: "Certain ARIA roles must contain particular children"

Apparently `doc-endnote` is missing.

The error is triggered at:

``` html
<section class="footnotes" role="doc-endnotes" aria-labelledby="note-hd">
```

Upon further checking, I actually don't see any child `<li>` element that *isn't* labelled `doc-endnote`; this is starting to look like a bug. I'll open another issue if this is the case.

That being said, since `doc-endnote` is deprecated, axe shouldn't raise this error when `doc-endnote` isn't found as a child of `doc-endnotes`.

**Comment by Seirdy** [comment]
Full context:

``` html
<section class="footnotes" role="doc-endnotes" aria-labelledby="note-hd">
	<h2 id="note-hd">References and endnotes</h2>
	<ol>
		<li id="fn:1" role="doc-endnote">
			<p>James Massey (1994). &ldquo;Guessing and entropy&rdquo; (PDF). Proceedings of 1994 IEEE
			International Symposium on Information Theory. IEEE. p. 204. <a href="#fnref:1" class="footnote-backref" role="doc-backlink">&#x21a9;&#xfe0e;</a></p>
		</li>
		<li id="fn:2" role="doc-endnote">
			<p>Assis, A. K. T.; Neves, M. C. D. (3 July 1995). &ldquo;History of the 2.7 K
			Temperature Prior to Penzias and Wilson&rdquo; <a href="#fnref:2" class="footnote-backref" role="doc-backlink">&#x21a9;&#xfe0e;</a></p>
		</li>
		<li id="fn:3" role="doc-endnote">
			<p>The MOAC 2 was supposed to be able to consume other sources of energy such as
			dark matter and dark energy. Unfortunately, Intergalactic Business Machines ran out
			of funds since all their previous funds, being made of matter, were consumed by the
			original MOAC. <a href="#fnref:3" class="footnote-backref" role="doc-backlink">&#x21a9;&#xfe0e;</a></p>
		</li>
		<li id="fn:4" role="doc-endnote">
			<p>This is a massive oversimplification; there isn&rsquo;t a single answer to the
			question &ldquo;What is the volume of the observable universe?&rdquo; Using this speed-of-light
			approach is one of multiple valid perspectives. The absolute size of the observable
			universe is much greater due to the way expansion works, but stuffing that into the
			MOAC&rsquo;s furnace would require moving mass faster than the speed of light. <a href="#fnref:4" class="footnote-backref" role="doc-backlink">&#x21a9;&#xfe0e;</a></p>
		</li>
		<li id="fn:5" role="doc-endnote">
			<p>Lloyd, S., &ldquo;Ultimate Physical Limits to Computation,&rdquo; Nature 406.6799,
			1047-1054, 2000. <a href="#fnref:5" class="footnote-backref" role="doc-backlink">&#x21a9;&#xfe0e;</a></p>
		</li>
		<li id="fn:6" role="doc-endnote">
			<p>Schneier, Bruce. Applied Cryptography, Second Edition, John Wiley &amp; Sons, 1996. <a href="#fnref:6" class="footnote-backref" role="doc-backlink">&#x21a9;&#xfe0e;</a></p>
		</li>
	</ol>
</section>
```

**Comment by siddoib** [comment]
Apologies for jumping on this one long after it's been closed. We've also been having the same issue with some of publications and we are not sure how to proceed further with it. Has it been flagged a bug? 

thanks!

**Comment by WilcoFiers** [comment]
Looking at this again, I think the change to this is premature. doc-endnote is required to be within doc-endnotes in DPUB-ARIA 1.0. This is proposed to be changed for 1.1. Version 1.1 however is currently an editors draft. It hasn't even been published as an official W3C draft yet, let alone making it into a stable standard.

Anyone wanting to change how this behaves, what you can do is modify axe-core's standard object like so:

```js
axe.configure({
  standards: { ariaRoles: {
    'doc-endnotes': { requiredOwned: [] }
  }}
})
```

Generally speaking, the W3C advises against using new versions of standards until they are in the "recommendation" stage. Axe-core sometimes gets ahead of that, but going off an editors draft seems too soon. What I will do is contact some folks that know more about DPUB than I do and see what they have to say about the issue.

**Comment by WilcoFiers** [comment]
I saw an update that the DPUB ARIA group is preparing to publish the first draft of version 1.1. At that point I think it reasonable for us to make this change.

**Comment by scottaohara** [comment]
realized my issue was a duplicate, so linking it here #3253

**Comment by padmavemulapati** [comment]
Verified with the latest dev branch code, 
` <div role="doc-biblioentry"></div> `
is showing failure on `aria-role`
![image](https://user-images.githubusercontent.com/47409579/148081550-939e4466-1e9a-4a52-8151-820b66b527c1.png)
