### ISSUE TITLE
nested-interactive doc?

### ISSUE THREAD

**Issue by Malvoz** [dequelabs/axe-core#2760]
I can't find the `nested-interactive` rule in https://dequeuniversity.com/rules/axe/4.1/. Looking at https://github.com/dequelabs/axe-core/pull/2705, it should live at https://dequeuniversity.com/rules/axe/4.1/nested-interactive?application=RuleDescription, but that doesn't return it.

**Comment by straker** [comment]
That is correct. The `nested-interactive` rule is part of the 4.2 release, so the docs for it aren't available yet. We are planning on releasing 4.2 in a few months.
