### ISSUE TITLE
Some tests fail when browser is at a mobile width

### ISSUE THREAD

**Issue by mfairchild365** [dequelabs/axe-core#277]
For example, 400px wide. Should axe be tested at both mobile and desktop widths? See #272 for further information.

**Comment by marcysutton** [comment]
Hi @mfairchild365, what do you mean by "tests fail"? Are you seeing false positives or negatives at mobile widths? Do you have a test page that we can use to validate this? Many sites in the wild change their markup at different viewports, so even if axe returns different violations for each they may not necessarily be inaccurate.

This would help me as I create a test condition at a mobile viewportSize. Right now all of our existing tests pass at 400 x 800.

**Comment by mfairchild365** [comment]
Ah, great question. I should have made that clearer.

Here are some steps to reproduce the problem.

1. run `grunt dev` on the master branch
2. open a new tab and using the responsive-viewer in dev tools, emulate the iphone 5 viewport size (320x568). Note that just shrinking your browser to the smallest width possible causes this problem too.
2. go the the URL like `http://localhost:9876/test/commons/` in Google Chrome (I'm using 55.0)
3. See the tests fail

![21 tests fail](https://cloud.githubusercontent.com/assets/498678/22613029/69f77bd4-ea3a-11e6-841c-b733349fe205.png)

Now, try the same steps above, only with #272 merged and you get 100% passing tests.

![0 tests fail](https://cloud.githubusercontent.com/assets/498678/22613036/70247e58-ea3a-11e6-9109-aea5f1bc9a73.png)

![Mulder from the x-files saying "Believe me, You can't unsee that"](https://cloud.githubusercontent.com/assets/498678/22613078/d9cbebf2-ea3a-11e6-8692-59b6a84e2cd8.gif)

**Comment by dylanb** [comment]
I can reproduce it

**Comment by dylanb** [comment]
Fixed on internal fork

**Comment by mfairchild365** [comment]
Ah that might explain the confusion. Does that mean I should close this and #272?

**Comment by dylanb** [comment]
No, I just fixed it this morning. Leave this open until we merge the code into GitHub.

**Comment by dylanb** [comment]
Actually @mfairchild365 can you confirm for yourself that your fix for #272 also fixes this problem? It did for me.

**Comment by mfairchild365** [comment]
Yep, merging #272 into master fixes this problem.

However, (and I should have been clearer earlier) I made this issue in part to suggest testing those pages at multiple widths automatically so that we can catch issues like this in the future before they become a problem.

**Comment by marcysutton** [comment]
Fixed with https://github.com/dequelabs/axe-core/commit/29be3bb7bf229e674e162a51e675a2c8d63c296f
