### ISSUE TITLE
Configuring browser extension feature request

### ISSUE THREAD

**Issue by myasonik** [dequelabs/axe-core#2784]
# Summary
I'd love to be able to customize some of the options that axe-core exposes in the browser extensions.

# Details
For the sites I work on, I know there are several warnings that either don't apply to us or are things we can't tackle right now so I'm only really interested in a subset of failures. Being able to limit the sometimes overwhelming output would be a big help in terms of focus but also not scaring away people new to testing.

axe-core exposes a lot of options and a lot might not be practical to expose in browser extension settings but an on/off toggle for each rule or group of rules would go a long way.

# Future follow-up dream
Really, what I'd love is a way for sites to customize this for users. As an a11y champion at a large org, reminding/convincing people to run axe on all of their PRs is a constant for me. Being able to limit their initial shock could help ramp people up into it instead of throwing them in the deep end immediately.

I haven't really seen something like this before, so just to explain a little more what I'm thinking:
- www.example.com sets a config object on the `window` 
- the axe browser extension looks for that config, following it if available
- axe browser extension adds a note in the UI that the config has been pre-set by the site, allowing the user to opt out of it

**Comment by erik-deque** [comment]
Interesting suggestion. We already have plans to add ruleset customization in the extension, but have never thought about it being configured in such a way. We will think about this as we move towards implementing ruleset configuratgion.

**Comment by erik-deque** [comment]
Wanted to follow up and say we're actively working on something related to this.

**Comment by myasonik** [comment]
Woo - awesome! Looking forward to see what y'all come up with!

**Comment by dylanb** [comment]
release 4.18.2 of the extension allows paid or trial users to set their axe-core version and/or their WCAG level in the settings
