### ISSUE TITLE
Axe extension breaks multiline code formatting from eleventy-plugin-syntaxhighlight

### ISSUE THREAD

**Issue by connorjclark** [dequelabs/axe-core#2786]
Extension version 4.7.1

When extension is enabled:
![image](https://user-images.githubusercontent.com/4071474/106339278-b7cacf80-625b-11eb-8151-4d2901fd9efb.png)
when disabled:
![image](https://user-images.githubusercontent.com/4071474/106339307-cd3ff980-625b-11eb-8a7f-a4a4279411e2.png)

https://web.dev/trusted-types/#fix-the-violations

First found: https://github.com/GoogleChrome/web.dev/issues/4555

Looking back at https://github.com/dequelabs/axe-core/issues/2686, all the example repros given are still rendering fine with the latest extension, so not sure what's different here...

`@11ty/eleventy-plugin-syntaxhighlight` v3.0.1

**Comment by scurker** [comment]
@connorjclark A fix for this should be available in `4.7.2`, which landed last week.

**Comment by connorjclark** [comment]
I have 4.7.2 and still see the same thing on the provided link. Are you also able to reproduce it?

**Comment by scurker** [comment]
@connorjclark Ah my bad I was looking at the wrong release. It will be in the next release which should be available in the coming weeks.

**Comment by erik-deque** [comment]
This was fixed in the latest release.
