### ISSUE TITLE
All page content must be contained by landmarks - impact rating/value

### ISSUE THREAD

**Issue by jcrawfor** [dequelabs/axe-core#2787]
Expectation: I have a page that is marked up with logical landmarks, but some of the text is not contained by them. However, when using a screen reader, the user can navigate to the start of landmarks and the landmark hierarchy makes sense in the list of landmarks. I don't expect an issue to be flagged as moderate impact.

Actual: Axe reports the text not contained in landmarks as having moderate impact? It doesn't seem to have any impact on my ability to use the page.
https://dequeuniversity.com/rules/axe/4.1/region?application=AxeChrome

Note that the training course header on Deque's own Website flags this error because the skip link at the top of the page isn't contained in a landmark, which kind of makes sense. The user doesn't want/need to hear the skip link read out as the first element inside the first landmark when they are navigating by landmarks.
e.g. https://dequeuniversity.com/class/ux2/toc

Motivation: I can see that it is good to check that landmarks are present on the page and the order/nesting is logical. However, I don't understand the value of an automated check to determine whether all text is inside a landmark or why that would have a moderate impact, at least for the end user.

<pre><code>
axe-core version: 4.1.1
axe-webdriver, extension or other integration version: 4.7.1
</code></pre>

**Comment by straker** [comment]
@WilcoFiers would be more knowledgable on the subject, but I believe the rule is to help when important page content is outside a landmark. If the user navigates by landmark they may miss that important information. 

It's true that for a lot of content it's probably a minor problem if a screen reader misses it. Automation can't determine what "important content" means, so we take the most common scenarios we know of and rate based on that information.

**Comment by jcrawfor** [comment]
Thanks for the feedback @WilcoFiers. The page I am working on is built from different components and I can't get the <main> landmark to enclose all of the content area of the page, as best practice suggests. Some of the content towards the end of the content area is outside the <main> landmark but before the footer i.e. not enclosed in any landmark. Unless a user is navigating backwards through a page, I can't think of any scenario where they would be inconvenienced by this. In terms of user impact it seems like a minor issue in this context. The moderate rating given by the aXe tool seems inappropriate.

**Comment by WilcoFiers** [comment]
Thanks for opening the issue. I agree with you that the DQU skiplink shouldn't be failed. The region rule is supposed to take that into account, so I'm going to treat that as a bug. We'll fix it in an upcoming release.

As for distinguishing between minor and moderate, this is fairly subjective. Axe-core's impact is determined by checks, which have a certain granularity. All things flagged by a check will have the same impact. In this particular case, moderate is an estimated average impact of this check. That means the impact should in many cases be considered higher, and in others lower.

Impact is highly context dependant. A missing alt attribute can be minor, or it can be a complete blocker. Impact as axe-core reports it is a fair starting point for prioritisation, but that's all they are, a starting point. I would recommend you always look them over and shift things higher or lower in the priority list depending on context.


I'm going to close this issue. I don't think there is any change we can reasonably make here.
