### ISSUE TITLE
Region rule does not account for absolute URLs in skiplinks

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2791]
This course page creates 3 issues in the region rule: https://dequeuniversity.com/class/ux2/toc The ones on the "next" links are legit, those should be findable through landmarks. The skiplink however should have been excluded The URL "class/ux2/toc#content" is clearly a reference to another element on the same page. The rule should understand this.

**Comment by padmavemulapati** [comment]
Valdiated with the latest axe-core dev branch code base,

earlier, it was finding `region` rule for `skiplinks` as well `next` links available in the page ` https://dequeuniversity.com/class/ux/toc`
![image](https://user-images.githubusercontent.com/47409579/151567243-6e7f0d2b-5c9d-4efe-96a7-7cd3d7aa6173.png)

As the suggested fix, `Region` rule does not account for `skiplinks`, with the latest code, not seeing failure for `skiplinks`
![image](https://user-images.githubusercontent.com/47409579/151567707-ec13a5b6-b7c3-41b7-8c0f-7a7050c81039.png)
