### ISSUE TITLE
Runtime issue: axe.run arguments are invalid

### ISSUE THREAD

**Issue by kdayanand** [dequelabs/axe-core#2799]
<< Please describe how you encountered this issue >>

axe-core version: `4.1.1`
axe-extension version: `4.7.1`

```
TypeError: axe.run arguments are invalid
    at wu (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:333611)
    at Object.ku [as run] (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:334565)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/content.bundle.js:33:5971
```

**Comment by straker** [comment]
Thanks for the issue. Could you provide a bit of information about how the error happened, such as any configuration changes that might have been made?

**Comment by straker** [comment]
Going to close this issue. Please reopen if more information can be provided.
