### ISSUE TITLE
add aria-current as a valid attribute name

### ISSUE THREAD

**Issue by robfentress** [dequelabs/axe-core#280]
Running the aXe chrome extension on a Facebook page on the following HTML:
`<a class="_3f-h _3f-i" aria-current="page" href="https://www.facebook.com/VTLibraries/?ref=page_internal"><span class="_3f-j  _50f4"><div class="clearfix _ikh"><div class="_4bl7">Home</div><div class="_4bl7"></div></div></span></a>`

I got the error, `Invalid ARIA attribute name: aria-current`.  

The attribute `aria-current` appears to be a valid  attribute according to the [ARIA 1.1 spec](https://www.w3.org/TR/wai-aria-1.1/#aria-current).  Should this error have been thrown?

**Comment by marcysutton** [comment]
This has already been fixed internally and will be in the next release of axe-core. See duplicate issue: #270
