### ISSUE TITLE
Chrome Extension "appendChild" console errors appear on certain pages

### ISSUE THREAD

**Issue by chrisblakley** [dequelabs/axe-core#2804]
On certain pages I've noticed that several JavaScript console errors appear:

![Screen Shot 2021-02-14 at 12 59 38 AM](https://user-images.githubusercontent.com/6349678/107869795-0e412c00-6e60-11eb-9425-fb733a5a1462.png)

`Uncaught TypeError: Cannot read property 'appendChild' of undefined`

I don't know if this helps, but here is the line from `vendor.bundle.js`:

![Screen Shot 2021-02-14 at 1 01 04 AM](https://user-images.githubusercontent.com/6349678/107869818-32047200-6e60-11eb-8a89-430c7e244baa.png)

It has happened on several pages, but this is the latest one I've seen it occur on:
- https://nebula.gearside.com/examples/native-lazy-loading-in-browser/

I'll update this issue with additional pages if that helps.

Expectation: No errors should appear in the console
Actual: Several errors appear in the console
Motivation: Uncluttering the console

axe-core version: 4.1.2
axe-webdriver, extension or other integration version: 4.7.2

![Screen Shot 2021-02-14 at 1 03 13 AM](https://user-images.githubusercontent.com/6349678/107869831-709a2c80-6e60-11eb-852b-234e49a2ee59.png)

Browser and Assistive Technology versions
Chrome Version 88.0.4324.150 (Official Build) (x86_64)

For Tooling issues:
- Node version: n/a
- Platform:  Mac OS 11.2.1

**Comment by straker** [comment]
Thanks for letting us know. We'll do some investigation.

**Comment by erik-deque** [comment]
We're working on cleaning this up, should have a new release out soon with a fix.

**Comment by erik-deque** [comment]
Are you still seeing this @chrisblakley? I've tried reproducing but haven't had any success and I'm thinking it might have been fixed when we updated one of our dependencies.

**Comment by chrisblakley** [comment]
I have not seen this error in a while, and checked a few pages specifically for it and you may be correct.

**Comment by dylanb** [comment]
fixed
