### ISSUE TITLE
Angular js ng-view issue

### ISSUE THREAD

**Issue by NS123987** [dequelabs/axe-core#281]
I am using angular js and using ng-view to load the content with page footer and header which is in on html and all other html comes in ng-view .when i run the axe test on the pages it does not show issues of header and footer code

**Comment by marcysutton** [comment]
Hi, can you put your info in the description instead of the title? Thanks.

**Comment by NS123987** [comment]
Hi, I have made the changes

**Comment by marcysutton** [comment]
Great. Can you also provide a Codepen or jsbin with sample code? That will help us debug your issue.

**Comment by marcysutton** [comment]
Hi @NS123987, can you provide a demo? Otherwise I'll close this issue, as we need more information from you to debug it. Thanks.

**Comment by marcysutton** [comment]
I'm going to close this issue due to inactivity. If/when you provide a demo we can reopen and look closer at it.
