### ISSUE TITLE
Is video-caption still included in 4.1?

### ISSUE THREAD

**Issue by jaimeiniesta** [dequelabs/axe-core#2819]
Hi! I've seen that the [video-caption rule](https://dequeuniversity.com/rules/axe/4.1/video-caption) is not included in the [axe Rules 4.1 list](https://dequeuniversity.com/rules/axe/4.1/) but I think this rule is still in use, is it?

The 4.1 list contains 90 rules, I'm not sure if it's up to date - let me know if I can submit an issue or PR to other repo for Deque University instead.

**Comment by WilcoFiers** [comment]
That is odd! The rule still exists in axe-core, and the [page still exists](https://dequeuniversity.com/rules/axe/4.1/video-caption?application=RuleDescription) too. No idea why it isn't in that list. I'll go see if I can figure that out. Thanks for reporting!

**Comment by WilcoFiers** [comment]
Aaannnddd fixed :).
