### ISSUE TITLE
ARIA 1.1: Update allowed values of aria-haspopup

### ISSUE THREAD

**Issue by SiTaggart** [dequelabs/axe-core#282]
With ARIA 1.1 comes a new set of allowed values for `aria-haspopup`. `haspopup` is no longer a boolean value and allows the following values:

- true
- false
- menu
- listbox
- tree
- grid 
- dialog

This can be referenced from the [aria-haspopup specification](https://www.w3.org/TR/wai-aria-1.1/#aria-haspopup)

Requires a change in type and additional values https://github.com/dequelabs/axe-core/blob/0fc66099816786170a4ad9e246a6b21437e72f6c/lib/commons/aria/index.js#L60

**Comment by marcysutton** [comment]
Thanks, we'll incorporate them soon!

**Comment by marcysutton** [comment]
Fixed with #479.
