### ISSUE TITLE
ACT rules IDs in Axe rules?

### ISSUE THREAD

**Issue by fpetrone** [dequelabs/axe-core#2820]
I was not able to find the ID from the ACT rules in the results that Axe shows in the console nor in the rules description.

For example, for the rule "button-name" there is the tag "ACT" but not an "ACT ID". I am not sure if that rule is linked to the  [ACT rule with the ID 97a4e1](https://act-rules.github.io/rules/97a4e1) .  If it is not there, I think that adding it would be a good improvement for a tool that is already great.

**Comment by WilcoFiers** [comment]
Thanks for asking! That's a very good point. We should put links to the corresponding ACT rules in the rule help pages I think. Haven't yet, but I'll put it on our list! Great idea.

**Comment by fpetrone** [comment]
Thanks for replying. I was thinking of the ID inside the object if that makes sense. In any case, it would be great to have a mapping. Cheers!

**Comment by rweberkaf** [comment]
Taking on this task, making the "hackathon" label true!

**Comment by straker** [comment]
Was resolved in #2866
