### ISSUE TITLE
Why not let role="img" on <img>?

### ISSUE THREAD

**Issue by DavidMacDonald** [dequelabs/axe-core#2821]
```<img role="img" src="/on/demandware.static/Sites-givenchy-beauty-us-Site/-/default/dw073bdeb8/images/my-account.svg" alt="">```

is currently failing AXE. While I agree its not necessary to have role="img" I don't think it hurts, and it fixes a problem in VoiceOver.

AXE says:
>Fix the following:
ARIA role img must be removed when the element is made visible, as it is not allowed for the element

Expected result
No issue flagged.

**Comment by straker** [comment]
Thanks for the issue. I believe axe-core is correct in this case as an img is not considered an `img` role when it has an empty alt. When an `img` has `alt=""` [it's considered presentational](https://www.w3.org/TR/html-aam-1.0/#details-id-54) and a presentational image [is not allowed any roles](https://www.w3.org/TR/html-aria/#el-img-empty-alt).

**Comment by WilcoFiers** [comment]
Definitely Steve's right, putting role=img on it will cause the image to get added back into the accessibility tree. Would like to know if screen readers ignore it in that case. I'm guessing they don't, or at least not all of them will. But if this gets ignored consistently I think we should change it.

@DavidMacDonald what problem does this fix in VO?

**Comment by straker** [comment]
Testing the following code:

```html
<img role="img" src="https://random.dog/0886de63-9a5d-41c5-b750-4e7633f63ce1.jpg" alt="">
```

It would appear all browsers ignore the role on the image and keep it presentational.

* Safari / VO - ignores the image
* FireFox / NVDA - ignores the image
* Chrome / JAWS - ignores the image
* Chrome / IE11 - ignores the image

**Comment by scottaohara** [comment]
assuming the issue at hand here was that VoiceOver used to treat `<img src=...svg>` as a "group".  This is no longer the case though, so the need to declare the explicit `img` role wouldn't be necessary

**Comment by straker** [comment]
@DavidMacDonald Going to close this issue as even with `role=img` screen readers ignore the image element when the alt is empty. Axe-core correctly flags the element as not allowed any roles per spec. Let us know if you have any other questions.
