### ISSUE TITLE
Incorrectly reporting aria-sort is not allowed on TH elements

### ISSUE THREAD

**Issue by SiTaggart** [dequelabs/axe-core#283]
Applying `aria-sort="ascending"` or `aria-sort="descending"` to a `th` element will throw a "Ensures ARIA attributes are allowed for an element's role" error.

TH has [an implicit role of `columnheader`](http://w3c.github.io/html-aria/#th) or `rowheader`, which are both [allowed to have `aria-sort`](http://w3c.github.io/html-aria/#index-aria-columnheader)

**Comment by jkva** [comment]
We can reproduce; this issue is related to #290.

**Comment by dylanb** [comment]
duplicate @SiTaggart can you see whether the changes committed for #290 fix your issue?
