### ISSUE TITLE
On using analyse in chrome for a HTML ,its not analyzing the code

### ISSUE THREAD

**Issue by ankitatalgotra123** [dequelabs/axe-core#2834]
[

Expectation: << Describe what you expect the product to do >>

Actual: << Describe what the product actually does >>

Motivation: << Describe why you want the behavior to be changed >>

<pre><code>
axe-core version: X.Y.Z
axe-webdriver, extension or other integration version: X.Y.Z

Browser and Assistive Technology versions

For Tooling issues:
- Node version: XX  
- Platform:  
</code></pre>

**Comment by dylanb** [comment]
No details
