### ISSUE TITLE
Localisation partially fails

### ISSUE THREAD

**Issue by gyp5y** [dequelabs/axe-core#2839]
When building with --lang=<locale> rules translations are applied well but "checks" are generating in en.

Expectation: "checks" section from locale file is used

Actual: EN locale is used for "checks" section for any locale

axe-core version: 4.1.3

For Tooling issues:
- Node version: v15.8.0
- Platform: Mac

**Comment by WilcoFiers** [comment]
Yikes! Thank you for reporting. We'll see what's up with that. Apologies!

**Comment by padmavemulapati** [comment]
Validated with latest code base of axe-core, 
executed command: `npm run build -- --lang=ja` 
and validated  with `axe.ja.js` file - the out put is like below:
![image](https://user-images.githubusercontent.com/47409579/113698118-bd2c1680-96f1-11eb-8769-a2d8b600073c.png)
