### ISSUE TITLE
scanning team not accepting this library its not free to use

### ISSUE THREAD

**Issue by manohard** [dequelabs/axe-core#2852]
HI team,

please help me is there any MIT license or any other free license of this library without this i cant go ahead.

thanks and regards,
manohar.

Product: <<axe-core | axe Extension | axe Linter>>

Expectation: << Describe what you expect the product to do >>

Actual: << Describe what the product actually does >>

Motivation: << Describe why you want the behavior to be changed >>

<pre><code>
axe-core version: X.Y.Z
axe-webdriver, extension or other integration version: X.Y.Z

Browser and Assistive Technology versions

For Tooling issues:
- Node version: XX  
- Platform:  
</code></pre>

**Comment by dylanb** [comment]
no, we only have MPL2 license
