### ISSUE TITLE
Element's background color could not be determined due to a pseudo element issue

### ISSUE THREAD

**Issue by m-harsovski** [dequelabs/axe-core#2856]
Hi, guys! I have a problem as "Element's background color could not be determined due to a pseudo element"..
[
<img width="354" alt="Screenshot 2021-03-31 at 15 37 30" src="https://user-images.githubusercontent.com/57360535/113145388-06362380-9237-11eb-976f-537420524a04.png">
](url)

i should put overlay 60% to image  using 
.banner {
       &:after {
        position: absolute;
        top: 0;
        right: 0;
        left: 0;
        bottom: 0;
        background: rgba(siteColor(vam-black), 0.6);
        content: '';
    }
}
  
and axe tool says that error.
Could you please help me?

**Comment by straker** [comment]
Thanks for the issue. Axe-core will mark elements as needs review if they have any ancestor with a pseudo element with a background color. Due to lack of browser capability, we can't know what the size of the pseudo element is so have to resort to letting you manually check that the contrast works.
