### ISSUE TITLE
Runtime issue: Unknown Error

### ISSUE THREAD

**Issue by CurtisKimball** [dequelabs/axe-core#2858]
<< Please describe how you encountered this issue >>
I accessed the page, 
https://perkinsaccess.org/proof-accessible-websites-can-be-beautiful-too/?utm_medium=email&utm_campaign=March%20Newsletter%20New%20website%20announcement%20CURRENT%20MARCH%2024&utm_content=March%20Newsletter%20New%20website%20announcement%20CURRENT%20MARCH%2024+CID_9d7f73e3dacd3bb673ac1703e7934b74&utm_source=Perkins%20Message&utm_term=Go%20behind%20the%20scenes%20on%20our%20new%20site
entered inspect
chose axedev tools
and chose run on full page
then I got the "Sorry there was a problem with Axecore" and no data on the page.
I signed in and  tried to re-run it, but got the same result.

I just went back and hit "rerun automatic test" again when I was copying the URL and it worked this time.

axe-core version: `4.1.3`
axe-extension version: `4.8.6`

```

```

**Comment by straker** [comment]
Thanks for the issue. I tested with axe-core itself and it ran without issues, so something about the extension is having the issue.

**Comment by CurtisKimball** [comment]
Ok, like I noted, it did run eventually.

Am I missing it or does the tool no longer show the number designation of what WCAG criterion the errors are related to?

-Curtis

Curtis Kimball | AVP Digital Accessibility & Compliance, and Lead EIT Coordinator | Southern New Hampshire University
33 South Commercial St, Manchester, NH 03106
Office: 603.314.1463 | snhu.edu<https://www.snhu.edu>

[/Users/c.kimball/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_489503439]

From: Steven Lambert ***@***.***>
Reply-To: dequelabs/axe-core ***@***.***>
Date: Wednesday, March 31, 2021 at 11:12 AM
To: dequelabs/axe-core ***@***.***>
Cc: Curtis Kimball ***@***.***>, Author ***@***.***>
Subject: Re: [dequelabs/axe-core] Runtime issue: Unknown Error (#2858)


Thanks for the issue. I tested with axe-core itself and it ran without issues, so something about the extension is having the issue.

**Comment by dylanb** [comment]
Cannot reproduce either

> Ok, like I noted, it did run eventually. Am I missing it or does the tool no longer show the number designation of what WCAG criterion the errors are related to?

open the "more details" section up to reveal the tags

![Screen Shot 2021-04-05 at 2 57 05 PM](https://user-images.githubusercontent.com/79245/113613417-360e6e00-961f-11eb-8673-f506b7fd8771.png)
