### ISSUE TITLE
presentation-role-conflict should not error when element has no implicit role

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core#2859]
The following code should not throw a presentation-role-conflict error as the element does not have an implicit role.

```html
<div role="none" tabindex="1"></div>
```

**Comment by padmavemulapati** [comment]
Validated with latest develop branch code base,
observed `presentation-role-conflict` is appearing in `inapplicable` when tested with
`<div id="inapplicable1" role="presentation">Test</div> `
![image](https://user-images.githubusercontent.com/47409579/123645619-1ebcd680-d844-11eb-9802-857ed607606b.png)
