### ISSUE TITLE
Incorrectly reporting "links have discernible text"

### ISSUE THREAD

**Issue by WW3** [dequelabs/axe-core#286]
axe does not recognize svg title node as legit accName

**Comment by marcysutton** [comment]
Title wasn't always exposed without `aria-labelledby`. @dylanb do you know if that was holding up support axe-core? I know that Chrome in particular has since fixed that discrepancy.

**Comment by dylanb** [comment]
I believe we will need to include svg elements in the selector for the image-alt rule and also have logic in the accessible name calculation code in order to fix this

**Comment by dylanb** [comment]
This is a duplicate of https://github.com/dequelabs/axe-core/issues/20
