### ISSUE TITLE
`<footer>` should not be considered a landmark role in `<div role="main">`

### ISSUE THREAD

**Issue by myasonik** [dequelabs/axe-core#2862]
**Product**: axe-core

**Expectation**:
These two examples should give them same results: neither should be a problem.
```html
<div role="main">
	<footer>test</footer>
</div>
```
```html
<main>
	<footer>test</footer>
</main>
```

**Actual**:
The [first example](https://cdpn.io/myasonik/debug/bGgqEEE/yPMJjREmeBDM) throws an error of `landmark-contentinfo-is-top-level` while the [second example](https://cdpn.io/myasonik/debug/NWdpxGx/bYMdypNgJDLr) has no errors.

<pre><code>axe-core version: 4.1.2
</code></pre>

**Comment by clottman** [comment]
Looking at the [WAI-ARIA practices on W3](https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/landmarks/contentinfo.html), there is a difference in behavior described for a particular set of html5 elements (including the `main` element but not including `div role='main'`). 

Based on that, it seems to me that the difference in behavior between these two examples is actually expected. 

On the [ARIA landmarks contentinfo example](https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/landmarks/contentinfo.html) see the tab: "Aria Techniques" which reads just:
> A role="contentinfo" attribute is used to define a contentinfo landmark.

and the tab "HTML5 Techniques" on the same page which reads:
> 
>    The HTML5 footer element defines a contentinfo landmark when its context is the body element.
>    The HTML5 footer element is not considered a contentinfo landmark when it is descendant of any of following elements:
>        article
>       aside
>        main
>        nav
>        section

**Comment by clottman** [comment]
The html-aria spec says roles apply though so never mind.
https://www.w3.org/TR/html-aria/#el-footer 
> footer	If not a descendant of an article, aside, main, nav or section element, or an element with role=article, complementary, main, navigation or region then role=contentinfo. Otherwise no corresponding role.

**Comment by WilcoFiers** [comment]
I think Cassey's right, but we should probably do some screen reader testing.

**Comment by straker** [comment]
Testing results for

```html
<div role="main">
	<footer>test</footer>
</div>
```

* Safari / VO - treats as contentinfo landmark (the rotor menu lists it as a landmark)
* IE11 / JAWS - treats it as a contentinfo landmark (going to next region <kbd>R</kdb> announces as "test content information")
* Chrome / JAWS - treats it as a contentinfo landmark (going to next region <kbd>R</kdb> announces as "test content information")
* Firefox / NVDA - treats it as a contentinfo landmark (going to next region <kbd>D</kdb> announces as "main  landmark, contentinfo landmark test")
