### ISSUE TITLE
heading-order rule throws when frame with heading is the first element

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2868]
Haven't looked at why, but I noticed this setup throwing an the following error:
https://github.com/dequelabs/axe-core/blob/develop/lib/checks/navigation/heading-order-after.js#L104

```html
<!-- index.html -->
<!DOCTYPE html>
<html lang="en">
  <iframe src="frame.html"></iframe>
  <h2>Hello</h2>
  <script src="../axe.js"></script>
  <script>
    window.addEventListener('load', function() {
      axe.run(document, function(err, res) {
        console.log(err);
      });
    });
  </script>
</html>
```

```html
<!-- frame.html -->
<script src="../axe.js"></script>
<h1>hello</h1>
```

**Comment by padmavemulapati** [comment]
Validated with  latest axe-core code base, 
Not seeing `heading-order` issue when used `iframe` as the first element, even the heading order is altered.
Test snippet:
```index1.html
<iframe title="frame" src="frame1.html"></iframe>
  <h2>Hello</h2>
  <script src="/axe.js"></script>
```
```frame1.html
<script src="/axe.js"></script>
<h1>hello</h1>
```

![image](https://user-images.githubusercontent.com/47409579/116075234-524a7b80-a6b0-11eb-8862-da5c64ae983a.png)
