### ISSUE TITLE
Webkit browsers (phantom, safari) use 100% CPU when analyzing heavy sites like getbootstrap.com/css

### ISSUE THREAD

**Issue by jdat82** [dequelabs/axe-core#288]
Hi,

Running axe2 on very heavy pages in webkit browsers make webkit go crazy to 100% CPU. Analysis seems to never end even after several hours.

One such page is: [getbootstrap.com/css](getbootstrap.com/css)

Here is a very simple script I wrote to reproduce the problem in safari devtools:

```js
var axeScript = document.createElement('script');
axeScript.src = 'https://cdnjs.cloudflare.com/ajax/libs/axe-core/2.1.7/axe.js';
axeScript.onload = runAxe;
document.body.appendChild(axeScript);

/////////////

function runAxe() {
    try {
        console.log('Running axe…');
        window.axe.run(document, {}, function(err, results) {
            console.log('Axe runned');
            if(err) console.error('Axe error:', err);
            console.log('Axe results:', results);
        });
    } catch (ex) {
        console.error('Axe exception:', ex);
    }
}
```

Are you aware of this issue and much important do you know any workaround ?

Thanks a lot.

**Comment by dylanb** [comment]
@jdat82 this is because these browsers do not implement document.elementsFromPoint and we have to do a lot of calculations to polyfill that API

https://developer.mozilla.org/en-US/docs/Web/API/Document/elementsFromPoint

**Comment by marcysutton** [comment]
One workaround would be to disable the color contrast rule, (the one requiring `document.elementsFromPoint`):

```
let config = {
  "rules": {
    "color-contrast": { enabled: false } 
  }
}
axe.run(context, config, function(err, callback)
```

**Comment by jdat82** [comment]
Thanks everyone for your quick and precise answers. 

Have you ever tried to use axe-core with chrome in headless mode ? I'm going to test it real soon but I'm interested by any feedback.
