### ISSUE TITLE
Runtime issue: Unknown Error

### ISSUE THREAD

**Issue by lsbweb** [dequelabs/axe-core#2882]
<< Please describe how you encountered this issue >>

axe-core version: `4.1.3`
axe-extension version: `4.8.6`

```

```

**Comment by straker** [comment]
Do you have more information about the unknown error? Without more info we won't be able to do anything about this issue.

**Comment by lsbweb** [comment]
May be able to replicate it.


  1.  Installed in Chrome dev tools
  2.  Created a new account
  3.  Login to new account
  4.  Scan all of page
  5.  Review Issues Today (Yesterday there was an error, which prompted me to message you)

Looks like it may be remedied.

Thanks!

-cassandra

From: Steven Lambert ***@***.***>
Reply-To: dequelabs/axe-core ***@***.***>
Date: Wednesday, April 21, 2021 at 2:24 PM
To: dequelabs/axe-core ***@***.***>
Cc: Cassandra Marshall ***@***.***>, Author ***@***.***>
Subject: Re: [dequelabs/axe-core] Runtime issue: Unknown Error (#2882)

EXTERNAL EMAIL: This email came from someone outside our company. Before you reply or click that link, it’s a good idea to make sure you know this person and you’re not sending them any confidential information.

Do you have more information about the unknown error? Without more info we won't be able to do anything about this issue.
