### ISSUE TITLE
Axe-Core does not see global styling when analyzing popup modal

### ISSUE THREAD

**Issue by FearsomeFurball** [dequelabs/axe-core#2883]
Product: axe-core

Expectation: On pop-up modals, where the background color is applied globally, I expect Axe to recognize the global style applied to the modal when analyzing. 

Actual: A violation is shown related to color contrast between the background/foreground. 
Violation: 
    Elements must have sufficient color contrast
    Description: Ensures the contrast between foreground and background colors meets WCAG 2 AA contrast ratio thresholds
    Help: Elements must have sufficient color contrast
    Help URL: https://dequeuniversity.com/rules/axe/4.1/color-contrast?application=axeAPI
    Impact: serious
    Tags: cat.color, wcag2aa, wcag143

Html:
<div _ngcontent-nsn-c135="" class="content-header">Last 4 Digits</div>

Selector(s):
.delete-card-table-container[_ngcontent-nsn-c135=""]:nth-child(2) > .delete-card-table-item[_ngcontent-nsn-c135=""]:nth-child(1) > .content-header[_ngcontent-nsn-c135=""]

Html:
<div _ngcontent-nsn-c135="" class="content-header">Expires</div>

Selector(s):
.delete-card-table-container[_ngcontent-nsn-c135=""]:nth-child(2) > .delete-card-table-item[_ngcontent-nsn-c135=""]:nth-child(2) > .content-header[_ngcontent-nsn-c135=""]

![image](https://user-images.githubusercontent.com/19674057/115761290-cfe85180-a367-11eb-98e8-5f29c97a7cbd.png)

*NOTE* When we manually change the background color to white for the element, then the violation is not reported. But this is a global style. 

![image](https://user-images.githubusercontent.com/19674057/115761490-ff975980-a367-11eb-9196-77a2dd7d3302.png)

Motivation: To suppress false violations

<pre><code>
axe-core version: 4.1.1
Selenium.Axe version: 2.0.3

Browser and Assistive Technology versions

For Tooling issues:
- Node version: XX  
- Platform:  
</code></pre>

**Comment by straker** [comment]
Thanks for the issue. Is the page in question public that I could take a look at it? Color contrast is a difficult one to debug without seeing it all on the page.

**Comment by FearsomeFurball** [comment]
Unfortunately this page only exists in our dev environment. It's a new ADA compliant site that we are creating, and is in the early stages.

**Comment by straker** [comment]
I see. Would it be possible to recreate the issue with a codepen or something similar?

**Comment by FearsomeFurball** [comment]
I don't think that will be possible. Let me know if that blocks you from going forward.

**Comment by straker** [comment]
Ya, unfortunately without being able to see the problem it blocks me from working on it.

**Comment by straker** [comment]
Going to close this issue as without a reproducible test case there's nothing we can do about it. Please reopen if one can be provided.
