### ISSUE TITLE
Allow access to axe standards

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2889]
Axe standards are a very useful tool. It would be great if there was a way to get the standards information out of axe-core. Something as simple is this could be sufficient.

```js
axe.getStandard()
```

**Comment by padmavemulapati** [comment]
Verified with the latest axe-core-develop branch code base, with 4.2.0 version, 
Now it is allowing `getStandards` from `utils`
running a command from console, ` await axe.utils.getStandards('ariaAttrs');` 
will result,
![image](https://user-images.githubusercontent.com/47409579/120323186-dcff4580-c302-11eb-8494-c28558655f52.png)
