### ISSUE TITLE
axe reporters should return instead of using callback

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2890]
Axe reporters for some reason are not expected to return the report. Instead they pass them into a callback. This allows reporters to be async. As far as I'm aware none of our reporters actually are async, so this seems unnecessary.

The big drawback of callbacks on the reporter is that axe-core is that they can never be used in a function that returns synchronously, notably `axe.runVirtualRule()`. This is an unfortunate and unnecessary restriction. I think we should make the following changes to axe-core:

1. If a reporter only has 2 arguments, use the return value as the report. The return type can either be the actual report, or a thenable. In case of a thenable we await it until the report is produced. That way we continue to allow async reports, but we do so through the return type.
2. Migrate all existing reporters over to returning their result
3. Use a reporter in axe.runVIrtualRule. If the reporter returns a promise, throw an error, since runVIrtualRule is only intended for running synchronous tests.
4. We deprecate callbacks in reporters, and remove support for them in axe-core 5.0

**Comment by padmavemulapati** [comment]
devTask
