### ISSUE TITLE
Deprecate "brand" in axe.configure

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2891]
Up until about a year ago axe-core used `axe.configure({ branding: { brand }})` to distinguish results produced by Attest products from results produced with axe. This is no longer necessary, since all Attest products have been renamed to axe DevTools. This should let us deprecate the `brand` property. As we're doing that, we might also want to consider changing the "branding" API. Maybe it could just be `axe.configure({ application })`?

**Comment by WilcoFiers** [comment]
Talked to @dylanb about this. What I think we should do is to deprecate `branding.brand`, and no longer use it to generate help URLs. It can only ever be `axe`, anything configured with `branding.brand` will be ignored as of axe-core 4.3. In addition, I think we should update `axe.configure({ branding })` and allow `branding` to be a string, if it is, it is used as the application key in the help URL.

**Comment by padmavemulapati** [comment]
Validated with the latest develop branch axe-core code based,
```
// previously
axe.configure({
  branding: { application: 'axe' }
})
// current
able to configure `branding` with specified string.
axe.configure({ branding: 'axe' })
```
for ex: if I pass `await axe.configure({ branding: 'axe' });`
I am seeing helpURL: 
![image](https://user-images.githubusercontent.com/47409579/141986507-c8359a3b-42e0-4fef-a0f4-b4267c332c41.png)

If I pass `await axe.configure({ branding: 'Padma' });` also 
I am seeing helpURL with string "Padma"
![image](https://user-images.githubusercontent.com/47409579/141986694-806fbff7-3044-4280-812b-18f5dfe8d2f8.png)
