### ISSUE TITLE
empty-table-header is documented as being able to fail despite specifying reviewOnFail: true

### ISSUE THREAD

**Issue by dbjorge** [dequelabs/axe-core#2894]
[rule-descriptions.md](https://github.com/dequelabs/axe-core/blob/v4.2.0/doc/rule-descriptions.md#L76) documents the new `empty-table-header` rule as having Issue Type `failure, needs review`, but I think this should probably just be `needs review` based on the rule's config specifying [`"reviewOnFail": true`](https://github.com/dequelabs/axe-core/blob/v4.2.0/lib/rules/empty-table-header.json#L5) and the rule only having pass/incomplete [integration test cases](https://github.com/dequelabs/axe-core/blob/v4.2.0/test/integration/rules/empty-table-header/empty-table-header.json).

Product: axe-core

Expectation: Docs should match config/tests

Actual: Docs and config/tests don't match

Motivation: We'd like to understand whether the docs vs the implementation are the intended behavior, so we can adjust our documentation/ruleset accordingly in Accessibility Insights

<pre><code>
axe-core version: 4.2.0
axe-webdriver, extension or other integration version: n/a

Browser and Assistive Technology versions: n/a

For Tooling issues:
- Node version: n/a
- Platform:  n/a
</code></pre>

**Comment by WilcoFiers** [comment]
Thanks for the report @dbjorge! We'll be sure to fix that.

**Comment by straker** [comment]
Fixed in #2986 and #2987
