### ISSUE TITLE
Implicit node role ambiguously inferred when multiple options available

### ISSUE THREAD

**Issue by jkva** [dequelabs/axe-core#290]
Currently, given a node where multiple implicit roles are available, such as a `th` with multiple valid implicit roles ('cell', 'gridcell', 'rowheader', 'columnheader'), the first available implicit role is returned.

This causes a problem in cases where the expected role is implicitly defined by the aria attributes present on the node.

Example:

`<th aria-sort="descending">`

While the above example is valid, currently `cell` is returned as the implicit role, and aXe correctly marks this as error, since a `cell` cannot have `aria-sort`.

In order to fix this, aXe needs to determine the optimal combination of valid aria-attributes and possible implicit roles, and return this role.

**Comment by marcysutton** [comment]
Thanks for working on this issue! I look forward to seeing what you come up with. :)
