### ISSUE TITLE
How do I get moderate issues in violations?

### ISSUE THREAD

**Issue by cywang16** [dequelabs/axe-core#2911]
Product: axe-core

Expectation: axe.run should return the same issues in violations as axe browser extension

Actual: I only see serious issues in violations

Motivation: I hope to get the same issues in automation as I get in axe extension. My code is as follows.

<pre><code>
axe-core version: 4.2.0
  const config = {
    runOnly: {
      type: "tag",
      values: ["wcag2a", "best-practice"],
    },
  }
  axe.run(homeNode.getRootNode(), config, (err, { violations }) => {
    expect(err).toBe(null)
    for (let v of violations) {
      console.log(JSON.stringify(v, null, 2))
    }
    expect(violations).toHaveLength(0)
    done()
  })
</code></pre>

**Comment by WilcoFiers** [comment]
You're only running the `wcag2a` and `best-practice` tags. The browser extension by default runs `wcag2a`, `wcag2aa`, `wcag21a`, `wcag21aa`, and depending on your settings `best-practice` may be on or off.

**Comment by WilcoFiers** [comment]
I think this is addressed. I'm closing the issue.
