### ISSUE TITLE
Deprecate autocomplete-appropriate check

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2912]
Research from ACT has shown that autocomplete-appropriate is no longer appropriate. No modern browser cares what the type os on an input element to determine whether or not to apply `autocomplete`. Because of that, I'd like to deprecate autocomplete-appropriate and remove it from the autocomplete-valid rule.

**Comment by clottman** [comment]
@WilcoFiers are you looking for anything in particular in order to deprecate it, or would removing it from the codebase be what you're looking for? 

Either way I'd be happy to take a look at this.

**Comment by straker** [comment]
@clottman Thanks for looking into it. 

To deprecate a check you'll just need to add `deprecated: true` to the checks `.json` metadata file and mark the commit as a `feat` (we only deprecate in feature PRs). We can't remove it from the rule for now, so it'll still run until we're ready to release the next feature version.

**Comment by padmavemulapati** [comment]
Validated with latest code from develop branch
`autocomplete-appropriate` is not available and it is deprecated.
We can see with the latest change, for the couple of test snippets, where one is for `auto-complete` and the other is for `autocomplete-appropriate`(we can see both violations in old axe-core rule 4.1.1)
1. `<input autocomplete="badterm" id="fail-auto-complete" />`
2. `<input type="NUMBER" autocomplete="email" id="fail-auto-appropriate" />`
