### ISSUE TITLE
Button names not being recognised in axe DevTools Extension

### ISSUE THREAD

**Issue by kellyvanderveen** [dequelabs/axe-core#2915]
Product: axe-core

Expectation:
We (booking.com/attractions) would like our button names to pass the accessibility checks by the axecore tooling.

Actual: 

Following an analysis of the Booking.com Attractions website (http://booking.com/attractions) axecore, Google’s Lighthouse and PageSpeed reports flag that buttons do not have an accessible name (https://web.dev/button-name/). This issue is not limited to our Attractions page, but also occurs on other pages that use a similar header (e.g. flights.booking.com).

The recommended suggestion from Google's documentation is to ensure that buttons have an aria-label attribute providing information to screen readers. The button elements have an aria-describedby attribute referencing a tooltip that contains text describing the button elements. For screen readers, this implementation should enable them to read the tooltip information. However on the Lighthouse report it does not pass the checks. As such, booking.com/attractions and other pages’ accessibility scores are penalised.

We've raised this on[ Lighthouse's bug reporting](https://github.com/GoogleChrome/lighthouse/issues/12433) first, but were recommended to report upstream.

Motivation:
As mentioned above not passing the checks penalises our accessibility scores.

axe-core version: v4.8.6 axe DevTools Extension
Chrome: Version 90.0.4430.93 (Official Build) (x86_64)

Thanks in advance, in case more information is required please let me know.

**Comment by WilcoFiers** [comment]
@kellyvanderveen aria-describedby does not provide an accessible name. You'll need to use aria-labelledby instead. In the accessibility API, an element must have a name, they can have a description in addition to having a name, but not giving them a name, and trusting that the description will be picked up instead is not going to be reliable.

**Comment by kellyvanderveen** [comment]
@WilcoFiers thanks for your swift response! That makes sense, I'll forward your feedback to our developers.
