### ISSUE TITLE
axe-linter doesn't appear to be linting

### ISSUE THREAD

**Issue by markgoho** [dequelabs/axe-core#2916]
Product: axe Linter

Expectation: Lint

Actual: Let a11y errors go unchecked

Motivation: fixing a11y is important to my job

<pre><code>
axe-linter extension version: 4.1.1

Browser and Assistive Technology versions

For Tooling issues:
- Node version: 12
- Platform:  Windows
</code></pre>

![image](https://user-images.githubusercontent.com/9759954/117028058-53406600-accb-11eb-904d-fcf27f89f6df.png)

Just installed the linter, added an image tag without an alt attribute and there is no error. This is an Angular v11 project.

**Comment by straker** [comment]
Thanks for the issue. Unfortunately axe-linter does not support Angular at the moment. As we continue to develop it we may include it.

**Comment by markgoho** [comment]
@straker that's really unfortunate to hear, although I get that you can't support every framework that exists

I would encourage you to update your documentation to be very clear about not supporting Angular since it's currently implied that you do, i.e. you say you support linting of `.html` files and that's what Angular templates are written in.

**Comment by straker** [comment]
That makes sense. I'm going to close this issue but I'll look into updating the docs for more clarity
