### ISSUE TITLE
Test axe-core against ARIA practices

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2918]
We have from time to time had false positives because we've overlooked different ARIA patterns. Axe-core would be better if we proactively tested it against the ARIA practices. We could perhaps do this in a similar way to how we test ACT rules.

Here is the repo we'd have to check out https://github.com/w3c/aria-practices

**Comment by Malvoz** [comment]
This issue should be closed per https://github.com/dequelabs/axe-core/pull/3144.

**Comment by WilcoFiers** [comment]
Yes it should be. Thanks @Malvoz.
