### ISSUE TITLE
Add nodeIndex property to DqElement

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#2938]
Required for #2936

In order to properly sort results in `finishRun`, which does not have access to elements, we will need to know the relative order of each result to the frames on a page. We can do this by adding a nodeIndex property to DqElement. Since the virtual tree is constructed in order, it might be easiest to do this by keeping a simple counter and assigning the current value to the virtual node when it is created. That way nodes higher up the tree have a lower number, and we can sort results based on that.

**Comment by padmavemulapati** [comment]
Validated with latest develop branch code base, 
test snippets:
```
<div id="target"></div>
  <div id="foo">\n      <div id="bar"></div>\n    </div>
  <div id="foo">\n      <div id="bar"></div>\n    </div>
  <svg aria-label="foo" id="target"></svg>
  <div id="target" class="bar">Hello!</div>
  <main id="main"></main><iframe id="iframe"></iframe>
  ```
![image](https://user-images.githubusercontent.com/47409579/123646785-25981900-d845-11eb-85b2-66354833e947.png)
