### ISSUE TITLE
id attribute value must be unique - false negative

### ISSUE THREAD

**Issue by maverickandy** [dequelabs/axe-core#294]
Whenever I run a scan on AIDS.gov (more specifically this page: https://www.aids.gov/hiv-aids-basics/hiv-aids-101/signs-and-symptoms/) I get ' id attribute value must be unique'

Looking at the results it gives it shows this:
<a href="/hiv-aids-basics/just-diagnosed-with-hiv-aids/find-care-and-treatment/locating-hiv-aids-services/" id="anch_45">Locating HIV/AIDS Services</a>
<a href="/hiv-aids-basics/just-diagnosed-with-hiv-aids/find-care-and-treatment/addressing-cost-barriers/" id="anch_46">Addressing the Cost of Care</a>
<a href="/hiv-aids-basics/just-diagnosed-with-hiv-aids/find-care-and-treatment/navigating-the-system/" id="anch_47">Navigating the System</a>

Those IDs are all incremental to each other and seem to be unique. Is this an error or am I looking at this wrong?

A

**Comment by WilcoFiers** [comment]
Hey Andy. Yep, you are missing something :) The IDs are used twice, first in the header, and then again in the footer. Hope that helps!

**Comment by maverickandy** [comment]
Hi @WilcoFiers,

Not sure if I follow. I can only see them in the footer. If I open the HTML source of the page and take the example of "Locating HIV/AIDS Services", I can see id="anch_45" on line 803 (in the footer). I can't seem to locate the 2nd one though. Could you let me know where I can find it?

Thanks for your swift reply!
A

**Comment by WilcoFiers** [comment]
@maverickandy You can find the other one in the mega menu.

The easiest way to spot things like this is to do: `document.querySelectorAll('#anch_45')` in ithe console. You'll see both of them.

**Comment by dylanb** [comment]
@maverickandy what are you running the scan in?

**Comment by maverickandy** [comment]
Thanks a lot for your help Wilco

@dylanb, I'm using rocketvalidator.com to test URLs however I'm currently implementing axe-core in my own tool. According to rocketvalidator, they use axe-core as well.

**Comment by dylanb** [comment]
@maverickandy  Look at the relatedNode information in the results, that contains selectors for the related elements

**Comment by maverickandy** [comment]
@WilcoFiers 
Forgive my ignorance but I still only see 1 item. I've loaded the page, ctrl+a, inspect element and then typed document.querySelectorAll('#anch_45') in the console. It only returns 1 item. What do you use to check this? Is the process the same?

@dylanb what tools are you using to check? I don't understand how/where I should use relatedNode?

**Comment by dylanb** [comment]
@maverickandy if you use the aXe extension, you will notice that in the details for each issue, it lists the set of nodes that are "related" to the node being flagged. For the duplicate ID issue, this will list all the nodes that have the same ID as the failed node.

This same information is available in the results object returned by the API. If you (or Rocket Validator) is using the API, then you (or Rocket Validator) can print out those selectors so you can more easily identify the related elements.

**Comment by marcysutton** [comment]
For some additional debugging info: I also get an array with 2 items when I run `document.querySelectorAll('#anch_45')` on that page using the JavaScript console. You can also reproduce it by opening the Elements inspector and using the "Cmd + F" (on a Mac) to find the ID string, which brings up both elements.
