### ISSUE TITLE
Ensures ARIA attributes are allowed for an element's role` error on DatePicker field is false positive

### ISSUE THREAD

**Issue by rosibaj** [dequelabs/axe-core#2940]
Product: Axe DevTools - axe-core 4.2.0; Chrome extension

Expectation: A false positive has been identified on a date-picker field. 
'
Actual: Critical error `Ensures ARIA attributes are allowed for an element's role` is presented, but this is wrong. It is allowed for a date picker to have aria elements.  I have found logs of similar bugs:
- https://github.com/microsoft/fluentui/issues/15332 
- https://github.com/microsoft/fluentui/issues/14464 

![image](https://user-images.githubusercontent.com/15824252/118518373-0f575300-b706-11eb-8891-f9b808bb0595.png)

Motivation: This is a false positive; there is no indication that a date-picker should not have an aria label. in contrast, WAVE does not report this error. 

<pre><code>
axe-core version:  4.2.0;
axe-webdriver, extension or other integration version: 

axe DevTools - Web Accessibility Testing
4.9.3
Accessibility Checker for Developers in Chrome
ID: lhdoppojpmngadmnindnejefpokejbdd

Browser and Assistive Technology versions 
Chrome Version 90.0.4430.85 (Official Build) (64-bit)

For Tooling issues:
- Platform:  Windows

**Comment by straker** [comment]
Thanks for the issue. I believe this is related to #2933 and #2926 and should be fixed by #2929 and #2935

**Comment by padmavemulapati** [comment]
Verified as part of https://github.com/dequelabs/axe-core/issues/2933

**Comment by straker** [comment]
Thanks @padmavemulapati. Closing this ticket as it's a duplicate and we have a fix merged.
