### ISSUE TITLE
Update documentation to identify what languages axe supports

### ISSUE THREAD

**Issue by mgifford** [dequelabs/axe-core#2957]
In axe-core 3.4, axe supported "English (default), French, German (limited), Japenese, Spanish (new), Brazillian Portuguese (new)" - note that "Japenese" should be spelled "Japanese" & "Brazillian" should be spelled "Brazilian". 
  https://www.deque.com/blog/announcing-axe-core-3-4/

Looks like we're at 4.9.3, but I don't see what languages are supported in the documentation I could find. Is it still the same as it was in 3.4. Might just be able to point to a README in https://github.com/dequelabs/axe-core/tree/develop/locales to ensure that you've got an ongoing document to refer to. 

Also, unrelated, but often errors go to https://dequeuniversity.com/ which is great. But would be great if that were also multi-linugal. 

Thanks!

**Comment by WilcoFiers** [comment]
@mgifford Thanks for the feedback. I agree, we should probably include a list of supported languages in our documentation somewhere.

As for localising Deque University; we do have it localised in Japanese, and there are select parts localised in a few other languages too. There is a lot of work in that though, and so we can only localise the content that we're confident we can keep up to date.

**Comment by mgifford** [comment]
It's no small undertaking. I totally understand that. On the Japanese, How would I link to the Japanese content? I can see a list of individual rules in Japanese if I click into items in this list https://dequeuniversity.com/rules/axe/4.2 but can't see a list in Japanese.  

I'd like to link to it here https://github.com/accessibility/multilingual/blob/master/%E6%97%A5%E6%9C%AC%E8%AA%9E.md

I'm just beginning to appreciate how terrible non-English support is for accessibility documentation.
