### ISSUE TITLE
aria-text example shows different scenarios

### ISSUE THREAD

**Issue by connorjclark** [dequelabs/axe-core#2959]
https://dequeuniversity.com/rules/axe/4.2/aria-text

The example changes the content to not include a link, which changes things enough to make the issue go away but is not useful as an example because it changes content.

Instead, what if the "Correct" solution had an anchor element (just like the failing example) but used `role=label` (which I think can have focusable descendants).

**Comment by WilcoFiers** [comment]
Thank you for the suggestion. Do you have a specific example you'd like to propose? That would be great.
