### ISSUE TITLE
Restore autocomplete-valid act-mapping test

### ISSUE THREAD

**Issue by clottman** [dequelabs/axe-core#2960]
Related to https://github.com/dequelabs/axe-core/pull/2917
When autocomplete-appropriate was changed, the act-mapping test for that had to be removed because axe-core got ahead of the ACT tests. Once ACT has been updated, we should put back the ACT test for autocomplete-appropriate.

**Comment by WilcoFiers** [comment]
This can be resolved when https://github.com/act-rules/act-rules.github.io/pull/1583 is merged.

**Comment by straker** [comment]
Closed via #2997
