### ISSUE TITLE
Contrast issues of button with pseudo element styles

### ISSUE THREAD

**Issue by davodavodavo3** [dequelabs/axe-core#2966]
Product: Axe Extension, LH

**Expectation:** 
LH/Axe should recognize that there is a :before pseudo element with background color of #000000 and in this case the button text contrast is enough 21.

**Actual:** 
Background and foreground colors do not have a sufficient contrast ratio.
Element has insufficient color contrast of 1.07

LH/Axe are checking directly the button styles where background color is transparent, and they says that contrast of white text is not enough.
![image](https://user-images.githubusercontent.com/10462563/120120603-4bcb8a00-c1af-11eb-9f68-dceec8a46293.png)

Motivation: Because it's showing wrong information

Browser and Assistive Technology versions
Affected Channels: DevTools
Axe version: 4.1.2
Lighthouse version: 7.2.0
Chrome version: 91.0.4472.77
Node.js version:
Operating System: Windows 10

**Comment by davodavodavo3** [comment]
Steps to reproduce
Run LH Accessibility audit on https://theskinexperts.co.uk
Check Contrast issues related to the black button with white text

**Comment by WilcoFiers** [comment]
Unfortunately, there are no APIs to get at computed properties of pseudo elements. That makes testing them challenging. Axe-core has some code that tried to figure out the impact pseudo elements can have on color. We'll have to check why in this particular scenario it does not.

**Comment by straker** [comment]
Looks like we [start the pseudo check at the parent element](https://github.com/dequelabs/axe-core/blob/develop/lib/checks/color/color-contrast-evaluate.js#L102-L115) of the node and never look at the node itself.

**Comment by davodavodavo3** [comment]
Great, thank you guys. Do I need to inform Google LH about this so they put some notification there about that color contrast can be not correct?

**Comment by padmavemulapati** [comment]
Validated with latest develop branch code base,
color-contrast is checking now for pseudo elements (node level check not just if any of the element's parents have pseudo elements)
![image](https://user-images.githubusercontent.com/47409579/124585351-d2d8e580-de72-11eb-8798-0b1f3aeb2773.png)
