### ISSUE TITLE
Runtime issue: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by asteriusj** [dequelabs/axe-core#2999]
<< Please describe how you encountered this issue >>
Tring out accessibility scan on a Wix editor page (https://editor.wix.com/)
specifically https://editor.wix.com/html/editor/web/renderer/edit/90e63cc8-6dcf-4a93-845f-b5611e3e870d?editorSessionId=21d4ebaa-0889-4fa7-8823-b05437d801e1&metaSiteId=0605511e-896c-473d-a690-19ad038079db&templateId=88750b48-264b-4d5a-993f-17f5c2a08e9e

axe-core version: `4.2.0`
axe-extension version: `4.9.3`

```
TypeError: Cannot read property 'data' of undefined
    at Xl._l [as after] (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:289593)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:324563
    at Array.forEach (<anonymous>)
    at ec.after (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:324396)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:332384
    at Array.map (<anonymous>)
    at e.value (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:332240)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:341091
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:97118
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:100990
```

**Comment by straker** [comment]
Thanks for the issue. We currently have a fix in place and will soon update the extension with it. We're currently tracking this in #2944
