### ISSUE TITLE
<th> with no scope is not being identified as an issue 

### ISSUE THREAD

**Issue by ackleyk** [dequelabs/axe-core#3005]
Product: axe Extension using axe Rules 4.2

**Expectation**: When a table has <th> with no specified scope, a critical issue should be identified according to the axe ruleset (rule #83), which states "scope attribute should be used correctly on tables". The explanation of the rule, which can be found here, https://dequeuniversity.com/rules/axe/4.2/scope-attr-valid, states "Add scope attribute values to all th elements that do not have one".

**Actual**: Testing the following page where there is a table with no scope attributes on the <th>, the issue is not identified by axe in the browser extension. https://alphagov.github.io/accessibility-tool-audit/tests/tables-table-has-no-scope-attributes.html

**Motivation**: The current rule seems to not be working as it was intended. Other tools, such as AChecker and HTML CodeSniffer, are identifying this issue.
 It is important to note that if an invalid value is used, such as <th scope="both">, this is being correctly identified as an issue.

axe-core version: 4.2

Here is the code example:

<table>
<caption>Opening
times</caption>
<tbody><tr>
<td></td>
<th>Monday-Friday</th>
<th>Saturday</th>
<th>Sunday</th>
</tr>
<tr>
<th>08:00
-
12:00</th>
<td>open</td>
<td>open</td>
<td>closed</td>
</tr>
<tr>
<th>12:00
-
16:00</th>
<td>open</td>
<td>closed</td>
<td>closed</td>
</tr>
</tbody></table>

Kudos to our intern, Jennifer Crary, for finding this issue while testing with axe.

**Comment by straker** [comment]
The `scope-attr-valid` rule only checks `th` elements with the `scope` attribute to make sure the value is a valid value. Most browsers / screen readers automatically assign the first `th` of a row to `rowheader` and the first row of `th` to `columnheader` (even IE11 / JAWS), so if you keep to a simple table adding `scope` isn't strictly needed.

In IE / JAWS, Chrome / JAWS, and Firefox / NVDA the table is traversable and announces the correct headings as you move around the table.
