### ISSUE TITLE
Support HTML 5.2 dl changes

### ISSUE THREAD

**Issue by dylanb** [dequelabs/axe-core#301]
specifically, `<div>` will be allowed as a child of `<dl>` 

https://github.com/w3c/html/commit/ec2e514d525e7a7191d0287bf5b48a02f4d28312

**Comment by marcysutton** [comment]
Pretty sure this is a duplicate of https://github.com/dequelabs/axe-core/issues/262.

**Comment by dylanb** [comment]
nice...I was going off the change list and forgot about the other issue

**Comment by web-bert** [comment]
Hi, any ideas when this will get added? Is there a way I disable this rule for now as it's making my tests fail?
