### ISSUE TITLE
"axe Linter setup: Starting local-server" runs in infinity

### ISSUE THREAD

**Issue by BossElijah** [dequelabs/axe-core#3027]
Product:  Axe accessibility Linter for VSCode

Expectation: I expect the vscode extension to start.

Actual: When I open VSCode, a popup pops up int the bottom-right corner saying: "axe Linter setup: Starting local-server", and it never goes away. The extension is not working either.

Motivation: I want the extension to actually start
![Screenshot 2021-06-22 at 17 46 15](https://user-images.githubusercontent.com/54446109/122956938-bec8ba80-d381-11eb-9537-8c39663c5260.png)
 up
<pre><code>
- Platform:  Mac
</code></pre>

**Edit:** The extension seems to load sometimes, so it's like every other time I want to use it, it actually starts up.

**Comment by straker** [comment]
Thanks for letting us know. I'll make sure the right people see this and look into it.

**Comment by AStoker** [comment]
This is still an issue I'm experiencing too.

**Comment by Gristof** [comment]
Same thing happening here - also on a Mac

**Comment by nrgnrg** [comment]
I'm also having this problem all of a sudden

**Comment by BossElijah** [comment]
**@straker** any news on this?

**Comment by vfonic** [comment]
In my case, it seems like the problem went away by itself. Maybe restarting VS Code or OS could help until the bug is fixed.

**Comment by BossElijah** [comment]
**@vfonic** This has been an issue for more than a half year now, and I have restarted the program and my mac to infinity.

**Comment by BossElijah** [comment]
and I also reinstalled the extension

**Comment by straker** [comment]
Thanks for the ping. This should be resolved when axe linter 4.3 is released, which should be later this month.

**Comment by BossElijah** [comment]
Thank you, that sounds awesome — I'm gonna close this issue then..
