### ISSUE TITLE
Is it possible to maintain session and cookies of the site using Axe-core?

### ISSUE THREAD

**Issue by syndy1989** [dequelabs/axe-core#303]
Hi, I wanted to know how to maintain sessions and cookies in a user authenticated site using Axe-core? If Yes, How would i do that ? need to add any actions to the script or Is there any other way to do it?
Any advise on this would be helpful. Thanks in advance.

**Comment by dylanb** [comment]
@syndy1989 this requirement is orthogonal to axe-core and would be dependent on whatever test system you are integrating axe-core into. So the answer is "yes, as long as your test system supports this"
