### ISSUE TITLE
Ignore rule example

### ISSUE THREAD

**Issue by smustgrave** [dequelabs/axe-core#3034]
So in pa11y you can ignore specific rules but they don't seem to work with axe runner.   Is there an example of how to ignore an axe rule?  Example I want to ignore       "WCAG2AA.Principle1.Guideline1_3.1_3_1.G141",

**Comment by straker** [comment]
I guess what do  you mean by ignore specifically? We have a few different ways to run only specific rules or to turn a rule off during a run. See https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#options-parameter-examples for disabling a rule just once during a run, or https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#parameters-1 for disabling a rule for multiple runs (using the `enabled` property of a rule).

**Comment by smustgrave** [comment]
Maybe this is possibly a pa11y question?
I'm using this config
`{
  "defaults": {
    "standard": "WCAG2AA",
    "runners": ["axe"],
    "timeout": 90000,
    "level": "none",
    "chromeLaunchConfig": {
      "ignoreHTTPSErrors": true,
      "args": ["--no-sandbox"]
    },
    "ignore": [
      "Section508.D.H49.AlignAttr",
      "Section508.D.HeadingOrder",
      "WCAG2A.Principle1.Guideline1_3.1_3_1.H49.AlignAttr",
      "WCAG2AA.Principle1.Guideline1_3.1_3_1.H49.AlignAttr",
      "WCAG2AAA.Principle1.Guideline1_3.1_3_1.H49.AlignAttr",
      "WCAG2AAA.Principle1.Guideline1_3.1_3_1_AAA.G141"
    ]
  }
}
`
But axe doesn't ignore any rules it seems.

**Comment by straker** [comment]
Possibly. I'm not familiar with how pa11y handles it's ignore rules, but axe-core has support for it.

**Comment by WilcoFiers** [comment]
Issue opened with pa11y. Closing it here.
