### ISSUE TITLE
Foreground color is not correctly computed if opacity is specified

### ISSUE THREAD

**Issue by hamadu** [dequelabs/axe-core#3039]
Product: axe-core
Expectation: In html below, the text color is #808080 and axe-core also reports the color is #808080.
Actual: Axe-core reports the color is #804040.
Motivation: We need correct foreground color to compute the color contrast correctly

For example:

```html
<div style="opacity: 0.5; background-color: #ff0000;">
    <p>Lorem ipsum</p>
</div>
```
In my environment, the text color was #808080, but axe-core reports a different value at all, #804040.
For another example:

```html
<div style="opacity: 0.75; background-color: #ff0000;">
    <div style="opacity: 0.75; background-color: #ff0000;">
        <p>Lorem ipsum2</p>
    </div>
</div>
```
In my environment, the text color was #704144, but axe-core reports a different value at all, #700707.

<img width="547" alt="test_html" src="https://user-images.githubusercontent.com/307869/123382935-7bfb2280-d5cd-11eb-9f01-ac3dd14d2258.png">

<img width="956" alt="test_html-2" src="https://user-images.githubusercontent.com/307869/123382952-81f10380-d5cd-11eb-9685-148b31f620d6.png">

<img width="979" alt="test_html-4" src="https://user-images.githubusercontent.com/307869/123382962-84535d80-d5cd-11eb-9abc-4067d9fea02b.png">

<pre><code>axe-core version: 4.2.3
Browser: Google Chrome 91.0.4472.114
Node.js version: v14.10.0
Operating System: macOS Big Sur
</code></pre>

**Comment by straker** [comment]
Thanks for the issue. When you say "In my environment, the text color was #808080, but axe-core reports a different value at all, #804040," what do you mean exactly? The example snippets don't use CSS `color` so are you using the default text color of the page or is it assigned somewhere else?

**Comment by hamadu** [comment]
@straker The text color is plain black (`#000000`). I retried the snippets specifying the `color: #000000`, but the result was the same.

**Comment by WilcoFiers** [comment]
This issue has the same cause as #2924. Thank you for reporting. I'm going to close this as a duplicate. Thank you for reporting though.
