### ISSUE TITLE
Runtime issue: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by isc-lbateman** [dequelabs/axe-core#3040]
<< Please describe how you encountered this issue >>
We just developed a new login page and are trying to scan it. Happy to provide a screenshot if that would help. I should note that my installed axe Expert extension is able to scan the page, and that multiple people are encountering this issue on axe DevTools. Thank you!

axe-core version: `4.2.0`
axe-extension version: `4.9.3`

```
TypeError: Cannot read property 'data' of undefined
    at Xl._l [as after] (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:289593)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:324563
    at Array.forEach (<anonymous>)
    at ec.after (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:324396)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:332384
    at Array.map (<anonymous>)
    at e.value (chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:332240)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:341091
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:97118
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/vendor.bundle.js:56:100990
```

**Comment by erik-deque** [comment]
Thank you for reporting this. Could you try testing with the Edge axe Extension or the Firefox axe add-on? Those are both running newer versions of axe-core.

I suspect the release we have planned for Monday will fix the issue, but if we can confirm ahead of time by using one of the other extensions, that would be nice.

**Comment by isc-lbateman** [comment]
Hi Erik,

Thanks for your email! I can confirm that the Firefox axe extension works on MacOS. (My VM paralyzes my laptop, so I’ve asked a colleague to check it on Edge and will let you know.)

Thanks again,
Leah

From: erik-deque ***@***.***>
Reply-To: dequelabs/axe-core ***@***.***>
Date: Friday, June 25, 2021 at 12:30 PM
To: dequelabs/axe-core ***@***.***>
Cc: Leah Bateman ***@***.***>, Author ***@***.***>
Subject: Re: [dequelabs/axe-core] Runtime issue: Cannot read property 'data' of undefined (#3040)


Thank you for reporting this. Could you try testing with the Edge axe Extension or the Firefox axe add-on? Those are both running newer versions of axe-core.

I suspect the release we have planned for Monday will fix the issue, but if we can confirm ahead of time by using one of the other extensions, that would be nice.

**Comment by erik-deque** [comment]
We released a new version of the Chrome extension yesterday. Can you confirm it is working now?

**Comment by isc-lbateman** [comment]
Hi Erik,

It works for me now! Robert, any luck on the Windows end?

Thanks,
Leah

From: erik-deque ***@***.***>
Reply-To: dequelabs/axe-core ***@***.***>
Date: Tuesday, June 29, 2021 at 10:34 AM
To: dequelabs/axe-core ***@***.***>
Cc: Leah Bateman ***@***.***>, Author ***@***.***>
Subject: Re: [dequelabs/axe-core] Runtime issue: Cannot read property 'data' of undefined (#3040)


We released a new version of the Chrome extension yesterday. Can you confirm it is working now?

**Comment by isc-lbateman** [comment]
Hi Erik,

My colleague Robert confirmed that the Chrome extension works for him on Windows now, too. Thanks very much for your help!

Best,
Leah

From: erik-deque ***@***.***>
Reply-To: dequelabs/axe-core ***@***.***>
Date: Tuesday, June 29, 2021 at 10:34 AM
To: dequelabs/axe-core ***@***.***>
Cc: Leah Bateman ***@***.***>, Author ***@***.***>
Subject: Re: [dequelabs/axe-core] Runtime issue: Cannot read property 'data' of undefined (#3040)


We released a new version of the Chrome extension yesterday. Can you confirm it is working now?

**Comment by erik-deque** [comment]
Great to hear it! Closing this ticket now.
