### ISSUE TITLE
False positive: "nested-interactive" rule failure when the nested element has only a tabindex and has no interactive role

### ISSUE THREAD

**Issue by iamrafan** [dequelabs/axe-core#3043]
Demo link: https://codepen.io/iamrafan/full/MWpNRVr

<pre><code>axe-core 4.2.0-canary.43394bc
axe version: axe-coconut 4.8.6.11818</code></pre>

**Comment by straker** [comment]
Thanks for the issue. I believe this is related to #2954

**Comment by WilcoFiers** [comment]
It's sort of related, but this is a clearer case of when there actually is a problem. Putting tabindex on an element, any element, will make it focusable. Using the pointer, you can put focus on your tabindex="-1" element. I'm going to consider this largely a duplicate, but I would suggest you fix this @iamrafan.
