### ISSUE TITLE
Best practices for nested interactive controls

### ISSUE THREAD

**Issue by kidokidozh** [dequelabs/axe-core#3044]
Our product has a control like below. Each option can be selected, and has a link inside it.
But this structure is obviously against the **"Nested-interactive"** rule (https://dequeuniversity.com/rules/axe/4.2/nested-interactive?application=msftAI)
Is there any suggestion on the best practices for this use case?
```html
<div role="option" aria-selected="true" tabindex="0">
    <span>Option 1</span>
    <span>Description for option 1</span>
    <a role="link" tabindex="0">View detail</a>
</div>
```
![image](https://user-images.githubusercontent.com/58833558/123584344-c837a400-d813-11eb-99ca-c90cef57f370.png)

**Comment by WilcoFiers** [comment]
Yeah, that pattern is not going to work reliably in assistive tech.  You're probably better off switching to a radiogroup. Something like this:

```html
<div role="radiogroup"
     aria-labelledby="group_label">
  <h3 id="group_label">Heading here</h3>

  <div>
    <span role="radio" 
          aria-checked="false" 
          tabindex="0" 
          aria-describedby="description_1">
      Option 1
    </span>
    <span id="description_1">
      Description for option 1
      <a role="link" tabindex="0">View detail</a>
    </span>
  </div>

  <div>
    <span role="radio" 
          aria-checked="false" 
          tabindex="0" 
          aria-describedby="description_2">
      Option 2
    </span>
    <span id="description_2">
      Description for option 2
      <a role="link" tabindex="0">View detail</a>
    </span>
  </div>
</div>
```

This isn't so much an axe-core issue, as just a general accessibility question. You may want to join the [axe community slack](https://accessibility.deque.com/axe-community). It's pretty good for questions like this.
