### ISSUE TITLE
axe.getFrameContexts mutates its input

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#3045]
This shouldn't fail:

```js
const context = { exclude: [['iframe', 'foo']] }
axe.utils.getFrameContexts(context);
assert.deepEqual(context, { exclude: [['iframe', 'foo']] });
```

**Comment by WilcoFiers** [comment]
This isn't going to need QA. Closing it.

**Comment by padmavemulapati** [comment]
Validated with the latest develop branch code base, 
on passing the `axe.utils.getFrameContexts({exclude: [['iframe','#testFrame']] });` 
for a test file
"http://qateam.dequecloud.com/attest/api/test.html" , and `id` of the `iframe` being `#testFrame`
and it excluding the frame contexts, below is the screenshot,
![image](https://user-images.githubusercontent.com/47409579/128203601-811fbd7c-4bd1-42c3-a0a3-08f0d9a475f7.png)

**Comment by straker** [comment]
No docs
