### ISSUE TITLE
Prompt users to check iframes when they are disabled in API (new rule)

### ISSUE THREAD

**Issue by marcysutton** [dequelabs/axe-core#307]
One we've merged #304, we need a way to float up iframes that were skipped to give a more complete picture of a11y on a given page. We could write a rule that puts these items into Needs Review.

From @dylanb:
> Create a rule that puts every iframe into a "needs review" result if there are iframes and `options.iframes === false`

Pros: every user would be able to know/display-to-end-users the fact that there are parts of the page that are not being analyzed

Cons: We would have to pass this option into every check so that it could operate appropriately dependent on the options - this is not a huge con IMO because it would allow all checks to modify their behavior based on options

**Comment by WilcoFiers** [comment]
Axe-core should inform users when frames didn't get tested. We can do that by adding it as a result into `incomplete`. This should only be the case if that frame is visible, and if it didn't get excluded through scope.

I think the best way to build this is to have a rule that selects frames, then in a check, test that that frame is visible, and ping the frame, see if axe responds. This check would have to be async, which axe should be able to do (we've got `this.async()` in checks). But we don't currently have any checks that use it, so we'll have to test this properly.
