### ISSUE TITLE
ARIA combobox only requires 'aria-controls' in expanded state

### ISSUE THREAD

**Issue by vskh** [dequelabs/axe-core#3091]
**Product:** axe-core
**Expectation:** Pass 'aria-required-attr' rule on combobox with no 'aria-controls'/'aria-owns' when 'aria-expanded'=false
**Actual:** Critical error "Required ARIA attribute not present: aria-controls" is triggered.
**Motivation:** The part of WAI-ARIA that the rule refers to[ in part applicable to combobox](https://www.w3.org/TR/wai-aria-1.1/#combobox) mentions that

> **When a combobox is expanded**, authors MUST ensure it contains or owns an element that has a role of listbox, tree, grid, or dialog. This element is the combobox popup. **When the combobox is expanded**, authors MUST set aria-controls on the textbox element to a value that refers to the combobox popup element.

i.e. 'aria-controls' is only required when the combobox is in expanded state (which mentioned dropdown implementation complies with, as the listbox part is dynamically inserted and not present in the DOM before expansion). There are no other mentions of these attributes with regards to behavior in a collapsed state. But axe-core requires those attributes unconditionally.
<pre><code>
axe-core version: 4.3.1

- Node version: v14.15.4
- Platform:  Linux, Windows
</code></pre>

**Comment by vskh** [comment]
Duplicate of #3090

**Comment by straker** [comment]
Ha, I liked your issue better so was going to close mine :)
