### ISSUE TITLE
Axe Linter VS Code with Typescript and KnockoutJS Project - Throws false positive on link with aria-label

### ISSUE THREAD

**Issue by kmdinake** [dequelabs/axe-core#3092]
Product: axe Linter (VS Code)

Expectation: Axe will check the LINK `data-bind` attribute to see if the attributes of the link (binded via the `attr` object, has a value set for the `'aria-label'` property. Upon finding that there property is set and has a value it would not raise an issue.

Actual: Raises an issue that the link does not have discernable text
> Axe Linter (link-name): Ensures links have discernible text.

![image](https://user-images.githubusercontent.com/20728351/126545480-cd1ac4c4-2c09-4abd-8ef7-9b0a49c78703.png)

Motivation: This will ensure that link tag is defined and compliant at very least to the accessibility standards that can be enforced by automated tests. Instead of a false positive for the way in which KnockoutJS binds values to `HTML` elements' attributes or ignoring the rule in the project as these links behave as expected in the browser, this issue could be resolved.

<pre><code>
- Axe Linter VS Code Extension Version: 4.2.1
- VS Code Version: 1.58.2 (user setup)
- Commit: c3f126316369cd610563c75b1b1725e0679adfb3
- Date: 2021-07-14T22:10:15.214Z
- Electron: 12.0.13
- Chrome: 89.0.4389.128
- Node.js: 14.16.0
- V8: 8.9.255.25-electron.0
- OS: Windows_NT x64 10.0.19043

For Tooling issues:
- Node version: v12.18.0
- Platform:  Windows
</code></pre>

**Comment by straker** [comment]
Thanks for the issue. Currently axe-linter vscode does not support KnockoutJS. We only support pure HTML (.html .htm) files without any frameworks syntax.

**Comment by kmdinake** [comment]
Oh okay. Well, thank you for the quick response. I will close this issue.
