### ISSUE TITLE
cypress axe-core vs chrome extension (color-contrast)

### ISSUE THREAD

**Issue by doemac** [dequelabs/axe-core#3094]
Product: <<axe-core>>

Expectation: << both the axe core extension and cypress (cy.checkA11y()) should report the same set of violations >>

Actual: << axe-core cypress check does not report color-contrast rule violation at all>>

Motivation: << To maintain consistency between manual browser testing and  cypress automated testing  >>

<pre><code>
axe-core node version: 4.3.1
axe-core-devTools - 4.3.1
cypress-axe-core - 1.1.3

Browser and Assistive Technology versions

For Tooling issues:
- Node version: 12.18.3
- Platform:  Mac

**Comment by WilcoFiers** [comment]
@doemac I'm afraid you're going to have to open an issue with [cypress-axe](https://github.com/component-driven/cypress-axe/issues) on this. Cypress-axe is not maintained by the team that developed axe-core. There isn't much we can do about problems with cypress-axe.
