### ISSUE TITLE
Where is "not an issue" in aXe DevTools (axe-core 4.3.1)?

### ISSUE THREAD

**Issue by ronilaukkarinen** [dequelabs/axe-core#3116]
Not sure if this a right place to ask about this, please forgive me if I made a mistake here. But here you go:

Product: aXe DevTools, axe-core 4.3.1

Expectation: Under an issue I expect to see "not an issue" radio button

Actual: No such option exists any more

Motivation: There are some things that need to be ignored for example the issue "ARIA hidden element must not contain focusable element" is false positive when there is the same content in the user interface that is focusable and some for only seeing users. If aria-hidden is disabled in this element it causes repetition for screen readers. In these use cases it would be nice to be able to say to aXe that this is not an issue for us.

<pre><code>axe-core version: 4.3.1

Browser and Assistive Technology versions

For Tooling issues:
- Node version: v10.24.1 (using aXe via Chrome though)
- Platform: MacOS Big Sur
</code></pre>

**Comment by straker** [comment]
Just a clarifying question. Are you using the axe devtools the browser extension?

**Comment by ronilaukkarinen** [comment]
Yes, as Google Chrome extension. Was not sure where to open an issue about this.

**Comment by straker** [comment]
No problem, this is indeed a good place to post it. So there is an ignore / "not an issue" feature but you have to be logged into your deque account in order to do it.

**Comment by ronilaukkarinen** [comment]
I am logged in, but I don't see it anywhere.

![Screen-Shot-2021-08-12-09-37-46 58](https://user-images.githubusercontent.com/1534150/129149554-127deabe-5083-4d9c-8dbc-33d93eed4ce5.png)

**Comment by WilcoFiers** [comment]
This looks to be resolved.

**Comment by dylanb** [comment]
> Motivation: There are some things that need to be ignored for example the issue "ARIA hidden element must not contain focusable element" is false positive when there is the same content in the user interface that is focusable and some for only seeing users. If aria-hidden is disabled in this element it causes repetition for screen readers. In these use cases it would be nice to be able to say to aXe that this is not an issue for us.

The case that you mention is NOT a false positive because a screen reader user will get to the focusable item and it will read "blank" or some equivalent - which could confuse the user. This violates WCAG 4.1.2 and is easily remediated by simply not hiding the item even if there is another way to got to the functionality.
