### ISSUE TITLE
Deque University docs don't line up with axe-core

### ISSUE THREAD

**Issue by myasonik** [dequelabs/axe-core#3125]
(Apologies if this is the wrong spot to report this type of thing; I wasn't sure where else might be a better fit!)

Product: [Deque University page on definition lists](https://dequeuniversity.com/rules/axe/4.3/definition-list))

Expectation: The [docs for what's allowed for a definition list](https://dequeuniversity.com/rules/axe/4.3/definition-list) should match what [axe-core allows](https://github.com/dequelabs/axe-core/issues/262). Namely, the doc's don't list a `<div>` as a valid child of `<dl>` but the [linked, closed issue](https://github.com/dequelabs/axe-core/issues/262) enables just that. 

Actual: Deque University does not list `<div>` as a valid child of `<dl>`

Motivation: Well intentioned folks come to the a11y team with proof that the `<div>` needs to be removed, citing the docs page

**Comment by WilcoFiers** [comment]
@myasonik Thank you for reporting! You are right, that needs to be fix. We're on it!

**Comment by straker** [comment]
A fix has been made to the docs. The next time we push a release of the docs it should be updated.
