### ISSUE TITLE
p-as-heading rule should account for text length

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#3130]
Axe-core's p-as-heading rule is reporting an incorrect issue on the Azure page:
https://azure.microsoft.com/en-us/services/active-directory/external-identities/#customers

This problem can be avoided by checking the length of the possible heading, compared to the length of the supposed paragraph. I would say that if the heading is longer than the paragraph, we pass it. If it's less than twice as long, we set it for review, and only if the suspected fake heading is at least 200% shorter than the paragraph do we allow it to be failed.

The way to do this would be in the `p-as-heading-evaluate.js` file, to grab textContent of both nodes and compare the length. We should probably make these configurable through a check option as well.

**Comment by WilcoFiers** [comment]
Not the easiest "good first issue", but doable for anyone comfortable with JS, and willing to dig a little.

**Comment by ilyaryabchinski** [comment]
May I take work on this one?

**Comment by Zidious** [comment]
> May I take work on this one?

Sorry! I am currently working on this ticket.

**Comment by ilyaryabchinski** [comment]
No worries!

**Comment by dan-tripp** [comment]
I was looking at this issue too.  I'm happy to leave it to @Zidious - but @WilcoFiers , I don't suppose you have any more "good first issues" that I could work on?   I don't see any more which don't have an assignee or a PR.

**Comment by padmavemulapati** [comment]
Validated with the latest axe-core develop branch code base, 
as per the fix validations went like:
If the heading is longer than the paragraph, it will be  pass . 
If it's less than twice as long, it will go for review, 
and only if the suspected heading is at least 200% shorter than the paragraph it will fail.


![image](https://user-images.githubusercontent.com/47409579/137679728-e7da44aa-6123-43aa-80a6-afe82242777c.png)
