### ISSUE TITLE
Bug: reports incorrect error on aria-errormessage (ARIA 1.2) 

### ISSUE THREAD

**Issue by Zidious** [dequelabs/axe-core#3149]
Ref: https://github.com/dequelabs/axe-core-npm/issues/328

[ARIA 1.2](https://www.w3.org/TR/wai-aria-1.2/#aria-errormessage)

axe-core not reporting that content is hidden when `aria-errormessage` is referenced by a `hidden` element.

**Comment by dylanb** [comment]
Is the error incorrect or is it just missing the information about the content being hidden?
What about `aria-labelledby` as a way to announce the error message in addition to the ones we currently check for?
