### ISSUE TITLE
Bug: does not correctly handle the option to have elements with role="group" in a listbox context ARIA 1.2

### ISSUE THREAD

**Issue by Zidious** [dequelabs/axe-core#3152]
Ref: https://github.com/dequelabs/axe-core-npm/issues/313

Note: I was able to replicate the issue within axe-core's `playground.html` and `cli`

**Comment by straker** [comment]
Confirmed that `group` inside `listbox` works in our supported screen readers and browsers. opened https://github.com/dequelabs/axe-core/pull/3195

cc @spectranaut
