### ISSUE TITLE
[Chrome extension] DevTools does not export / save data

### ISSUE THREAD

**Issue by rvantonisse** [dequelabs/axe-core#3162]
Product: axe DevTools - Web Accessibility Testing (Google Chrome) version 4.17.0

Expectation: I expect the buttons "Save" and "export issues" to actually export some data or possibly prompt me with a file dialogue to save the export with desired filename.

Actual: Nothing happens. The first time prompts me with a login form, where I signed in with Github. Pushing save / export buttons after login, reopening browser, re-loggin and redo test makes pushing the buttons nothing happen.

Motivation: It does not work as expected and there is no link available to help documentation (access restricted).

<pre><code>
axe-core version: 4.3.3
axe DevTools - Web Accessibility Testing version: 4.17.0

Google Chrome Version 93.0.4577.82 (Official Build) (x86_64)

</code></pre>

**Comment by WilcoFiers** [comment]
Thank you for reporting the issue. I'll make sure it gets to the team responsible for the browser extension.

**Comment by dylanb** [comment]
@rvantonisse is it possible that your trial has expired? Could you add a screenshot showing your record page after login?

**Comment by rvantonisse** [comment]
Hey @dylanb, 

> is it possible that your trial has expired?

I have never started it. I asume this is to use the "Pro" version.

> Could you add a screenshot showing your record page after login?

<img width="1438" alt="Screenshot 2021-09-23 at 15 50 11" src="https://user-images.githubusercontent.com/5967550/134519533-a848e0f3-f93b-43b5-a7f6-7388f135fa61.png">

**Comment by dylanb** [comment]
@rvantonisse it is supposed to work only for the Pro (or the trial)

So what I am taking away is that you
1. clicked the button
2. It took you to login and you logged in (with Google or Github)
3. You did not complete the signing of the T's and C's and the starting of the trial
4. You are logged in but the upgrade link is still showing
5. Clicking save or export at this point does nothin

Can you confirm all of the above or correct it?

**Comment by rvantonisse** [comment]
> @rvantonisse it is supposed to work only for the Pro (or the trial)

If this is the case than the issue is more likely to be of user feedback type. Disabling the buttons, giving information on what Pro unlocks or a combination of both would then fix this.

> So what I am taking away is that you
> 
> 1. clicked the button

Yes, "export issues"

> 2. It took you to login and you logged in (with Google or Github)

Yes, github sso

> 3. You did not complete the acceptance of the T's and C's and the starting of the trial

Yes, I did not apply for trial of Pro I did accept on side of github though.

> 4. You are logged in but the upgrade link is still showing

Probably, if you mean the banner that mentions to start the pro trial.

> 5. Clicking save or export at this point does nothing

Exactly.

> Can you confirm all of the above or correct it?
👆👍

**Comment by shawnthompson** [comment]
Same thing is happening for me.

**Comment by dylanb** [comment]
extension release 4.18.2 will now display a message when a user is in this state so they know to go and complete their trial signup
