### ISSUE TITLE
Inconsistent console errors and incorrect results when scanning PART of the page with that has nested iframes

### ISSUE THREAD

**Issue by dylanhochreiter** [dequelabs/axe-core#3167]
Hi there,

We are seeing the following issue when scanning a "PART" of the page with the aXe chrome extension devtool. This does not happen consistently, but when do encounter the error we get the following in the console:

`content.bundle.js:62 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getById')
    at Rn.handleDomWalkerChange (content.bundle.js:62)
    at Rn.handleTestMessage (content.bundle.js:61)
    at content.bundle.js:61
handleDomWalkerChange @ content.bundle.js:62
handleTestMessage @ content.bundle.js:61
(anonymous) @ content.bundle.js:61
highlighter.js:1`

`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at t (highlighter.js:1)
    at new H (highlighter.js:1)
    at Object.highlight (highlighter.js:1)
    at Dt.hover (content.bundle.js:32)
    at Rn.handleDomWalkerChange (content.bundle.js:62)
    at Rn.handleTestMessage (content.bundle.js:61)
    at content.bundle.js:61`

The area in question has a nested iframe within an iframe, so I am thinking this is the source of the issue.

Here is what the HTML looks like for what we are scanning. We are scanning the searchFrame iframe in particular.
![html](https://user-images.githubusercontent.com/6334160/134705732-f55618c8-f687-4d28-8557-cafb5f4841be.png)

The good news is this doesn't happen all the time, and we are able to get the proper results half the time when scanning this so this isn't a huge blocker for us.

Anyways, just wanted to report it in case it's an issue that needs to be looked in on your side.

Thanks,

Dylan Hochreiter

**Comment by straker** [comment]
Thanks for letting us know. I'll be sure to pass this along to the appropriate team

**Comment by scurker** [comment]
@dylanhochreiter Is this a page that's publicly accessible? We do try to test for the scenario you are mentioning, so I wonder if there's something uniquely different here that we haven't accounted for.

**Comment by dylanhochreiter** [comment]
@scurker Hi there. Unfortunately the page is not publicly accessible. One would have to log in to our application in order to access this page.

Another note is that this area we are scanning is within another parent iframe. Not sure if that should matter or not.

**Comment by dylanb** [comment]
@dylanhochreiter I don't understand what you mean by `within another parent iframe`. Do you mean the content is within a specific iframe (i.e. not in the top frame)?

Either way, is this a same domain or a cross domain iframe? Do same domain ones work while cross domain ones fail?

**Comment by dylanb** [comment]
@dylanhochreiter can you try extension version 4.18.2 (most recent) we have made some fixes to iframe code in that release

**Comment by dylanb** [comment]
@dylanhochreiter it would be awesome if you could confirm the fix

**Comment by dylanhochreiter** [comment]
@dylanb Apologies for the lack of responses on this ticket.

I tried the same steps, and it looks like the main error is gone when running against this iframe.

I still do see this error:
`highlighter.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'getBoundingClientRect')`

Since this is a highlighter js error, it might not be as much of a concern.

The results are consistently being returned as "0" in each case.

**Comment by dylanb** [comment]
Highlighter is a known, separate problem - thanks, closing this
