### ISSUE TITLE
dom.isVisible does not take into account 0 width element

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core#3171]
Consider the following dom:

```html
<style>
  .target {
    width: 0;
    height: 50px;
    overflow-y: scroll;
  }

  .sub {
    height: 200px;
    width: 200px;
    background: blue;
  }
  </style>

  <div class="target">
    <div class="sub">Hello World</div>
  </div>
```

Calling `axe.commons.dom.isVisible` on the `.target` element results in `true`, even though visually the element is hidden. However, if we swap the width/height values, the element is then considered hidden. It seems our isVisible function only looks at height as a way to hide the element but does not consider width.

```css
.target {
    width: 50px;
    height: 0;
    overflow-y: scroll;
  }
```

This is the cause of https://github.com/dequelabs/axe-core/issues/2674

**Comment by padmavemulapati** [comment]
Validated with the latest axe-core develop branch code base,
seeing `scrollable-region-focusible` failing when width of scroll regions is zero (0), using `color-constrast`
![image](https://user-images.githubusercontent.com/47409579/137506026-07fafd60-a7ab-495f-9eba-7bf2676e02f0.png)
