### ISSUE TITLE
Angular template support

### ISSUE THREAD

**Issue by digeomel** [dequelabs/axe-core#3198]
Product: <<axe-core | axe Extension | axe Linter>> - I suppose it applies to all 3

Expectation: work with Angular 2+ templates

Actual: it doesn't work with Angular 2+ templates

Motivation: working with Angular

I could find very specific issues related to Angular by searching, but nothing general about Angular support.
I also found this repo https://github.com/dequelabs/ngA11y which seems to be abandoned.
If a developer would like to implement Angular support in the current axe library, is this the repo to start from? If not, what needs to be done to support Angular? Maybe I or someone else can do a related PR?

**Comment by WilcoFiers** [comment]
Glad to hear. In that case I think this can be closed.

**Comment by kalpeshhpatel** [comment]
Hey @WilcoFiers , I am looking for something similar for the angular template. The VSCode extension works nice, but my use-case is the linting phase during pre-commit hook.

Can you please help suggest the possible solution?

**Comment by WilcoFiers** [comment]
@kalpeshhpatel axe Linter service is available for pre-commit hooks:
https://www.deque.com/axe/devtools/linter/
