### ISSUE TITLE
Determine if text shadow flatten algorithm is correct

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core#3199]
In #3193 we changed how the `flattenColors` algorithm works (making it exactly to spec), but that broke a lot of text shadow tests (things that were barely passing stop passing). We added back the old way to flatten colors just for text colors to make the tests pass, but we need to take time to test the new flatten colors with the text shadows to see if we can use it (and remove the old flatten color).

**Comment by padmavemulapati** [comment]
Validated with the latest code base of `axe-core` develop branch , 
for the code snippet, where in `-webkit-text-stroke` support implemented: 
```
<p style="color: #ccc; -webkit-text-stroke: 0.03em #444" id="fail1">
    Text-stroke 0.03em
  </p>
  <p style="color: #ccc; -webkit-text-stroke: 0.02em #444" id="fail2">
    Text-stroke 0.02em
  </p>

```



![Image](https://user-images.githubusercontent.com/47409579/205665422-4be01ea7-1088-415c-8ea9-bfd41e963163.png)
