### ISSUE TITLE
allow utils.getFrameContext to accept options

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core#3242]
Allow the function to accept an object with property `iframes: false` and return an empty array if set. This just future proofs the function so we can do more if we need to.

**Comment by padmavemulapati** [comment]
Verified with the latest dev branch code,` iframes`  allowing true and false options with `getFrameContext()` , with code snippet:
```
<html lang="en">
  <title>O hai</title>

  <div class="foo" id="foo">foo</div>
  <iframe></iframe>
</html>
```
and passing with `axe.utils.getFrameContexts({ }, { iframes: true });`
getting focusible : true result.
![image](https://user-images.githubusercontent.com/47409579/147928465-6fac481c-d2d1-4d68-9bd9-7c8e79e56225.png)

also with iframe:false option:
getting below:
![image](https://user-images.githubusercontent.com/47409579/147928692-e73a50a1-2efa-4428-b413-62f164e8b2cf.png)
