### ISSUE TITLE
Runtime issue: c is undefined

### ISSUE THREAD

**Issue by jabedini** [dequelabs/axe-core#3250]
I am trying to incpect our website. Not sure if the devtools is blocked from our organization end or there is an issue with the connection. 

axe-core version: `undefined`
axe-extension version: `4.18.2`

```
48269/<@moz-extension://ec8f88b4-0644-45ec-9f50-57b2b30be687/content.bundle.js:1:21716

```

**Comment by dylanb** [comment]
duplicate of https://github.com/dequelabs/axe-core/issues/3248
