### ISSUE TITLE
update dpub role allowances for li element

### ISSUE THREAD

**Issue by scottaohara** [dequelabs/axe-core#3253]
[ARIA in HTML](https://github.com/w3c/html-aria/pull/369) is removing the allowances for [`doc-biblioentry`](https://w3c.github.io/dpub-aria/#doc-biblioentry) and [`doc-endnote`](https://w3c.github.io/dpub-aria/#doc-endnote) on `<li>` elements.  

These are not technically valid children of `ul`, `ol` or `role=list` elements per the ARIA spec.  Due to this, these roles are being deprecated in DPUB ARIA 1.1. Authors should be using standard list elements, or `role=list` and `role=listitem` elements instead.

Edited issue description to provide more clarity / per the closure of the original PR.

**Comment by straker** [comment]
Moving conversation from the pr. In essence, we won't remove the roles from the allowed list since they are only deprecated and as far as we know don't cause problems with screen readers if present. Will need to figure out how we want to handle and announce to the user deprecations in the ARIA spec.

**Comment by scottaohara** [comment]
@straker I saw that https://github.com/dequelabs/axe-core/pull/3280 was merged, but that this issue is still open.  I think this can be closed per your comment in the PR, but wanted to verify before closing myself.

**Comment by straker** [comment]
Yep. I think this can be closed as well. Thanks for the reminder.

**Comment by danielweck** [comment]
This issue was partially fixed (a bug was mistakenly introduced), see new issue https://github.com/dequelabs/axe-core/issues/3372
