### ISSUE TITLE
Color contrast incomplete for label and input

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core#3257]
This returns incomplete for the `label` element because we try to get the midpoint of the label, which is way outside the text content.

```html
<label>Do you like peas?
  <input name="peas" style="width: 100%">
</label>
```

**Comment by padmavemulapati** [comment]
Validated with the latest code base of axe-core develop branch,
with the code snippet:
```
<label>Do you like peas?
  <input name="peas" style="width: 100%">
</label>
```
`label` element is getting `incomplete` results 
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/47409579/206959286-87efd879-ccf4-49b6-8b37-702da0faabeb.png">
