### ISSUE TITLE
Allow "skip buttons" in region rule

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#3260]
As seen in ARIA practices:
https://w3c.github.io/aria-practices/examples/link/link.html

![Screenshot Jump to content button, expanded](https://user-images.githubusercontent.com/530687/140549691-a6e9e242-6ff6-40b4-9454-cbea72331ee1.png)

Axe-core fails these because it's a button, rather than a link.

**Comment by dylanb** [comment]
I hate this, it is not semantic and there is no way we can validate that the skip button works

**Comment by padmavemulapati** [comment]
Verified with the latest dev branch code base, 
fix is allowing region rule for skip button, validated with the code snippet:
`<button id="target">Skip menu</button><main><h1>Introduction</h1></main>`
`region` rule is failing but not for skip button.
![image](https://user-images.githubusercontent.com/47409579/148079224-b6a1382f-8c50-4207-bc36-2bf5734bfe37.png)
