### ISSUE TITLE
Better Document Critical, Serious, Moderate & Minor errors

### ISSUE THREAD

**Issue by mgifford** [dequelabs/axe-core#3263]
axe-core Documentation

Expectation: It should be clear:
1) What issues fall within each category
2) Why axe has identified this issue in this way
3) Who is affected

Actual: Best I can find is the [rule description](https://github.com/dequelabs/axe-core/blob/b44529130568347816fa810c959b68f980161241/doc/rule-descriptions.md). It's great, but...

Motivation: A government client asked. Best I could come up with was, "Because Deque said".  You guys are great and all, but would be nice to have the rationale spelled out a bit more.

**Comment by straker** [comment]
Does https://github.com/dequelabs/axe-core/blob/develop/doc/issue_impact.md help? Or are you looking for even more details?

**Comment by mgifford** [comment]
Yes, that is basically what I was looking for. Possibly with a link to a table sorta like this with the rules organized by error strength - https://github.com/dequelabs/axe-core/blob/b44529130568347816fa810c959b68f980161241/doc/rule-descriptions.md

Client was asking today, "why is this critical?" and your issue impact does a good job explaining that.
