### ISSUE TITLE
Request updates to allowed roles for area without href

### ISSUE THREAD

**Issue by scottaohara** [dequelabs/axe-core#3266]
[ARIA in HTML](https://github.com/w3c/html-aria/pull/360) is looking to update the allowed roles for `area` without `href` from **no role** to instead allow `link` and `button`, only.

**Comment by WilcoFiers** [comment]
That makes a lot of sense. Any particular reason you wouldn't also allow button on `area[href]` though?

**Comment by scottaohara** [comment]
thanks Wilco.

That idea did come up when discussing this change (both in the ARIA WG when they had done the initial review during CR, and when we were discussing after I looked into what other roles might have made sense here).

Essentially, keeping the status quo boils back down to a version of the links vs buttons debate / user expectations of role announcement.  If authors need an `area` to be a `role=button`, then they would now have this opportunity by not adding, or by removing, the `href`.  

If need be, we can discuss this further in a new issue in ARIA in HTML.  

Related issue: https://github.com/w3c/html-aria/issues/187

**Comment by WilcoFiers** [comment]
Tanks for clarifying. Sounds good.

**Comment by padmavemulapati** [comment]
Validated with the develop branch axe-core code base,
`aria-allowed-role` rule allowing the roles for `button` and `'link` `area` without `href`

![image](https://user-images.githubusercontent.com/47409579/141989802-f2c6a355-dbfa-4541-96c4-b454cd12cfda.png)
