### ISSUE TITLE
Improve axe-core documentation styling

### ISSUE THREAD

**Issue by marcysutton** [dequelabs/axe-core#327]
The styling of the axe-core API documentation is hard to digest, especially on the axe-core website. A more clear and readable design would help people understand how axe-core works more quickly: a few treatments we could consider include dividers, grids/layout tables, better syntax highlighting, etc. 

This issue could be opened against the axe-website too, but since it pulls from this repo we should start by improving it here.

**Comment by marcysutton** [comment]
One idea is to move documentation to axe-core.org and link to it from Github instead of pulling from Github onto the website. Otherwise, we're pretty limited by what can be done in Markdown styling. It's especially limiting for our JSON API structure, which has multiple depths.

**Comment by nschonni** [comment]
What about using https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch like Bootstrap?

**Comment by WilcoFiers** [comment]
@marcysutton I'm not sure what you mean by "Otherwise, we're pretty limited by what can be done in Markdown styling." We have to use markdown because we want to have the docs in the github repo. We can use plain HTML in the website if we wanted that. Even so, you can use HTML in markdown

```markdown
## Heading

<p class="note">Some note</p>
```
AFAIK this works fine.

**Comment by marcysutton** [comment]
I'd love to see our docs in a more readable format, similar to Angular Material: https://material.angularjs.org/latest/api/service/$mdColors

But–the JSON required for `axe.configure` is multiple levels deep, and it's a single structure. The trouble is that styles get stripped from Markdown on Github, even though you can write custom HTML. So styling a data table with indentation (padding) and headers that stand out isn't possible in that format. And then we pull it in to the website, so we're limited to Markdown and HTML with no custom styles.

I like the idea of using Github pages, but we already have a website so we wouldn't want to distract people away from that. If we move the docs to our website, we'd have way more styling flexibility AND avoid [build issues like this one](https://github.com/dequelabs/axe-website/issues/1).

**Comment by nschonni** [comment]
Although the GH version is a little ugly, https://github.com/twbs/bootstrap/blob/v4-dev/docs/4.0/components/alerts.md renders into https://v4-alpha.getbootstrap.com/components/alerts/

I think those `{% highlight js %}` should be able to be changed to regular code fences though.

Alternately, we've used https://www.npmjs.com/package/grunt-gh-pages to just build using a Node/Handlebars engine and just push the built files to a separate repo too.

**Comment by WilcoFiers** [comment]
@marcysutton I think we should optimise the docs for the website, and leave the Github view for what it is. It doesn't have to be optimal, as long as it's readable. We should encourage users to go to the website anyway. As I see it, having GH strip styles that we end up using on the site doesn't hinder the GH view, and it improves the view on the site.
