### ISSUE TITLE
Runtime issue: c is undefined

### ISSUE THREAD

**Issue by a-tiwari2** [dequelabs/axe-core#3270]
<< Please describe how you encountered this issue >>

axe-core version: `undefined`
axe-extension version: `4.18.2`

```
48269/<@moz-extension://2b254d75-2d4f-4d1d-9651-97cccd108197/content.bundle.js:1:21716

```

**Comment by scurker** [comment]
@a-tiwari2 Can you provide more details? How did you come across this issue?

**Comment by dylanb** [comment]
This is a duplicate. https://github.com/dequelabs/axe-core/issues/3248 Please upgrade to Firefox ESR 93
