### ISSUE TITLE
scrollable-region-focusable rule false positive on clip overflow

### ISSUE THREAD

**Issue by backwardok** [dequelabs/axe-core#3283]
Product: axe Extension (not sure if it exists elsewhere as well, but found on the axe extension)

Expectation: Setting `overflow` to `clip` doesn't get flagged as an error for `scrollable-region-focusable` since it doesn't actually scroll

Actual: Setting `overflow` to `clip` gets flagged as an error for `scrollable-region-focusable`

Motivation: Results in false positives, which encourages people to turn off the rule or ignore the results

[Example codepen to test behavior](https://cdpn.io/backwardok/debug/bGrxdMO)

<pre><code>axe extension version: 4.3.5
Browser version: Chrome 95.0.4638.69
Platform: Mac
</code></pre>

Similar issue to https://github.com/dequelabs/axe-core/issues/1582

**Comment by WilcoFiers** [comment]
Seems I forgot to comment... apologies! Thanks for reporting this. I confirmed the issue, and will have a fix for it in the next release.

**Comment by padmavemulapati** [comment]
Verified with the latest dev branch code , not seeing failure on `scrillable-region-focusible` when clip as hidden.
This is reproducible in the old code using axe-core3.4.1

![image](https://user-images.githubusercontent.com/47409579/148077091-df77c7b9-81a1-4b0d-a7e8-96e8a634fee1.png)
