### ISSUE TITLE
HTML Menu Element allows for HTML List Item Element direct children

### ISSUE THREAD

**Issue by MrGrigri** [dequelabs/axe-core#3284]
Product: axe Extension

Expectation: The HTML Menu Element allows for HTML List Item Element(s) as direct children.  

Actual: Throws axe-core 4.3 exception

Motivation: This goes agains the web standards.

axe-core version: 4.3.5
axe-webdriver, extension or other integration version: 4.18.2 (Chromium/Brave)

Browser and Assistive Technology versions

Brave Browser (Chromium v95.0.4638.69) v1.31.91

---

The following HTML snippet it valid HTML. The menu element has an implicit role of list and allows for list item children. In the reference section, I have included a link to the demo that I have created. Setting the role attribute on the menu element to list solves the issue. But as stated in the MDN documentation. The menu element has an implicit role of list.

``` html
<menu>
  <li><button onclick="copy()">Copy</button></li>
  <li><button onclick="cut()">Cut</button></li>
  <li><button onclick="paste()">Paste</button></li>
</menu>
```

---

References:

1. MDN Menu Element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu
2. MDN List Item Element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li
3. Demo: https://cc-form.glitch.me/
4. Axe Error: https://dequeuniversity.com/rules/axe/4.3/listitem?application=AxeChrome

**Comment by WilcoFiers** [comment]
@MrGrigri Thanks for reporting. Not sure how that went slipped by us. It certainly shouldn't have. I'll get it fixed ASAP.

**Comment by MrGrigri** [comment]
Thanks @WilcoFiers for handling this.

**Comment by padmavemulapati** [comment]
Verified with the latest dev branch code, 
fix is working fine and now `menu`  element is  allowing `listitem` as direct children.
Below is the screenshot showing no failure on `listitem` for the code snippet: with the latest axe-core version, which is now (4.3.5)
```
 <menu>
    <li><button onclick="copy()">Copy</button></li>
    <li><button onclick="cut()">Cut</button></li>
    <li><button onclick="paste()">Paste</button></li>
  </menu>
```
![image](https://user-images.githubusercontent.com/47409579/148080496-35ddb787-60bc-41e7-a215-7c17d3d64e3a.png)
 
Its reproducing with the old version(3.4.1)
![image](https://user-images.githubusercontent.com/47409579/148080715-d3cf5d00-bf5f-4204-bb5b-db3a053c9d10.png)
