### ISSUE TITLE
Group color-contrast issues by background

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#331]
One of the reasons the color-contrast rule returns so many results is because it tests each text node individually. That's certainly the right way to do it, but it bloats the results quite a bit. A single block of text can often have several issues. I think we can make this better if, rather then have the background element be the 'related node', we have those elements be the node that we have the issue on, and have all text nodes that fail it be the 'related nodes'.

**Comment by dylanb** [comment]
The data returned includes the information about the foreground color, font weight and font size. These change for the node and not the background. This means we would be losing data. It would be much better to add a filter (outside of axe-core) that will de-duplicate based on exact matches for all the attributes. The tota11y tool that Khan Academy developed does this and I think it works very well.

**Comment by WilcoFiers** [comment]
Good point! Dangit, hadn't thought of that.

So where would you suggest we do such a thing, if not in axe-core itself? We could do it in the extensions, but might it not cause confusion if the issue count is different in the extension from what it might be running axe in a different way?

**Comment by dylanb** [comment]
I think it is a UI thing. We could add an axe-core API to do this for clients but I think it is better done as a separate concern altogether.

**Comment by WilcoFiers** [comment]
Sounds good. I'll close this here then.
