### ISSUE TITLE
a[href][disabled] is still a focusable element

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#3315]
Noticed this in reviewing #3165. In determining if an element is focused, axe-core looks at the disabled attribute. However it doesn't check if that attribute is allowed for the node. So the following link is incorrectly determined as not focusable:

```html
<a href="foo.html" disabled>Hello</a>
```

This bug exists in `lib/commons/dom/focus-disabled.js`. The fix is to check `vNode.props.nodeName` before looking for the `disabled` attribute.

**Comment by dan-tripp** [comment]
I would like to fix this one.  But it might take me a few weeks to get around to it.

**Comment by WilcoFiers** [comment]
@dan-tripp You are welcome to it. Much appreciated!

**Comment by OmiCoding** [comment]
I was looking for issues to fix and I noticed this issue was already fixed in https://github.com/dequelabs/axe-core/commit/bb8b5ca760f45755ba628ac5873350b5dc4c47d1, could a maintainer mark this as closed?

**Comment by padmavemulapati** [comment]
Verified with the latest dev branch code , role=text is allowing to have "tabindex=-1" as a descendants

and with the `nested-interactive/aria-text` allowing "tabindex=-1" on elements when role is not there.
and role conflict is appearing, when `tabindex=-1` and `role=presentation`



![Image](https://user-images.githubusercontent.com/47409579/196704442-a3f14df8-d34b-4cb5-b9a2-73333c90bf51.png)



![Image](https://user-images.githubusercontent.com/47409579/196703826-ac251a67-0d68-4b23-bd26-8383394fb2fd.png)
