### ISSUE TITLE
Can getRules return "impact" and other details that are included in deque university pages?

### ISSUE THREAD

**Issue by ls-andrew-borstein** [dequelabs/axe-core#3321]
### Product: 
axe-core

### Expectation
The [`axe.getRules()` API method](https://github.com/dequelabs/axe-core/blob/f62f0cf18f7b69b247b0b6362cf1ae71ffbf3a1b/doc/API.md#api-name-axegetrules) returns a rule's [impact](https://github.com/dequelabs/axe-core/blob/1fd4b004b2543727d4a3775f355934327765baa1/axe.d.ts#L6) and ideally also the same info available in the `Compliance Data & Impact` section of each rule on a [deque university rule page](https://dequeuniversity.com/rules/axe/4.2/html-has-lang): Disabilities Affected, Requirements, Success Criteria, Section 508 Guidelines.

<img width="417" alt="Screen Shot 2021-12-03 at 7 45 24 AM" src="https://user-images.githubusercontent.com/82463438/144605434-19cda0c0-727d-4a75-865c-47b7a4d74add.png">

### Actual

Only `ruleId`, `description`, `help`, `helpUrl`, and `tags` [are returned](https://github.com/dequelabs/axe-core/blob/f62f0cf18f7b69b247b0b6362cf1ae71ffbf3a1b/lib/core/public/get-rules.js#L19-L25).

I can see WCAG Sucess Criteria and Requirements are there via the `tags` key, albeit in a truncated way that I'd need to parse, i.e.

```js
{ 
  tags: ['cat.language', 'wcag2a', 'wcag311', 'ACT']
}
```

instead of something like 

```js
{ 
  requirements: [{ id: 'wcag2a', description: 'WCAG 2.0 (A): MUST' ]
  section508guidelines: [],
  wcagSuccessCritera: { id: 311, description: '3.1.1 Language of Page' }
}
```

### Motivation

I'm trying to find a way to do something very similar to https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md but make it a _filterable/sortable_ table, so someone can view only WCAG AA rules or sort by impact (critical first). This would be part of internal documentation, helping my company and teammates to better prioritize which rules to address or to understand their impact when considering them while building new products. Although I could imagine other developers would also find a public resource like that quite useful.

Here's a live demo of what I'm attempting (with a static, non-interactive table at the moment): https://codesandbox.io/s/axe-core-get-rules-qpvmh?file=/src/App.js

I found what seemed like [a similar issue](https://github.com/dequelabs/axe-core/issues/2644) but it was unclear to me what the outcome was. I'm confused about the suggestion that the rule impact is only calculated at run time / during test evaluations, because it's is available at https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md outside of any specific test and also on each deque university rule page. 

I could potentially scrape the deque university website for that info, but if it's available in the axe-core API I'd much prefer that.

### axe-core version
4.3.5

**Comment by WilcoFiers** [comment]
It is unlikely we'll ever provide an API like this. Part of why we can make axe-core available for free is that it gets folks to our documentation pages. This is important to keep axe-core properly maintained. If there are changes you'd like to see for the documentation please let us know. We'll gladly consider those.

That said, it really isn't difficult to get that information out of axe-core. All the JSON files are included in the release, you could read out the directory. That's how the rule-descriptions.md file is created.

**Comment by ls-andrew-borstein** [comment]
Thanks for the response @WilcoFiers 👌 

> it really isn't difficult to get that information out of axe-core

I appreciate the suggestion — I'll see if I can retrieve the info I need that way. It looks like [the `any` attribute](https://github.com/dequelabs/axe-core/blob/develop/lib/rules/html-has-lang.json#L12) connects a rule to [its associated check](https://github.com/dequelabs/axe-core/blob/f62f0cf18f7b69b247b0b6362cf1ae71ffbf3a1b/lib/checks/language/has-lang.json#L2), which _does_ contain the `impact` info. 

> Part of why we can make axe-core available for free is that it gets folks to our documentation pages

I totally get that. FWIW you've got at least one vote in favor of improving the documentation such that the rules are filterable and sortable. And if that's something axe would be interested in, I'd be happy to make a separate issue to discuss how it could be implemented.
