### ISSUE TITLE
roles that allow aria-expanded and aria-roles.js question

### ISSUE THREAD

**Issue by scottaohara** [dequelabs/axe-core#3339]
ARIA 1.2 has fixed an error where ARIA 1.1 allowed `aria-expanded` on a number of elements that didn't make sense.  e.g., `role=alert aria-expanded=...`.  [ARIA issue where this topic was discussed](https://github.com/w3c/aria/issues/681) - fixed in 2019, so has been part of the initial and current ARIA 1.2 CR draft.

I noticed in the aria-roles.js file that `aria-expanded` is still marked as an allowed attribute on these roles, which at first made sense to me because the file notes on the first line that it is referencing ARIA 1.1... so since they were allowed then, if axe is still referencing ARIA 1.1 then they would still be allowed, though their use by authors is suspect / probably incorrect.   

However, upon further review of the file, there are a number of roles that were introduces in ARIA 1.2 that are also included... which again also makes sense as many of them have been implemented by browsers... but this then made me wonder if it would be a good idea for axe to also correct the `aria-expanded` allowances, even though the correction is tied to ARIA 1.2.  

Regardless of when axe might want to pull in the correction, I'd be happy to create a PR to remove the `aria-expanded` allowances from the necessary roles in this file.

**Comment by WilcoFiers** [comment]
Thanks for the update Scott. It's a little late for 4.4, but putting it on the list for 4.5.

**Comment by padmavemulapati** [comment]
Validated using axe-core develop branch code base, 
Test snippet:
```
<body>
    <button id="alert-button" aria-expanded="true" aria-controls="alert-message">
        Show Alert
    </button>

    <div id="alert-message" role="alert" >
        This is an important alert message.
    </div>
```
Not seeing any failure even `aria-expanded` make it false or even after removed completely

## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Product**                | _axe-core_ |
|**Version** | _4.7.2-canary.49eaa0e_ |
| **OS-Details**      | _MAC- Intel Core i7 - 11.6.8 _ |
|**BrowserDetails**|_Chrome Version 1115.0.5790.114 (Official Build) (64-bit)_|
