### ISSUE TITLE
Allow role=combobox for button and input type=button

### ISSUE THREAD

**Issue by scottaohara** [dequelabs/axe-core#3353]
[ARIA in HTML](https://github.com/w3c/html-aria/pull/396) is planning to allow `role=combobox` on a `button` and `input type=button` element.  

[`button role=combobox` test case](https://w3c.github.io/html-aria/tests/button-combobox.html)

Additionally, the ARIA in HTML PR adds `role=checkbox` as an allowed role for `input type=button` to match the `button` element allowances.  This was an oversight in the spec which this PR will help correct.

**Comment by MattyBalaam** [comment]
How do I configure the latest version of Axe to pass when a button has the role of combobox?

**Comment by scottaohara** [comment]
I don't think the PR for this change has landed yet, @MattyBalaam.

@WilcoFiers what else needs to happen here?  I think I addressed what I needed to in the PR?  Understood if other priorities have punted this, but it's unclear what else is needed if not just 'time'?

**Comment by MattyBalaam** [comment]
I was wondering if someone had a tip for some config which can be used as a workaround while we wait for this to land.

**Comment by straker** [comment]
For a workaround you can configure the `standards` object to allow it, similar to what the [pr is doing](https://github.com/dequelabs/axe-core/pull/3354/files#diff-71c6e1ff51ae19a73e38e88147c50e670e87b1293961bff4b9f6a21fe3b56609)

```js
axe.configure({
  standards: {
    htmlElms: {
      button: {
        allowedRoles: [
          'checkbox',
          'combobox',
          'link',
          'menuitem',
          'menuitemcheckbox',
          'menuitemradio',
          'option',
          'radio',
          'switch',
          'tab'
        ]
      }
    }
  }
})
```

@scottaohara I think this might have fallen through the cracks (as well as a few other of your prs). I'll go back and look into them.

**Comment by adcortes** [comment]
@straker , hi, i am using the axe DevTools plugins on chrome and it seems not updated yet.
Will it gonna be accepted?
I am using:
DevTools
extension: v4.41.0
axe-core: v4.4.2

**Comment by straker** [comment]
@adcortes We are planning a release later this month which should include this change. After axe-core releases, it'll probably be another couple of weeks or so before it is released into the extension.

**Comment by padmavemulapati** [comment]
Validated with the latest axe-core develop branch code base, 
test-snippet:
```


```
seeing `aria-allowed-role` failing on `button` , `role=combobox` and for `input` - `role=checkbox` 

![Image](https://user-images.githubusercontent.com/47409579/205636274-ca577505-365b-466d-867b-346ad61846cd.png)
