### ISSUE TITLE
helpURL link for `nested-interactive` rule is invalid

### ISSUE THREAD

**Issue by ecbolend** [dequelabs/axe-core#3365]
When using axe-core 4.3.4, I've receive a `nested-interactive` rule violation in a web page, but when I clicked on the helpURL to get more documentation on this rule, I got an invalid page.

Product: axe-core

Expectation: The helpURL given for a violation of the `nested-interactive` rule is an invalid URL.

The URL given is https://dequeuniversity.com/rules/axe/4.3/nested-interactive?application=axeAPI

Actual: The helpURL given for a violation of the `nested-interactive` rule is a valid URL and brings the user to a documentation page.

Motivation: I'd like for the helpURL to bring me to a valid page, so I can learn more about fixing this issue.

<pre><code>
axe-core version: 4.3.4
</code></pre>

**Comment by straker** [comment]
Thanks for the issue. So https://dequeuniversity.com/rules/axe/4.3/nested-interactive?application=axeAPI brings up the correct help page. What are you seeing on your end (what does invalid page mean)? Are you able to see other rules listed in https://dequeuniversity.com/rules/axe/4.3/?

**Comment by ecbolend** [comment]
Earlier today I was getting "version not found" error message when navigating to the link, but now I'm able to access the page without any issues. I'll go ahead and close the issue. Apologizes for the noise.
