### ISSUE TITLE
type issue on getFrameContexts

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#3371]
The `getFrameContexts` method will never return DOM Nodes, unlike what its type suggests. This makes serialisation more difficult than it needs to be.

**Comment by padmavemulapati** [comment]
Validated with the latest develop branch code base, 
`await axe.utils.getFrameContexts({exclude: [['iframe','#testFrame']] });` and 
`await axe.utils.getFrameContexts('#testFrame')`
its giving return type and with Array objects
<img width="663" alt="image" src="https://user-images.githubusercontent.com/47409579/187345263-c09ce934-9817-4151-8f8f-138ad7da28e4.png">
