### ISSUE TITLE
DPUB ARIA 1.1 - incorrect deprecation of `doc-endnotes` (plural), should have been `doc-endnote` (singular)

### ISSUE THREAD

**Issue by danielweck** [dequelabs/axe-core#3372]
Product: axe-core

Expectation: incorrect deprecation of `doc-endnotes` (plural), should have been `doc-endnote` (singular)

`doc-biblioentry` was correctly marked as `deprecated`:
https://github.com/dequelabs/axe-core/blob/2c6f0285b979b11874089a1e18ed94a917ad900a/lib/standards/dpub-roles.js#L29-L39

...however `doc-endnotes` (plural) was incorrectly marked as `deprecated`, should have been `doc-endnote` (singular):
https://github.com/dequelabs/axe-core/blob/2c6f0285b979b11874089a1e18ed94a917ad900a/lib/standards/dpub-roles.js#L96-L101

Spec. references:
* `doc-endnote` (singular): https://www.w3.org/TR/dpub-aria-1.1/#doc-endnote
* `doc-endnotes` (plural): https://www.w3.org/TR/dpub-aria-1.1/#doc-endnotes

Impacted PRs and issues:
* https://github.com/dequelabs/axe-core/issues/3253
* https://github.com/dequelabs/axe-core/pull/3280

<pre><code>
axe-core version: 4.4.0
</code></pre>

**Comment by WilcoFiers** [comment]
Wow! Good catch. Thank you so much for the report. We'll fix it right away!

**Comment by padmavemulapati** [comment]
Validated with the latest axe-core dev branch code base: 
test script : `<div role="doc-endnote"></div>` (singular)  instead `role-"doc-endnotes" (plural) 
showing failure on `aria-roles` 
![image](https://user-images.githubusercontent.com/47409579/152533452-13c882d9-fea4-4f24-a478-42f5173fc077.png)

Working as expected
