### ISSUE TITLE
Updated table of WCAG SC & Impact Status

### ISSUE THREAD

**Issue by mgifford** [dequelabs/axe-core#3412]
I'd love to see a table and CSV file of the Issue Impact (Critical/Serious/Moderate/Minor) issues.

Issue impacts are great https://github.com/dequelabs/axe-core/blob/develop/doc/issue_impact.md

But for people to adopt this framework (and abandon their own) it helps to have a simple, maintained list that allows people to understand how these issues are grouped.

I'm not sure how/when these are revised. Hopefully it is something that is updated by the core team from time to time as issues change.  

However, it would go further if people could easily see what is bundled in the JSON files.

**Comment by straker** [comment]
Thanks for the issue. I'm not quite sure I understand what it is you are asking for. Does https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md help or are you thinking about something else?

**Comment by mgifford** [comment]
That's perfect. Thanks! 

Can you link it from the Issue Impact document so that it is clear @straker - would be nice to have a clear path to/from those pages.

**Comment by straker** [comment]
I'll bring this up with the team and see what they say.
