### ISSUE TITLE
Add note to invalid IdRef value error that it may be due to a Shadow DOM boundary

### ISSUE THREAD

**Issue by joppekroon** [dequelabs/axe-core#3419]
Product: axe-core

Expectation: Indicate that the referenced id is located beyond a Shadow DOM boundary. Even a message that states that this may be potentially the reason of the error would be very helpful.

Actual: Indicates that the value of the IdRef attribute is invalid

```
    "ARIA attributes must conform to valid values (aria-valid-attr-value)"

    Fix all of the following:
      Invalid ARIA attribute value: aria-controls="id-in-shadow"
```

Motivation: It is currently quite a confusing error message if you're not acutely aware that referencing an id that is located on the other side of a Shadow DOM boundary is problematic. 

<pre><code>
axe-core version: 4.2.0
</code></pre>

**Comment by padmavemulapati** [comment]
Validated with the latest develop branch axe-core code base, 
test snippet is:
```
<div></div>
  <button id="target1" aria-describedby="test1">Button1</button>
  <div></div>
  <button id="target2" aria-labelledby="test2">Button2</button>
```
so that the failure message now is:
<img width="855" alt="image" src="https://user-images.githubusercontent.com/47409579/175059066-74f22876-5e53-4469-bf43-01cd8d2a9633.png">
