### ISSUE TITLE
False positive: "Ensures landmarks are unique" on role=region 

### ISSUE THREAD

**Issue by siiron** [dequelabs/axe-core#3425]
Product: axe DevTools extension v4.24.4, using axe-core v4.4.1

Expectation: Expected no errors on page

Actual: div-tags using role="region" with the aria-labelledby-attribute pointing to unique ids, still throws 1 moderate error using axe: "Ensures landmarks are unique". If only one accordion is present on screen, the error goes away.

Motivation: I think this is a false positive

Demo: https://cdpn.io/pen/debug/PoEWbYY/8b366773a3213bf5f0a8e30648fdad79
Code: https://codepen.io/siiron/pen/PoEWbYY/8b366773a3213bf5f0a8e30648fdad79

**Comment by straker** [comment]
Thanks for the issue. The reason `landmark-unique` is a violation is because all the text on the buttons are the same. Each accordion has 1 non-hidden region (`sect1` and `sect6`), which both have the same accessible name. If the button text get's updated to be unique, then the rule passes.

**Comment by siiron** [comment]
Ah, so it's not enough that the ids referenced by aria-labelledby are unique, but the text also needs to be unique. I was not aware of that. I've updated the demo with numbers on the buttons. It now passes: https://cdpn.io/pen/debug/PoEWbYY/8b366773a3213bf5f0a8e30648fdad79

Thank you @straker!
