### ISSUE TITLE
Ambiguous Link: same name/description as another link but different href.

### ISSUE THREAD

**Issue by smustgrave** [dequelabs/axe-core#3432]
Feature request.  If links are the same it should be flagged. 
Example "Read more" is a violation.

**Comment by straker** [comment]
Thanks for the issue. This sounds similar to the [identical-links-same-purpose rule](https://dequeuniversity.com/rules/axe/4.4/identical-links-same-purpose?application=RuleDescription). The rule only flags elements as Needs Review, so it won't show violations for these nodes. Does the rule cover your request?

**Comment by smustgrave** [comment]
I apologize I just realized our runner was not using warnings or notices.  This can be closed

**Comment by smustgrave** [comment]
Would argue though that this should be an error and not warning.  If the page has a 100 "Read More" links a screen reader person would be screwed
