### ISSUE TITLE
Invalid session id 

### ISSUE THREAD

**Issue by u5ha12** [dequelabs/axe-core#3433]
Product:  "@axe-core/webdriverjs": "^4.4.2",
Expectation: list all the violations when I run axe -library on across all our browsers and desktop app's 

Actual:</ error: invalid session id
[2022-04-07T20:30:36.717Z]          Please check out https://github.com/dequelabs/axe-core-npm/blob/develop/packages/webdriverjs/error-handling.md>>

Description Our desktop app is  elctron wrapper around a browser

**Comment by Zidious** [comment]
Hey @u5ha12, 

Thanks for raising this issue, 

Could you please provide a snippet of how you set up axe-core/webdriverjs as well as a snippet of a test?

**Comment by u5ha12** [comment]
```
async function collectAccessibilityData() {
  const results = await new AxeBuilder(this.driver).analyze();
  return this.attach(Buffer.from(JSON.stringify(results.violations, undefined, 4)).toString('base64'), 'text/plain');
}
```
and added afterhook to excute 
`After(collectAccessibilityData);`
it's running well on browsers but invalid session id for all desktop app's on three environments (mac,windows and linux)

**Comment by WilcoFiers** [comment]
Not officially, but I don't see any reason why it wouldn't work.

**Comment by WilcoFiers** [comment]
Lacking any recent comments, and since I don't see any follow-up action from our end I'm going to close this.
