### ISSUE TITLE
Runtime issue: Cannot read properties of undefined (reading 'source')

### ISSUE THREAD

**Issue by ktdid518** [dequelabs/axe-core#3435]
<< Please describe how you encountered this issue >>

axe-core version: `4.4.1`
axe-extension version: `4.25.0`

```
TypeError: Cannot read properties of undefined (reading 'source')
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:167184
    at Array.map (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:167154
    at Array.forEach (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:167104
    at Array.forEach (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:167000
    at Array.map (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:166668
    at Array.map (<anonymous>)
```

**Comment by ktdid518** [comment]
Attempting to scan a quiz form withing an iframe

**Comment by straker** [comment]
Thanks for the issue. Is the quiz form public that we could take a look at it and see what might be the issue?

**Comment by straker** [comment]
Gotcha. I'm going to close this issue as it seems to be working but also since without a page to test it on we can't do much to fix it. 

Please fell free to reopen if this continues to be a problem and when the affected page becomes public.

**Comment by ktdid518** [comment]
@straker Hi, Can you please delete this customer service chat from public view? I was never informed that CS conversations would be made public. I just deleted sensitive info from one of the threads. Please delete any others if they exist. Can you confirm when that's done? Thank you.

**Comment by straker** [comment]
@ktdid518 Can do. I deleted the reversion from history.

**Comment by ktdid518** [comment]
Thank you!

Any way to ensure that any axe help requests I have in the future are not made public? I don’t want to discover my phone number in a public forum again.


KTdid.

Katie Diduch
Accessibility Web and Print Designer, Accessibility Auditor, and Accessible Document Creator and Remediator

***@***.***
518.629.6256

KTdid.Design <http://www.ktdid.design/>
LinkedIn <https://www.linkedin.com/in/katiediduch/>

**Comment by straker** [comment]
@ktdid518 If you respond to these issues via email it'll automatically add your email signature in your comment. To prevent that you'll need to navigate to the issue in a browser and respond through the comment form.

**Comment by ktdid518** [comment]
Good to know. I had no idea that my responses would go anywhere external. Thank you!
