### ISSUE TITLE
Allow role="textbox" for H tags with contenteditble="true" 

### ISSUE THREAD

**Issue by Develliot** [dequelabs/axe-core#3436]
Product: axe-core 

Expectation: If I have an edit-in-place type web page you can click on something and edit it, for example I have a title in an h1 tag, the user clicks on it and it has contenteditable="true" and appears in a mini form, I should be allowed to add role="textbox" on the h1 

Actual: axe core says h1 that is contenteditable='true' is not allowed to have role="textbox"  this doesn't seem to be a problem with p tags only h tags

"ARIA role should be appropriate for the element"

Motivation: to make edit in place forms for WYSIWYG editors more a11y friendly

<pre><code>
axe-core version: 4.4.1

For Tooling issues:
- Node version: 14 
- Platform:  Mac
</code></pre>

**Comment by WilcoFiers** [comment]
What this axe-core rule essentially does is test if you've correctly followed guidance of HTML in ARIA. There are only a few roles allowed on h1 - h6 elements. none, presentation, tab, and doc-subtitle

You can see the spec here: https://www.w3.org/TR/html-aria/#el-h1-h6


I don't think you should need to put role=textbox on elements with contenteditable. I'm not familiar enough with how the accessibility of contenteditable works to say for sure, but that seems problematic to me. In either case, this is probably something you'll want to bring to the folks behind ARIA in HTML. You can find their github here: https://github.com/w3c/html-aria/issues

**Comment by WilcoFiers** [comment]
I'm going to assume the response no further conversation is happening here. Closing this as a non-issue.
