### ISSUE TITLE
axe.commons.text.accessibleText returns <noscript> content

### ISSUE THREAD

**Issue by isner** [dequelabs/axe-core#344]
`axe.commons.text.accessibleText()` identifies the content of `<noscript>` tags as accessible text.

To reproduce this behavior, visit [http://aventuraannarbor.com/](http://aventuraannarbor.com/), find the Twitter _link_ (`<a>`) in the page footer, and pass this element reference into `axe.commons.text.accessibleText()`. It returns the content of the `<noscript>` tag that is a child of the anchor. If you remove the `<noscript>` tag, `accessibleText()` returns a blank string, which is expected.

The links in question:
<img width="1021" alt="screen shot 2017-06-05 at 4 00 27 pm" src="https://cloud.githubusercontent.com/assets/5174819/26832524/c95cc3a4-4a9d-11e7-9f8b-ed8c9f8145bd.png">

**Comment by jkodu** [comment]
The website in question http://aventuraannarbor.com/ has changed and I cannot seem to spot the social links.

@isner by any chance, can you help replicate this?

The question I have though, to see content with in a place that is `noscript` js has to be disabled. How then was `axe` loaded? Was it an axe instance inside the extension, to which you passed this argument?

I tried by dynamically creating a node like so:

```js
var node = document.createElement('noscript')
node.innerHTML = '<a href="awesome.html">awesome</a>'
axe.commons.text.accessibleText(node.firstChild)
```

But does not produce the description above.

I will close this issue for now. Please reproduce if you can replicate again & do provide a jsfiddle or demo.
