### ISSUE TITLE
Add Firefox's color contrast checker for text on background image

### ISSUE THREAD

**Issue by shaal** [dequelabs/axe-core#3447]
Product: axe-core

Expectation: << Describe what you expect the product to do >>
Add Firefox's automatic color contrast checker for text on complex background image (e.g. a gradient)
https://firefox-source-docs.mozilla.org/devtools-user/accessibility_inspector/#color-contrast
![image](https://user-images.githubusercontent.com/22901/166485731-a65e7195-6288-4c7f-a316-4e7bd7921347.png)

Actual: << Describe what the product actually does >>
Currently axe-core only checks for contrast of text over simple background color.
When a text is over gradient or complex image background, axe-core adds it to "manual review" list.

Motivation: << Describe why you want the behavior to be changed >>
Many websites use images as background, and manually each text on complex image background, is a daunting task that takes a lot of time. The technology is ready (Firefox, since version 65), so we should utilize it and get computers to test it automatically instead of people testing manually.

**Comment by WilcoFiers** [comment]
I'm afraid that will not be possible. There are no APIs in the DOM to allow this sort of thing. Firefox has direct access to the paint layer of the browser, axe-core does not. We are working on improving color contrast testing in the axe DevTools extension, but it will not be possible to do this in axe-core itself unfortunately.

**Comment by shaal** [comment]
@WilcoFiers thank you.
Would it be possible to add this functionality to the Axe browser-extension?
