### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by imartinflores** [dequelabs/axe-core#3449]
Hello guys, I am just starting with Axe. I am trying it with Playwright in JS. Is there anyway to generate a report without using another npm package ?

I am just using:

`new AxeBuilder({page}).analyze();`
And logging the results in the console, how can, instead of logging them, generate a report ?
Thanks!

**Comment by WilcoFiers** [comment]
With a report I assume you mean something in HTML or PDF, something like that? If so the answer is no. Axe-core packages output a data structure. Turning that into something else isn't part of the open source functionality we provide. I believe there is one or the other reporter on NPM if you look. Deque also provides report generation as part of [axe DevTools Enterprise](https://www.deque.com/axe/devtools/).

**Comment by imartinflores** [comment]
Thank you @WilcoFiers , yes, that was what I was wondering. Makes sense, I will take a look at that, thank you again!
