### ISSUE TITLE
Utilizing axe-core in a unit-test workflow

### ISSUE THREAD

**Issue by phun-ky** [dequelabs/axe-core#345]
After a landslide of inspiration from @marcysutton at web rebels, I wanted to test out axe-core, but I find no decent documentation to include this in an existing unit-test workflow. 

How can I incorporate this, say in a npm script task? or as unit tests?

**Comment by WilcoFiers** [comment]
Glad to hear you enjoyed Marcy's web rebels talk. I heard it was an excellent event all together!

As for your question, there are quite a few ways you could do it. We've created a few examples here:
https://github.com/dequelabs/axe-core/tree/develop/doc/examples

There's also the axe-webdriverjs project which you could use:
https://github.com/dequelabs/axe-webdriverjs

Alternatively, you could run axe-cli. With exit code enabled you can run it on a list of pages you've got hosted somewhere, and it'll spit out errors it finds.
https://github.com/dequelabs/axe-cli

Hope this helps. Let us know!

**Comment by phun-ky** [comment]
I'm currently using a webpack + react combo, and can't test the whole SPA (authorization) like it is suggested. What is the best approach to use axe-core component-wise?  Can I use it in existing jsdom test? :

    /*eslint-env node, mocha */
    import React from 'react';
    import jsdom from 'jsdom';
    import { mount } from 'enzyme';
    import chai, { expect } from 'chai';
    import chaiEnzyme from 'chai-enzyme';

    import DropDown from './DropDown';

    const doc = jsdom.jsdom('<!doctype html><html><body></body></html>');
    global.document = doc;
    global.window = doc.defaultView;

    chai.use(chaiEnzyme());

    describe('<DropDown />', () => {
      it('renders a `.dropDown`', () => {
        const props = {
          id: 'DropDownSpec',
          data: [
            {
              id: '123',
              displayName: 'Foo'
            },
            {
              id: '124',
              displayName: 'Bar'
            }
          ]
        };

        const wrapper = mount(<DropDown {...props} />);
        expect(wrapper.find('.dropDown')).to.have.length(1);
      });
    });

**Comment by WilcoFiers** [comment]
You certainly can! Mind you, JSDOM is kind of slow, and we can't run color tests on it. But it's a good start. We use it internally. Mount doesn't append elements to the DOM, so you'll need to do that, then you can call `axe.run()` with the node in the first argument. Let me put together an example with jsdom / React.

**Comment by WilcoFiers** [comment]
@phun-ky I created an example here, which I think shows you all you need.
https://github.com/dequelabs/axe-core/tree/jest-example/doc/examples/jest%2Breact

Feel free to reach out to us on Gitter if there's anything else we can help with. https://gitter.im/dequelabs/axe-core

**Comment by dylanb** [comment]
You can also use [react-axe](https://www.npmjs.com/package/react-axe) for in-browser testing....

**Comment by mohanraj-r** [comment]
> I created an example here, which I think shows you all you need.
> https://github.com/dequelabs/axe-core/tree/jest-example/doc/examples/jest%2Breact

The working link is [axe-core/doc/examples/jest_react at develop · dequelabs/axe-core](https://github.com/dequelabs/axe-core/tree/develop/doc/examples/jest_react)
