### ISSUE TITLE
Understanding performanceTimer metrics

### ISSUE THREAD

**Issue by khiga8** [dequelabs/axe-core#3451]
Hi team.

I'm playing around with the `performanceTimer` config option for the first time. It seems pretty great. I can't find much about how to interpret the output so wanted to get some clarification.

This is a sample output of running a single rule on a page:

```
gather ( 0 ): 8641.300000071526ms
axe.js:4923 Measure audit_start_to_end took 18.699999928474426ms
axe.js:4923 Measure rule_area-alt took 16.299999952316284ms
axe.js:4923 Measure rule_area-alt#gather took 15.800000071525574ms
axe.js:4923 Measure rule_area-alt#matches took 0ms
axe.js:4923 Measure runchecks_area-alt took 0.10000002384185791ms
axe.js:4923 Measure axe took 311.8000000715256ms
```

It looks like this last output is a measure of the _total_ time it takes for the axe scan to complete from start to finish. What is `audit_start_to_end`?  

I'm also trying to make sense of this `gather` output which doesn't seem factored in the `axe` metrics. Could someone help me understand?

**Comment by straker** [comment]
Thanks for the issue. So the `performanceTimer` options is mostly used as an internal tool to gauge how each individual rule performs on a page. The time to run all the rules is measured with  `audit_start_to_end`, and then generating the report and all the unique selectors is measured with `axe`.

After that, each rule has a few different outputs to let us know how each part of a rule is performing. So `#gather` is the step to find all the nodes in the current page that apply to the rule, `#hidden` is how long it took to make sure each node was visible, `#matches` is how long the rule's matcher function took on all the gathered nodes, and `#runchecks` is how long all the checks took for all the gathered nodes.

You can see how we've used it to improve performance of axe-core with [a currently opened pr](https://github.com/dequelabs/axe-core/pull/3423).

**Comment by khiga8** [comment]
@straker Thanks for the quick follow-up. This is helpful! 

Now my only confusion is how to interpret this first metric which is much larger than the `Measure axe took` time:
```
gather ( 0 ): 8641.300000071526ms
```

This appears distinct from the `#gather` called on a per rule basis like `rule_area-alt#matches ` that you seem to be referring to when you say:

> step to find all the nodes in the current page that apply to the rule

**Comment by khiga8** [comment]
Also, greatly looking forward to the speed improvements in your open PR. Thank you for your work!

**Comment by straker** [comment]
Ya, that `gather ( 0 )` metric is a little confusing. I don't remember what the measure is (something like the current time of the run or something), but it outputs the number of nodes found from the gather step. I've been meaning to fix that title for a bit but haven't gotten around for it.

**Comment by khiga8** [comment]
Hm ok. I have another clarifying question since it's not fully clicking with me: how is it that this time: `gather ( 0 ): 8641.300000071526ms` significantly exceeds `axe.js:4923 Measure axe took 311.8000000715256ms`? It didn't seem like the axe scan was taking over 8 seconds.

Does `axe` took not stand for the *total* time?  Or is there no output that stands for the total `axe.run` time?

**Comment by straker** [comment]
It's just that the `gather ( 0 ): 8641.300000071526ms` is measuring a completely different thing and not how long the thing ran for. It's a very misleading output

**Comment by khiga8** [comment]
That's good to know. I'll ignore it too, then. Thanks for all the clarification.

**Comment by khiga8** [comment]
Hi! I have a couple of follow-up questions!

I see that an axe scan will take at minimum a couple hundred ms even on a smaller page with a few rules. As I'm understanding it, this is due to axe's architecture which relies constructing a Virtual DOM per `axe.run`. This use of a Virtual DOM seems to be for good reason but I would like to understand it better.

Our team has been exploring the idea of a runtime accessibility checker to gather accessibility violation data as developers are navigating pages. We do not necessarily need to run all the checks at once and want to avoid interfering with the user.

With every `axe.run` call, a VirtualDOM is constructed and all the enabled checks are run at once. I believe axe is meant to be used in a more "stop what you're doing" kind of way. 

I'd love to know if the team has any thoughts on if the sort of thing we want to try to achieve is possible with axe's architecture and if there is interest to support this sort of performant runtime use. Would love to hear your thoughts.

**Comment by dylanb** [comment]
@khiga8 I sent you an email

**Comment by straker** [comment]
Going to close this issue as I believe the questions were answered here or offline.
