### ISSUE TITLE
Have axe.getRules() return actIds

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#3469]
A while back we included an `actIds` property to rules for easier mapping between axe-core and ACT. This data is in axe-core, but there is no way to get it out.

This info is too niche I think to be useful in results, but there should be some way to get at it at least. I propose we use `axe.getRules()` for that. Seems like the easiest way to get that done.

**Comment by padmavemulapati** [comment]
Validated with the latest axe-core develop branch code base source, `axe.js` , with `axe.getRules()` it is displaying the total ruleIds, 97 totally.
![image](https://user-images.githubusercontent.com/47409579/170037166-8c1ea5fc-0804-435e-9533-f429f86587d2.png)
