### ISSUE TITLE
frame-title rule should not have the wcag241 tag

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#3483]
Not having a title on a frame isn't a guaranteed failure of SC 2.4.1 Bypass Blocks. There are other ways to bypass blocks then through frames.

To address just remove the `wcag241` tag from `lib/rules/frame-title.json`.

**Comment by padmavemulapati** [comment]
Validated with the latest code base, not seeing `wcag241` tag for `frame-tile`
<img width="1295" alt="image" src="https://user-images.githubusercontent.com/47409579/187349049-1ac01749-5bb2-45f0-ba92-6b831064016e.png">
Script:
`<iframe tabindex="-1" srcdoc="<a href='/' tabindex='-1'>Home</a>"></iframe>`
