### ISSUE TITLE
Update axe-core ACT tests

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#3499]
For axe-core 4.5 we're doing a lot of work to improve consistency with ACT rules. This is going to let us run more rules in the act-test job. We'll need to make sure to enable those.

**Comment by straker** [comment]
Use https://wai-wcag-act-rules.netlify.app/standards-guidelines/act/implementations/axe-core/ to determine which rules to bring over (based on which ones we are conformant with).
