### ISSUE TITLE
Potential issue with Aria 1.1 role=feed

### ISSUE THREAD

**Issue by derekjohnson** [dequelabs/axe-core#350]
I'm not totally sure if this is an issue as https://github.com/dequelabs/axe-core/issues/91 states all ARIA 1.1 roles are supported.

However [`role=feed`](https://www.w3.org/TR/wai-aria-1.1/#feed) is marked as an error in Lighthouse. [I opened an issue there](https://github.com/GoogleChrome/lighthouse/issues/2468#issuecomment-307170188) and was directed here.

I looked in https://github.com/dequelabs/axe-core/blob/9ce24bc9babdf33fff10dfeb4ef1c6d16f57df08/lib/commons/aria/index.js and https://github.com/dequelabs/axe-core/blob/020fd150ed0bf0702a89d19712bd38ea0c3817d8/test/integration/rules/aria-roles/aria-roles.html which seem like good places to look, but I'm not 100% sure, and `feed` isn't there.

**Comment by dylanb** [comment]
@derekjohnson thank you for reporting this. We will definitely add this to the rules. We have not researched the support for this role. Do you know which assistive technologies support this behavior?

**Comment by derekjohnson** [comment]
I haven't researched it either @dylanb, nor can I find any resources on the subject.

I have just tested in VO on Safari and it's not supported there.

**Comment by WilcoFiers** [comment]
@dylanb Isn't something like `role=feed` more a case of progressive enhancement? I.e. the page works well enough without AT support for it, but once support lands, users will have a better experience. Do you know of any scenario in which using it actually causes an accessibility problem?

**Comment by dylanb** [comment]
@WilcoFiers I agree - I just wanted to know where the support is currently

**Comment by WilcoFiers** [comment]
I've gone through the ARIA 1.1 spec and worked out a list of rules/attributes that I think we should allow in axe.

### ARIA 1.1 roles/attrs allowed:

- term role
- feed role
- aria-orientation
- aria-setsize and aria-posinset
- aria-modal
- aria-current
- aria-placeholder
- aria-keyshortcuts
- aria-colcount, aria-rowcount, aria-colindex, aria-rowindex, aria-colspan, and aria-rowspan.

### ARIA 1.1 roles/attrs NOT YET allowed

- cell and table roles
- searchbox role
- figure role
- switch role
- none role
- text role
- aria-roledescription
- aria-details

**Comment by dylanb** [comment]
Of the roles you say we should not yet allow - the following roles are already supported in axe

- none
- text
- switch
- searchbox

Of the attributes you say should be supported, the following already are:

- aria-orientation
- aria-setsize
- aria-posinset
- aria-current
- aria-colcount, aria-rowcount, aria-colindex, aria-rowindex, aria-colspan, and aria-rowspan

Although there is a known issue with posinset and setsize for which we have a ticket in our internal JIRA
