### ISSUE TITLE
add option to isFocusable to take into account negative tabindex

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core#3500]
The [isFocusable function](https://github.com/dequelabs/axe-core/blob/develop/lib/commons/dom/is-focusable.js) currently does not take into account negative tabindex (and for the default use case it shouldn't take into account negative tabindex). This causes us to pair the function call with a check on tabindex to ensure that the element is currently keyboard focusable and not programmatically focusable.

```js
const tabindex = vNode.attr('tabindex');
if ((isNaN(tabindex) || tabindex >  -1) && isFocusable(element)) {
  // ...
}
```

We should add an option to the function that enables looking for negative tabindex and changes the return to `false` for the element. Something like `programmatically: false` or `noNegativeTabindex: false`.

```js
if (isFocusable(element, { programmatically: false }) {
  // ...
}
```

**Comment by padmavemulapati** [comment]
Validated using latest develop branch code base, 
If negative tab index is there within the frame it is failing but if it is in `focussible` area, then it is ignoring
Script:
```<iframe title="frame"  srcdoc="<a href='/' tabindex='-1'>Home</a>"></iframe>
<script src="/axe.js"></script>
```
![image](https://user-images.githubusercontent.com/47409579/188117741-e8ed0c0b-7814-4d34-a85f-f7d0973f2cb6.png)
