### ISSUE TITLE
Add Feature for mark if scanned issue is "Global" issue or not

### ISSUE THREAD

**Issue by lw-pwc** [dequelabs/axe-core#3508]
Hi axe-core team,  can you help to check if an enhancement feature can be added, for scanned issue results, mark it if it's a global issue or not. 

We know current ruleset impact criticality does consider the count of issues occurrence upon same violation requirements; 
Whereas it would be helpful, if the same issue has been reported across every scanned pages, the report can show additional markons that this is a "Global" issue, so to make user easilier to identify such global issues? 

This request is for an enhancement feature that can be applied across all rulesets in axe core, rather than bug. 

The feature is raised for axe-core npm library.

Product: axe-core 

Expectation: Get the returned result meta data additionally with global issue or not 

Actual:  no global markon currently

Motivation:  DGet the returned result meta data additionally with global issue or not

<pre><code>
axe-core version: 4.4.2

Browser and Assistive Technology versions

**Comment by jthickens** [comment]
Hey there! Could you reach out to helpdesk@deque.com with this request?

**Comment by WilcoFiers** [comment]
This isn't something we can do in axe-core itself. Anyone interested in such features, use the above e-mail to get in touch. This is something we can potentially do in axe DevTools.
