### ISSUE TITLE
Option to disable telemetry for axe Linter

### ISSUE THREAD

**Issue by robinmetral** [dequelabs/axe-core#3526]
- Product: axe Linter
- Expectation: it should be possible to disable telemetry
- Actual: I don't think it is?
- Motivation: privacy, compliance
- axe versions: irrelevant

First things first: thanks for the axe Linter! It's still not working super consistently for me, but caught a few things here and there, and I'm excited to seeing future progress with it.

I just wanted to follow-up on the following statement on [the extension's page](https://marketplace.visualstudio.com/items?itemName=deque-systems.vscode-axe-linter):

> Axe-linter gathers a minimal amount of telemetry in order to assist in monitoring the plugin's heartbeat.

If telemetry is used for general monitoring, surely it shouldn't be required for everyone? I'd really like an option to disable this, for privacy reasons.

Apologies if the option already exists—I haven't found it documented anywhere (the link on [this page](https://marketplace.visualstudio.com/items?itemName=deque-systems.vscode-axe-linter&ssr=false#qna) is broken)

**Comment by jthickens** [comment]
Thanks for reaching out. I’m happy to hear you’re getting some good use out of axe-linter. 

Telemetry/usage data is an important part of our product and allows us to verify the health of our code in the wild and provides us with essential feedback. Any data axe-linter produces is completely anonymous, and doesn’t capture any source code or other potentially sensitive information. The gathering of telemetry/usage data is part of the axe-linter license agreement linked from the marketplace listing [here](https://marketplace.visualstudio.com/items/deque-systems.vscode-axe-linter/license). If you have further concerns, I’d be happy to discuss them with you.

I’d also like to know more about the consistency issues you’ve been having. Could you elaborate on that as well?

**Comment by robinmetral** [comment]
Thanks a lot for your reply @jthickens, even if it's not the one I was hoping to hear 😕 I understand the reasoning behind it and will probably continue using the linter, but still wish that data wasn't indiscriminately collected without regard for user preferences. On the web when a user enables DNT (do not track), it doesn't mean "anonymous data is okay", it means "do not track".

About consistency, I haven't pinned anything down, but some errors have been flagged in some contexts and went unseen in others. Could be related to file type or layers of abstractions—I'm not sure how the linter works under the hood so it's hard for me to tell. If I notice patterns I'll be sure to open a separate issue 🙂 Take care!
