### ISSUE TITLE
Backwards compatibility for node removed as part of a patch

### ISSUE THREAD

**Issue by apettenati** [dequelabs/axe-core#3537]
Product: axe-core
Expectation: run on older versions of node

Actual: requires node engine of >=12 with a only a patch change

Motivation: removing support for node versions prior to 12 should be a breaking change

![image](https://user-images.githubusercontent.com/71611913/178343850-7db353ce-23ff-4bf2-923e-233fc2e1a0fa.png)

[This commit](https://github.com/dequelabs/axe-core/pull/3378/files) deployed in version 4.4.2 removed support for node versions under 12. This caused a breaking change.

axe-core version: 4.4.2

For Tooling issues:
- Node version: 10
- Platform:  Liniux

**Comment by WilcoFiers** [comment]
Thanks for bringing this up. We have definitely made a mistake there.

**Comment by WilcoFiers** [comment]
@apettenati @ljharb Axe-core 4.4.3 was released yesterday. This should be fixed. Apologies for the inconvenience.
