### ISSUE TITLE
Potential false positive for role=radiogroup when wrapping a table containing radio buttons

### ISSUE THREAD

**Issue by mfairchild365** [dequelabs/axe-core#3541]
axe throws this error: "Certain ARIA roles must contain particular children" - stating that role=radiogroup is missing required children... even though they are present (but within a table). Interestingly, if role=radiogroup is changed to role=group... axe no longer throws the error.

I believe this may be a false positive.

Here is an example: https://codepen.io/mfairchild365/full/PoRPMqY (please note that this table is intentionally silly... real world examples of this do exist).

Product: axe Extension

Expectation: axe does not throw the above-referenced error

Actual: axe throws the above-referenced error

Motivation: << Describe why you want the behavior to be changed >>

<pre><code>
axe-core version: 4.4.2
axe-webdriver, extension or other integration version: 4.31.2
</code></pre>

**Comment by WilcoFiers** [comment]
Thanks Michael, yeah this shouldn't be failed. Unlike something like listitems in lists, radiobuttons do not need to be a direct child of the radiobutton group.

**Comment by WilcoFiers** [comment]
It looks like this was fixed already in axe-core 4.5 in PR https://github.com/dequelabs/axe-core/pull/3597.
