### ISSUE TITLE
Warn during test when Node 12+ isn't used

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#3544]
PR https://github.com/dequelabs/axe-core/pull/3538, axe-core is back to using Node v4 as its minimum. That's true enough when it comes to importing and using axe, but Node 12+ is required for building / testing. We should add an explicit warning of sorts to call out when an older version of Node is used to build / test axe.

I am very open to how to do this. Easiest might be to add some little script that returns exit code 1 in the `pretest` and `prebuild` scripts in package.json.

**Comment by pandu-supriyono** [comment]
Hi, I have the time and motivation to look into this.

Do I understand correctly that we want to produce a fatal error with exit code 1 if the minimum Node version isn't found instead of a warning message that exits with exit code 0?

**Comment by straker** [comment]
Thanks for taking this on @pandu-supriyono. I believe having the build script or test script exit with exit code 1 if Node version is < 12 would be fine. Adding a note in the developer guide on minimum Node version would also be very helpful.
