### ISSUE TITLE
Issue is not raising when same font color and background color applied

### ISSUE THREAD

**Issue by ArunShankar424** [dequelabs/axe-core#3551]
I'm using a text element with same background color and same font color and yes axe couldn't flag the issue. the text visibility issue is not reproducing in Axe core. This issue should raise the flag(https://dequeuniversity.com/rules/axe/4.3/color-contrast?application=axeAPI)

**Comment by straker** [comment]
Thanks for the issue. Do you have a code snippet or site that reproduces that error?

**Comment by WilcoFiers** [comment]
This is intentional. This is effectively hidden text, so axe-core treats it as it does any other hidden text. It's ignored.
