### ISSUE TITLE
incomplete nodes should have impact

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#356]
The incomplete nodes currently don't have their impact property set. Makes sense, but then when it's reviewed, and set to violation, the impact is undefined. It's probably best to pass the potential impact along so it can be used when it was determined the result is a violation.

**Comment by marcysutton** [comment]
They do have it set from what I can tell. I just ran axe-core on a page with incomplete color contrast issues and the impact is set to serious in both the rule and the check.

Was there a specific rule that prompted this, or is it just not being handled correctly in the extensions?

**Comment by WilcoFiers** [comment]
Should be resolved with #465.
