### ISSUE TITLE
Request for help with an article about Axe-core

### ISSUE THREAD

**Issue by resonantspectrum** [dequelabs/axe-core#3578]
I would like to interview a team member for an article about making web sites in Health IT more accessible. I've interviewed people from a couple of proprietary companies, as well as designers, but it's important to include Axe-core. I would just like a little background on who started Axe-core and why, whether you've had special achievements to boast about, and anything else you would like my technical readers to know about. I would also appreciate someone reviewing my draft after I finish it. Email is a good way to reach me: username andyo at praxagora dot com. The site I'm writing for is healthcareittoday.com.

**Comment by WilcoFiers** [comment]
E-mail sent. Closing this.
