### ISSUE TITLE
presentation-role-conflict-matches.js is unused

### ISSUE THREAD

**Issue by dbowling** [dequelabs/axe-core#3591]
The `presentation-role-conflict` rule currently points to [has-implicit-chromium-role-matches.js](https://github.com/dequelabs/axe-core/blob/develop/lib/rules/has-implicit-chromium-role-matches.js), leaving [presentation-role-conflict-matches.js](https://github.com/dequelabs/axe-core/blob/develop/lib/rules/presentation-role-conflict-matches.js) unused.

This looks like it was introduced in PR #2948 ([relevant diff](https://github.com/dequelabs/axe-core/pull/2948/files#diff-52dd98210580be22b94fc58cd519efdc593214654489f3c089128a7fb35ca59a)).

**Comment by WilcoFiers** [comment]
Lets just deprecate it.
