### ISSUE TITLE
Incorrectly flagging historic UI elements for poor contrast

### ISSUE THREAD

**Issue by AvidaHancock** [dequelabs/axe-core#3607]
### Product

axe-core

### Product Version

Generated by Lighthouse 9.6.5

### Lastest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
We altered the colour contrast(over 2 months ago) to our One Trust Cookie banner.
I expected Lighthouse to scan the latest changes and new UI button elements showing black font.

#### Actual
The report flats the historic elements showing white font which are not acceptable for accesibility. 

#### How to Reproduce
Scan this page using [Lighthouse:]
https://eequ.org/s?view=map&zoom=12&neLat=51.194460&neLng=0.247999&swLat=50.998470&swLng=-0.180467
Compare actual cookie banner buttons to reported failing buttons

#### Additional context
We changed the buttons 2 months ago.

<img width="1032" alt="Screenshot 2022-08-15 at 20 01 52" src="https://user-images.githubusercontent.com/35893319/184700381-e459f3e1-c8b8-42ea-b51b-7a30726ce893.png">
![Screenshot 2022-08-15 at 20 01 05](https://user-images.githubusercontent.com/35893319/184700384-1186e7c2-726b-44bb-8c1b-1002790b4423.png)
[Lighthouse Report Viewer.pdf](https://github.com/dequelabs/axe-core/files/9339289/Lighthouse.Report.Viewer.pdf)

**Comment by straker** [comment]
Thanks for the issue. However, I'm not sure I follow. I followed the link and the cookie banner I get uses green (#34c759) with white (#FFFFFF), which fails 3.5:1 color contrast (2.21:1).

<img width="642" alt="image" src="https://user-images.githubusercontent.com/2433219/184713243-afee2e5d-48ea-482a-a765-c439f3aa1351.png">

**Comment by AvidaHancock** [comment]
Hi @straker,
Thanks so much for assisting!
Do you mean you followed [the link to our map search page](https://eequ.org/s?view=map&zoom=12&neLat=51.194460&neLng=0.247999&swLat=50.998470&swLng=-0.180467) and saw this white font?

When I open this page incognito I see black font as per our design specifications on One Trust.

<img width="1914" alt="Screenshot 2022-08-16 at 09 19 29" src="https://user-images.githubusercontent.com/35893319/184833009-1b373306-4f06-4d05-a00a-2ca146283b26.png">

**Comment by AvidaHancock** [comment]
Huge apologies @straker  - on further investigate we appear to have 2 cookie templates floating around and have resolved this.
