### ISSUE TITLE
Avoid duplicates between color-contrast and color-contrast-enhanced

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#3612]
### Product

axe-core

### Feature Description

Currently the color-contrast-enhanced rule fails nodes that also fail the color-contrast rule. This creates duplicates when both rules are on. This isn't ideal. A better solution would be to pass nodes that are below the contrast threshold of color-contrast.

There are already options available in color-contrast-evaluate to do this. We should add caching to this evaluate method to avoid calculating the contrast of a node more than once though, since this is a fairly slow operation.

**Comment by WilcoFiers** [comment]
Can probably memoize `getBackgroundColor`, that'll be the quickest way to cache this.

**Comment by padmavemulapati** [comment]
Validated with the latest develop branch code base, 
when run both `color-contrast-enhanced` and `color-contrast` , now it is not resulting both incomplete results instead it is giving only `color-contrast` incomplete result and avoiding duplicate

Test snippet:
```
<p id="target" style="color: #666; background: linear-gradient(to right, #FFF, #0FF); width: 300px">
    Some text in English
  </p>
  <p id="target" style="color: #666; background: linear-gradient(to right, #FFF, #0FF); width: 300px; font-size: 18pt;">
    Some text in English
  </p>
  
```




![Image](https://user-images.githubusercontent.com/47409579/196725090-de60f60f-f99f-450e-bc38-ee70c2875471.png)
