### ISSUE TITLE
meta-refresh-no-exceptions should not create duplicate issues with meta-refresh

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#3613]
### Product

axe-core

### Feature Description

If both `meta-refresh-no-exceptions` and `meta-refresh` run, if something fails `meta-refresh` it is also reported as an issue under `meta-refresh-no-exceptions`. This duplicate issue isn't ideal. We should update `meta-refresh-no-exceptions` so that it only fails if `meta-refresh` isn't failed; i.e. it only fails if the refresh delay is over 20 hours long.

**Comment by padmavemulapati** [comment]
Validated with the latest develop branch code base,
When run both `meta-refresh-no-exceptions` and `meta-refresh` , only `meta-refresh` is failing
test script fro `meta-refresh-no-exception`
```
<meta charset="utf8" />
    <title>Meta-refresh-no-exceptions fail 1</title>
    <!-- Greater than 20 hour is still not allowed at Level AAA -->
    <meta http-equiv="refresh" content="90000; https://deque.com/" />
    <link
      rel="stylesheet"
      type="text/css"
      href="/node_modules/mocha/mocha.css"
    />
```
`meta-refresh` test script:

```
<meta charset="utf8" />
    <title>Meta-refresh fail 1</title>
    <meta http-equiv="refresh" content="10 https://deque.com/" />
    <link
      rel="stylesheet"
      type="text/css"
      href="/node_modules/mocha/mocha.css"
    />
```

![Image](https://user-images.githubusercontent.com/47409579/196712624-9be165a6-a778-4632-ad2c-355c1f6cae4d.png)
