### ISSUE TITLE
Runtime issue: Cannot read properties of undefined (reading 'source')

### ISSUE THREAD

**Issue by JackieHayduk** [dequelabs/axe-core#3627]
<< Please describe how you encountered this issue >>

axe-core version: `4.4.2`
axe-extension version: `4.36.2`

```
TypeError: Cannot read properties of undefined (reading 'source')
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:167249
    at Array.map (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:167219
    at Array.forEach (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:167169
    at Array.forEach (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:167065
    at Array.map (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:12:166733
    at Array.map (<anonymous>)
```

**Comment by WilcoFiers** [comment]
Can you provide some information on how you got this error?

**Comment by JackieHayduk** [comment]
Hello,

I was attempting to "scan part of the page" on a local hosted storybook
instance.

Thanks,
Jackie

Please Note: My working hours may be different than yours. Please do not
feel obligated to respond outside your normal working hours. (Philadelphia
Based | EST)

JACKIE HAYDUK

______________________________________________

Senior Front End Engineer • Certified Web Accessibility Specialist
Philadelphia,
PA


[image: Hero Digital Logo] <https://herodigital.com/>      [image: IAAP Web
Accessibility Certification]
<https://www.accessibilityassociation.org/s/wascertification>

**Comment by WilcoFiers** [comment]
That'll be difficult to debug. I can't think of anything either related to running on localhost, or running storybook that could cause this issue. @scurker / @schne324 any thoughts?

**Comment by padmavemulapati** [comment]
Cannt reproduce with axe-core also it is tracking from the extension, https://github.com/dequelabs/axe-extension/issues/3185 . So closing here
