### ISSUE TITLE
[image-redundant-alt] Are aria-labels taken into account ?

### ISSUE THREAD

**Issue by sparky-raccoon** [dequelabs/axe-core#3629]
### Product

axe-core

### Question

Hello, 

I ran the axe DevTools today and had an `image-redundant-alt` issue on the following case : 
```
<div>
  <picture>
     <img src="..." alt="Example" />
  </picture>
</div>
<a aria-label="Example With Concanated Text">Example</a>
```
I wonder if aria-label is read since aria-label is different from the alt provided. Why would the visible text matter prior to the aria-label, since screen readers will read aria-label instead of the link content when aria-label is set ? 

Thanks !

**Comment by straker** [comment]
Apologies for having missed this. I tried to run the example provided in latest version of axe-core  (v4.4.3) and it's passing the `image-redundant-alt` rule. Are you still experiencing this problem?

**Comment by straker** [comment]
Going to close this. Please feel free to reopen if you are still experiencing this issue.
