### ISSUE TITLE
Document grunt tasks

### ISSUE THREAD

**Issue by marcysutton** [dequelabs/axe-core#364]
It's pretty difficult to work with some of our more magical Grunt tasks, which are hidden under `build/tasks`. We should document these somewhere, perhaps in the developer guide. 

Related to #357.

**Comment by marcysutton** [comment]
Closed with #365.

**Comment by nschonni** [comment]
#365 only did a single task (that I think I understood). I think this needs to be re-opened so the rest can be done

**Comment by marcysutton** [comment]
Ah, you're right. I can work on that later this week unless someone beats me to it.
