### ISSUE TITLE
Map custom components to HTML elements

### ISSUE THREAD

**Issue by ppseprus** [dequelabs/axe-core#3662]
### Product

axe Linter

### Question

Is there a way to configure the VSCode linter to treat custom elements as some HTML tag?
Even better: Is there an IDE-agnostic solution to this problem?

Eg.

```javascript
import { CustomButton } from '@whatever/elements'

const SomeComponent: FC = () => {
  return (
    ...
    <CustomButton></CustomButton>
    ...
  ) 
}
```

**Comment by jthickens** [comment]
Hey @ppseprus, this is a feature that we're already working on developing. If you'd like, get in contact with us via helpdesk@deque.com and we can get you access to the beta.

**Comment by ppseprus** [comment]
I understand! Thank you!
