### ISSUE TITLE
fix header scope error on nested tables

### ISSUE THREAD

**Issue by robfentress** [dequelabs/axe-core#367]
In a table marked with `role="presentation"` there is another table that does not have `role="presentation"` set.  In that table is a `<th>` with `scope="row"`.  This is, indeed, a row header, but I get the following error in aXe:

> Ensures the scope attribute is used correctly on tables

**Comment by robfentress** [comment]
Actually, I don't have time to verify everything that is going on with this page, so I can't rule out other causes, and the site I am evaluating will be disappearing soon.  Just wanted to pass it along the, in case it meshed with anything else you were experiencing.  I'll follow up if I encounter is again.

**Comment by WilcoFiers** [comment]
@robfentress Just as an FYI, axe-core does distinguish between layout tables and any tables that might be nested within it. I've put together a quick example here:
https://codepen.io/wilcofiers/pen/GEWZRo
