### ISSUE TITLE
github/axe-linter vs eslint-plugin-jsx-a11y

### ISSUE THREAD

**Issue by FSou1** [dequelabs/axe-core#3740]
### Product

axe-core

### Question

We are going to start using the axe products for a React project and here is a question we'd like to clarify. There are at least 2 options for static analysis with axe:
* https://github.com/marketplace/axe-linter
* https://www.npmjs.com/package/eslint-plugin-jsx-a11y

If we do have control over the source code, is there a reason we should prefer one over another? The difference between these two are unclear for us.

**Comment by straker** [comment]
Going to close this as completed. Feel free to reopen if you have any further questions about axe-linter vs eslint-plugin-jsx-a11y.
