### ISSUE TITLE
target-size and meta-refresh-no-exception rule description pages has no sufficient data 

### ISSUE THREAD

**Issue by padmavemulapati** [dequelabs/axe-core#3749]
### Product

axe-core

### Product Version

4.5

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
Dequeuniversity help pages should provide necessary data regarding Success criteria, Tags, Disabilities affected etc.,

#### Actual
NO information available 
![image](https://user-images.githubusercontent.com/47409579/198021407-0f2df02a-1759-45ac-aeec-a893d78d04bc.png)
![image](https://user-images.githubusercontent.com/47409579/198021816-e676a763-dcd3-4600-9fe9-45fdc87ae151.png)

#### How to Reproduce
Open a `target-size` rule description page, https://dequeuniversity.com/rules/axe/4.5/target-size , https://dequeuniversity.com/rules/axe/4.5/meta-refresh-no-exceptions

**Comment by straker** [comment]
Should be fixed now

**Comment by padmavemulapati** [comment]
Validated with the latest `https://dequeuniversity.com/rules/axe/4.5/` rules page, `target-size` and `meta-refresh-no-exceptions` rules pages has appropriate data now.

<img width="1665" alt="image" src="https://user-images.githubusercontent.com/47409579/199028175-2b4926bd-cd36-419d-9fef-80c68e0e3247.png">
<img width="1561" alt="image" src="https://user-images.githubusercontent.com/47409579/199028243-bfe8a83c-f539-4f0f-b47f-a0b8051e08ce.png">

<img width="1613" alt="image" src="https://user-images.githubusercontent.com/47409579/199028336-2891d3e7-b592-46f5-afec-8a4abf0ebe4a.png">
<img width="1584" alt="image" src="https://user-images.githubusercontent.com/47409579/199028420-d65e14f9-1909-498f-a4ed-52584afa388d.png">
