### ISSUE TITLE
dequeuniversity.com downtime degrades reports

### ISSUE THREAD

**Issue by joshbruning** [dequelabs/axe-core#375]
dequeuniversity.com downtime degrades accessibility reports.

Whether a report has been collected in the past or present, when links like:

- https://dequeuniversity.com/rules/axe/2.1/html-has-lang?application=axeAPI

return like:
- We are currently performing some server maintenance.
- Check back again later.
- See also the Deque main web site.

this project's utility is degraded.

Please consider moving this help information directly into the GitHub project documentation so that it can be more available, open to contributions, and versioned.

**Comment by dylanb** [comment]
@joshbruning thank you for your feedback - the content that is referenced there is not open source

**Comment by dylanb** [comment]
@joshbruning this was an unplanned downtime...I am looking into why it happened. Of course we take all the precautions we can to prevent this from happening.

**Comment by joshbruning** [comment]
Thanks for the quick response.

Would you be open to updating https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md or adding a page to:
- Have rules linkable by adding things like "#html-has-lang" to the URL?
- Link to the non-open-sourced content (more information links)?
- Open sourcing any of the content?

For context: Quite unfortunately, the unplanned downtime happened just as I convinced several teams at Google to begin evaluating the quality this product.

(fwiw: I don't intend to reopen this issue as I'm happy just working around.)

**Comment by iandotkelly** [comment]
@joshbruning ... the pages are up again now.

**Comment by dylanb** [comment]
@joshbruning ironically, this is the first time we have had a major outage on that site....timing is everything...

This page https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md is updated with every pull request that affects that content. The content on that page is actually auto-generated from the source code.

In terms of the content hosting...the current URL scheme is

https://dequeuniversity.com/rules/axe/{version}/{ruleid}?application={application}

If you go to https://dequeuniversity.com/rules/axe/2.1/ you will see a list of the rules for that version of the API.

the content there is versioned i.e. if a rule algorithm changes from 2.1 to 2.2, then links from the 2.1 version of the API will show the content appropriate for that version of the rule, whereas from 2.2 on, the changes would be reflected.

We could change the URL scheme to https://dequeuniversity.com/rules/axe/{version}#{ruleid}?application={application} but I am not sure how much more of a benefit that would bring?

We may open source the rule info content at some point but I cannot guarantee that.

**Comment by joshbruning** [comment]
Thanks - I didn't mean to propose any changes to the content at dequeuniversity.com urls; I just desired a generatable open source URL that I could point users to as a fallback if full content was not available. Open sourcing the content would be useful. I would also find it useful if the content was made available open source in a pre-rendered format (json, for example).

(Off topic, but if you could investigate open sourcing the aXe Chrome extension as well, that would be helpful. As the extension must be able to "Read and change all your data on the websites you visit", we cannot use it without auditing the code.)
