### ISSUE TITLE
How to enable WCAG 2.2 and experimental rules in axe-core 4.5?

### ISSUE THREAD

**Issue by jaimeiniesta** [dequelabs/axe-core#3751]
### Product

axe-core

### Question

Hi, according to the [axe-core 4.5 announcement](https://www.deque.com/blog/axe-core-4-5-first-wcag-2-2-support-and-more/):

> Until WCAG 2.2 is a W3C Recommendation that is more widely required, this rule will be off by default. To use this rule you will need to configure your axe products to use the WCAG 2.2 ruleset.

How can I do that in axe-core? I've searched in the documentation but I couldn't understand how to do that.

Also, how can I enable all the experimental rules?

In short, how can I include all rulesets, including WCAG 2.2, and all experimental rules?

Thanks!

**Comment by straker** [comment]
If you want to enable the new `target-size` rule or other experimental rules, you can use [`rules` option](https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#options-parameter) to enable it by name:

```js
axe.run({
  rules: {
    'target-size': { enabled: true },
    // other experimental rules
  }
});
```

The list of experimental rules can be found in the [rule-descriptions](https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md#experimental-rules)

**Comment by jaimeiniesta** [comment]
Thank you! This worked great. :)
