### ISSUE TITLE
Experimental rule 'td-has-header' guidance on support for `headers` needs clarification

### ISSUE THREAD

**Issue by aardrian** [dequelabs/axe-core#3764]
### Product

axe-core

### Description

On the rule information page for [td-has-header](https://dequeuniversity.com/rules/axe/4.5/td-has-header) is the following note:

> *Note: Old Versions of VoiceOver did Not Support the `id` + `headers` Method*
>
> Up until Mac OSX 10.10.2, VoiceOver did not support the ability to read table headers with the `id` + `headers` method. Some versions even read the wrong headers with the data cells. Fortunately, the current version of VoiceOver does read the data and header associations correctly.

This note for a single screen reader both implies that `id` + `headers` work in the current version of VoiceOver on macOS and that no other browsers or screen readers have any issues with `id` + `headers`. Unfortunately, neither is the case:

* Chromium: [1081201: headers attribute ignored in tables resulting in an incorrect screen reader experience (accessibility)](https://bugs.chromium.org/p/chromium/issues/detail?id=1081201) opened Monday, May 11, 2020;
* Chromium: [1290375: Screen readers announce spanning row header as many times as columns it spans](https://bugs.chromium.org/p/chromium/issues/detail?id=1290375) opened Monday, Jan 24, 2022;
* JAWS:  [601: JAWS announces wrong column header info after spanned cell](https://github.com/FreedomScientific/VFO-standards-support/issues/601) opened Monday, Jan 24, 2022;
* Safari/VoiceOver/macOS: [235740: AX: Incorrect row header announcement in VoiceOver macOS](https://bugs.webkit.org/show_bug.cgi?id=235740) opened Thursday, Jan 27, 2022.

I suggest replacing that statement with guidance for users to test in their target audience screen reader and browser pairings, or to track all issues. I think tracking all issues is outside the scope of this documentation

**Comment by straker** [comment]
Change will be released with axe-core 4.7 next week.
