### ISSUE TITLE
Webpack Error: axe-core cannot be extracted

### ISSUE THREAD

**Issue by TheJaredWilcurt** [dequelabs/axe-core#3771]
### Product

axe-core

### Product Version

4.5.0 and 4.5.1

### Latest Version

- [X] I have tested the issue with the latest version of the product

### Issue Description

**Steps to Reproduce:**

I'm using `vue-axe` in a Vue 3, Vue-CLI project.

1. Install the Vue-CLI to generate an app from a boilerplate
   * `npm install @vue/cli`
   * `vue create bug-repro` > "Default Vue 3"
1. Follow the instructions in the `vue-axe` README:
   * https://github.com/vue-a11y/vue-axe-next#readme
1. Start webpack
   * `npm run serve`

**Expected:**

* Webpack starts up with no warnings/errors.

**Actual:**

```
WARNING  Compiled with 1 warning

warning  in ./node_modules/axe-core/axe.js

Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

**Additional information:**

Issue was not present in `v4.4.3`. It is present in `v4.5.0` and `v4.5.1`.

**Comment by seanBlommaert** [comment]
The error seems to occur on 2 places. Hope this helps.

```
./node_modules/axe-core/axe.js 379:46-53
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
./node_modules/axe-core/axe.js 386:15-22
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

**Comment by padmavemulapati** [comment]
dev task
