### ISSUE TITLE
a row in a table is not treated as a descendant of a treegrid

### ISSUE THREAD

**Issue by hawkchen** [dequelabs/axe-core#3797]
### Product

axe-core

### Question

I use a simplified example to explain my question.
When I scan the page below with axe 4.4.2, I found the 2nd treegrid produces issues:

1. ARIA attribute is not allowed: aria-level="1"
2. Required ARIA children role not present: rowgroup, row

I think 2nd issue causes the 1st one.

There is a table between treegrid and row.

```html
<h2>contain a table</h2>
<div id="e3"  tabindex="0" role="treegrid">
    <table>
        <tr role="row" aria-level="1">
            <td role="cell">item1</td>
        </tr>
        <tr role="row" aria-level="1">
            <td role="cell">item2</td>
        </tr>
    </table>
</div>
```

But if you enclose `row` with a `div`, there is no issues:

```html
<h2>enclosed 1 more div</h2>
<div id="e2"  tabindex="0" role="treegrid">
    <div>
        <div role="row" aria-level="1">
            <div role="cell">item1</div>
        </div>
        <div role="row" aria-level="1">
            <div role="cell">item2</div>
        </div>
    </div>
</div>
```

Can someone explain the reason? thanks a lot.

**Comment by WilcoFiers** [comment]
You're correct that this doesn't work because of the table. Screen readers and other assistive technologies are going to treat these rows as being part of the table, instead of your treegrid. The [ARIA spec](https://www.w3.org/TR/wai-aria-1.2/#row) has the following to say about this:

> While the row role can be used in a [table](https://www.w3.org/TR/wai-aria-1.2/#table), [grid](https://www.w3.org/TR/wai-aria-1.2/#grid), or [treegrid](https://www.w3.org/TR/wai-aria-1.2/#treegrid), the semantics of [aria-expanded](https://www.w3.org/TR/wai-aria-1.2/#aria-expanded), [aria-posinset](https://www.w3.org/TR/wai-aria-1.2/#aria-posinset), [aria-setsize](https://www.w3.org/TR/wai-aria-1.2/#aria-setsize), and [aria-level](https://www.w3.org/TR/wai-aria-1.2/#aria-level) are only applicable to the hierarchical structure of an interactive tree grid. Therefore, authors MUST NOT apply [aria-expanded](https://www.w3.org/TR/wai-aria-1.2/#aria-expanded), [aria-posinset](https://www.w3.org/TR/wai-aria-1.2/#aria-posinset), [aria-setsize](https://www.w3.org/TR/wai-aria-1.2/#aria-setsize), and [aria-level](https://www.w3.org/TR/wai-aria-1.2/#aria-level) to a [row](https://www.w3.org/TR/wai-aria-1.2/#row) that descends from a [table](https://www.w3.org/TR/wai-aria-1.2/#table) or [grid](https://www.w3.org/TR/wai-aria-1.2/#grid)

If you want to use a `table` element, the way to fix it is to put `role="none"` on it. That tells screen readers to ignore it, and treat the `row`s as children of the `treegrid` instead.

**Comment by hawkchen** [comment]
Thanks for your explanation and the solution.

As I understand, the `table` that [ARIA spec](https://www.w3.org/TR/wai-aria-1.2/#row) mentioned is the role `table`, not the HTML tag `<table>`. But my `<table>` doesn't have a `role="table"`. Do you mean Axe automatically treats an HTML `<table>` as a `role="table"` even I don't specify it?

**Comment by straker** [comment]
Yes. Many native HTML element have implicit ARIA roles associated with them. You can see the full list of which elements map to which roles in the [ARIA in HTML spec](https://www.w3.org/TR/html-aria/#docconformance).
