### ISSUE TITLE
Newest Version 4.5.2 seems not to be published to mvn search / mvn Central

### ISSUE THREAD

**Issue by boris779** [dequelabs/axe-core#3802]
### Product

axe-core

### Product Version

4.5.2

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
Describe what you expected the product to do.

#### Actual
The latest version which is already 15 days released is not available in mvn Central. 4.5.1 is there.

#### How to Reproduce
Add Version 4.5.2 to your pom

**Comment by michael-siek** [comment]
Hi @boris779 ,

The axe-core maven project is at version 4.5.1 but is using axe-core version 4.5.2. 

Reference: 
- [selenium](https://github.com/dequelabs/axe-core-maven-html/blob/develop/selenium/package.json#L9)
- [playwright](https://github.com/dequelabs/axe-core-maven-html/blob/develop/playwright/package.json#L11)
