### ISSUE TITLE
Runtime issue: Cannot read properties of undefined (reading 'source')

### ISSUE THREAD

**Issue by archfordmutengwa** [dequelabs/axe-core#3834]
<< Please describe how you encountered this issue >>

axe-core version: `4.4.2`
axe-extension version: `4.45.0`

```
TypeError: Cannot read properties of undefined (reading 'source')
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:166565
    at Array.map (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:166534
    at Array.forEach (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:166483
    at Array.forEach (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:166376
    at Array.map (<anonymous>)
    at chrome-extension://lhdoppojpmngadmnindnejefpokejbdd/axe-versions/latest/axe.js:2:166044
    at Array.map (<anonymous>)
```

**Comment by straker** [comment]
Thanks for the issue. Could you provide a link to a site or a code sample that reproduces the issue?

**Comment by archfordmutengwa** [comment]
[screen-capture (1).webm](https://user-images.githubusercontent.com/120664275/208070651-1e3e3f19-f095-477e-b712-155c83715058.webm)
I am not able to give you access to the library so I have done a screen recording instead. Please let me know if this is useful at all.

**Comment by archfordmutengwa** [comment]
Hello, just checking if you have any updates for me because I have a monthly license and I have lost a few days already to do some testing.

**Comment by scurker** [comment]
@archfordmutengwa I apologize that this issue has been affecting your testing, we have an update to the extension that will land in the next few weeks that will hopefully address this issue.

In the meantime, a temporary work around you could try is to first save your test (on any page, doesn't have to be the same page) and run the forms IGT from the _Guided Tests_ tab after your results are saved.

**Comment by WilcoFiers** [comment]
This issue should have been solved with the latest release.
