### ISSUE TITLE
axe core throws relying on color alone false positive issue when the link and surrounded text have same color

### ISSUE THREAD

**Issue by DQUday** [dequelabs/axe-core#3848]
### Product

axe-core

### Product Version

4.5.1 and 4.5.2

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
If the link text and the surrounded text color are same, then this check should not take place as there is no color alone usage here.

#### Actual
Axe-core flags an issue here assuming there is color alone since there is no additional indicators for the link surrounded with text.

#### How to Reproduce
1. Launch the URL - https://online.citi.com/US/ag/investing/investingwithciti
2. Select continue button on the modal.
3. Now run the axe-core using axe Expert and axe DevTools
4. Notice false positive raised for one of the links in the footer section where the link and surrounding text colors are same.

#### Screenshot
<img width="1718" alt="False Positive_color alone" src="https://user-images.githubusercontent.com/71381558/211107353-05efbf91-be97-4c1f-aca6-dc6ba1e5fa77.png">

**Comment by dylanb** [comment]
This is not a false positive, if you look at the "fix this" section you will see that it is complaining that the text contrast with the surrounding text is too low - which is 100% accurate.

@WilcoFiers should we change the help text to make it more precise?

**Comment by melaniephilipp** [comment]
@dylanb You can't fail it under 1.4.1 Use of Color when link text and surrounding body text are the same color because there is literally no use of color to differentiate the link text from the body text.

**Comment by melaniephilipp** [comment]
Some additional context to this issue: https://github.com/w3c/wcag/issues/1467

**Comment by dylanb** [comment]
In the specific example, the link DOES have color to distinguish it from the background UNTIL you hover it and then it does not - so do we fail it under 1.4.11 because the hover state does not pass 3:1?

**Comment by dylanb** [comment]
looks like a false positive to me then

**Comment by WilcoFiers** [comment]
I agree, axe-core should pass if the colors are identical. Good catch.

**Comment by melaniephilipp** [comment]
@WilcoFiers Thanks for the confirmation. Do you have an estimate of release timing to remove the false positive? Thanks!
