### ISSUE TITLE
support new aria-braille* properties

### ISSUE THREAD

**Issue by pkra** [dequelabs/axe-core#3899]
### Product

axe-core

### Feature Description

The new properties [aria-braillelabel](https://w3c.github.io/aria/#aria-braillelabel) and [aria-brailleroledescription](https://w3c.github.io/aria/#aria-brailleroledescription) are on track to be added to ARIA 1.3, see https://github.com/w3c/aria/issues/1331 for additional details.

Basic support (i.e., not flagging them as invalid) would be great to have in time for 1.3.

**Comment by pkra** [comment]
Thanks for the response, @WilcoFiers!

> Since there's no support for this yet, the benefit of this will be minimal. 

Just for those who don't want to look up the ARIA 1.3 milestone: all major browsers now have support. On the AT side, Orca supports them already. Since this idea came out of a workshop a few years ago where both NVDA and JAWS developers were involved, I'm hopeful they'll get around to it. Apple seems open to them (e.g., Safari already includes the webkit patches).

> I see no reason why we couldn't add them, and so maybe encourage some early adoption.  That seems fairly harmless to me. 

That would be great!

> I do think we should put some guard rails in place though. It has kind of the same problem aria-description has.

Right. A lot of wordsmithing went into warnings in the spec language to generally discourage their use. I'd say the properties are for extraordinary use cases where authors have highly specialized braille requirements (and knowledge), e.g., in education. 

I think it would not hurt at all if tools like axe would give similarly strong warnings.

**Comment by padmavemulapati** [comment]
Validated with the latest axe-core-develop branch code base,
`aria-valid-attr` is now allowing the attributes `aria-braillelabel` and `aria-brailleroledescription` with these two attributes its passing.


![Image](https://user-images.githubusercontent.com/47409579/228129721-45252454-77fe-4379-9526-70908fc058c4.png)
