### ISSUE TITLE
"graphics-chartdata" not recognized as valid role

### ISSUE THREAD

**Issue by gabycperezdias** [dequelabs/axe-core#3910]
### Product

axe-core

### Product Version

extension: v4.49.0  axe-core: v4.6.3

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
As per https://www.w3.org/wiki/SVG_Accessibility/ARIA_roles_for_charts I would think that `graphics-datachart` is a valid role for a svg, but I keep getting error on Axe Reports that I need to use valid Roles...

#### Actual
![image](https://user-images.githubusercontent.com/6580266/218173586-d0902267-178c-4670-b8b3-65dcb380fa6b.png)

#### How to Reproduce
In here: https://codesandbox.io/s/charming-resonance-ui2zqj?file=/src/index.js you can see the code (but if you run Axe on top of the  sandbox you will get lots of issues...) So one easy way to check this is:
![image](https://user-images.githubusercontent.com/6580266/218175218-5496c6bb-190a-4b3f-9449-815a5446e596.png)

Click in this button to open the result html into a new tab and then, run the Axe Tools on it

**Comment by WilcoFiers** [comment]
@gabycperezdias the `graphics-chartdata` is not a ARIA role. The work you're referencing is preliminary work for what ended up as the [WAI-ARIA Graphics Module](https://w3c.github.io/graphics-aria/). It was simplified a good bit though, and didn't end up with `graphics-chartdata`.  As far as i can tell those roles you reference never made it into a W3C working draft.

If you have a basic graphic like the bar in your screenshot your best option is to use `role="img"`. You can add something like `aria-roledescription="chart"` if you wanted to add to that. For more complex graphics, where someone would need to explore the content `role="graphics-document"` is the way to go, although support for that in screen readers is spotty, so you should test that carefully. In both cases, be sure to add an accessible name with `<title>` or `aria-label`

I'm curious though how you got this issues. If its some common library we might add a more explicit failure message for it. I've never personally seen these roles you mention, so I'm kind of curious how you got them.

**Comment by gabycperezdias** [comment]
Hi @WilcoFiers I am sorry, I didn't know this was not the final roles, this is a custom developed library, so I just researched on Google what would be the best role to be added for my charts (I do have other more-complex charts) and I found those... I thought that having role="img" would not be correct considering that the chart is important and a very important part to understand the screen where I am using it. As far as I know, ScreenReaders interact differently with charts than they do with Images... so now I am a bit confused... I still think "img" is weird for my use case, but if `graphics-document` is also spotty I am not sure how to go about my solution :/

**Comment by WilcoFiers** [comment]
Yikes! Looks like I missed a comment. My apologies @gabycperezdias. If you need a more explicit description of what this does you could use `role="img"` along with `aria-roledescription`. This is fairly well supported on `img`.
