### ISSUE TITLE
isIconLigature fails on leading invisible character

### ISSUE THREAD

**Issue by SirUppyPancakes** [dequelabs/axe-core#3913]
### Product

axe-core

### Product Version

4.6.3

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
Expected `axe-core` to be able to handle any valid HTML (the HTML in this case is 100% valid according to the W3C validator)

#### Actual
The `isIconLigature` function fails to consider invisible characters at the start of the input, resulting in a `SupportError` being thrown.

#### How to Reproduce
Project which reproduces the issue: 
[axe-core-invisible-issue.zip](https://github.com/dequelabs/axe-core/files/10725677/axe-core-invisible-issue.zip)

Steps:
1. Run `npm install`
2. Start a server to serve the html file (I used the `html-server` npm package, for example) or simply open the html file in a browser
3. Optionally put some breakpoints (in `node_modules/axe-core/axe.js`) to observe the exact source of the issue, on the following lines:
    - 11378 `var compareData = new Uint32Array(canvasContext.getImageData(0, 0, width, fontSize).data.buffer);`
    - 11379 `if (!compareData.some(function(pixel) {`
    - 22005 `reject(new SupportError({`

After hitting the break point right before `isIconLigature` calls `canvasContext.getImageData`, you'll be able to see that `width` and `fontSize` have been determined to be `NaN` and `Infinity` which are invalid parameters for this function, causing it to throw an exception and result in the `SupportError` being generated. This happens because the first character in the link content of my HTML in this case is [U+2069] which is an invisible character relating to the left-to-right or right-to-left nature of the text (we ran into this issue when checking one of our Arabic-translated files).

Would it be possible to change `isIconLigature` to look for the first visible character? I suppose there would also need to be a case to handle if there isn't any visible characters in the span as well...

**Comment by straker** [comment]
Thanks for the issue. For security reasons I can't open a zip file. However, thanks to the description I can reproduce this on my end using the HTML string `&#2069Hello World`.

**Comment by SirUppyPancakes** [comment]
Thanks! For future reference for myself, what would have been a preferable way to share a test project? A gist maybe?

**Comment by straker** [comment]
A gist or HTML snippet work best.

**Comment by padmavemulapati** [comment]
Validated with the latest axe-core develop branch code base, not seeing any failure with the ligature icon on invisible charecters, 
 for ex: ` <main> <a href="https://www.google.com">⁩البطاطس</a > </main>`



![Image](https://github.com/dequelabs/axe-core/assets/47409579/8954fab6-8fb0-4a06-9cb9-68561f332a42)
