### ISSUE TITLE
Clarify aria-busy remediation message

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#3934]
We had some confusion about this message:

```
Element has no aria-busy="true" attribute
```

This doesn't explain when aria-busy would be appropriate. I think the following would be better:

```
Element uses aria-busy="true" while showing a loader
```

This required a small change to `lib/checks/aria/aria-busy.json`.

**Comment by straker** [comment]
To expand on this issue, we may not want to show the aria-busy remediation message when there are unallowed roles. Otherwise the remediation message suggests that adding `aria-busy` will fix the issue (when it won't).

```
"Fix any of the following:
  Element has children which are not allowed: button
  Element has no aria-busy="true" attribute"
```
