### ISSUE TITLE
Allowance of presentational li elements inside a list

### ISSUE THREAD

**Issue by Al-Dani** [dequelabs/axe-core#3935]
### Product

axe-core

### Feature Description

Is it possible to include `role=presentation` to the list of allowed roles for the `<li>` inside `<ul>`?
Having a presentational element won't interrupt the user while navigating through a list, as it will be removed from the a11y tree.

A use-case for this is to have a navigation list with separators between items. Separators are decorative.

**Comment by Al-Dani** [comment]
That's what I want to achieve:
```
<ul> 
 <li> <a/> </li>
 <li> <a/> </li>
 <li role='presentation'> <hr/> </li>
 <li> <a/> </li>
 <li> <a/> </li>
</ul>
```

**Comment by WilcoFiers** [comment]
Putting role=presentation on an `li` means the li is hidden, but its content is not. You should use aria-hidden instead if you want it ignored.
