### ISSUE TITLE
What is `bridge` in the context of using frameMessenger?

### ISSUE THREAD

**Issue by ali-habibzadeh** [dequelabs/axe-core#3946]
### Product

axe-core

### Question

Hi,

I see you have this in your docs for setting up communication between frames:

```
axe.frameMessenger({
  // Called to initialize message handling
  open(topicHandler) {
    // Map data from the bridge to topicHandler
    function subscriber(frameWin, data, response) {
      // Data deserializations / validation / etc. here
      topicHandler(data, response);
    }
    // Start listening for "axe-core" events
    const unsubscribe = bridge.subscribe('axe-core', subscriber);
    // Tell axe how to close the connection if it needs to
    return unsubscribe;
  },

  // Called when axe needs to send a message to another frame
  async post(frameWindow, data, replyHandler) {
    // Send a message to another frame for "axe-core"
    const replies = bridge.send(frameWindow, 'axe-core', data);
    // Async handling replies as they come back
    for await (let data of replies) {
      replyHandler(data);
    }
  }
});
```

However it is unclear what `bridge` is in this context. I suspected from the source code that its ` axe.utils.respondable` however `const unsubscribe = axe.utils.respondable.subscribe("axe-core", subscriber);` doesn't call the callback so I am guessing I am not right. Could you provide some assistance please?

**Comment by WilcoFiers** [comment]
@ali-habibzadeh The bridge interface is part of axe-core's internals. It isn't something users of axe-core should need to interface with. Can you provide more information on what you are trying to do?

**Comment by WilcoFiers** [comment]
Can you provide steps to reproduce the issue?
