### ISSUE TITLE
Axe Core 4.6 should trigger the `audio-caption` rule either in "violations" or "incomplete".

### ISSUE THREAD

**Issue by jaimeiniesta** [dequelabs/axe-core#3961]
### Product

axe-core

### Product Version

4.6

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
Axe Core 4.6 should trigger the `audio-caption` rule either in "violations" or "incomplete".

#### Actual
It doesn't trigger the "audio-caption" rule.

#### How to Reproduce
This page contains an audio without a captions track:

https://dummy.rocketvalidator.com/audio/2022/06/24/missing-audio-captions.html

When checked with axe core 4.6, it doesn't trigger any "audio-caption" rule.

#### Additional context
As far as I understand this rule was first deprecated but it currently should show up in "incomplete" to treat it as a "needs review" case?

**Comment by straker** [comment]
The `audio-caption` rule was deprecated and turned off by default, so it won't run unless it's enabled either through the run options of `axe.run` or through `axe.configure`.

**Comment by jaimeiniesta** [comment]
Thanks for the update!

Then I guess the [rule list](https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md) needs to be updated to reflect that.

The `audio-captions` doesn't appear under "deprecated", and there's no clue about what rules are turned off by default.

**Comment by WilcoFiers** [comment]
Yeah, seems we forgot to put the deprecated tag on it, and then didn't remove it as part of 4.6. Lets correct that and make sure it gets pulled in 5.0.

**Comment by padmavemulapati** [comment]
Vaidated with the latest code base, as it is deprecated, we run with `runOnly()` , it is resulting `incomplete` results


![Image](https://user-images.githubusercontent.com/47409579/229018748-8086b6b1-0cd0-45ab-b1fc-81bce8543536.png)
