### ISSUE TITLE
axe.setup should set globals

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#3962]
Axe-core's setup and teardown methods should be able to work with JSDOM:

```js
import axe from 'axe-core'
import { JSDOM } from 'jsdom'
const { window } = new JSDOM(`<!DOCTYPE html>\n<html></html>`);
axe.setup(window)
```

Currently the only way to use `axe.setup()` with JSDOM is if `globalThis.window` and `globalThis.document` are defined before axe-core is imported. This is annoying and shouldn't be necessary. We handle this in `axe.run()` by calling `setupGlobals`. Probably this call should just be moved into `axe.setup()`, and the `resetGlobals()` call should go into `axe.teardown()`.

Another problem I'm spotting is that `axe.runPartial()` doesn't set up globals either. Moving these calls to setup/teardown will solve that too. A test for this would be useful.

**Comment by padmavemulapati** [comment]
Steps validated:
1. npm install axe-core@next jsdom (installed axe-core_4.7.2-canary.2cc5547 , jsdom_22.1.0)
2. created test.js file with the content

```
// accessibility-test.js
const axe = require('axe-core');
const { JSDOM } = require('jsdom');

const html = `<!DOCTYPE html>\n<html></html>`;

// Create a virtual DOM with JSDOM
const { window } = new JSDOM(html);

// Setup axe with the virtual DOM
axe.setup(window);

// Run accessibility tests
axe.run(window.document, {}, (err, results) => {
  if (err) {
    console.error(err);
  } else {
    console.log(results.violations);
  }
}); 

```
3. Execute the test using `node test.js`


getting the error:

```
/Users/dq_user/Desktop/axecoretest/node_modules/axe-core/axe.js:16201
      nodeName2 = node.nodeName.toLowerCase();
                                ^

TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at flattenTree (/Users/dq_user/Desktop/axecoretest/node_modules/axe-core/axe.js:16201:33)
    at _getFlattenedTree (/Users/dq_user/Desktop/axecoretest/node_modules/axe-core/axe.js:16170:18)
    at Object.setup (/Users/dq_user/Desktop/axecoretest/node_modules/axe-core/axe.js:26995:19)
    at Object.<anonymous> (/Users/dq_user/Desktop/axecoretest/test.js:18:5)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

@straker can you please confirm on this whether fix is working properly or not

**Comment by straker** [comment]
I don't think you can pass `window` to `axe.setup`. Try passing `window.document`.

**Comment by padmavemulapati** [comment]
Thank you @straker , Ran ` await axe.setup(window.document);` it returns its `virtualNode`



![Image](https://github.com/dequelabs/axe-core/assets/47409579/89a2d8ba-7842-4179-80f2-f537ff0fe45c)
