### ISSUE TITLE
Possible false positive contrast issue for color that doesn't seem to be visible on the webpage

### ISSUE THREAD

**Issue by CharlesBelov** [dequelabs/axe-core#3977]
### Product

axe-core

### Product Version

extension: v4.49.0 axe-core: v4.6.3

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
I expect the product not to report contrast issues which are not visible to the website visitor.

#### Actual
The product seems to be reporting a contrast issue which is not visible to the website visitor.

#### How to Reproduce
The [SFMTA.com homepage](https://www.sfmta.com/) currently produces this issue. Here is the code which is subjected to by axe-core specific to this issue:

axe-core reports a violation for 1.4.3 for class .compact-form-label:

<label class="control-label compact-form-label" for="edit-text"><span class="search-icon"></span> Search SFMTA...</label>

Element has insufficient color contrast of 4.44 (foreground color: #75787b, background color: #ffffff, font size: 10.8pt (14.4px), font weight: bold). Expected contrast ratio of 4.5:1

I am questioning whether this might be a false positive, because I do not see any element visible on the page with a foreground color of #75787b and a background color of #ffffff.

Actual steps:

1. Launch Firefox with the axe-core extension
2. Go to https://www.sfmta.com/ (HTML and relevant CSS source code attached)
3. Right click the search icon in the top navigation bar
4. Choose inspect 
5. Go to the axe DevTools tab
6. Click scan all of my page
7. Note the errors for contrast 
8. Go to the Inspector tab
9. Option click the expand arrow for the element having ID equal to navigation-right
10. Continue scrolling down in the inspector
11. Locate the label tag with the class including compact-form-label and click it
12. Note that the element does not seem to be visible on the page
13. Narrow the browser window (to the left) as narrow as it will go
14. Go to the axe DevTools tab
15. Click rerun scan
16. Note that axe DevTools now reports no errors
17. Return to the inspector tab the element with class compact-form-label
18. Note that the CSS now has display:none

#### Additional context
The question here is: If content is supposedly being displayed but is actually not visible in reality, does that qualify as a false positive if it is flagged for contrast issues?

Possibly related issues: #3214,  #2768.

Note: The code in question may be an artifact of technical debt from the development process. That said, I would expect axe-dev to handle it correctly.

[home.page.source.code.txt](https://github.com/dequelabs/axe-core/files/11162199/home.page.source.code.txt)
[relevant css file.txt](https://github.com/dequelabs/axe-core/files/11162384/relevant.css.file.txt)
<img width="1658" alt="Screenshot 2023-04-05 at 12 35 54 PM" src="https://user-images.githubusercontent.com/3281090/230186417-5bedd46f-f6be-4d6b-846c-a77b8bc00d61.png">

**Comment by straker** [comment]
Thanks for the issue (and the previous one). I'm going to address both of them here if that's OK. 

So what I can gather from testing the page is that the search element in question only appears when the browser size is >=1200px wide. Before that size the search input form is hidden. When it's visible, the browser extension correctly reports a color contrast violation for the element. I believe this is the reproduction steps 1-7. When I narrow the page to <1200px, the search input form goes away and running the extension again shows 0 violations (as the element is now hidden).

However, I'm unable to reproduce steps 8-12 as I only get the violation when the element is visible (screen size >=1200px). Are you saying that when the screen size is <1200px and the form is not visible, the extension is giving violations for the element?

<img width="1658" alt="image" src="https://user-images.githubusercontent.com/2433219/230215651-b98cc312-1113-4af5-ab1e-314047d93dfd.png">

<img width="1658" alt="image" src="https://user-images.githubusercontent.com/2433219/230215760-aceca957-b78c-4d42-8b83-d3a9f56c9c4e.png">
