### ISSUE TITLE
axe-core extension not correctly identifying violating target-size

### ISSUE THREAD

**Issue by chas-klaviyo** [dequelabs/axe-core#3979]
### Product

axe Extension

### Product Version

4.6.3

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
Report a target-size violation when the target size is too small for a touch target (e.g. button)

#### Actual
Not seeing a target size violation reported

#### How to Reproduce

Go to https://chas-rickarby-test-store.myshopify.com/ (password: `chas`)
see the modal pop up
note the small button size (text `asdf`)
see that axe does not report the target size

#### Additional context

![image](https://user-images.githubusercontent.com/81972436/230672968-7971dbbd-8c1f-4f30-ac2c-116e0289ea3e.png)

**Comment by straker** [comment]
Thanks for the issue. The reason why target-size is not reporting violations is because it is a `wcag22aa` rule and the extension only runs `wcag21aa` and below.

**Comment by straker** [comment]
Going to close. Please feel free to reopen if the question was not answered to your satisfaction.
