### ISSUE TITLE
axe core throws 1.4.1.b (Use color alone) false positive issue even if the link text (font weight) is bolded

### ISSUE THREAD

**Issue by DQUday** [dequelabs/axe-core#3981]
### Product

axe-core

### Product Version

4.6.3

### Latest Version

- [X] I have tested the issue with the latest version of the product

### Issue Description

Expectation
If the link text has any additional indicators apart from color alone differentiation with the surrounded text, then this check should not take place as there is no color alone usage here. 

Actual
Axe-core flags an issue here assuming there is color alone since the link text alone (not the entire <a> tag) is provided font weight as bold. 

How to Reproduce
1. Take any link with surrounded text and ensure the link text alone (within <a> tag) is bolded.
2. Now run the axe-core using axe Expert and axe DevTools (Enable the "Needs Review" option)
3. Notice false positive raised for the link even though it has additional differentiation.

Screenshot
![link with bold text issue](https://user-images.githubusercontent.com/71381558/230992589-c88b607e-05f7-4f61-92a2-949602a508ae.png)

**Comment by DQUday** [comment]
@melaniephilipp,

**Comment by WilcoFiers** [comment]
I wasn't able to reproduce this. Please provide a page or codepen where you've seen the problem.

**Comment by DQUday** [comment]
Codepen example I have created - https://codepen.io/udayshetty2023/pen/abRvboN

**Comment by WilcoFiers** [comment]
Tested. This is reported as incomplete. This is expected behaviour for axe-core. I think the confusion here came from this failing in 4.6.0.
