### ISSUE TITLE
IGT keyboard test Datatable (role=grid) issues

### ISSUE THREAD

**Issue by dkdewitt** [dequelabs/axe-core#3985]
### Product

axe-core

### Question

IGT table tests state that 
"The Table IGT does not currently support ARIA grids and tables (role="grid" and role="table")." when I run the Keyboard IGT it is failing for "The element's role is missing or is not appropriate for the element's function." on the table header.  The th element and aria attributes are created within the library.  Because the Table IGT does not support these aria grids and tables will that cause issues on the Keyboard IGT?

Library used for tables
https://datatables.net/

**Comment by thuey** [comment]
Hi @dkdewitt 👋 

Sorry, I don't fully understand the question. The disclaimer in the Table IGT that it does not support ARIA grids and tables is just referring to the fact that it requires tables be created using HTML `<table>`, `<th>`, `<td>`, etc. elements and not things like `<div role="table">` or `<div role="gridcell">`.

The example on the home page for https://datatables.net/ looks like it is using HTML table elements, so it seems like it should be okay.

Hopefully that helps. If not, could you elaborate on your question and/or provide a more specific example?

**Comment by dkdewitt** [comment]
@thuey I was thinking that may be an issue seeing the deque example had buttons.  I'll check with the library maintainers to see if they have an option for this or let them know they may not be compliant currently.
