### ISSUE TITLE
axe DevTools does not respect prefers-reduced-motion

### ISSUE THREAD

**Issue by CharlesBelov** [dequelabs/axe-core#4002]
axe DevTools 4.49.03
axe-core 4.6.3
macOS 13.3.1 (a)
Firefox 112.0.2

#### Expectation
I expect axe-core to respect prefers-reduced-motion by not serving me animation.

#### Actual
When clicking an item in an accessibility report for a page, axe-core does a sliding animation even though I have prefers-reduced-motion specified in my operating system.

#### How to Reproduce
Provide a code sample or link to a webpage that reproduces the issue. Without this, your issue may be closed without investigation.

Steps:
In macOS:
1. In the Apple menu, choose System settings.
2. Choose Accessibility.
3. Choose Display.
4. Enable Reduce motion.

In Firefox with axe-core enabled:
5. Go to a page that has multiple errors. (https://www.sfmta.com/system/test-page-accessibility-errors)
6. In the Tools menu, choose Browser Tools.
7. Choose Web Developer Tools.
8. Click on the axe DevTools tab.
9. Click start new scan.
10. Click Scan all of my page
11. Wait for the results to appear
12. Click on one of the issue titles

Expected result: the issue displays as expanded without animation
Actual result: the issue does a sliding expansion

13. Click on the same issue title

Expected result: the issue collapses without animation
Actual result: the issue does a sliding collapse

#### Additional context
None

**Comment by scurker** [comment]
This was implemented in [cauldron 5.3.0](https://github.com/dequelabs/cauldron/blob/develop/CHANGELOG.md#530-2023-05-05) and should be available in the next axe extension release.
