### ISSUE TITLE
Axe fails with new color spec

### ISSUE THREAD

**Issue by enyo** [dequelabs/axe-core#4007]
### Product

axe-core

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation

I’m using `oklch` on my page. I have added a media query to test if the browser supports it, and fall back to `rgb()` if not. I expect `axe-core` to either ignore my `oklch` definitions, or be able to parse them properly.

#### Actual

`axe-core` fails with:

`axe-core Error: Unable to parse color "oklch(0.992 0.03 171.25)”`

<img width="276" alt="image" src="https://user-images.githubusercontent.com/133277/236427407-f53dbc48-d722-4918-a3c1-45ee730a71bb.png">

#### How to Reproduce

```html
<div>Test</div>
<style>
  div {
    background: #000;
    text: white;
  }
  @supports (color: oklch(0% 0 0)) {
    div {
      background: oklch(0% 0 0);
    }
  }
</style>
```

#### Additional context

This prevents me from using the new color syntax since my accessibility tests completely break.

**Comment by bramus** [comment]
Was just about to file a similar issue, after I noticed it couldn’t parse oklab colors: `axe-core Error: Unable to parse color "oklab(0.876139 0.0000397742 0.0000175595)"`

My snippet specifically uses the `color-mix` function:

```css
--bgcolor: red;
background: color-mix(in oklab, var(--bgcolor), white 20%);
```

**Comment by WilcoFiers** [comment]
Thanks for reporting. We clearly missed something here.

**Comment by straker** [comment]
@enyo Could you elaborate on what you mean that this completely breaks your accessibility tests? I tested out the code and axe-core does not crash but instead just reports the problem as an incomplete issue of color-contrast. Are you checking the incomplete property in your tests?

**Comment by bramus** [comment]
It breaks the accessibility test in Lighthouse, which uses axe-core under the hood.

See https://twitter.com/bramus/status/1655504052518637569 + follow-up tweet for an example report.

**Comment by straker** [comment]
Thanks for the added context, that helped a lot understand what is going on.

**Comment by enyo** [comment]
@straker exactly as @bramus said: it breaks my lighthouse tests, and so I can’t use the color because then I just don’t get a meaningful result (and I wouldn’t settle for anything less than 100 anyway 😉)

I too reverted to using basic colors but I’d love to use the new ones because they are just more vibrant on displays that support them.

**Comment by enyo** [comment]
@straker wow! Thanks for the quick fix. Do you know when this will be available on pagespeed.web.dev?

**Comment by straker** [comment]
@enyo Can't say for certain but I feel that they do a good job of keeping up-to-date on patch releases.

**Comment by padmavemulapati** [comment]
Validated with the lates axe-core develop branch code base,

now not seeing failures for color combinations, like  hwb(), lab(), lch(), oklab(), and oklch(). 
We are supporting all those css color specs [hwb(), lab(), lch(), oklab(), and oklch]

https://github.com/dequelabs/axe-core/assets/47409579/93f43554-7cb4-4700-93dc-547fc25f308e

**Comment by wokalek** [comment]
Still have this issue.

You can run lighthouse on https://evilmartians.com/chronicles/oklch-in-css-why-quit-rgb-hsl

**Comment by straker** [comment]
@wokalek i tested the page with axe-core@4.7.2 and it doesn't break the color contrast test. Looks like lighthouse pulled in 4.7.2 [a few weeks ago](https://github.com/GoogleChrome/lighthouse/pull/15165). I tried to run lighthouse on the page but it just freezes on "Lighthouse is warming up..."

**Comment by wokalek** [comment]
> @wokalek I tested the page with axe-core@4.7.2 and it doesn't break the color contrast test. Looks like lighthouse pulled in 4.7.2 [a few weeks ago](https://github.com/GoogleChrome/lighthouse/pull/15165). I tried to run lighthouse on the page but it just freezes on "Lighthouse is warming up..."

I know this issue with "Lighthouse is warming up...", that's another (:

You can `chrome://restart` if you see this issue in lighthouse. Retest please.

**Comment by wokalek** [comment]
@straker 
Testing in guest window.

![image](https://github.com/dequelabs/axe-core/assets/23037847/9c832ab3-c334-4ed9-81bd-9e1d88884829)

**Comment by enyo** [comment]
I just tested on PageSpeed Insights and my oklch colors finally pass! :)

**Comment by axeen** [comment]
I'm actually still getting this

<img width="800" height="415" alt="Image" src="https://github.com/user-attachments/assets/ce6c977b-00f0-4f97-a7d9-5c743ee8749b" />

Was solved by replacing `none` with `0`. But feels like valid CSS should still pass.

**Comment by coder2000** [comment]
Just a nudge, I have currently disabled my contrast checks because of this issue and Tailwind v4 using `none` in it's generated values.
