### ISSUE TITLE
Label-title-only inconsistent on whether labels not provided visually are violative

### ISSUE THREAD

**Issue by nolandanley** [dequelabs/axe-core#4015]
### Product

axe-core

### Product Version

v4.7.0

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
Violations of `label-title-only` should be consistent about whether labels must be visible to avoid a violation.

#### Actual
Violations of `label-title-only` may appear if a label is provided programmatically (e.g. with `aria-labelledby`) but calculated to not be visible although no violation will be raised if the label is only provided programmatically (e.g. with `aria-label`) without a visual label.

#### How to Reproduce

```html
<!-- 
  Copyright 2023 Google LLC.
  SPDX-License-Identifier: Apache-2.0
-->

<span id="description">Description</span>

<!-- LABEL NOT VISIBLE, VIOLATION -->
<span id="no-display-label" style="display: none">Label not displayed visually</span>
<input aria-labelledby="no-display-label" aria-describedby="description" />

<!-- LABEL NOT VISIBLE, VIOLATION -->
<span id="no-visibility-label" style="visibility: hidden">Label not displayed visually</span>
<input aria-labelledby="no-visibility-label" aria-describedby="description" />

<!-- LABEL NOT VISIBLE, NO VIOLATION -->
<input aria-label="Label not displayed visually" aria-describedby="description" />
```

#### Additional context
This is coming from [a comment in a prior thread](https://github.com/dequelabs/axe-core/issues/3174#issuecomment-1531909726) that was asked to be filed as a new issue. Tested with v4.7.0 on Chrome.

**Comment by WilcoFiers** [comment]
This is intentional. The idea is that if you can associated the element with another element that represents the label, then you might as well make the label visible. There are scenarios for using aria-label, even if there is a visible label. Particularly that might be necessary when the label and form element are in different (shadow) DOM trees.
