### ISSUE TITLE
Incorrect if-test on 'refresh under 20 hours'

### ISSUE THREAD

**Issue by mem76** [dequelabs/axe-core#4043]
There is a minor error in the "Delayed refresh under 20 hours must not be used"

The test is off by one second. The correct value is saved in the json config-files in the code, but the test should be:

`if ( $refresh_time >= 72000 ) { // test pass }`

and not

`if ( $refresh_time > 72000 ) { // test pass }`

**Comment by WilcoFiers** [comment]
I don't think so?

> 20 Hour Exception: The time limit is longer than 20 hours.

The way I read this, if the time limit is exactly 20 hours, it's not longer than 20, so the exception wasn't met. Am I missing something there?

**Comment by mem76** [comment]
W3.org : 
> 20 Hour Exception: The time limit is longer than 20 hours. 

Axe DevTools: 
> Delayed refresh under 20 hours must not be used

By the quote from w3.org, the code is correct.

But this makes the text displayed in Axe incorrect.

I made the mistake of thinking you had quoted the standard correctly.

**Comment by Sandrakay49** [comment]
Omg show new one so I can get pictures. Hurry I've got to go to work
