### ISSUE TITLE
Memory issue causing browser crash

### ISSUE THREAD

**Issue by nolandanley** [dequelabs/axe-core#4045]
### Product

axe-core

### Product Version

v4.7.1

### Latest Version

- [X] I have tested the issue with the latest version of the product

### Issue Description

We had reports of some tools within our company that used axe-core crashing because of memory issues on certain pages. Someone investigated this and found 2 places where `VirtualNode` references are retained after `teardown()`.

1. [`recycledLocalVariables`](https://github.com/dequelabs/axe-core/blob/0e73be039eed78fda20e9bf28ee7f6f7c0d62fd8/lib/core/utils/query-selector-all-filter.js#L30)
2. [`channels`](https://github.com/dequelabs/axe-core/blob/0e73be039eed78fda20e9bf28ee7f6f7c0d62fd8/lib/core/utils/frame-messenger/channel-store.js#L3)

The second one seems to be causing the most issues. [There's a timeout, but it doesn't seem to clean up the handlers.](https://github.com/dequelabs/axe-core/blob/0e73be039eed78fda20e9bf28ee7f6f7c0d62fd8/lib/core/utils/send-command-to-frame.js#L50)

This is not a blocking issue for us right now. We have a way of working around it in our tools, so it's not as high of a priority for us to get resolved as it would be otherwise.

**Comment by Sandrakay49** [comment]
I want to know name or company need it fast am getting so tired of this person and I know who IT is just need proof
