### ISSUE TITLE
How to exclude element in a list?

### ISSUE THREAD

**Issue by MelSumner** [dequelabs/axe-core#4061]
### Product

axe-core

### Question

I use `<li role="separator">` inside of lists. 

I don't mind it if axe wants to fail on that, but how do I target it in an exclude? 

I tried using `selectors` but it fails on the list element itself, not the `li` element. So I can only exclude on the list itself.

I'd prefer not to exclude the whole list, because it's a component and users could invoke it incorrectly and I _do_ want a11y tests to catch that. I only want to exclude a list item with the role of separator. 

Any ideas here?

**Comment by WilcoFiers** [comment]
Hey Melanie. Yeah, I'm not sure what's up with `separator` in lists. I opened an issue on it with ARIA a while back (https://github.com/w3c/aria/issues/1889).

Axe-core will ignore items with `aria-hidden` and `role="none"`; although if you use role=none you do need to make sure there's nothing inside that li that could get included in the accessibility tree. That should get assistive tech to skip them consistently and ignore them in the listitem count.

**Comment by MelSumner** [comment]
ok I will try adding aria-hidden on the li with the role of separator. Thanks for the feedback!
