### ISSUE TITLE
Text stroke (shadow) edge case not getting picked up

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#4064]
This should pass, however when I run it through axe the text-stroke is seen as too thin to be relevant. Not sure why that is, but this end up with a 1px stroke around text that is really fairly readable. My guess is this comes because it has move overlapping shadows than I initially accounted for:

```html
<style>
  h3 {
    text-shadow:
      -1px -1px 0 #000,
      0 -1px 0 #000,
      1px -1px 0 #000,
      1px 0 0 #000,
      1px 1px 0 #000,
      0 1px 0 #000,
      -1px 1px 0 #000,
      -1px 0 0 #000;
    color: #ffcc00;
    font-size: 24px;
    letter-spacing: normal;
    text-transform: uppercase;
  }
</style>
<h3>Hello World</h3>
```

**Comment by padmavemulapati** [comment]
Validated using axe-core develop branch code base,

the code with text-shadow stroke with 1px around it is passing as it is readable



https://github.com/dequelabs/axe-core/assets/47409579/e1ceb56b-946e-4684-b9af-6adc2e714f8c
