### ISSUE TITLE
Put aria-prohibited-attr (from aria-allowed-attr) into its own rule

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#4067]
Part of https://github.com/dequelabs/axe-core/issues/4066

The `aria-prohibited-attr` check should run in its own rule, instead of as part of `aria-allowed-attr`.

**Comment by padmavemulapati** [comment]
Validated using latest axe-core develop branch code base,
seeing `aria-prohibited-attr` as a seperate rule instead `aria-allowed-attr` for the prohibited attributes like caption, code, deletion, emphsis, insertion ... etc.,



https://github.com/dequelabs/axe-core/assets/47409579/24659caf-0399-4008-9a6f-5a1e0fbd343b
