### ISSUE TITLE
Update `math.getOffset` algorithm to better align with spec

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core#4119]
As part of #4117 we determined that the `math.getOffset` calculation is not correct and needs to be updated. It didn't produce any false-positives so we decided to update the code in another pr in order to get 4.8 out the door.

The algorithm should be as follows:

For targets with target size >= 24x24px, we should make sure we skip the (potentially expensive) offset calculation since the spacing exception isn't relevant. Target size === largest unobscured rect from `math.splitRects`. E.g. the result of calling `dom.getTargetSize`.

Otherwise, for undersized `target`s:

1. determine bounding rect of `target` and get the center (we'll call `centerTarget`). [Bounding rect](https://www.w3.org/TR/WCAG22/#dfn-bounding-boxes) === the result of calling `math.getBoundingRect` for each rect in `splitRects`. (should be a new function)
1. determine the target's "neighbors" using grid (any other target that might be within 24px of any part of `target`'s bounding rect is a neighbor)
1. for each `neighbor`:
    1. determine `neighborSplitRects` using `math.splitRects(neighbor)`
    1. for each `neighborSplitRect`:
        1. calculate distance from `centerTarget` to the nearest point in `neighborSplitRect` (may be 0 if `centerTarget` lies within `neighborSplitRect`)
    1. let `neighborSpacing` be the minimum `neighborSplitRect` distance
    1. if the `neighbor` is *also* undersized (target size < 24x24px):
        1. calculate `centerNeighbor` similarly to `centerTarget` using the neighbor's bounding box
        1. if the distance from `centerTarget` to `centerNeighbor` is < `neighborSpacing`, use that as the new `neighborSpacing`
1. return the minimum `neighborSpacing` from among all neighbors

**Comment by padmavemulapati** [comment]
Validated with the latest axe-core develop branch code base,
on running ` await axe.run({runOnly:'target-size'});` at the console for latest `axe.js` script

seeing the target-size failure when the element - 

```
<button style=\"width: 10px; height: 10px; margin: 0; padding: 0; position: absolute; top: 0; left: 0\">&nbsp;</button>"

```
and also failure summary is more precised now:

```
failureSummary:
"Fix any of the following:\n  Target has insufficient size (10px by 10px, should be at least 24px by 24px)\n  Target has insufficient space to its closest neighbors. Safe clickable space has a diameter of 0px instead of at least 24px."

```


![Image](https://github.com/dequelabs/axe-core/assets/47409579/ea2b7945-5af2-4f44-a9fa-431d108afe9a)
