### ISSUE TITLE
Plugins not running in iframes using srcdoc

### ISSUE THREAD

**Issue by curtbellew** [dequelabs/axe-core#4134]
### Product

axe-core

### Product Version

4.7.2

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
We are using axe-core plugin functionality.  We run custom code against main pages and iframes.  The code should run in each iframe whether the source is provided via the src or srcdoc attribute.

#### Actual
When run against iframes where the source is provided using srcdoc, the plugin does not run against the iframe.

#### How to Reproduce
I have a version of a developer tools extension that implements a very simple axe-core plugin but I'm not sure how to share it here. My developer tools extension sample will find H1 elements in the page and add a border around them.  When my demo developer tools extension runs against a page with code like below, the H1 heading in the main page and the H1 heading in the iframe should have a border rendered around them but the iframe H1 does not get the border.
```
<html><body>
<h1>Main Page</h1>
<iframe id="result" srcdoc="<h1>Frame content</h1>"></iframe>
</body></html>
```

If we separate them out in to two actual files then both of the H1 elements get borders.

iframe1.html = 
```
<html><body>
<h1>Main Page</h1>
<iframe id="result" src="iframe2.html"></iframe>
</body></html>

```
iframe2.html = 
```
<html><body>
<h1>Frame Content</h1>
</body></html>
```

#### Additional context
Any thing else we should know about the issue?

**Comment by straker** [comment]
Thanks for the issue. For axe-core to work with iframes it has to be injected into each of the iframes, including those using `srcdoc`. It's hard to tell from your example, but are you injecting axe-core into the iframe using `srcdoc`?

**Comment by curtbellew** [comment]
Yes we do.  I have a small web extension demo in a zip file that I will try to attach here.  We use axe.registerPlugin where in the run function we loop through all the frames and use sendCommandToFrame for each iframe.  We started to see issues with iframes using srcdoc after trying to upgrade axe-core from 4.1.3. 
[simple.zip](https://github.com/dequelabs/axe-core/files/12423598/simple.zip)

**Comment by straker** [comment]
For security reasons I cannot open the zip file. Is there another way you could send me the code, such as an online code editor like Codepen or the like?

**Comment by curtbellew** [comment]
There are several files involved in the test so I thought I would try adding it to a github repository.  I have placed some iframe code in the repository as well as instructions for installing the extension.  I'm sure I have some unnecessary files in the repository but I'm running too short on time to clean things up - sorry about that.   https://github.com/curtbellew/simpleDevTools/tree/main

**Comment by curtbellew** [comment]
That does seem to have fixed it.  Thanks, @straker !

**Comment by straker** [comment]
No problem. Going to close as resolved.
