### ISSUE TITLE
`target-size` rule contains typos

### ISSUE THREAD

**Issue by adamraine** [dequelabs/axe-core#4148]
### Product

axe-core

### Product Version

4.8.0

### Latest Version

- [X] I have tested the issue with the latest version of the product

### Expectation

Failure message ends with:
"Safe clickable space has a diameter of 10px instead of at least 24px"

10px is just an example value.

### Actual

Failure message ends with:
"Safe clickable space has a diameter of {$data.closestOffset}px instead of at least 24px)"

It appears that the actual `data.closestOffset` value is not being filled in. There is also an unpaired `)` at the end of the string that I think should be removed.

### How to Reproduce

Any code that fails the `target-size` rule.

#### Additional context

https://github.com/dequelabs/axe-core/pull/4117

**Comment by straker** [comment]
Ops, you're right. Thanks for spotting that. We'll get it fixed for the next release.
