### ISSUE TITLE
Oversized NPM version registry

### ISSUE THREAD

**Issue by marcusletric** [dequelabs/axe-core#4178]
### Product

axe-core

### Product Version

Independen

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
NPM registry JSON is not 17Mb
https://registry.npmjs.org/axe-core

#### Actual
JSON is 17Mb

#### How to Reproduce
curl https://registry.npmjs.org/axe-core

#### Additional context
I see thousands of canary hashed versions in the registry JSON
axe-core-4.6.2-canary.dc9feba
axe-core-4.6.2-canary.4c3a00c
etc....

People who use artifactory on lesser hardware than NPM's registry, this can end up being a 3-4 minute long response time that times out on PNPM

**Comment by WilcoFiers** [comment]
@marcusletric Thanks for bringing this up. I agree this is an issue, and I'd like to figure out what can be done about it. Do you have any suggestions?

Unfortunately NPM doesn't support rolling prereleases (we would have used those if that was available). I don't think it offers a way to filter the version file by date or release type or anything. Going from the NPM docs it doesn't seem like they would want us deleting these releases. That feels a bit problematic too. Do you have any suggestions?

**Comment by dbjorge** [comment]
I agree that it'd be nice for the package metadata to be a more reasonable size, but I'm also not sure what we'd realistically be able to do about older existing versions at this point (assuming we're unwilling to attempt to unpublish them, which I'd prefer to avoid).

I don't think this is a problem unique to `axe-core` - for example, `typescript`, `react`, and `aws-sdk` all have same order of magnitude registry sizes.

You mention `curl https://registry.npmjs.org/axe-core` is the correct repro step - in practice, pnpm (and yarn/npm) all do something closer to `curl -H "Accept: application/vnd.npm.install-v1+json" https://registry.npmjs.org/axe-core`, which requests a more minimal form of the package metadata. Against `registry.npmjs.org`, this is still large, but not as large as the original repro step suggests (3.4M vs 16.4M). I note that there appear to be a few Artifactory support tickets tracking various open or recenty-closed issues with Artifactory's support for this abbreviated form ([RTFACT-29557](https://jfrog.atlassian.net/browse/RTFACT-29557), [RTFACT-27265](https://jfrog.atlassian.net/browse/RTFACT-27265), [RTFACT-18398](https://jfrog.atlassian.net/browse/RTFACT-18398)) - it would be good to check on whether your specific artifactory version/setup is correctly responding with that abbreviated form, and if not, report it as an issue to the artifactory folks.

Finally, in general, pnpm (and yarn/npm) only fetch this metadata when they actually need to resolve a specific version of a package - in general, if they already have the specific version established in a lockfile, they'll download the required version directly without querying the registry metadata. In practice, I'd expect that to means that so long as you're using a lockfile, you shouldn't see these large requests during typical `pnpm install` operations, only when when adding/updating the version of axe-core you're using. Are you seeing the problematic performance even in cases where you're already installing against a lockfile? If not, "use a lockfile in your CI builds" might be the workaround you're looking for.

**Comment by straker** [comment]
Closing per request

**Comment by marcusletric** [comment]
FYI: Artifactory has a setting that re-writes the package metadata. Turning that feature off solved our issues.
