### ISSUE TITLE
CORS error in Chrome console with AXE extension

### ISSUE THREAD

**Issue by woody-li** [dequelabs/axe-core#4198]
### Product

axe Extension

### Product Version

4.8.2

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
No errors.

#### Actual
Console error:

> Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://axe.deque.com') does not match the recipient window's origin ('https://www.google.com').

#### How to Reproduce
* Open a site, such as https://www.google.com
* Execute "Scan all"
* Then there's a CORS error in console.

#### Additional context
Chrome: 118.0.5993.71 (Official Build) (64-bit)
axe Extension: v4.65.0
axe-core: v4.8.2

**Comment by straker** [comment]
Thanks for the issue. I've let the appropriate team know

**Comment by scurker** [comment]
@woody-li Thanks for bringing this to our attention, we're currently investigating this. It appears the error in the console is getting raised from the extension, but should not impact the results you get from axe-core. We will update when we have a fix for this error your are seeing.

**Comment by Amandeque** [comment]
I am closing this ticket as reported issue was [fixed](https://github.com/dequelabs/axe-extension/issues/4202) in Axe Devtools Extension v4.67.0 release.
