### ISSUE TITLE
Request tags for WCAG A, AA, AAA levels without specifying version

### ISSUE THREAD

**Issue by backwardok** [dequelabs/axe-core#4238]
### Product

axe-core

### Feature Description

The [current list of tags](https://www.deque.com/axe/core-documentation/api-documentation/#axe-core-tags) includes tags for different versions of WCAG and conformances levels (e.g. `wcag2a`, `wcag21a`, etc), but there's not currently a tag for all A/AA/AAA levels. As far as I can tell, if I want to run tests that meet WCAG 2.2AA, I'd need to include tags `wcag2a`, `wcag2aa`, `wcag21a`, `wcag21aa`, and `wcag22aa`. 

Could there be something like `wcag-a`, `wcag-aa`, `wcag-aaa` that are evergreen to the latest version of WCAG? That way, if you wanted to run all A and AA level, you could use tags `wcag-a` and `wcag-aa`. Alternatively and/or additionally, maybe there could be tags that are something like `wcag-conform-a`, `wcag-conform-aa`, `wcag-conform-aaa`, where `wcag-conform-aa` includes all `wcag-aa` and `wcag-conform-a`, and `wcag-conform-aaa` includes all `wcag-conform-aa` and `wcag-aaa`

**Comment by WilcoFiers** [comment]
Thank you for the suggestion @backwardok. I don't think we can do this though. Firstly, tags are used in reports and interface. Duplicating information in tags means that various reports and interfaces will end up with duplicate information. That's not ideal. Second, I'm not keen on the complexity this adds to tags. People who want to use tags will now need to know the difference between these two (or three) different ways that things get tagged. It introduces more opportunities for people to misunderstand things.

Axe-core lets you run with tags that don't currently exist, so if you are concerned about us at some point introducing a rule with `wcag22a`, feel free to add that tag in your configuration.  I very much doubt there will ever be a WCAG 2.3, but you can add tags for that without issue too. It's a little extra configuration, but not so much that I think we can introduce new tags for it.

What Deque does have, but this is only in paid products, is the concept of a ruleset. You turn on for example the WCAG 2.1 level A ruleset, and it configures axe to only use the `wcag2a` and `wcag21a` tags. This is a setting that can be configured organisation-wide. There are no plans to make this part of the open source product, but if we do ever add something like that it would be through a ruleset option, not through a new tag.

**Comment by backwardok** [comment]
Thanks for the response @WilcoFiers ! How does axe currently treat reports that are related to categories vs wcag version + levels? Could it be something that's more similar to that?

**Comment by WilcoFiers** [comment]
@backwardok I'm not sure what you meant. Can you explain?

**Comment by backwardok** [comment]
Hey @WilcoFiers ! My thought was related to how there are tags that are categories (like `cat.aria`) that can apply to different rules, and they have overlap with WCAG levels and rulesets. If we didn't want to use something that started with `wcag` since it might be confused with the existing tags, maybe there could be something like `level-a`, `level-aa`, `level-aaa` so that if you picked `level-a` and `level-aa`, that would always get all the A and AA SC rules regardless of version
