### ISSUE TITLE
Axe-core Error: TypeError in getImageData after adding Affirm Promotional Messaging to our website

### ISSUE THREAD

**Issue by rafad1v** [dequelabs/axe-core#4242]
### Product

axe-core

### Product Version

Axe version: 4.7.2

### Latest Version

- [X] I have tested the issue with the latest version of the product

### Issue Description

Encountered an error while using Axe-core on Lighthouse 11.0.0 via https://pagespeed.web.dev/. The issue seems to be specific to pages that include Affirm's Promotional Messaging.

Error Details:

axe-core Error: `TypeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Value is not of type 'long'.` - feature unsupported in your environment. Skipping color-contrast rule.:

![image](https://github.com/dequelabs/axe-core/assets/30705846/b29c3b82-0cb2-4635-bb7c-c1d2f9c96275)

**Comment by dylanb** [comment]
Please report this to Google
