### ISSUE TITLE
Locales incomplete

### ISSUE THREAD

**Issue by EvilKarter** [dequelabs/axe-core#4248]
### Product

axe-core

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
I have set the locale to German as described in the documentation. However, not all rules and checks are translated. 

#### Actual
I expected that all rules and checks are translated

#### How to Reproduce
Set axeSource to german localized build.

#### Additional context
Any thing else we should know about the issue?

**Comment by straker** [comment]
Thanks for the issue. Axe-core's translations are provided by the community as a curtesy and so are only as up-to-date as the last provided translation. I see you opened a pr to update the translations. Thanks for your contribution. I'll go ahead and close this issue and try to review the pr next week.
