### ISSUE TITLE
 empty List  `<li>`  `<ol>` ordered list or `` unordered list

### ISSUE THREAD

**Issue by asthaawasthi-laitkor** [dequelabs/axe-core#4309]
### Product

axe-core

### Question

does axe-core check for the list contains empty `<li>` elements,  `<ol>` ordered list or `` unordered list that contains no list items.
if the list item are nested with <a>and <svg>.

**Comment by straker** [comment]
Thanks for the question. Axe-core does not do HTML validation so has no rule to check for empty lists or list items.

**Comment by asthaawasthi-laitkor** [comment]
Thank you @straker  for the information
