### ISSUE TITLE
Make some ARIA data public

### ISSUE THREAD

**Issue by clamli** [dequelabs/axe-core#4348]
### Product

axe-core

### Feature Description

Hi Deque!

We are developing a tool (like axe Linter) with the ability to detect axe-core violations within a codebase and provide users with suggestions on how to fix these violations. The suggested fixes for three specific rules (aria-roles, aria-valid-attr and aria-valid-attr-value) involve calculating the closest valid option, which includes a list of ARIA roles, attributes and values. Do you think this is achievable? If yes, is it possible to make this data accessible outside the library?

The suggested fixes we plan to implement,

aria-roles | replace role value with closest valid ARIA role
aria-valid-attr | replace violative attribute with closest valid ARIA attribute
aria-valid-attr-value | replace violative attribute value with closest valid ARIA attribute value

**Comment by WilcoFiers** [comment]
@clamli This information is considered part of axe-core's internal mechanisms. I'm afraid this is not something Deque provide support for.
