### ISSUE TITLE
Axe hangs forever on https://almanac.httparchive.org/en/2021/ecommerce

### ISSUE THREAD

**Issue by adamraine** [dequelabs/axe-core#4360]
### Product

axe-core

### Product Version

4.8.2

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation

Axe to produce results.

#### Actual

Axe hangs forever.

#### How to Reproduce

Run axe-core or the axe extension on this site: https://almanac.httparchive.org/en/2021/ecommerce

#### Additional context
https://github.com/GoogleChrome/lighthouse/issues/15824

**Comment by straker** [comment]
Thanks for the issue. It just so happens that I just ran into this problem earlier today and opened https://github.com/dequelabs/axe-core/issues/4359. For this site's case it's the comment section which produces the problem as the div surrounding the comments has a `tabindex=0` and each of the comment blocks contain links and buttons that are the overlapping elements.
