### ISSUE TITLE
Aria-roles standards object contains many roles that are classified as widgets but are not

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core#4371]
Role such as `tabpanel`, `timer`, `alert`, etc. are marked as widgets but they shouldn't be. This problem is contributing to https://github.com/dequelabs/axe-core/issues/4360 as each example uses a tabpanel with many overlapping child nodes.

We'll need to investigate the ramifications of changing these to their correct types before we make the change.

**Comment by WilcoFiers** [comment]
An example where this is creating a false positive is on https://www.hep.ca/horse-insurance/. The close button the cookie banner is 15x15. Axe is failing this for being too close to the to the cookie banner, which has tabindex=0 and role=alert.

**Comment by gaiety-deque** [comment]
Just as a note, the description I believe is _slightly_ inaccurate as `tabpanel` **does belong** to the widget abstract role https://www.w3.org/TR/wai-aria/#widget_roles

I'm playing with getting everything synced to the spec now to see where that gets us
