### ISSUE TITLE
False positive for `nested-interactive` on custom elements with a shadow DOM

### ISSUE THREAD

**Issue by scottsb** [dequelabs/axe-core#4372]
### Product

axe-core

### Product Version

4.8.4

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
Given a custom element with an interactive role (e.g., `button`) that has a shadow DOM containing a native interactive element (e.g., `<button>`), the `nested-interactive` rule should not fail.

In this scenario, the nested interactive element inside the shadow DOM cannot receive focus or direct interaction; instead, the parent custom element captures the focus. Therefore, there is no problem, and the rule should not fail.

#### Actual
The rule fails.

#### How to Reproduce
See this CodePen for an example:
https://codepen.io/scottsb/pen/jORrgxX

**Comment by straker** [comment]
Thanks for the issue. So I tested this in our supported AT / browser combinations and this is the results:

* JAWS / Chrome
  * Tabbing to the button announces "My Custom Button Button, My Custom Button Button" (reads the name twice). The regular buttons only have their name read once
  * Navigating line-by-line has two stops on the custom button, each one reads the name of the button 
* NVDA / Firefox
  * Tabbing to the button announces "My Custom Button Button Button" (role gets twice). The regular buttons only have the role announced once
  *  Navigating line-by-line announces "Button Button My Custom Button" (role gets read twice again)
* VO / Safari
  * Tabbing to the button announces "My Custom Button, button" 
  * Can't seem to navigate line-by-line to text inside a shadow dom. Trying to do so just skips over the button (even if I remove the role from the host element). Seems Safari treats the shadow dom as a frame? When you tab to it the button the help text says it's a button inside frame 0

Based on the results where the button or role is read out twice, or produces an extra stop, nesting interactive elements even across shadow dom still causes problems for screen readers.

**Comment by scottsb** [comment]
Hmm, thanks for the testing. I was depending on what the spec seemed to indicate and what I could test with VoiceOver, since I don't have access to a PC to test with JAWS/NVDA.

FWIW, when it comes to VO/Safari, I am able to get to the custom button if I use V.O.-Left or V.O.-Right to navigate, but I see it skips the button when using the arrow keys without modifier (QuickNav). This difference in behavior seems like a browser bug (but not one directly relevant to this issue).

**Comment by dylanb** [comment]
The principle we are following here is called [accessibility supported](https://www.w3.org/TR/WCAG22/#cc4) so when the browsers/ATs fix their bugs, we'll change the tests
