### ISSUE TITLE
"heading-order: true" not working

### ISSUE THREAD

**Issue by FedericoBrianzi** [dequelabs/axe-core#4378]
### Product

axe Linter

### Product Version

v4.8.2

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation:
I'm expecting the tool to print out an error whenever the headings order is not respected.

#### Actual:
No error is printed.

#### How to Reproduce:

That's all the code that i have:
![Cattura](https://github.com/dequelabs/axe-core/assets/43077235/3dcaee16-0bb4-46fc-8cb9-a15a4a9f3fcc)

And that's the only rule i have:

![Cattura2](https://github.com/dequelabs/axe-core/assets/43077235/8ef62470-f495-43a7-9d30-a325c31bc153)

#### Additional context:
I'm really new to all of this so i might be missing something.

**Comment by straker** [comment]
Thanks for the issue. The `heading-order` rule only reports violations when heading levels are skipped going in sequential order (going from `h1` to `h3` for example). The `heading-order` rule doesn't look at the headings that go in reverse order (`h3` to `h1`) as that order is valid since that signifies the end of the section (`h1`, `h2`, `h3`, `h1` is valid). It also doesn't enforce that headings start at `h1` so the starting order isn't validated which is why in your example you can start at `h3`.

See https://dequeuniversity.com/rules/axe/4.4/heading-order and https://www.w3.org/WAI/tutorials/page-structure/headings/ for more information.

**Comment by FedericoBrianzi** [comment]
Thanks for the quick reply @straker !
Anyway i still have some doubts about this topic, as the first page you linked me says:


> "Usually, the best practice is to start the main content of a web page with a level 1 heading element (h1), with no other headings before this high-level heading."

 And also

> "Anything that comes before the main content of the page **_should not_** be marked up with any headings at all, though this is not an iron-clad rule. One of the main reasons that the h1 element should appear at the beginning of the main content is because screen reader users can use keyboard shortcuts to navigate directly to the first h1 element, which, in principle, should allow them to jump directly to the main content of the web page. If there is no h1 element, or if the h1 element appears somewhere other than at the start of the main content, screen reader users will have to listen to additional web page content to understand the page structure, wasting valuable time."

I tought this was enought for the tool to point out accessibility problems with the code i submitted, am i totally wrong with that?

**Comment by straker** [comment]
It is indeed a best practice to start the main section with an `h1` element, but that is nothing something axe-core checks. The `heading-order` rule only checks that headings are not skipping orders.

**Comment by FedericoBrianzi** [comment]
Got it, thank you for you time 👌

**Comment by dylanb** [comment]
@FedericoBrianzi I would also argue that starting with an H1 on a web page that is not just a document is not a best practice.

The reason for this is that the actual content on the page is almost always preceded by some sort of header and this header should have heading if it is at all complex/large.

A much better best practice statement is "the main content of the page should start with an h1 and if there are multiple equal sections of a page (e.g. articles), each one should start with an h1"
