### ISSUE TITLE
Make rule descriptions more consistent

### ISSUE THREAD

**Issue by sknep** [dequelabs/axe-core#4385]
### Product

axe-core

### Description

In the rule description tables at https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md#rule-descriptions , many start with "Ensures...", but some start with "Ensure..." or "Ensure that...".

Is the description field meant to be an explanation of what the rule is for, or what the reader should do to remediate? The second seems more appropriate, but the implied subject of the sentence (rule vs remediation) changes between rules.

Also, "Ensure touch target have sufficient size and space" -- target should be plural, regardless.

**Comment by straker** [comment]
Thanks for the issue. I've brought this up with the team and we've agreed that we'd like to go with "Ensure" for each of the rule descriptions. If you're willing, we'd love a PR fixing all the rule descriptions to be consistent, as well as fixing the target size rule as you've mentioned.
