### ISSUE TITLE
getSelector very slow on some DOM patterns

### ISSUE THREAD

**Issue by Janpot** [dequelabs/axe-core#440]
Been doing some performance testing with axe-core library with the following code:

```html
<!doctype html>
<html>
<head>
  <title>Test</title>
</head>
<body>
  <div id="container">
    <p class="links"></p>
  </div>

  <script src="../axe.js"></script>
  <script>
    const links = document.querySelector('.links');
    for (let i = 0; i < 1000; i++) {
      const a = document.createElement('a');
      a.text = `link text ${i}`
      a.href = `http://example-${i}.com`
      links.appendChild(a);
      const br = document.createElement('br');
      links.appendChild(br);
    }

    async function run () {
      const start = performance.now();
      const res = await axe.run(document);
      console.log(res);
      console.log(`took: ${performance.now() - start}ms`);
    }

    async function runTest () {
      console.log('with getSelector');
      await run();
      console.log('without getSelector');
      axe.utils.getSelector = () => null;
      await run();
    }

    setTimeout(runTest, 2000);
  </script>
</body>
```

On my machine, running with getSelector takes about 6 seconds, running without takes about 1.5 seconds.

I tried with a version that caches the selector on the element with the following (naive) code, and it took down the runtime to about 2.5 seconds:

```js
axe.utils.getSelector = function createUniqueSelector (elm, options = {}) {
  //jshint maxstatements: 22
  if (!elm) {
    return '';
  }
  if (elm.__selector) {
  	return elm.__selector;
  }
  let selector, addParent;
  let { isUnique = false } = options;
  const idSelector = createSelector.getElmId(elm);
  const {
    featureCount = 2,
    minDepth = 1,
    toRoot = false,
    childSelectors = []
  } = options;

  if (idSelector) {
    selector = idSelector;
    isUnique = true;

  } else {
    selector = getElmFeatures(elm, featureCount).join('');
    selector += getNthChildString(elm, selector);
    isUnique = options.isUnique || document.querySelectorAll(selector).length === 1;

    // For the odd case that document doesn't have a unique selector
    if (!isUnique && elm === document.documentElement) {
    	selector += ':root';
    }
    addParent = (minDepth !== 0 || !isUnique);
  }

  const selectorParts = [selector, ...childSelectors];

  if (elm.parentElement && (toRoot || addParent)) {
    elm.__selector = createUniqueSelector(elm.parentNode, {
      toRoot, isUnique,
      childSelectors: selectorParts,
      featureCount: 1,
      minDepth: minDepth -1
    });
  } else {
    elm.__selector = selectorParts.join(' > ');
  }
  return elm.__selector;
};
```

For real world use this should probably be implemented differently since it influences subsequent runs. or example, it could be done with using an ES6 `Map` that maps elements to cached values, or by using ES6 Symbols for properties to hold cached values.

Looking through the rest of `get-selector.js` there are several more opportunities to optimize in this way. For instance `getNthChildString` does a lot of duplicate iteration on the 1000 element node list in this test.

**Comment by dylanb** [comment]
@Janpot thank you for using and contributing to axe-core!!

Have you experienced performance problems on real world sites related to getSelector? What concerns me about this specific test is the fact that the page basically consists only of anchors at the exact same level within the DOM. This is a particularly bad case for this code.

**Comment by Janpot** [comment]
I'm evaluating this library at the moment and running it on a lot of webpages. When analyzing our logs yesterday I found about 300 pages passing per day that take well over a minute to run axe on. I just started manually checking a few to find common patterns in the DOM and replicated in this little test.

**Comment by dylanb** [comment]
@Janpot when you run the library on those files without getSelector - what is the execution time?

**Comment by Janpot** [comment]
@dylanb Sorry for the late answer,

I just nulled out the `getSelector` as I don't need it
```
axeInst.utils.getSelector = () => null;
```

**Comment by dylanb** [comment]
@Janpot excellent - however you might want to check out axe-core v3 - the performance is much improved
