### ISSUE TITLE
Don't break on window.CSS === null

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#4400]
Angular + Jest documentation recommends a solution which ends up setting `window.CSS` to null. This creates an issue when axe-core imports colorjs, which has a falsey check for `window.CSS`, but when `null` errors out.

Since ColorJS didn't accept [our patch](https://github.com/color-js/color.js/pull/472/files), we'll try to use [patch-package](https://www.npmjs.com/package/patch-package) to fix the issue ourselves. We'll need some tests to go along with that to confirm our solution continues to work after updating ColorJS.

patch-package should probably run in the build step, not as a post-install.

**Comment by gaiety-deque** [comment]
Just for full context, `window.CSS` is no longer recommended in the Jest docs (thanks Michael) https://github.com/thymikee/jest-preset-angular/commit/ac30648347ab41e0cbce741f66ae2a06b766fe13 which is live on their docs site https://thymikee.github.io/jest-preset-angular/docs/getting-started/installation/#global-mocks
