### ISSUE TITLE
Label not found when using button with exotic role (eg checkbox)

### ISSUE THREAD

**Issue by csmatt** [dequelabs/axe-core#4401]
### Product

axe-core

### Product Version

4.8.4

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
Describe what you expected the product to do.

#### Actual
Describe what the product actually does.
axe should find the label via label-for with the button role=combobox or role=checkbox associated via `id`

#### How to Reproduce
Provide a code sample or link to a webpage that reproduces the issue. Without this, your issue may be closed without investigation.

The best way to reproduce is to go to the shadcn page for their `<Select>` [component](https://ui.shadcn.com/docs/components/select) and run the axe extension on the page. It will be the last violation under 'Buttons must have discernible text'.

It can also be seen via the shadcn page for their `<Checkbox>` [component](https://ui.shadcn.com/docs/components/checkbox) as the second violation under 'Buttons must have discernible text'.

#### Additional context
Any thing else we should know about the issue?

I also see the issue when running the axe Jest extension so I believe this is an issue in core.

**Comment by straker** [comment]
Thanks for the issue. I believe this is related to https://github.com/dequelabs/axe-core/issues/3696 where `button` elements using `label` aren't supported in Dragon Naturally Speaking so we continue to flag them as issues. We've been meaning to add a "not well supported" message but just haven't gotten around to it.
