### ISSUE TITLE
prototype.js breaks axe-core v4.9.0

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core#4428]
Websites that use `prototype.js` cause axe-core v4.9.0 to not be able to load. When trying to load axe-core on the page we get an error `Uncaught TypeError: No color space found with id = "oklch"`.

In order to get v4.9.0 working we are going to revert our update to colorjs from v0.5.0. This will allow axe-core to load on the page but will cause color-contrast to error during it's run. To fix that we're going to load an `Array.from` polyfill right before we call colorjs code to fix the problem, then restore the `prototype.js` `Array.from` implementation right afterwards.

**Comment by romankulkovsf** [comment]
>

**Comment by padmavemulapati** [comment]
Validated with the latest axe-core dev branch code base, now on websites that uses prototype.js  (http://script.aculo.us/), we are able to load and getting the a11y issues if any. But not getting color space with id="oklch"


https://github.com/dequelabs/axe-core/assets/47409579/3154792d-757b-4246-b6d4-f4076ba02a78


## Environment:
| **Label**                        | **Value** |
| -------------------------- | ------ |
| **Product**               | _axe-core_ |
|**Version** | _4.9.0(Dev Branch Code base_ |
| **OS-Details**     | _MAC- Intel Core i7 - 11.6.8 _ |
|**BrowserDetails**|_Chrome Version 124.0.6367.119 (Official Build) (64-bit)_|
