### ISSUE TITLE
1-document report with full website scan issues noted

### ISSUE THREAD

**Issue by kstevo06** [dequelabs/axe-core#4432]
### Product

axe-core

### Product Version

4.84

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
We are trying to find a simple solution to acquire a 1-document report with all the issues on our website as found by DevTools Axe-Core 4.84 extension.

I had initially tried to save each in-browser window result as a complete page and then access after the fact... as a sort of way to view the results without having the extension installed, but I realized it did not retain full report functionality.

We are working with a team that asked, "can you list all of the concerns in one doc, I'd like our Dev lead to take a look."

#### Actual
The only way to see a report, as far as I know, with the Axe-Core tool is too scan 1 page at a time.

#### How to Reproduce
The following link is zipped file of all the in-browser Axe-Core scan results saved as a complete page. However, the saved "complete page" lost functionality. https://drive.google.com/file/d/1a52Z8Lxn7b_Xe2h2OsOc4y12jPn5nZHp/view?usp=sharing

#### Additional context
I was told to submit this issue as "report a problem" by helpdesk@deque.com and I am looking for a 1-document report that lists all the issues on our website rather than 1 page at a time. We were asked by a team working on our website to "list all of the concerns in one doc, I'd like our Dev lead to take a look."
[DevTools Axe-Core 4.8.4 set at WCAG 2.1 AA with Best Practices ON.zip](https://github.com/dequelabs/axe-core/files/15131042/DevTools.Axe-Core.4.8.4.set.at.WCAG.2.1.AA.with.Best.Practices.ON.zip) 

Thank you for your assistance or guidance.

**Comment by schne324** [comment]
axe DevTools Extension does offer a single page HTML report with an overview page and an issues breakdown page. You can learn about these reports here: https://docs.deque.com/devtools-for-web/4/en/devtools-share

**Comment by kstevo06** [comment]
@WilcoFiers @schne324 Thank you both for your help.

@schne324 I am using Firefox 125.0.3 and this "Save" option does not appear when used on this browser. There doesn't appear to be a way to sign into the axe DevTools Extension in Firefox? 

I am now successfully using the save option in Google Chrome. Thank you again!

**Comment by schne324** [comment]
@kstevo06 I'm glad you found the save option in Chrome. Unfortunately, the pro features are only available in Chrome and Edge. Firefox doesn't have API support for what we need for the pro features.

Let me know if you have any additional questions!
