### ISSUE TITLE
landmark-unique does not reflect latest HTML-role mappings

### ISSUE THREAD

**Issue by gabalafou** [dequelabs/axe-core#4460]
### Product

axe Extension

### Product Version

4.79.3

### Latest Version

- [X] I have tested the issue with the latest version of the product

### Issue Description

Note: I wrote up this issue based on the browser extension, but I also checked that this issue holds with the newer axe-core 4.9.1 using [@axe-core/cli](https://github.com/dequelabs/axe-core-npm/blob/develop/packages/cli/README.md).

#### Expectation

The following URL should have zero [landmark-unique](https://pydata-sphinx-theme.readthedocs.io/en/latest/examples/kitchen-sink/generic.html) violations:
https://pydata-sphinx-theme.readthedocs.io/en/latest/examples/kitchen-sink/generic.html

#### Actual

Axe finds several landmark-unique violations at the above URL. 

These landmark-unique violations are for several `<aside>` tags on that page that are actually not represented by the latest browsers as role=complementary landmarks.

#### How to Reproduce

Using:

- Chromium 124
- axe DevTools v4.79.3 (axe-core 4.8.4)

Scan the following URL:
https://pydata-sphinx-theme.readthedocs.io/en/latest/examples/kitchen-sink/generic.html

Observe that the tool reports several instances of the landmark-unique violation.

#### Additional context

The latest browsers follow the [HTML-role mapping specification](https://w3c.github.io/html-aam) and do not assign `role=complementary` to unnamed `<aside>` tags that are scoped to a sectioning content element ([section 3.4.9](https://w3c.github.io/html-aam/#el-aside)). 

But apparently Axe-core treats all `<aside>` tags in the document as landmarks, which triggers the landmark-unique violation.

For more context:

- This was the motivating issue on my end: https://github.com/pydata/pydata-sphinx-theme/issues/1479
- Here are links to issues showing the problem fixed recently in Firefox and Safari (it was fixed even longer ago in Chrome):
  - Firefox: [Conditional role mapping for aside element (WPT html-aam/roles-contextual.html el-aside-in-section-without-name)
](https://bugzilla.mozilla.org/show_bug.cgi?id=1749505)
  - Safari: [Assign generic role to aside tag within the sectioning content elements #20013
](https://github.com/WebKit/WebKit/pull/20013)

**Comment by WilcoFiers** [comment]
@gabalafou Thank you for reporting. I agree with your findings, and knowing this has been updated in the latest browsers now I see no reason for axe not to do the same thing. I'll add it to the 4.10 milestone. If you're interested, we'd welcome a pull request.

**Comment by gabalafou** [comment]
I created pull request #4469. This is my first pull request for Axe-core, so I doubt I got everything right
