### ISSUE TITLE
axe DevTools Linter Accessibility

### ISSUE THREAD

**Issue by Arjunanpalanichamy** [dequelabs/axe-core#4482]
I have created a axe-linter.yml file following code

rules:

  heading-order: true # Disable this rule

  html-has-lang: false # this rule is disabled for all files

  button-has-role: false # this rule is disabled for all files

  img-has-alt: true # this rule is disabled for all files

  image-alt: false

exclude:
  - meta-refresh.html
  - 'tests/**/*.html' # Skip files
  - '*.tmp' # Skip the temp files

Expectation: linter extension will highlight axe rule violations in HTML code 

Actual: The linter immediately yields the error Unable to start axe-linter

Motivation: I want the linter to run correctly in order to test my frontend code

But not reading this yml in VScode and not execute axe-lint 

i have copied this yml file path : C:\Users\username\axe-linter.yml

can help to resolve this issue.

thanks

**Comment by michael-siek** [comment]
Hey @Arjunanpalanichamy do you mind sharing what version you are using of the vscode extension?

**Comment by Arjunanpalanichamy** [comment]
Thanks for your reply Michael-siek.. i have resolved this issue as of now.. 

![image](https://github.com/dequelabs/axe-core/assets/45002444/4311d38c-6b74-4c48-97de-d6f7c5494b94)
