### ISSUE TITLE
Is there a way to detect non-accessible interactive elements on a webpage?

### ISSUE THREAD

**Issue by kozack-webspark** [dequelabs/axe-core#4487]
### Product

axe-core

### Question

Let's say I have a webpage with `<div>` on it. This element doesn't have any role or `tabindex`. But JavaScript on this page create a `click` event listener on this element. Obviously this is a critical issue but seems, axe doesn't detect it. I just try to run analyze (i use play write integration) with non-accessible div and axe ignore this issue. 

 Is there a way to detect such cases?

**Comment by straker** [comment]
Thanks for the question. Unfortunately JavaScript has no way to detect event listeners on elements so it's not possible to detect interactive elements that only use event listeners. Chrome supports [getEventListeners](https://developer.chrome.com/docs/devtools/console/utilities/#getEventListeners-function), but it's only available in the DevTools console.
