### ISSUE TITLE
Lighthouse flags 1x1 tracking pixels under the 'image elements do not have [alt] attribute'

### ISSUE THREAD

**Issue by omriariav** [dequelabs/axe-core#4513]
### Product

axe-core

### Latest Version

- [X] I have tested the issue with the latest version of the product

#### Expectation
I think the lighthouse accessibility audit should ignore tracking pixels (usually 1x1 image sizes) as they mean nothing to the end users (although that I am not an accessibility expert) 

#### Actual
We see the tracking pixels flagged in Lighthouse under the 'image elements do not have [alt] attribute'

#### How to Reproduce
https://pagespeed.web.dev/analysis/https-www-khaleejtimes-com/e08ds96fqe?form_factor=desktop
![Screenshot 2024-06-10 at 6 13 09 PM](https://github.com/dequelabs/axe-core/assets/6891042/f58f1806-658c-4bb2-9189-168a59e4f301)
![taboola](https://github.com/dequelabs/axe-core/assets/6891042/e568f0e0-3bd8-4acb-8f34-03b6d7b3754e)

#### Additional context
As a third-party library (Taboola), we fire those tracking pixels on behalf of our advertisers. We are responsible for not downgrading LH scores, including this example.

**Comment by dylanb** [comment]
just put `alt=""` on all your tracking pixels

**Comment by omriariav** [comment]
Many third-party vendors or website owners curate these tracking pixels. I think the Lighthouse team needs to work with those vendors so that they will share the tags with the attribute. We, Taboola, can sustain the overhead of checking in our systems if this attribute is missing and then adding it on our own, but I think this is something we need to let all tracking pixels vendors be aware of.

Other than that, I don't understand how putting an empty alt on 1x1 pixels serves our esteem goal of improving accessibility, so it's worth rethinking this.

**Comment by dylanb** [comment]
It does the correct thing - it tells the user that the image has no semantic value and thereby also eliminates assistive technologies from reading out a bunch of file names to screen reader users

**Comment by omriariav** [comment]
@dylanb you are right. I appreciate the time you took to reply/explain.
