### ISSUE TITLE
new rule: frame-tested

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#453]
Axe-core should inform users when frames didn't get tested. We can do that by adding it as a result into `incomplete`. This should only be the case if that frame is visible, and if it didn't get excluded through scope.

I think the best way to build this is to have a rule that selects frames, then in a check, test that that frame is visible, and ping the frame, see if axe responds. This check would have to be async, which axe should be able to do (we've got `this.async()` in checks). But we don't currently have any checks that use it, so we'll have to test this properly.

**Comment by marcysutton** [comment]
I think that's pretty closely related to #307

**Comment by WilcoFiers** [comment]
Right you are. I'll move my comment over and we can close this.
