### ISSUE TITLE
False positive for "aria-valid-attr-value" rule?

### ISSUE THREAD

**Issue by quachtina96** [dequelabs/axe-core#461]
Note: I'm using the version of axe.js built from the shadowDOM branch on Mon Jul 24 12:17:05 2017, with latest revision from commit: d02dba3

The audit tells me, "Invalid ARIA attribute value: aria-describedby="cloudPrintersSecondary"
![image](https://user-images.githubusercontent.com/10423718/28603768-0a6fdf58-717b-11e7-8dac-17f0aa2fde13.png)

However, there is an element with id="cloudPrintersSecondary" (as highlighted in the photo) that is referenced by the aria-describedby. I'm confused about why this is identified as an accessibility issue.

**Comment by marcysutton** [comment]
Hi @quachtina96, I can't reproduce it, even when I append an `aria-describedby` pairing inside a shadow root. Is the snippet inside of nested Shadow DOM subtrees, or is there anything else unusual about how the markup is written? A live demo would help us debug.

**Comment by dylanb** [comment]
@quachtina96 Are the button and the target of the aria-describedby in the same shadow DOM or in the light DOM?

**Comment by marcysutton** [comment]
@quachtina96 do you have an update on this? Otherwise I'm going to close it for inactivity.

**Comment by quachtina96** [comment]
@marcysutton Sorry for the delay in response. I was not able to reproduce this issue.

**Comment by marcysutton** [comment]
Ok, feel free to reopen it if the problem resurfaces!
