### ISSUE TITLE
isFocusable is too strict on tabindex

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#4632]
The way axe-core checks whether tabindex is valid is by calling `parseInt()`. That's different from how [HTML]()https://html.spec.whatwg.org/#rules-for-parsing-integers says to do it. Basically, axe should use this to match, and then parseInt the captured group: `/^\s*([-+]?\d+)/`

The issue is here: `lib/commons/dom/is-focusable.js`
The tests for it need to be here: `test/commons/dom/is-focusable.js`

**Comment by ahmedhalac** [comment]
Hi @WilcoFiers. Can I work on this?

**Comment by WilcoFiers** [comment]
@ahmedhalac, yeah that would be great!
