### ISSUE TITLE
[link-in-text-block] Rule should ignore links containing their link target

### ISSUE THREAD

**Issue by sebastiannielsen** [dequelabs/axe-core#4639]
### Product

axe-core

### Feature Description

The rule "link-in-text-block" is made so vision impaired users, can see where links are and where clickable regions exist.

HOWEVER, if a link text contain their link target, the link must be assumed to be clickable. I feel that skipping this rule if the link physically contains the link target, is a resonable option to do, as it wont impair disabled users if clickable links containing their target, is not styled as clickable links. (They should be assumed to be clickable, as the opposite is rare)

So I suggest the "link-in-text-block" rule is updated, so, if:

a link is `href=".*://(.*)\?.*"` and the text between `<a>` and `</a>` *CONTAINS* the text in (.*), the link is ignored for this rule execution.

a link is `href="mailto:(.*)\?.*"` and the text between `<a>` and `</a>` *CONTAINS* the text in (.*), the link is ignored for this rule execution.

a link is `href="tel:([0123456789+]*)"` and the text between `<a>` and `</a>` evaluated as `/[0123456789+]*/` *CONTAINS* the text in (.*), the link is ignored for this rule execution. (With evaluated as (regexp) I mean that all characters between `<a>` and `</a>` that are not matching the regexp is deleted before comparing, this so a phone number of tel:+1555123123 can be visually displayed as "Call us: +1 (555) 123 123" for example)

Examples of links PASSING the rule regardless of style:
`<a href="mailto:info@example.org">Send us a email on info@example.org!</a>`
`<a href="tel:+1555123123">Call us: +1 (555) 123 123</a>`
`<a href="https://www.example.org">Come visit our partner at www.example.org!</a>`
`<a href="https://www.example.org?referrer=ourCorporation&metrics=topAd">Come visit our partner at www.example.org!</a>`

Examples of links REQUIRING the constraints on style (ergo NOT PASSING if style is not right):
`<a href="mailto:info@example.org">Send us a email here!</a>`
`<a href="tel:+1555123123">Call us now!</a>`
`<a href="https://www.example.org">Come visit our partner Example LTD</a>`

**Comment by WilcoFiers** [comment]
Can you clarify what you are basing this interpretation on? Reading over WCAG's understanding documents I see no reason for this. It seems to me that, yes link text may enable someone to guess that something could be a link, but it is just a guess. Not all phone numbers are links, not all references to web sites are links. That does not seem like a method someone can rely on to know where the links in a text is.

**Comment by sebastiannielsen** [comment]
Im basing the interpretation on common sense.

A link that is inside a block of text, is impossible to find (even for seeing users) if it doesn't share a unique style that displays the link is clickable. If the style is unique, but not in contrast 3:1 or contains a unique non-color dependant style, users who are vision impaired can impossibly find the link, as the link could be anywhere, any word on the page could contain the link.

However, a visible phone number, visible email adress or a visible URL can be assumed to contain a link. A user can try clicking a phone number, email adress, or URL. If its a link, success. If its not a link, nothing happens and user can proceed to type the URL, email or phone number manually.

This means, a link containing its link target, can be styled even like regular text - no differences from surrounding text, and users would have no trouble finding the link. That the text contains the target itself is the visible cue that makes it possible for the user to understand that there can possibly be a link there.

I agree, there should be atleast some additional cue that the target is a link, but the cue doesn't need to be as strong. Maybe, require a unique style, BUT with no constraints on contrast or color.
