### ISSUE TITLE
Divergence of results for the same WCAG 2.1 AA tag in Axe Core to Axe-Core DevTools with WCAG 2.1 AA

### ISSUE THREAD

**Issue by douglascugliaridev** [dequelabs/axe-core#4652]
### Product

axe-core

### Question

Hello, I would like to know if I can do an analysis using the Axe-core to analyze only for example by the WCAG 2.1A and WCAG 2.1 AA tag. Pegunto, because I’m trying to do an analysis by just passing these two Tags and it’s not bringing any problem. Already in the Axe-Core Devtools Free version that comes with the WCAG 2.1 AA tag selected it brings several defects to the page I’m analyzing.

**Comment by WilcoFiers** [comment]
@douglascugliaridev Yes this is possible. You can use the `runOnly` option for this with the `wcag21a` and `wcag21aa` tag:

```js
const results = await axe.run({ runOnly: ['wcag21a', 'wcag21aa'] })
```

You can find the documentation for it here:
https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#options-parameter
