### ISSUE TITLE
inapplicable results aren't returned

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#473]
In the result, the inapplicable array is always empty.

**Comment by robdodson** [comment]
@WilcoFiers do you happen to know if anyone is working on this? I'd love to roll this into Lighthouse to improve the accuracy of our scores.

**Comment by WilcoFiers** [comment]
@robdodson I don't think so. You're welcome to it if you've got the time. If you get it done by the end of next week we can release it as part of 2.6.0. Otherwise it might have to wait until 3.0 in February.

**Comment by robdodson** [comment]
ok i'll take a shot at it. I may be bugging you and marcy on Slack a bit 😸

**Comment by marcysutton** [comment]
Rob's awesome fix got merged, so I believe we can close the issue. Please let us know if we need to reopen.
