### ISSUE TITLE
Having a 'runOnly' property in axe.configure

### ISSUE THREAD

**Issue by bhamde** [dequelabs/axe-core#474]
Hi,

When running axe we have the option to runOnly specific tags. Is there a reason we do not have this option in the config file (as a generic property, not per rule)?

**Comment by WilcoFiers** [comment]
What would be the use case for this? I'd say the main reason not to have it would be that this can already be achieved, and adding a feature twice may just cause confusing.

**Comment by bhamde** [comment]
The main use case is if you set the axe.configure in a setup file that runs before all unit tests - just so that u don't need to specify that per test or per rule id

**Comment by WilcoFiers** [comment]
I'd suggest instead of doing a separate configure call, use the configuration as your options object in `axe.run()` instead.

**Comment by marcysutton** [comment]
I'm going to close this issue, as it seems this is already achievable with the current API. We are very unlikely to add this feature. If it is a blocker more than an inconvenience, let us know.
