### ISSUE TITLE
Additional rules properties in axe.run parameters

### ISSUE THREAD

**Issue by philipjia123** [dequelabs/axe-core#484]
Would it be OK if I added more configurable properties to the rules property in axe.run's options parameter?  Right now I think the only property customizable on a per-run basis is 'enabled.'  This would be useful with WebDriver integrations, since we'd be able to configure a rule's selector without having to maintain the state of the axe object.

**Comment by WilcoFiers** [comment]
Off the top of my head, I believe there are a few more things you can manipulate with the options object of `axe.run`. But if you want greater configurability, `axe.configure` is where you should look. You can configure anything you want with that. Are there particular cases you can't solve with `axe.configure`?

**Comment by philipjia123** [comment]
There are some odd cases where it would be nice to be able to set rule configurations on a per-run basis, such as when dealing with dynamic content (where multiple calls to axe.run will be made on different contexts) it would be nice to be able to configure the color-contrast rule's selector or excludeHidden property to ignore logo/purely decorative text without having to call axe.configure/axe.reset before and after each run.

**Comment by WilcoFiers** [comment]
Sounds reasonable. @dylanb What's your take on this?

**Comment by marcysutton** [comment]
@philipjia123 how do you feel about contributing a PR for this?

**Comment by philipjia123** [comment]
Sorry for the delay!
