### ISSUE TITLE
Ensure CircleCI is running on PRs coming from forks

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#497]
This PR never got tested. It seems to be because it's from a fork, but we need to figure it out.
https://github.com/dequelabs/axe-core/pull/492

**Comment by marcysutton** [comment]
I found out a little more information: https://twitter.com/shawnbot/status/907302027692089345

> It's a security measure—If your CI configuration includes private or encrypted environment variables, they could be compromised by the fork.

Trying to determine if there's a safe workflow, given that we have no environment variables as far as I can tell.

**Comment by marcysutton** [comment]
Found the setting, you have to enable it in CircleCI Settings.

**Comment by WilcoFiers** [comment]
Nice!

**Comment by WilcoFiers** [comment]
@marcysutton can you make the same changes to our other open source projects?

**Comment by marcysutton** [comment]
I did. But I only had access to aXe-webdriverjs and aXe-matchers.
