### ISSUE TITLE
Add 'aria-errormessage' to definitions list

### ISSUE THREAD

**Issue by AutoSponge** [dequelabs/axe-core#499]
context: https://github.com/dequelabs/axe-core/blob/645d1fa52f1bee7e452a3d9b5927b32005fa5a93/lib/commons/aria/index.js#L51

spec: https://www.w3.org/TR/wai-aria-1.1/#aria-errormessage

Suggested fix: insert

```js
	'aria-errormessage': {
		type: 'idref'
	},
```

**Comment by WilcoFiers** [comment]
I have some reservations about allowing this into axe-core just yet. Do you know if there are any assistive technologies that support this yet? We have a policy of only taking in accessibility feature that have sufficient support. The only exception to that being, those features that wouldn't get in the way if they weren't support. I don't think that's the case here, but certainly open to some counter-arguments.

**Comment by AutoSponge** [comment]
@WilcoFiers, as far as I know, `aria-errormessage` is not supported by browser/AT yet. Currently, techniques that use `aria-describedby` to link the error message read out when the linked element is focused. The error message is also read out when using `role=alert` or `aria-live=assertive`.

I see three options here:

# Option 1
Replacing `aria-describedby` with `aria-errormessage` and continued use of `aria-live` (adoption now)

## PRO: 
- the error message will read out when the error is added
- the code will be spec compliant
- will have future functionality when `aria-errormessage` is widely supported
- sends message to AT community is ready to support the feature

## CON: 
- focus element with current error state will not read out

# Option 2
Use both `aria-describedby` and `aria-errormessage` and continued use of `aria-live`  (adoption now)

## PRO: 
- the error message will read out when the error is added
- will have future functionality when `aria-errormessage` is widely supported.
- focus element with current error state will read out
- sends message to AT community is ready to support the feature _BUT_ requires AT to plan for conflict (see below)

## CON: 
- when `aria-errormessage` becomes widely available, _IF_ AT chooses to read both `aria-describedby` and `aria-errormessage`, the error message will be read twice on focus. Otherwise, `aria-errormessage` must proceed `aria-describedby` when both exist.

# Option 3
No changes to current pattern (opposes adoption now)

## PRO:
- No need to change code/patterns

## CON:
- AT may never implement since no one codes for it or is ready to support it

**Comment by WilcoFiers** [comment]
@AutoSponge Sounds good. I agree, if aria-errormessage was to point to a live region, or if it pointed to the same element as aria-describedby, I think it should pass axe-core. Are you interested on working on a PR for this? If not I think we can leave it on the issue board and we'll get to it when we can.

**Comment by AutoSponge** [comment]
Great! I will start work on a PR.

**Comment by DavidMacDonald** [comment]
JAWS appears to support it in browsers.
