### ISSUE TITLE
Make results better for calculating metrics based on passes and failures

### ISSUE THREAD

**Issue by dylanb** [dequelabs/axe-core#501]
The passes for rules that do not filter with a matches function contain "passes" that are not that meaningful. For example, the aria-required-children should only evaluate aria roles that actually require children and should not mark things as passed if they do not have any required children.

Other rules probably suffer from similar issues.

So first order of business is to review all the rules to see where we could benefit from filtering and review all the current filters to see which ones could be made better

**Comment by straker** [comment]
Going through all the rules these are the ones I found that I think could benefit:

- `aria-required-children` - matches to see if role requires children
- `aria-required-parent` - matches to see if role requires parent
- `avoid-inline-spacing` - matches to see if element has the CSS properties we look for (right now all `[style]` elements will pass even if they don't use any inline-spacing properties)

**Comment by straker** [comment]
Issue has been addressed. We will always run `inline-spacing` rule on `[style]` nodes.
