### ISSUE TITLE
Add rule for hreflang values 

### ISSUE THREAD

**Issue by rviscomi** [dequelabs/axe-core#502]
The [hreflang](https://support.google.com/webmasters/answer/189077?hl=en) attribute (as in `<link rel="alternate" hreflang="...">`) is similar to the lang attribute (as in `<html lang="...">`).

I'd like to propose a new rule to validate hreflang values. It could be based off the "html-lang-valid" rule and modified to check all `link[rel="alternate"][hreflang]` elements. In addition to the standard lang values, it would also need to support the "x-default" value.

This rule would be used downstream in https://github.com/GoogleChrome/lighthouse/issues/3117

**Comment by WilcoFiers** [comment]
Interesting idea. It shouldn't be too difficult to add, but I'm not seeing how this is an accessibility issue. Can you elaborate?

**Comment by rviscomi** [comment]
AFAIK it's primary use case is for crawlers to discover alternate content, but the hreflang attribute could just as well be used by a11y tools to redirect to pages in the user's preferred language/locale.

**Comment by WilcoFiers** [comment]
In that case I think this should only be added to axe-core itself if there are assistive technologies out there that do this. For axe-core, we do want to stick to what AT do today, and not speculate on what they might do too far. That's the main reason we haven't implemented a lot of ARIA 1.1 yet.

**Comment by rviscomi** [comment]
That's fair. Thanks for the explanation.

Are there any other options to be able to reuse the lang parsing/validation logic? For example, it could be broken out into a separate library that we could include in our project.

**Comment by WilcoFiers** [comment]
There sure is! Axe-core is highly configurable. You can pass new rules and checks into `axe.configure()` and run them that way. Many of our clients use custom rulesets, although often with aXe's commercial big brother Attest, which has a few more feature. You can find more about axe.configure here:

https://axe-core.org/docs/#api-name-axeconfigure

**Comment by rviscomi** [comment]
Ah interesting I didn't know about custom rules.

Could a custom rule reuse built-in utils like https://github.com/dequelabs/axe-core/blob/develop/lib/commons/utils/valid-langs.js? It doesn't seem like utils are exposed in the top-level `axe` object. If that's the case it seems like we would need to duplicate that list of ~8k lang values or sideload it into scope.

The docs also mention overwriting existing rules. So it should be possible to replace the selector for the valid-lang rule with `link[rel="alternate"][hreflang]` for this purpose. Would that mean that in order to run the original valid-lang rule, we'd need to call `axe.run` twice with and without the custom rule?

**Comment by WilcoFiers** [comment]
All commons are exposed on the axe object. This particular one is on `axe.utils.validLangs`, which you can see if you look at the bottom of that file.

Full disclaimer about them though. The commons are internal, and although we do try to keep their APIs stable, occasionally we do change the call signature as part of minor or patch releases. I recommend you write sufficient unit tests for your custom rule so you can test them against new versions of axe-core.
