### ISSUE TITLE
Axe reporter is very slow with large datasets

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#512]
On extremely large pages, it is possible for the reporter to take several times longer than the actual audit to complete. The main problem appears to be in `helpers.processAggregate()`. Running it 30 000 times took several minutes to complete. Part of the issue here is that the extension is hugely inefficient here because it's processing passes, which won't actually get displayed. 

Part of the solution should be in preventing that. But there's certainly an extra problem. The method doesn't (or at least shouldn't) do anything that's particularly slow, so we need to figure out what's so slow and we should fix it.

This problem can be reproduced on the following page: 
https://dev.office.com/fabric#/components/detailslist

**Comment by isner** [comment]
Fixed by https://github.com/dequelabs/axe-core/pull/568, provided the implementation uses the new 'resultTypes' options (see PR).
