### ISSUE TITLE
Run CI on additional platforms incl. Windows

### ISSUE THREAD

**Issue by marcysutton** [dequelabs/axe-core#519]
To catch issues like #516, we should run our tests on additional platforms, starting with Windows. We could use Sauce Labs through CircleCI for this. It would allow us to catch installation and test problems with minimal effort. https://circleci.com/docs/1.0/browser-testing-with-sauce-labs/

**Comment by nschonni** [comment]
I'd suggest https://www.appveyor.com/ so you get a full install experience since you're a developer tool.

SauceLabs is :100: better for testing the cross platform browser stuff though.

**Comment by marcysutton** [comment]
Closed with #545.

**Comment by WilcoFiers** [comment]
Reopening this - we're not actually using AppVeyor right now, since it's been causing some build issues. We need to resolve those.
