### ISSUE TITLE
"Parent resource parameter invalid" in help pages

### ISSUE THREAD

**Issue by jaimeiniesta** [dequelabs/axe-core#522]
Hello, I'm getting a "Parent resource parameter invalid." message on top of help pages like this:

https://dequeuniversity.com/rules/axe/2.4/button-name?application=webdriverjs

This URL comes from the help url for violations when using 2.4. The same page for 2.3 does not produce the error message:

https://dequeuniversity.com/rules/axe/2.3/button-name?application=webdriverjs

**Comment by marcysutton** [comment]
This is a known issue, and is unrelated to axe-core. Thanks for the input!
