### ISSUE TITLE
getElmScrollRecursive fails on SVG in some browsers

### ISSUE THREAD

**Issue by fofr** [dequelabs/axe-core#525]
When recursing through the DOM to calculate the scroll position here: https://github.com/dequelabs/axe-core/blob/83daaa53023c8ad5ea927244617cf7807bf1fd37/lib/core/utils/scroll-state.js#L32-L40

If the code encounters an SVG it essentially runs, `document.querySelector('svg').children`. This doesn't always return an HTMLCollection object which in turn causes `Array.from` to error.

JS fiddle demonstrating issue:
https://jsfiddle.net/uvftjtre/2/ (version 3.0.0.alpha.4)

Running the above example in EDGE:
```
Array.from: argument is not an Object
```

Running in IE11 will return:
```
TypeError: Array.from requires an array-like object - not null or undefined
```

This error surfaced when running automated tests through Phantom JS 1.9.7

More context:
https://stackoverflow.com/questions/7935689/what-is-the-difference-between-children-and-childnodes-in-javascript#7935719

**Comment by WilcoFiers** [comment]
Problem turns out to be that .children is undefined. The work around is to use .childNodes instead and filter them for elements.

**Comment by benbcai** [comment]
@WilcoFiers This issue causes our accessibility tests to fail on any page that contains an SVG element. Looks like this is scheduled to be fixed in axe-core 3.4. Do you have a timeframe when 3.4 is scheduled to be released?

**Comment by emilyrohrbough** [comment]
Do you expect the changes be to add fallback for childNodes like:
```diff
- return Array.from(root.children).reduce((scrolls, elm) => { 
+ return Array.from(root.children || root.childNodes || []).reduce((scrolls, elm) => { 
```
or are the scroll position of SVG children necessary to worry about?

**Comment by benbcai** [comment]
Another option could something like [this](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/children#Polyfill).

```diff
+ var i = 0
+ var node;
+ var nodes = root.childNodes;
+ var children = [];

+ while (node = nodes[i++]) {
+ 	if (node.nodeType === Node.ELEMENT_NODE) {
+ 		children.push(node);
+ 	}
+ }
- return Array.from(root.children).reduce((scrolls, elm) => { 
+ return Array.from(children).reduce((scrolls, elm) => { 
```

@WilcoFiers What are your thoughts?

**Comment by benbcai** [comment]
@WilcoFiers @straker When do you plan to release 3.3.3/3.4.0 so that my project can consume the release with this fix?

**Comment by benbcai** [comment]
@WilcoFiers @straker Just wanted to follow up to see when you plan to release the next version of axe-core so my team can consume this fix.

**Comment by benbcai** [comment]
@WilcoFiers @straker You may ignore my question above. Just noticed the release date here: https://github.com/dequelabs/axe-core/milestone/11
