### ISSUE TITLE
New rule: H2 -  Combine adjacent image and text links for the same resources

### ISSUE THREAD

**Issue by jmucha** [dequelabs/axe-core#530]
#  H2 -  Combine adjacent image and text links for the same resources

This test checks if the anchor text of a link is the same as the ‘alt’ text of an image contained within the link.

**Tags:** wcag2a, wcag311, cat.language, best-practice

## Selector

Select each node that has an anchor element.

### language/image-text ( all )

1.    Check if the anchor element contains any `img` elements .
2.    If 1. returns true, for each `img` element check whether the value of the `alt` attribute is set to null or to a value that supplements the link text and describes the image.

**Comment by WilcoFiers** [comment]
This seems very similar to `image-redundant-alt`. Have a look at this rule and see if there is anything you need in addition to it. I think we've got this pretty well covered though, so we may not need a new rule.

**Comment by jmucha** [comment]
Agree with your comment. No need to double the `image-redundant.alt` rule, which covers the case.
