### ISSUE TITLE
New rule: xml-lang

### ISSUE THREAD

**Issue by jmucha** [dequelabs/axe-core#531]
#  SC3-1-1-xml-lang

This test checks the value of the `xml:lang` attribute and the presence of the `lang` attribute.

**Tags:** wcag2a, wcag311, cat.language

## Selector

Select the root if it has both attributes `html[xml:lang][lang]`.

### language/xml-lang
1.    Check that the value of the `xml:lang` attribute is equal to the `lang` attribute. If true, pass; else 2.

### language/xml-lang-dialect
2.   Check that the language can match different dialects, e.g.

- `<html lang="en" xml:lang="en-US">`
- `<html xml:lang="nl" lang="nl-BE">`

If true, pass; else fail.

**Comment by WilcoFiers** [comment]
Few suggestions for this one too:

1. In the selector, have this rule only target the root if it has both attributes: `html[xml:lang][lang]`

2. I think you should add a second rule for 3.1.2 that tests the same thing but for other elements. 

3. I think we should allow the following. These are effectively the same thing. We'll need tests for that.
    - `<html lang="en" xml:lang="en-US">`
    - `<html xml:lang="nl" lang="nl-BE">`

**Comment by jmucha** [comment]
Which other elements do you mean @WilcoFiers ? Could you elaborate on this one? Are you thinking about the phrases in text in other languages?

**Comment by WilcoFiers** [comment]
@jmucha I mean just any other element. Any element which has both `lang` and `xml:lang` should have it match.

**Comment by jmucha** [comment]
Ok, got it, thank you. We can make a separate rule for the language of parts.

**Comment by jmucha** [comment]
Any ideas on how to solve a problem in testing the rule when there arises an error stating that html element cannot be added to the div element? Do you have any experience how to approach this?
The whole json file looks like this:
<html lang="en" xml:lang="en" id="pass1">English</html>

**Comment by marcysutton** [comment]
I'd say that might have to be an integration test where you can control the whole DOM, as our unit tests are already inside of a document. Or use an element other than `<html>`.

**Comment by jkodu** [comment]
Believe this PR https://github.com/dequelabs/axe-core/pull/999 tackles the above issue.
