### ISSUE TITLE
New rule: H71 - label-groups

### ISSUE THREAD

**Issue by jmucha** [dequelabs/axe-core#533]
#  H71 - label-groups

This test checks if a semantic grouping is provided for related form controls. Form controls that are logically related (e.g. address fields) should be grouped by enclosing them with a fieldset element. All controls within a given fieldset are then related.

**Tags:** wcag2a, wcag332, cat.semantics

## Selector

Select each input element of type `radio` and `checkbox` or `fieldsets`.

### semantics/label-groups-radiogroup
1.    Check that related `radio buttons` are grouped by `fieldsets`. Run `radiogroup`

### semantics/label-groups-checkboxgroup
1.    Check that related `checkboxes` are grouped by `fieldsets`. Run `checkboxgroup`

### semantics/label-groups-fieldset
1.    Check that each `fieldset` has a `legend` element: run`fieldset` check.

**Comment by WilcoFiers** [comment]
I think this is already covered by `checkboxgroup` and `radiogroup`. Have a look at those, see if you're missing anything.

**Comment by jmucha** [comment]
Yes, we can definitely reuse these ones and wrap them up in this rule

**Comment by marcysutton** [comment]
How is that different than the `Checkbox inputs with the same name attribute value must be part of a group` rule that already exists? Or is it more general?

**Comment by jmucha** [comment]
At first I was thinking about making the rule more general to include both the checkbox grouping and radio buttons. However, now I reviewed this idea and I would say that there won't be so much gain in it. Let's skip this rule, is that ok for you?

**Comment by WilcoFiers** [comment]
Agreed, we'll pass on this. Closing this issue.
