### ISSUE TITLE
New rule: H35 - applet-alt

### ISSUE THREAD

**Issue by jmucha** [dequelabs/axe-core#536]
#  H35 - applet-alt

This test checks if a text alternative is provided for an applet by using the `alt` attribute to label an applet and provide the text alternative in the body of the `applet` element. 

**Tags:** wcag2a, wcag111, cat.text-alternatives

## Selector

Select each `applet` element.

### text-alternatives/applet-alt-alt 
1.    Check that the `applet` element contains an `alt` attribute with a text alternative for the `applet`: use `has-alt` rule.
### text-alternatives/applet-alt-text 
1.    Check that the `applet` element contains a text alternative for the `applet` in the body of the `applet` element.
### text-alternatives/applet-alt-aria 
1.    Check whether the text alternative is set with use of ARIA. Look for aria-label, aria-labelledby attributes.

**Comment by WilcoFiers** [comment]
Suggestions:

1. Make step 1, checking if it has a source, part of the selector

2. Make step 2 and 3 separate checks. This is a pretty natural way to break the check up, plus you can reuse existing checks. There is already a `has-alt` and `button-has-visible-text` check which you can modify.

3. Add ARIA checks to this as well, aria-label and aria-labelledby should also be permitted.

4. As for the rule ID, `applet-alt` seems good

**Comment by Danidude** [comment]
Looking at this rule, all the checks already exsit in axe-core, so using them.

applet-alt-alt -> has-alt

applet-alt-text -> has-visible-text

applet-alt-aria -> aria-labelledby, aria-label

**Comment by WilcoFiers** [comment]
has-visible-text should do this for you. If it doesn't, that's a bug and it should be fixed. It computes the accessible name and than checks if that has a length greater than 0.

**Comment by Danidude** [comment]
Okay, when I tested the check against this html:
`<applet alt="tic-tac-toe game" id="fail3">
</applet> `
The HTML code passes check, even tried changing it to an `div` element, just to be sore it was not something special with applet elements. So then I do believe there is an bug in the check.

**Comment by WilcoFiers** [comment]
That's very strange... ware we sure that's correct? Can you do some testing with JAWS, NVDA and VoiceOver to see what works and what doesn't?

**Comment by dylanb** [comment]
@Danidude Remember - sufficient techniques are not the only way to achieve accessibility they simply provide AN example of how to make something accessible. This is different from making a determination that something IS NOT accessible - which is what axe-core has to do.

**Comment by Danidude** [comment]
@WilcoFiers These(JAWS, NVDA and VoiceOver) are Screen Readers you want me to test with to make sure? :)

@dylanb Ah, yes. That is an difference, and I have been trying to keep that in mind when creating the tests, that it should not contain any false negatives. :) With this in mind the need for the test of both body and alt text might not be needed then, as one of them might be enough :)

**Comment by WilcoFiers** [comment]
Yes, we need to make sure the techniques we allow are supported at least in those 3 screen readers, so please do those tests and let us know the outcomes.

**Comment by Danidude** [comment]
@WilcoFiers @dylanb 

Looking at this tag, as it is deprecated in html5(replaced by the object tag), so I was thinking of ignoring this tag if the document is html5. Do this sound correct for axe-core?

Also if we are ignore in html5, is it possible to set up an test in none html5 document? (integrated rules test).

**Comment by WilcoFiers** [comment]
@Danidude Deprecated doesn't mean it doesn't work anymore, so no I don't think we should change this rule for HTML5, unless browser actually treat it differently.

**Comment by WilcoFiers** [comment]
Issue no longer being worked on.
