### ISSUE TITLE
WebdriverIO compatibility?

### ISSUE THREAD

**Issue by KenzoM** [dequelabs/axe-core#538]
Not really an issue, but a question:

I know there is a library that's essentially the bridge between axe-core webdriverJS (https://github.com/dequelabs/axe-webdriverjs).

However, with my current projects, I am using WebDriverIO.  

Are there any implementation or future work that axe-core is/will be compatible to WebDriverIO? 

Unlike WebdriverJS (selenium-webdriver), WebDriverIO provides a more cleaner, easier code to write integration tests. It would be great if I can keep all my testing framework consistent.

**Comment by WilcoFiers** [comment]
There aren't any WebDriverIO implementations for axe-core. There are no plans for this either, but we'll certainly consider it.

**Comment by KenzoM** [comment]
Awesome, thanks for the quick reply

**Comment by KenzoM** [comment]
Hi @WilcoFiers 
Would you be interested in starting a collaboration with me to get things started? 
If you're busy at the moment, perhaps you can be some of the guidance for me to get started.

Let me know what you think

Kenzo

**Comment by WilcoFiers** [comment]
Hey Kenzo,
That sounds awesome, drop me an e-mail: wilco.fiers@deque.com
W

**Comment by marcysutton** [comment]
To anyone finding this issue, it looks like somebody created a WebdriverIO binding: 
https://github.com/snagi/axe-webdriverio
