### ISSUE TITLE
Allow using role 'combobox' without child role 'textbox' on a native input element with type="search"

### ISSUE THREAD

**Issue by iamrafan** [dequelabs/axe-core#549]
Issue is related to #160 . It was fixed for only type ="text", need to add support for type="search" too.

**Comment by marcysutton** [comment]
That seems reasonable to me, as an input with `type="search"` will have the same role of `textbox`. The only difference is the keyboard that is brought up on mobile devices.

**Comment by isner** [comment]
Fixed by https://github.com/dequelabs/axe-core/pull/559.

**Comment by iamrafan** [comment]
@isner thanks for the fix.
