### ISSUE TITLE
"checkbox-radio-group" 

### ISSUE THREAD

**Issue by devarshipant** [dequelabs/axe-core#551]
Test for checkbox pattern returned an interesting output in console. 

Test ID is 'checkbox-radio-group', but cannot be verified at https://dequeuniversity.com/rules/axe/2.0/checkbox-radio-group?application=axeAPI

See attached screenshot.
<img width="798" alt="checkbox-radio-group" src="https://user-images.githubusercontent.com/7377040/30980693-e1fad08e-a44f-11e7-8b1d-ae1c9025155f.PNG">

**Comment by WilcoFiers** [comment]
That's totally bizar... What page are you running this on, and are you also getting this when running axe 2.4?

**Comment by devarshipant** [comment]
My bad...I was using an older version of axe.min.js.

**Comment by marcysutton** [comment]
Ok, sounds like there's nothing to fix then.
