### ISSUE TITLE
Output command line response to HTML file?

### ISSUE THREAD

**Issue by pauldcollins** [dequelabs/axe-core#553]
Hi there, 

Just wondering if anyone has links/examples of outputting the Axe Core test results to a HTML file. Something that would look a bit prettier for reporting. Would appreciate any help!

**Comment by WilcoFiers** [comment]
Sure, we've got an example using handlebars you could use:

https://github.com/dequelabs/axe-core/blob/develop/doc/examples/html-handlebars.md

Something like that?

**Comment by pauldcollins** [comment]
Thanks @WilcoFiers, that's perfect. Appreciate it. 

Thanks for all the hard work on such a great tool by the way :)

**Comment by WilcoFiers** [comment]
Thanks for the complement :)
