### ISSUE TITLE
New rule: xml-lang-mismatch

### ISSUE THREAD

**Issue by jmucha** [dequelabs/axe-core#558]
# Update:
A detailed rule description with test cases can be found here: https://auto-wcag.github.io/auto-wcag/rules/SC3-1-1-html-xml-lang-match.html

# Language of parts: xml-lang-mismatch

This test checks the value of the `xml:lang` attribute and the presence of the `lang` attribute.

**Tags:** wcag2a, wcag311, cat.language

## Selector

descendent-or-self::body[@xml:lang][@lang]

### language/xml-lang
1.    Check that the value of the `xml:lang` attribute is equal to the `lang` attribute. If true, pass; else 2.

### language/xml-lang-dialects
1.   Check that the language can match different dialects, e.g.

- `<html lang="en" xml:lang="en-US">`
- `<html xml:lang="nl" lang="nl-BE">`

If true, pass; else fail.

**Comment by WilcoFiers** [comment]
Proposed name: xml-lang-mismatch

**Comment by jkodu** [comment]
Proposed name has been updated to `html-xml-lang-mismatch`.
PR - https://github.com/dequelabs/axe-core/pull/999

**Comment by WilcoFiers** [comment]
Rule was completed. Closing the issue.
