### ISSUE TITLE
TH in layout table when table has role=presentation

### ISSUE THREAD

**Issue by spanchang** [dequelabs/axe-core#561]
Gokhan Boybek reported on  10/06/17 that
Assure/Fireeyes is reporting a failure when a layout table contains `<th>` elements. Ok this is clearly a failure of 1.3.1 (https://www.w3.org/TR/WCAG20-TECHS/F46.html)
But it is called out as a failure even when the table contains role="presentation". Isn't that a false positive? Because the aria specs (see at http://www.w3.org/TR/wai-aria-practices-1.1/#presentation_role) clearly indicates that if role="presentation" is applied to the <table> tag, the descendants (including `<th>`) inherit this role as well.
So the client is questioning why Fireeyes is reporting this as a defect when the table tag had role="presentation", which is inherited by the th tag.

Sailesh: I agree, this is not a failure and should not be reported.

**Comment by WilcoFiers** [comment]
That would make sense. Can you test with VoiceOver, NVDA and JAWS to make sure tables with `role=presentation` or `role=none` get ignored even if they have `th` / `caption` / `scope=""` on them?

**Comment by spanchang** [comment]
Those roles have been working fine for a while now to hide the table
semantics even of a  table that is structured like a data table, say 2
col x7 rows.
The caption and TH cells are read normally as one arrows through but
one cannot navigate  the content using table nav keys. The TH cell
content still appears bold.
But this is not the content author's problems and should not be
flagged if those roles are present.
The browser has to be fixed so that TH cell is not rendered bold for
layout tables / table with those roles.
Best regards,


On 10/8/17, Wilco Fiers <notifications@github.com> wrote:
> That would make sense. Can you test with VoiceOver, NVDA and JAWS to make
> sure tables with `role=presentation` or `role=none` get ignored even if they
> have `th` / `caption` / `scope=""` on them?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dequelabs/axe-core/issues/561#issuecomment-335008407


-- 
Sailesh Panchang
Principal Accessibility Consultant
Deque Systems Inc
Phone 703-225-0380 ext 105
Mobile: 571-344-1765

**Comment by marcysutton** [comment]
Just to confirm the rule that failed, was it `th-has-data-cells`?

**Comment by marcysutton** [comment]
It was `layout-table` that failed. That scenario was already fixed with https://github.com/dequelabs/axe-core/pull/828, so I'm going to close this.
