### ISSUE TITLE
Rule: Skip-link

### ISSUE THREAD

**Issue by devarshipant** [dequelabs/axe-core#567]
- "Skip-link" does not work under "section-508" tag, only under "best-practice."

- The default impact level is moderate, but the guidance (https://dequeuniversity.com/rules/axe/2.0/skip-link) gives it Critical and suggests using the section-508 tag.

- Also, reporting a violation when only a link precedes form fields could be stretching the rule. It is okay to tab a few times to the get to the main body. The threshold to report violation and assess impact should be based on the number of times (x) it takes using the tab to get to the first form field / main content.

<img width="496" alt="skip-link rule" src="https://user-images.githubusercontent.com/7377040/31392197-a5e8a642-ada6-11e7-933a-7d014aaa2243.png">

**Comment by WilcoFiers** [comment]
We'll likely change how this rule works. That's being discussed in #515. The docs thing is valid though. We'll sort that out ASAP.
