### ISSUE TITLE
feature request for a11y rule "role=main should only appear on significant elements"

### ISSUE THREAD

**Issue by pauljadam** [dequelabs/axe-core#57]
Google's Accessibility developer tools extension has this check which I find useful. I guess this is a very rarely found a11y problem but could be related to checking for only one role=main or was the role=main put on a logical element. 

nav role="main"

**Comment by dsturley** [comment]
[Google Accessibility's implementation](https://github.com/GoogleChrome/accessibility-developer-tools/blob/master/src/audits/MainRoleOnInappropriateElement.js)

**Comment by marcysutton** [comment]
@jongund @ssanaul would you be interested in picking this one up?

**Comment by jongund** [comment]
Marcy,

We are looking at this rule.

I think it would be better to build a more generic role restriction rule based on the HTML 5.1 role restrictions.

The rule could go through the elements in the DOM once and find any elements with roles that are not allowed.

Jon

**Comment by WilcoFiers** [comment]
I'm going to close this issue. We've added several landmark related rules to axe-core which should find common bad uses.
