### ISSUE TITLE
Severity levels in rule-descriptions-md

### ISSUE THREAD

**Issue by devarshipant** [dequelabs/axe-core#574]
Consider - https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md

In an additional column, can default impact (severity) levels be part of the display?

thanks!

**Comment by WilcoFiers** [comment]
We don't really have a default. There's a highest and lowest value we could possibly dig up during built. Right now this thing is built without looking at the checks though. That's something that'd have to be added. If you want to work on a pull request for this, please do so.

**Comment by devarshipant** [comment]
Sounds good.

**Comment by marcysutton** [comment]
This could be done as part of #693.

**Comment by devarshipant** [comment]
Sounds good.

**Comment by WilcoFiers** [comment]
This was done a while ago, see: https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md
