### ISSUE TITLE
document shadowDOM limitations

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#576]
The docs need to explain that shadow DOM testing only works in open mode.

**Comment by marcysutton** [comment]
They do already: https://github.com/dequelabs/axe-core/blob/develop/doc/developer-guide.md#rules

**Comment by WilcoFiers** [comment]
Ahh right, in the `selector` bullet. I think it needs to be added to the shadow DOM section too. It doesn't mention open / closed shadow DOM.
