### ISSUE TITLE
Extension removes newlines from code blocks on a website

### ISSUE THREAD

**Issue by kleinfreund** [dequelabs/axe-core#579]
When having the extension enabled, it removes `<br>` elements from specific parts of the DOM.

**Steps to reproduce:**

- Make sure aXe is enabled
- Open https://mathiasbynens.be/notes/es-regexp-proposals
- Observe, that all code blocks in the article have no new lines (the comments section is not affected)
- Disable the extension and reload the page
- Observe, that all code blocks now have the original new lines

None of that makes sense to me. I don’t know how to provide a more helpful report.

Note, that during this, the developer tools aren’t even open.

**Comment by WilcoFiers** [comment]
@isner Is this the same issue we've got in JIRA?

**Comment by isner** [comment]
@WilcoFiers Yep, and this issue has been fixed by commit 3d7ac73. Should be resolved by the next release.

@kleinfreund Thanks for pointing this out, and sorry for the inconvenience.
