### ISSUE TITLE
DPUB ARIA roles shouldn't be reported as violations

### ISSUE THREAD

**Issue by rdeltour** [dequelabs/axe-core#580]
The [Digital Publishing WAI-ARIA Module 1.0](https://www.w3.org/TR/dpub-aria-1.0/) specification introduces various new roles (named using the `doc-*` pattern), for which are also defined [accessibility API mappings](https://www.w3.org/TR/dpub-aam-1.0/).

Both DPUB ARIA and DPUB AAM are implemented, tested, and [decision was recently taken](https://lists.w3.org/Archives/Public/public-aria-admin/2017Oct/0000.html) to advance them to PR.

Currently aXe report violations when a DPUB ARIA roles are used. If you're OK, I can submit a PR to change that and allow ARIA roles.

**Comment by WilcoFiers** [comment]
E-mailing you to set up a call. I think we're going to need a few more details before there's something we can work on.

**Comment by marcysutton** [comment]
Pretty sure this was resolved with https://github.com/dequelabs/axe-core/pull/759. I'm going to close it since that PR was merged, but let us know if we need to reopen.
