### ISSUE TITLE
inconsistent dlitem result depending on file extension

### ISSUE THREAD

**Issue by mattgarrish** [dequelabs/axe-core#581]
DT and DD elements are always flagged as not being contained in a DL element when they're inside a document with an xhtml extension, but not when in one with an html extension.

For example, these are identical documents, but only the latter generates an error:
http://matt.garrish.ca/res/pr01.html
http://matt.garrish.ca/res/pr01.xhtml

I believe this is a similar problem with nodeName as reported in https://github.com/dequelabs/axe-core/issues/563

**Comment by rdeltour** [comment]
@WilcoFiers I spotted the issue and have a fix coming. It's only in the 2.x branch. I'll try to submit a PR today if you want to include it in 2.6!

**Comment by WilcoFiers** [comment]
Should be fixed as of axe 2.6. Thanks @rdeltour
