### ISSUE TITLE
th-has-data-cells confusing error message

### ISSUE THREAD

**Issue by mattgarrish** [dequelabs/axe-core#585]
The error reported in axe is:

> All th element and elements with role=columnheader/rowheader must data cells which it describes

But the linked documentation page has the clearer title:

> All <th> elements and elements with role=columnheader/rowheader must have data cells they describe

Would be nice if the former matched the latter.

**Comment by marcysutton** [comment]
This would be a great thing to fix in a PR, if you're able

**Comment by marcysutton** [comment]
Closed with #586. Thanks again @mattgarrish !

**Comment by mattgarrish** [comment]
NP!
