### ISSUE TITLE
We have been trying find the logs

### ISSUE THREAD

**Issue by Sumtotal** [dequelabs/axe-core#588]
Hi, 
How can i find a logs for below screen shot, help me ASAP.
![github](https://user-images.githubusercontent.com/33124593/32054699-ef652ba0-ba7c-11e7-8fa1-4822b7250eeb.png)

**Comment by WilcoFiers** [comment]
I don't quite understand what you're asking here. Please provide some details of what you are trying to do, how you're doing it, and what isn't working.
