### ISSUE TITLE
No check for empty alt in image-alt rule

### ISSUE THREAD

**Issue by porelsoumen** [dequelabs/axe-core#590]
The existing has-alt checks only the existence of the attribute and does not check if the value is present or not. The **non-empty-alt** check should be added to the list of existing checks for _image-alt_ rule.

**Comment by WilcoFiers** [comment]
Empty alt attributes are a WCAG technique to indicate that images are decorative. This allows assistive technologies to ignore them. This is why axe doesn't flag them as violations.

**Comment by porelsoumen** [comment]
Understood. Is there a way to add this check for my test in my local machine? I am using the axe-selenium-java test example.

**Comment by WilcoFiers** [comment]
You'd have to create a custom rule and run it using axe.configure. That's not currently built into axe-selenium-java though. You're welcome to work on a pull request for something like that. You'd have to write the custom rule yourself, but that shouldn't be too difficult.
