### ISSUE TITLE
Expose lookupTables through public API

### ISSUE THREAD

**Issue by marcysutton** [dequelabs/axe-core#616]
As part of our ongoing Support agreement, we had a request to expose the ARIA lookupTables through the public axe-core API. These are pretty stable, so I don't anticipate much work in the way of maintaining backwards compatibility.

I believe the goal is to expose the roles, attributes, and global attributes inside of rules and checks.

https://github.com/dequelabs/axe-core/blob/develop/lib/commons/aria/index.js

**Comment by marcysutton** [comment]
These are available through the global axe object:

```
axe.commons.aria._lut
```

Should we alias this when we document it?

**Comment by WilcoFiers** [comment]
We can simply rename it. I think `axe.commons.aria.lookupTable` would be fine. We're not accessing it directly in any of our checks or commons.

**Comment by dylanb** [comment]
What are the uses/use cases for use of this table? Might be better to expose those use cases as functions so we can change the implementation of the ARIA data in a backwards compatible way.

**Comment by marcysutton** [comment]
I've asked for more details.
