### ISSUE TITLE
Expose select commons/utils functions via public API

### ISSUE THREAD

**Issue by marcysutton** [dequelabs/axe-core#617]
As part of our ongoing Support agreement, we need to expose select commons and util functions through the public API. For now we just need a few to start, but we may determine it makes more sense to expose an entire set at once.

- [aria.implicitRole](https://github.com/dequelabs/axe-core/blob/develop-2x/lib/commons/aria/roles.js#L105)
- [aria.label](https://github.com/dequelabs/axe-core/blob/develop-2x/lib/commons/aria/label.js)
- [dom.isVisible](https://github.com/dequelabs/axe-core/blob/develop-2x/lib/commons/dom/is-visible.js#L28)

**Comment by WilcoFiers** [comment]
What does "through the public API" mean exactly? You can get at all of them through `axe.commons`. Is the request to move them from `axe.commons` to `axe` itself?

**Comment by marcysutton** [comment]
I'll find out more if they weren't able to accomplish something, but most likely it's a documentation issue. Not everyone knows the innerworkings of it like we do!
