### ISSUE TITLE
Certain ARIA roles must contain particular children on combobox

### ISSUE THREAD

**Issue by iandevlin** [dequelabs/axe-core#618]
I have an `input` field that has `role="combobox"` and `aria-owns` which is set to the `id` of a `ul` that contains the required suggestions.

But when I run aXe, I get a "Certain ARIA roles must contain particular children on combobox"  error, and of course an `input` cannot have children.

I have found a similar bug report that has been closed as fixed: https://github.com/dequelabs/axe-core/issues/214

I am using axe-devtools: 3.1.1 and axe-core 2.4.1

**Comment by marcysutton** [comment]
Thanks for the issue @iandevlin, do you have a live demo somewhere we can check out? That will help us get to the bottom of it quicker.

**Comment by iandevlin** [comment]
@marcysutton I hadn't, but this quick CodePen shows it: https://codepen.io/iandevlin/pen/qVVPXx

**Comment by marcysutton** [comment]
This was fixed in axe-core@2.5.0: https://cdnjs.cloudflare.com/ajax/libs/axe-core/2.5.0/axe.js
