### ISSUE TITLE
Zooming and scaling must not be disabled

### ISSUE THREAD

**Issue by mara90** [dequelabs/axe-core#625]
I got an error related to zooming although I'm using the standard recommended code. I ran through the same issue with Lighthouse, and they said that its better to check with axe plugin to see if I get the same error.
Also, my site doesn't disable zooming and it doesn't have [user-scalable="no"].

Axe error:
![image](https://user-images.githubusercontent.com/22651469/33281953-018535bc-d375-11e7-823f-bd4e7864ea08.png)

Lighthouse error:
![image](https://user-images.githubusercontent.com/22651469/33282018-4bb62a10-d375-11e7-85e3-adbd1b1985d1.png)

Thank you!

**Comment by marcysutton** [comment]
Hi there, do you have a live demo somewhere? axe-core is pulling that from your element source.

**Comment by marcysutton** [comment]
I saw the source code after an email exchange, and axe-core is doing the right thing here. Remove `user-scalable=no` and you won't get the violation. That viewport option does prevent scaling in some mobile browsers (it definitely does in Brave, but oddly doesn't in mobile Safari)

**Comment by mara90** [comment]
@marcysutton  Thank you Marcy for helping me with this issue! I've looked everywhere in my code all around the website for this (user-scalable=no) but I couldn't find it, do you mean the whole "meta" tag should be removed so it can stop preventing the scaling? I even tried that and removed that specific meta tag with the viewport and still got the same error. Not sure if its something I missed?!

**Comment by marcysutton** [comment]
If you click "inspect node" you can look at the element that axe-core found. Try removing just the `user-scalable=no` bit. I checked [the tests for that rule](https://github.com/dequelabs/axe-core/blob/develop/test/checks/mobile/meta-viewport-scale.js), and it should report a different result based on the options supplied in the meta tag–it's not all-or-nothing.

**Comment by mara90** [comment]
@marcysutton  .... I finally found the culprit, it was one of the plugins that I'm using, it keeps adding the (user-scalable=no) and now I removed it and the error is gone from axe and lighthouse. Thanks again.
