### ISSUE TITLE
Different input types within fieldset should have the same name attribute

### ISSUE THREAD

**Issue by QSCGU** [dequelabs/axe-core#628]
I have created a group of radiobuttons with a fieldset wrapped around them. When I add other input elements such as buttons to the fieldset aXe gives me the following error: 
Radio inputs with the same name attribute value must be part of a group

I think this is a false positive since only multiple groups of inputs (radiobuttons and checkboxes) should be disallowed within a fieldset. I created a JSFiddle to demonstrate the issue: https://jsfiddle.net/8ezc9kw9/1/ when the button is removed aXe will no longer have validation errors.

**Comment by dylanb** [comment]
@QSCGU It is possible to have a fieldset within a fieldset and when you have a group of radio buttons you need to give that group a label separate from the label for the rest of a bigger group.

**Comment by WilcoFiers** [comment]
The point of this rule isn't to put all form elements fieldset, but rather to give every group of radiobuttons an accessible name. We believe this to be a best practice, helping you design better forms over all. 

I'm closing the issue because there was no followup discussion on this.
