### ISSUE TITLE
Section 3 example links are broken

### ISSUE THREAD

**Issue by dylanb** [dequelabs/axe-core#631]
Go to this page

https://www.axe-core.org/docs/

Click the link for Section 3: Examples

Click any link in the examples paragraph and you will see it is broken

**Comment by marcysutton** [comment]
The raw link URLs in that section look like this: `[jasmine](examples/jasmine)`

The problem stems from the API docs being in a `docs` folder on S3, whereas for the Github version they are in a `doc` folder. Our build system probably needs to do a bit more to correct the links.

The table of contents link to that section at the top is also outdated on Github, it says "section-5" in it while it's really "section-3". It would be better to auto-generate those links.

**Comment by marcysutton** [comment]
We should probably report this in [axe-website](https://github.com/dequelabs/axe-website) instead. I'm going to close this here, since it isn't an axe-core issue.
