### ISSUE TITLE
Malformed Error Description

### ISSUE THREAD

**Issue by preetykumar** [dequelabs/axe-core#633]
All th element and elements with role=columnheader/rowheader must data cells which it describes

should it be?

All th element and elements with role=columnheader/rowheader must _have_ data cells which it describes

**Comment by dylanb** [comment]
Hey, who let the CEO in?!?!

**Comment by WilcoFiers** [comment]
I'm surprised this fell through the cracks. We had this reported before. Thanks Preety. We'll be sure to fix this.

**Comment by WilcoFiers** [comment]
Correction. This was fixed. It hasn't been released everywhere though:
https://github.com/dequelabs/axe-core/commit/aff319536ddcdce09a7b99856a23a68dd98cddc2
