### ISSUE TITLE
Accessible Name computation skips subtree of table with role=presentation

### ISSUE THREAD

**Issue by jnurthen** [dequelabs/axe-core#634]
if (!shouldNeverCheckSubtree(element) && (!role || aria.getRolesWithNameFromContents().indexOf(role) !== -1)) {
            returnText = getInnerText(element, inLabelledByContext, inControlContext);
            if (nonEmptyText(returnText)) {
              return returnText;
            }
          }

shouldNeverCheckSubtree always returns true for a table element even if it is marked with role=none|presentation so the getInnerText function never gets called.

**Comment by WilcoFiers** [comment]
What's the use case here? Is it generating false positives anywhere?

**Comment by jnurthen** [comment]
False positives at the following URL.
http://jdevadf.oracle.com/adf-richclient-demo/faces/index.jspx
Get "Headings must not be empty" errors for each of the "accordion" headings at the left hand side.

**Comment by WilcoFiers** [comment]
Interesting! Ok sure. If you've got the time, we'd welcome a PR for this James.

**Comment by jnurthen** [comment]
I'll work on getting the CLA approvals completed. I need multiple approvals so won't be any time soon.

**Comment by WilcoFiers** [comment]
This should be resolved by #722

**Comment by marcysutton** [comment]
@jnurthen can you confirm if the work in #722 helps resolve this issue?

**Comment by marcysutton** [comment]
I'm going to close this issue, as we have no way to reproduce it. Let us know if the issue still persists.
