### ISSUE TITLE
New rule: color-contrast-placeholders

### ISSUE THREAD

**Issue by iamrafan** [dequelabs/axe-core#643]
I am not sure if there is a way to access the placeholder text's native color

**Comment by marcysutton** [comment]
We could potentially evaluate the computed style. Here's the CSS to get `:before` and `:after`, perhaps we could do a similar check for `:placeholder`. But I'd have to test it.

```
var beforeBGColor = window.getComputedStyle(
    node, ':before'
)

var afterBGColor = window.getComputedStyle(
    node, ':after'
)
```

For internal folks: there's an existing issue in the backlog that could be tackled at the same time. https://dequesrc.atlassian.net/browse/WWD-813

**Comment by marcysutton** [comment]
Even though you can style the placeholder, detecting it isn't supported according to the CSSOM. `window.getComputedStyle` only matches pseudo elements `:before:` and `:after`: https://www.w3.org/TR/cssom-1/#extensions-to-the-window-interface

It would be super cool if we could do this, but I don't see how it's possible with the current APIs at our disposal. I'm reaching out to some folks to try and learn more.

**Comment by marcysutton** [comment]
I've filed an issue with the spec editors, and we can see what they say: https://github.com/w3c/csswg-drafts/issues/2112

This issue should probably stay closed in axe-core as it would have to remain open for an unreasonable amount of time. But we can reopen it at some point if things change.

**Comment by iamrafan** [comment]
@marcysutton sure, thanks for the follow up

**Comment by dylanb** [comment]
@straker @WilcoFiers 

I think we can solve this issue ourselves with code akin to

```
async function rules () {
	axe._tree = axe.utils.getFlattenedTree(document)
	let sheets = await axe.utils.preloadCssom(axe._tree[0])
	let rules = sheets.reduce((out, s) => {
		return out.concat(Array.from(s.sheet.rules).filter((r) => {
			return /\:\:.*placeholder/i.test(r.cssText) &&
				r.style &&
				(r.style.color !== '' || r.style.backgroundColor !== '')
		}))
	}, [])
	return rules
}

function inputsToColors(rules) {
	const INPUTS = 'input[placeholder]:not([type=image]):not([type=button]):not([type=submit])'
	let inputs = Array.from(document.querySelectorAll(INPUTS))
	let riMap = inputs.map((i) => {
		let matches = []
		return {
			input: i,
			rules: matches.concat(rules.filter((r) => {
				let t = r.selectorText
				if (t) {
					t = t.replace(/\:\:.*placeholder[^\.\#\:\s]?/g, '')
					return i.matches(t)
				}
				return false
			}))
		}
	})
	return riMap.map((ri) => {
		ri.rules.reverse()
		let color = ri.rules.reduce((c, r) => {
			if (r.style.color !== '') {
				return r.style.color
			}
			return c
		}, '(rgb(117,117,117))')
		let bgColor = ri.rules.reduce((c, r) => {
			if (r.style.color !== '') {
				return r.style.backgroundColor
			}
			return c
		}, '')
		return {
			input: ri.input,
			color: color,
			bgColor: bgColor
		}
	})
}

inputsToColors(await rules())
```

**Comment by WilcoFiers** [comment]
This rule would have to be review only. There are good reasons to want a placeholder with a lower contrast. The information just needs to be available in some other way too.
