### ISSUE TITLE
Document the easiest way to start

### ISSUE THREAD

**Issue by mgifford** [dequelabs/axe-core#65]
Would be good to document the easiest way to get going on a given html page. 

I would think that doing an audit of the whole page would be the easiest.  How would I do that?

I'd rather not have Qunit or Selenium enabled to do this too.

**Comment by dsturley** [comment]
aXe needs to run in a browser, which is why all the examples use unit testing platforms or something to drive a browser.  If you just want to quickly check pages; you can use the [Google Chrome extension](https://chrome.google.com/webstore/detail/axe/lhdoppojpmngadmnindnejefpokejbdd).

**Comment by mgifford** [comment]
Ok. I've used some of these testing tools before, but not often.

**Comment by dylanb** [comment]
@mgifford - what were you thinking might be a good way to test a single page quickly?

**Comment by mgifford** [comment]
Well, we have to insert a JS file into the header anyways, right?

Could we just insert another line that creates a footer div on that page that displays the results of a full page scan? 

If that works, then maybe there could be a variation of that JS code that you could add to a div tag and just scan the contents within the div tag.

I really am not a JS person, but not sure why that wouldn't work.

**Comment by dylanb** [comment]
@mgifford we could create a bookmarklet that does something similar to tota11y (in fact I have ported tota11y to use aXe) - wdyt?

**Comment by mgifford** [comment]
There would be some good advantages to that I'd think.  Being able to test with FF would be good.

**Comment by dylanb** [comment]
@mgifford There is a FF extension https://addons.mozilla.org/en-US/firefox/addon/axe-firefox-devtools/

**Comment by mgifford** [comment]
Cool. I'd missed that.

**Comment by dsturley** [comment]
Closing issue; feel free contact again if you have additional concerns.
