### ISSUE TITLE
make the frame timeout limit configurable

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#660]
We had a client (issue WH-4054 on JIRA) that kept getting timeout errors while running axe on a particular page. A short term solution could be to extend this time limit. Longer term we should probably just add a feature that lets the frame report its still in progress if it's near the timeout limit. That way we can shorten the timeout too.

**Comment by dylanb** [comment]
How about allowing a configurable timeout?

**Comment by WilcoFiers** [comment]
Matt is working on that :)

**Comment by isner** [comment]
Feature added by https://github.com/dequelabs/axe-core/pull/661
