### ISSUE TITLE
Rule href-no-hash is reported but not exists in 2.6.0

### ISSUE THREAD

**Issue by Compilerrr** [dequelabs/axe-core#662]
After running Axe with tags "wcag2a","wcag2aa","best-practice"
I have several issues reported referring to https://dequeuniversity.com/rules/axe/2.6/href-no-hash?application=axeAPI
"Anchors must only be used as links with valid URLs or URL fragments"

There is no such a rule. I'm wondering if it is a bug or misconfiguration on my side?

**Comment by WilcoFiers** [comment]
It's not you, it's me :wink:. We're sorting it out. Thanks for reporting!

**Comment by Compilerrr** [comment]
Hi @WilcoFiers any updates on this?

**Comment by WilcoFiers** [comment]
Sorted. Thanks for the reminder.
