### ISSUE TITLE
href-no-hash missing from rule-descriptions.md

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#664]
On the current `develop` branch, it's not included, but I can see it on `develop-2x`:
https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md

**Comment by marcysutton** [comment]
ah, might have gotten messed up when merging since that file has to be built and then committed.

**Comment by iamrafan** [comment]
@WilcoFiers wasn't it decided to remove 'href-no-hash' as part of this discussion #515  and this PR #612

**Comment by WilcoFiers** [comment]
You are totally right Guru. I hadn't looked at it. It just got reported and I plopped down the issue. But that's correct. We dropped that rule for 3.0, which is why it's not in rule_descriptions.md. I didn't pull that change into 2x because it's a breaking change.
