### ISSUE TITLE
console.log() left in released code 

### ISSUE THREAD

**Issue by julianaleon** [dequelabs/axe-core#668]
I keep seeing a node tree trace logging out while I'm running my a11y tests. After some debugging we realized that there is a console.log() that was left in the `dom.isFocusable` function of `isFocusable.js` It looks that line has been removed from your develop branch but was still included in the 2.6.0 release. @0ddfell0w @WilcoFiers can you take a look at this? 

![screen shot 2017-12-26 at 3 40 37 pm](https://user-images.githubusercontent.com/6567368/34365229-8b004288-ea53-11e7-9d7c-9d462a86ea2f.png)

**Comment by marcysutton** [comment]
Here's the commit: https://github.com/dequelabs/axe-core/commit/08af138935c2298c8c7cbff683cc0ed9ff522dc5

**Comment by marcysutton** [comment]
Fixed in 2.6.1.

**Comment by julianaleon** [comment]
Thanks for the quick patch @marcysutton
