### ISSUE TITLE
Axe browser Extension: Line hight causing false fail for contrast

### ISSUE THREAD

**Issue by reastCC** [dequelabs/axe-core#669]
Hi,

I am having an issue where certain line heights are causing false fails in the aXe chrome extension. I have confirmed that the two colors we are using pass the manual contrast inspection. For some reason when the line high is enabled at 1.5em the tool picks up on it as a contrast failure. If I disable the line high the tool does not mark it as a contrast failure. I'm hoping to understand if this is a bug in the tool or if there is are requirement I am misunderstanding. I have attached the screenshots I have below. 

Thanks.

* Example of failure being raised

<img width="1429" alt="main issue" src="https://user-images.githubusercontent.com/34895185/34389980-b218d56c-eaf1-11e7-823c-32287312ab0e.png">

* Example of colors we are using

<img width="1288" alt="blue color edit" src="https://user-images.githubusercontent.com/34895185/34389985-b72687e8-eaf1-11e7-8b5a-1b3b4a8bf343.png">

<img width="1293" alt="gray color edit" src="https://user-images.githubusercontent.com/34895185/34389990-bb5bb874-eaf1-11e7-9656-ac09dcfdd394.png">

**Comment by marcysutton** [comment]
Hi @reastCC, thanks for your issue! Is it possible to get a live browser demo so we can debug this further? If your project isn't public-facing, perhaps you could boil it down to the essentials in a Codepen demo or similar?

**Comment by reastCC** [comment]
Thanks for the quick response, as you anticipated our project isn’t public-facing. I have never used Codepen but I will look into it and get back to you.

**Comment by reastCC** [comment]
I wasn't able to get my developers to create a live demo, and with the latest code changes the tool is no longer picking up the failure it once was. I think this can be closed now, sorry for any inconvenience.
