### ISSUE TITLE
Improve context parameter defaults

### ISSUE THREAD

**Issue by dsturley** [dequelabs/axe-core#67]
The following should default `include` to the document:

```javascript
axe.a11yCheck({}, function (r) { console.log(r); });
```
```javascript
axe.a11yCheck({ exclude: ['.bob'] }, function (r) { console.log(r); });
```
```javascript
axe.a11yCheck({ exclude: [] }, function (r) { console.log(r); });
```

**Comment by jasonkarns** [comment]
Of these, I think the last one is reasonable to *not* support. It's nonsensical to ask axe to check accessibility for an explicitly empty list of elements.

**Comment by jasonkarns** [comment]
According to the documentation:
https://github.com/dequelabs/axe-core/blob/master/doc/API.md#include-exclude-object

Example 1
```axe.a11yCheck({}, function (r) { console.log(r); });```

can be classified as an enhancement; documentation states at least one of `included`/`excluded` must be present):
> Either include or exclude is required.


But Examples 2 (and arguably 3)
```axe.a11yCheck({ exclude: ['.bob'] }, function (r) { console.log(r); });```
```axe.a11yCheck({ exclude: [] }, function (r) { console.log(r); });```

should probably be classified as bugs; documentation states an omitted include would default to entire document:
> If only exclude is specified; include will default to the entire document.

**Comment by jasonkarns** [comment]
cf12aa0fb68008bcd8f2024bf8efd06beec56cbc
