### ISSUE TITLE
Do not allow value 'false' for aria-haspopup attribute

### ISSUE THREAD

**Issue by iamrafan** [dequelabs/axe-core#670]
![image](https://user-images.githubusercontent.com/22068434/34460321-85a49cd4-edbf-11e7-85cc-e7f81c4edb41.png)

Here is the related ARIA 1.1 spec
![image](https://user-images.githubusercontent.com/22068434/34460363-b9f31e7e-edc0-11e7-8e79-8410ef8cbab3.png)

**Comment by WilcoFiers** [comment]
Are you proposing to remove `false` from the list? I don't see how that's a false positive or anything.

**Comment by iamrafan** [comment]
yes, it does not throw any false positives but I was suggesting to remove 'false' to stay consistent with the aria spec

**Comment by WilcoFiers** [comment]
In the list of allowed values for `aria-haspopup` in ARIA 1.1, `false` is listed. So I don't see why we shouldn't allow it.

**Comment by iamrafan** [comment]
ok. please close this issue.
