### ISSUE TITLE
Duplicate ID issue is not raised by axe on http://www.homesteadmiamispeedway.com/Connect/Newsletter.aspx

### ISSUE THREAD

**Issue by JerushaP** [dequelabs/axe-core#671]
I have observed that running Axe on http://www.homesteadmiamispeedway.com/Connect/Newsletter.aspx
page fails to show the duplicate ID issue.

The duplicate IDs in this page are newsLetterId and newsletterSignup.

Axe core version: 2.6
Browser: Chrome 63.0

**Comment by dylanb** [comment]
The inputs on that page are using the`name` attribute when they should be using the `id` attribute. Duplicate `name` attributes are not a problem but using `for` to point to a `name` is...closing
