### ISSUE TITLE
Role types in lookup table disagree with ARIA spec

### ISSUE THREAD

**Issue by 0ddfell0w** [dequelabs/axe-core#672]
These roles are marked as widgets in lib/commons/aria/index.js, but not in the aria spec

### tooltip
https://github.com/dequelabs/axe-core/blame/develop/lib/commons/aria/index.js#L874
https://www.w3.org/TR/wai-aria-1.1/#tooltip

### dialog
https://github.com/dequelabs/axe-core/blame/develop/lib/commons/aria/index.js#L319
https://www.w3.org/TR/wai-aria-1.1/#dialog

### alertdialog
https://github.com/dequelabs/axe-core/blame/develop/lib/commons/aria/index.js#L191
https://www.w3.org/TR/wai-aria-1.1/#alertdialog

### timer
https://github.com/dequelabs/axe-core/blame/develop/lib/commons/aria/index.js#L855
https://www.w3.org/TR/wai-aria-1.1/#timer

### status
https://github.com/dequelabs/axe-core/blame/develop/lib/commons/aria/index.js#L764
https://www.w3.org/TR/wai-aria-1.1/#status

### marquee
https://github.com/dequelabs/axe-core/blame/develop/lib/commons/aria/index.js#L494
https://www.w3.org/TR/wai-aria-1.1/#marquee

### log
https://github.com/dequelabs/axe-core/blame/develop/lib/commons/aria/index.js#L475
https://www.w3.org/TR/wai-aria-1.1/#log

### alert
https://github.com/dequelabs/axe-core/blame/develop/lib/commons/aria/index.js#L182
https://www.w3.org/TR/wai-aria-1.1/#alert

**Comment by marcysutton** [comment]
Long-term, we should consider moving to something like [aria-query](https://www.npmjs.com/package/aria-query) instead of maintaining our own lookupTable.

**Comment by WilcoFiers** [comment]
Our use of "type" in axe-core isn't intended as an exact match with the ARIA spec. I think keeping the flexibility to differ from ARIA is useful for us. I'm closing this issue, we're not going to resolve this as a whole, individually cases can be opened in separate issues.
