### ISSUE TITLE
`label-matches.js` should return gracefully if no `type` is present

### ISSUE THREAD

**Issue by downzer0** [dequelabs/axe-core#678]
In the `label-matches.js` file, if no `type` attribute is present on the element, the results crash. While not common, an `<input />` is possible so this should return gracefully in that event.

Suggestion:

```javascript
if (node.nodeName.toLowerCase() !== 'input') {
  return true;
}
if (!node.getAttribute('type')) {
  return true;
}
var t = node.getAttribute('type').toLowerCase();
var types = [
  'hidden',
  'image',
  'button',
  'submit',
  'reset'
];
if (types.indexOf(t) !== -1) {
  return false;
}
return true;
```

**Comment by marcysutton** [comment]
That seems easy enough. Would you be interested in submitting a PR?
