### ISSUE TITLE
Slow bootup of coconut

### ISSUE THREAD

**Issue by paulirish** [dequelabs/axe-core#679]
I was profiling the load of a webapp of mine, but looking in the trace, I saw 1.7s of axe-coconut initializing:

![image](https://user-images.githubusercontent.com/39191/34892571-9942979a-f78e-11e7-897f-ca21335f2706.png)

Do note that I had CPU throttling on, so this exaggerates all main thread time. But still, this is pretty heavy.  

I'm curious if running this code within the page could be deferred, especially since it's so heavy.

-----------

FWIW here's a zoom-in shot:
![image](https://user-images.githubusercontent.com/39191/34894063-c355c15a-f794-11e7-9828-ee336b808480.png)

**Comment by isner** [comment]
Thanks very much, @paulirish . I'm seeing a delay of between 100-200 ms when the CPU is running at full capacity, but we'll certainly look into this. It might be tricky for us to isolate and defer only certain dependencies.

By the way, how are you doing your CPU throttling? We'd love to know.

**Comment by dylanb** [comment]
@scurker if this is a duplicate, please close one of the performance issues

**Comment by scurker** [comment]
Closing issue and tracking updates with #1839. Ideally any performance improvements will help with both Coconut and Axe.
