### ISSUE TITLE
Extend 'landmark-one-main' rule to fail if a page has more than one banner, or contentinfo landmark

### ISSUE THREAD

**Issue by iamrafan** [dequelabs/axe-core#682]
Ensures that a page contain not more than one main, banner and contentinfo landmarks unless in nested document or application role.

If extending this rule does not seem appropriate, it is a good case for a new best practice rule

**Comment by WilcoFiers** [comment]
I think those make sense as separate rules. I wouldn't say that `banner` or `contentinfo` are required, but you shouldn't have more than one of them per frame.

**Comment by iamrafan** [comment]
I agree
