### ISSUE TITLE
Performance of dom.findUp is very slow

### ISSUE THREAD

**Issue by paulirish** [dequelabs/axe-core#696]
As you [know](https://github.com/dequelabs/axe-core/blob/develop/lib/commons/dom/find-up.js#L5), the performance of dom.findUp is really poor.   However it is used very heavily across the various rules/checks.

AFAICT, you could use the DOM API of [`element.matches()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/matches) which should be substantially faster.  ([browser support](https://caniuse.com/#feat=matchesselector) is good). 

You basically have written the polyfill for it, so you can fall back to your current implementation if `('matches' in element)` is false.

-----

Good site to reproduce on: https://www.mlb.com/
Screenshot of the color-contrast rule taking 26s to complete. (All of the time is spent in the querySelectorAll within findUp)

cc @patrickhulce @kdzwinel

![image](https://user-images.githubusercontent.com/39191/35372329-7415366c-01ed-11e8-96ee-d303736a0004.png)

**Comment by dylanb** [comment]
hmmm...good point, let me take a look - I am concerned about shadow DOM nodes but there may be some simple optimizations we could make to improve performance for most situations

**Comment by dylanb** [comment]
@paulirish AFAICT `element.matches` cannot be used to improve color contrast speed because we actually need to retrieve the ancestor element that causes the match and `element.matches` simply returns true or false

I tell you what would make this check blindingly fast - give us a JavaScript function that tells me what the browser thinks the background color is for any given point on the page and a matching one for the foreground color for any given point on the page (in fact if we could get the color stack at any point above an element and the actual color of any given point, we could do the rest of the calculation blindingly fast - know anyone who could help?

**Comment by kdzwinel** [comment]
I might be missing something here, but IMO `element.closest` is the native equivalent of `dom.findUp`. Not sure about the shadow DOM part though.

**Comment by dylanb** [comment]
@kdzwinel you are correct

@paulirish try this version of axe-core. I think I reduced the querySelectorAll time by 80% on mlb.com https://gist.github.com/dylanb/caeb6a12e2320a46925b462809924c3a

**Comment by kdzwinel** [comment]
I just tested and on https://www.mlb.com/yankees/schedule/2018-03%60 axe runtime is down from 60s+ (LH has a 60s timeout for gatherers) to 29s 🎉

**Comment by dylanb** [comment]
I am also going to use element.matches to improve the performance of the case where `element.closest` does not exist and see if I can optimize the shadow DOM worst case scenario too (nothing matches)

**Comment by dylanb** [comment]
what `element.closest` giveth, shadow DOM taketh away :-(

**Comment by dylanb** [comment]
@kdzwinel @paulirish Can you try this version? https://gist.github.com/dylanb/72387f45e38363d6bea5728809fdea8c

It is a bit slower than the previous super-fast one but actually handles all the conditions we need to handle. Y'all an look at the pull request above to see the changes if you want to make suggestions as to additional improvements

**Comment by patrickhulce** [comment]
Thanks for jumping on this @dylanb! I'm getting some pretty slow stats on that one MLB example site (https://www.mlb.com/yankees/schedule/2018-03) still :/

@kdzwinel how were you running that version, in LH? The one trace I was able to get spends about ~2 minutes. `pushNode` seems to be the biggest timesink here though, so maybe a separate issue?

![image](https://user-images.githubusercontent.com/2301202/35422060-cc787622-029a-11e8-88f3-9fa45856927c.png)

**Comment by dylanb** [comment]
@patrickhulce the mouseover there is showing 23s with pushNode only taking 16ms of that time. I think you are seeing similar performance to what I am seeing. Its a big improvement from where we started this morning.

**Comment by patrickhulce** [comment]
Yeah, yeah I'm aware it's not in pushNode itself 😄 (most of its time seems to be in `.find` actually). Since @kdzwinel was able to get a completion in ~30s before, ~140s seemed to be much slower, so I was wondering if something else changed.

**Comment by dylanb** [comment]
Apologies for the confusion, I must have been tired when I looked at your screen shot.

When @kdzwinel was getting 29s, I was getting about 21 seconds - here is a screenshot

![image](https://user-images.githubusercontent.com/79245/35440490-a475e916-026d-11e8-8780-ebdcac95add8.png)

After I made the changes to correctly support shadow DOM, I am gettin around 23 seconds - a decreased of 10% from the prior increase in performance of about 80%

![image](https://user-images.githubusercontent.com/79245/35440518-c8e6a6aa-026d-11e8-8a59-878915b79fcf.png)

so that gets us to an improvement of around 78% from before (i.e. it is now taking around 22% of the time it used to take)

**Comment by kdzwinel** [comment]
Three LH runs on https://www.mlb.com/yankees/schedule/2018-03 with this version of axe-core: https://gist.github.com/dylanb/72387f45e38363d6bea5728809fdea8c give me 36s, 31s, 37s.

The way I test it is I just [point accessability audit](https://github.com/GoogleChrome/lighthouse/blob/c225d0189f4ffc945168aff31523a20e7c6342ab/lighthouse-core/gather/gatherers/accessibility.js#L12) to a different version of axe.min.js file and call `lighthouse-cli https://www.mlb.com/yankees/schedule/2018-03 --view`.

**Comment by dylanb** [comment]
How does that compare to previously? Are you seeing about a 20% improvement?

**Comment by dylanb** [comment]
@patrickhulce nice find - that function was horribly inefficient. I have now reduced that page from over 200s to around 45s. Try this https://gist.github.com/dylanb/77334dd2c6d9ff510da89a09ccfa2490

**Comment by dylanb** [comment]
This is a fantastic improvement. It gets the time for the mlb.com home page down to around 14s from 28s - that is an improvement of 50% overall...thanks for the help @paulirish @patrickhulce and @kdzwinel

**Comment by benschwarz** [comment]
Would it be possible to get this in a point release @dylanb? We'd sure like to see it in Lighthouse soon

**Comment by paulirish** [comment]
@benschwarz I'm awaiting the merge of #701 and resolution of #702 before rolling. While a minor release from aXe would be awesome, I'm also happy to cherrypick these onto 2.6.1 and use that custom branch.

**Comment by WilcoFiers** [comment]
Cherry picking this fix for 2.x won't work. Much of it is build on shadow DOM code that isn't available in 2.x. We're pretty close to the 3.0 release at this point, I'd prefer all our current efforts go into 3.0 right now, instead of another 2.x release.

**Comment by paulirish** [comment]
K. that works for me.
