### ISSUE TITLE
documentation around `rules`

### ISSUE THREAD

**Issue by jasonkarns** [dequelabs/axe-core#70]
The documentation around selecting which rules should be run (https://github.com/dequelabs/axe-core/blob/master/doc/API.md#b-options-parameter) lists essentially three modes of operation:
1. only rules included in (presumably the union?) set of rules matching given tags
2. run all rules except x, y, z
3. run only rules x, y, z

syntax for 1. is `runOnly: type: "tag", values:[]`
syntax for 2. is `rules: rule1: enabled: false`
syntax for 3. is documented as `runOnly: type: "rule", values:[]`

However, [example 3](https://github.com/dequelabs/axe-core/blob/master/doc/API.md#example-3) shows  `rules: rule1: enabled: true`. With the documented behavior being that only the rules listed as `enabled` are run. This seemingly contradicts the documentation which states that: 
> The default operation for a11yCheck is to run all rules.

Is example 3 a typo? Should it have been `runOnly: type: "rule", values: [x, y, z]`? Or is the syntax truly `rules: rule1: enabled: true/false`. Or are both forms acceptable? If so, it sounds as if
> The default operation for a11yCheck is to run all rules.

 should be clarified to state that once *any* `rules`/`runOnly` is specified, then a11yCheck no longer defaults to "all rules". (For if that were true, then specifying a list of rules with `enabled:true` would be meaningless.)

**Comment by dsturley** [comment]
`rules` API is basically the method to set options for rules; it does not effect anything other than what it specifies, so if a rule is enabled by default, and options don't specify `enabled: false`, it will still run.

**Comment by jasonkarns** [comment]
So this means example 3 (https://github.com/dequelabs/axe-core/blob/master/doc/API.md#example-3) is wrong?

```
axe.a11yCheck(document, {
  rules: {
    "button-name": { enabled: true },
    "color-contrast": { enabled: true }
  }
}, function(results) {
  console.log(results);
});
```

It's the same as simply not specifying the rules at all:
```
axe.a11yCheck(document, {}, function(results) {
  console.log(results);
});
```

(Since it enables rules that were never disabled in the first place)

**Comment by dsturley** [comment]
Jason, yes the example was basically enabling rules that were enabled by default.  I've changed them in  #75 to reference best practice rules, which are disabled by default.
