### ISSUE TITLE
Document arguments to axe.cleanup()

### ISSUE THREAD

**Issue by lsiden** [dequelabs/axe-core#710]
axe.cleanup() takes two functional arguments, 'resolve' and 'reject', but the docs do not mention this.

**Comment by WilcoFiers** [comment]
Feel free to update your PR (#709) to include this.

**Comment by marcysutton** [comment]
Fixed with https://github.com/dequelabs/axe-core/pull/709/commits/4dfa58fbdfb33cb3da37e6282ca0f5d1aa79dad5.
