### ISSUE TITLE
Color contrast is slow on some pages

### ISSUE THREAD

**Issue by dylanb** [dequelabs/axe-core#716]
The vast majority of the time spent in analysis on this page (close to 90%) is spent in color-contrast

http://gotta.dance/ballroom/international/standard/quickstep/

**Comment by WilcoFiers** [comment]
Removing the 3.0 tag. We're not likely to fix this before the 3.0 release.

**Comment by patrickhulce** [comment]
Adding another example here. Color contrast alone takes 30+ seconds on this page.

https://m.check24.de/handytarife/allnet-flat

It looks like every call to `getBackgroundColor` is forcing a layout.

![image](https://user-images.githubusercontent.com/2301202/47119055-160c4980-d22f-11e8-959c-a2544aa434e1.png)


discovered in https://github.com/GoogleChrome/lighthouse/issues/6272

**Comment by marcysutton** [comment]
@patrickhulce `window.getComputedStyle` is needed to evaluate color contrast, and depending on the styles on the page it would definitely cause style recalc/layout. We're hoping to refactor the color contrast utilities at some point, but they have to maintain all of the use cases / edge cases currently detected by the algorithm. I doubt it would ever not cause a layout.

What forces layout / reflow, by Paul Irish: 
- https://gist.github.com/paulirish/5d52fb081b3570c81e3a

**Comment by patrickhulce** [comment]
Sorry I was imprecise before :)

I'm not hoping that color contrast will remove all forced layouts I know that's impossible, I'm just hoping that there's not a separate invalidation + forced layout for every element on the page that there seems to be now. It sounds like you're already well aware of this though and hope to refactor in the manner I'm talking about so sounds great! 👍

**Comment by dylanb** [comment]
Both of those pages are now fast, closing
