### ISSUE TITLE
Automated test VS browser extension

### ISSUE THREAD

**Issue by bjarman** [dequelabs/axe-core#719]
Hi! 

I am comparing the results from my automated test using webdriver.js and the results from the Axe browser extension. Both of which are using the same axe-core version.

I get different results.

In the browser extension I get lots of violations whereas in the automated test I only get a few.

Just wondered if there are any quirks or good to know stuff when using axe-core from within automated tests.

The test I am using for comparison is simply to run axe tests on the whole webpage and listing violations.

Any pointers are appreciated.

/F

**Comment by marcysutton** [comment]
@bjarman thanks for reporting your issue. In order to help you, however, we need more details. Can you provide the exact extension and API versions you're using? We also need a test page to debug. Can you provide us with a remote link or demo project with HTML, CSS and JS included? Thanks.

**Comment by marcysutton** [comment]
Hi @bjarman, please provide the details we've requested so we can help diagnose the problem. Otherwise this issue will be closed for inactivity.
