### ISSUE TITLE
aXe Coconut issue for rule: Elements in the focus order need a role appropriate for interactive content

### ISSUE THREAD

**Issue by MasaoYOMODA** [dequelabs/axe-core#736]
aXe-coconut  
[Learn more](https://dequeuniversity.com/rules/axe/3.0/focus-order-semantics?application=coconut) link 
https://dequeuniversity.com/rules/axe/3.0/focus-order-semantics?application=coconut
is not valid.

Error: The alias "focus-order-semantics" in the folder 15095 is not valid.

**Comment by ScottCooleyDeque** [comment]
The Learn more link is now valid.  https://dequeuniversity.com/rules/axe/3.0/focus-order-semantics?application=coconut
