### ISSUE TITLE
Regarding the Warning with new AXE tool

### ISSUE THREAD

**Issue by ajaybabudevalla** [dequelabs/axe-core#738]
Initially we have run the pnr on firefox version 46.0 with the respective AXE tool add on.In this case the axe tool doesn’t report any accessibility issues or voilations.For your reference you can see the below screenshots.For selectpax page and display pnr page.

With Firefox 57 and latest AXE tool:
[Accessibility_Analysis.docx](https://github.com/dequelabs/axe-core/files/1743143/Accessibility_Analysis.docx)
On the select pax page with the latest axe tool is showing some warnings regarding the color contrast with the new version of firefox.So I downloaded the color contrast analyzer for firefox and performed the color check for foreground and background on the respective texts.The color contrast analyzer is passing all the warnings.For your reference please see the below screenshots.Please confirm whether these warnings are to be considered or not.

**Comment by WilcoFiers** [comment]
I don't see the problem here. Axe shows 0 violations, which you've confirmed, and 15 items that needed to be manually reviewed, which you've done.
