### ISSUE TITLE
Chrome Extension Unable to Connect

### ISSUE THREAD

**Issue by thejamespower** [dequelabs/axe-core#746]
Receiving the following error when using the Chrome extension: 
```
Error: Could not establish connection. Receiving end does not exist.
```

Assume this is because Axe is trying to connect to an external server and I am running this on a locked down corporate network. Is there a way to add proxy configuration to the extension?

**Comment by marcysutton** [comment]
That's not the issue–it is a known bug with the extension that requires you to restart the devtools and refresh the page.

**Comment by dylanb** [comment]
@dreadnl1 are you getting this on an incognito page or `file:// url`? If so, go to the `chrome://extensions` page and give the extension permission to work in those contexts.

**Comment by dreadnl1** [comment]
@dylanb that worked--thanks a lot!

**Comment by thejamespower** [comment]
I followed your suggestion @dylanb and I am now receiving the following error: 
`Error: Invocation of form runtime.connect(null, ) doesn't match definition runtime.connect(optional string extensionId, optional object connectInfo)`

I am trying to run the tool through localhost.

**Comment by thejamespower** [comment]
I was able to get this working after rebooting my machine, so seems like a non-issue. Although more helpful error messages would be extremely useful.

**Comment by WilcoFiers** [comment]
We'll absolutely sort that out. Thanks for letting us know James.
