### ISSUE TITLE
false positive: input type="button" with @title only

### ISSUE THREAD

**Issue by jasonkiss** [dequelabs/axe-core#747]
`<input type="button" title="Search">` currently fails the "Buttons must have discernible text" test, but the `title` attribute is a permitted source for programmatically calculating the element's accessible name, as per the [HTML-AAM](https://w3c.github.io/html-aam/#input-type-button-input-type-submit-and-input-type-reset).

**Comment by marcysutton** [comment]
I wonder if it was written that way for historical reasons, since `title` wasn't always exposed. In any case, we have a similar issue open for messaging (#765) and will look into a fix.
