### ISSUE TITLE
Drop devDependencies that are in .retireignore.json

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#778]
Axe-core uses a number of packages that with low security risk according to retireJS as devDependencies. We should either upgrade those, or replace them like we recently did when we upgraded JSHint to ESLint.

**Comment by straker** [comment]
Github might have replaced the need for reitre.js with security alerts

**Comment by straker** [comment]
@jeankaplansky no docs needed
@padmavemulapati dev task
