### ISSUE TITLE
Issue when using axe API to get selector of an element

### ISSUE THREAD

**Issue by iamrafan** [dequelabs/axe-core#788]
On this url https://support.microsoft.com/en-us/help/12428/microsoft-account-security-info-and-security-codes , get an element using ```document.querySelector("#uhf-c-nav > a[href$="lang "]")``` and try to get the selector of the same element using axe-core API, it will return this ```#uhf-c-nav > a[href$='lang%20'] ```

**Comment by marcysutton** [comment]
Seems like we should trim href values to remove unescaped spaces.
