### ISSUE TITLE
Add a reading level best practice rule

### ISSUE THREAD

**Issue by dylanb** [dequelabs/axe-core#790]
Flesh-Kincaid formula is documented on this page https://readable.io/content/the-flesch-reading-ease-and-flesch-kincaid-grade-level/

We should aim for a reading level of grade 8 by default.

**Comment by marcysutton** [comment]
@dylanb can you write this in the rules format? https://github.com/dequelabs/axe-core/blob/develop/doc/rule-proposal.md

**Comment by isner** [comment]
Is Flesch-Kincaid an industry standard for accessibility? It's heavily biased toward a writing style that favors short sentences (and small words, which is more justifiable). These qualities don't always produce content that is more easily readable. It's a purely mathematical parsing of language, which is highly suspect, in my opinion.

I say this realizing that there might not be a more linguistically driven formula for calculating the readability of a text, so I'm ok with using it in the absence of a better alternative. This seems like a domain into which machine learning should have made some inroads by now.

**Comment by dylanb** [comment]
There is also the Gunning-Fog index https://readable.io/content/the-gunning-fog-index/
The Coleman-Liau Index https://readable.io/content/the-coleman-liau-index/
The SMOG index https://en.wikipedia.org/wiki/SMOG

Open to suggestions as I am not an expert in this area

**Comment by WilcoFiers** [comment]
The problem with this is that this only works well for English. Seeing as this hasn't been looked at in over a year, I think it's fair to say we're not going to do this. We can revisit this if it ever comes up again. I think the first thing to consider for that is if axe-core is the right tool to report something like this.
