### ISSUE TITLE
Make a command-line utility for new rule creation

### ISSUE THREAD

**Issue by marcysutton** [dequelabs/axe-core#806]
After watching folks struggle with our build system at the hackathon for creating new rules, I thought it would be incredibly useful to create a CLI for rule boilerplate stuff. What if you had a prompt to supply rule and check names, evaluate functions, optional matches functions and so on, and it created the files for you including tests? That seems like something we could do, and it would make it easier for all of us to create new rules. It's a very manual process right now, and automating is more in line with how we want to work.

I know we might not get to this right away but I wanted to jot it down for someone to pick up at some point.

**Comment by WilcoFiers** [comment]
Agreed. It would also help if we simplified some of this work.

**Comment by straker** [comment]
Closed via #1240
