### ISSUE TITLE
Add "setup" / "teardown" methods for checks

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#808]
We've got a couple of rules coming up the need to do setup work before it can run, such as zooming, and hover/focus contrast. This requires us to have a way to execute a method before we test the individual elements. This should only run if the selector / matches finds elements.

**Comment by dylanb** [comment]
Isn't this sort of function very dependent on the check? Why do we need a separate function, can this not simply be done in the check?

**Comment by WilcoFiers** [comment]
So for example, if I want to write a rule that checks if elements break their container after the page is zoomed. I need to do a few things:

1. Adjust `document.body.style.zoom` so that it simulates a page width of 400px
2. Run all my evaluate functions to see if any of the content elements overlap, or if they got clipped
3. Restore `document.body.style.zoom`

We shouldn't do step one more than once, since that is terribly unperformant. We also need to make sure the execution order is correct. While this is happening, axe-core can't be kicking off other checks. There is currently no guarantee that things get executed in the correct order.

**Comment by dylanb** [comment]
Ok, so this would execute once before all checks run for that rule?

Problem with the `before` name is that we already have an `after` which has nothing to do with this. I suggest `setup` and `teardown`.
