### ISSUE TITLE
Perhaps throw error/warning when `include` context selector doesn't match anything

### ISSUE THREAD

**Issue by jasonkarns** [dequelabs/axe-core#81]
This is clearly up to the maintainers (as the behavior is rather subjective), but in the process of working on the matcher gem, I found it odd that invoking `a11yCheck({include: "#nonExistant"})` doesn't throw an error when `#nonExistant` doesn't exist.

Perhaps it's not worth throwing an error, as the 'error state' can be derived by checking if *both* `violations` and `passes` are empty in the results? I'm not familiar enough with the underlying functionality to know if there are other instances where `violations` and `passes` would both be empty that *doesn't* indicate a no-match scenario.

Thoughts?

**Comment by dylanb** [comment]
We want this argument to allow users to only analyze content they are targeting. Throwing an exception would require users to handle that exception case even when they legitimately expect some of the pages being analyze to not have any content.

I think it would be better to return some indicator that the include matched nothing. This means you only have to write code if you want to handle this case.

**Comment by jasonkarns** [comment]
I should clarify that, since the a11yCheck is async, it shouldn't actually throw an exception, but the callback should take an error param. This would be very similar to what's happening now in that the callback still gets executed (so less custom code for handling the 'error' case).

**Comment by jasonkarns** [comment]
Since the callback doesn't yet seem to provide an error parameter, this would probably be dependent on #83

**Comment by dylanb** [comment]
I agree, we should implement the error as the first parameter - however this would be an API breaking change. Need to think about solutions here.

**Comment by WilcoFiers** [comment]
We have a version of this working in the internal repo. This was a bit more tricky than it looked initially as we needed to collect results from frames, which comes in asynchronously. We will have this feature available for the next major release of Axe-core.
