### ISSUE TITLE
New rule: focused-element-visible

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#810]
# focused-element-visible

Focused elements must be visible

Ensure that when elements have focus they are visible

**Tags:** experimental, wcag247, wcag2aa 

## Matcher

Any focusable element

### element-obscured (none)

By checking getElementsFromPoint, Needs review if the node is obscured by another opaque element

### element-off-screen (none)

Needs review if the element is off screen

### element-clipped (none)

Needs review if the element is hidden due to clipping

### element-no-size (none)

Needs review if the element is hidden because it has 0 width or 0 height

**Comment by dylanb** [comment]
I would vote for off screen elements being violations. What is the thought process for needs review?

**Comment by WilcoFiers** [comment]
Lots of things actually. Skiplinks for example, or menus. Deque.com for instance has a menu that is positioned off screen and becomes visible when its focused. I'm guessing because that way it still shows in the link list?
