### ISSUE TITLE
New rule: not-nesting-elements-in-the-focus-order

### ISSUE THREAD

**Issue by kurosawa-takeshi** [dequelabs/axe-core#813]
# not-nesting-elements-in-the-focus-order

Every descendant of elements in the focus order must not in the focus order.

Ensure that elements in the focus order don't have descendants in the focus order.

**Tags:** experimental, wcag2a, wcag212, cat.keyboard

Sometimes web pages nest `button` element inside `a` element. The problem with this kind of nesting is that the keyboard focus can't be moved away from those elements in some conditions.

For example, following snippet is a keyboard trap in Firefox.

```html
<a href="#">
  <div>
    <button type="button">a button in a link</button>
  </div>
</a>
```

Surprisingly (or not surprisingly), Facebook's Share button has this issue.

- [Share button generator](https://developers.facebook.com/docs/plugins/share-button?locale=en_US)
- [Share button](https://www.facebook.com/v2.12/plugins/share_button.php?app_id=113869198637480&channel=https%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter%2Fr%2FFdM1l_dpErI.js%3Fversion%3D42%23cb%3Df34c62ec420a752%26domain%3Ddevelopers.facebook.com%26origin%3Dhttps%253A%252F%252Fdevelopers.facebook.com%252Ffa02febafd09c6%26relation%3Dparent.parent&container_width=734&href=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&layout=button_count&locale=en_US&mobile_iframe=true&sdk=joey)

Although, following snippet isn't a keyboard trap in Firefox, nesting elements in the focus order is a bad practice in general.

```html
<a href="#">
  <button type="button">a button in link</button>
</a>
```

## Selector

Focusable elements which can have descendants (a[href], summary, button, [tabindex])

### Matcher

An element is in the focus order.

Pseudo code:

```js
function isInFocusOrder(candidate) {
	// disabled or hidden element can't receive the focus even if it has tabindex attribute
	if (axe.commons.dom.focusDisabled(candidate)) {
		return false;
	}

	// tabindex takes precedence of native focusability
	if (el.hasAttribute('tabindex')) {
		var tabindex = parseInt(el.getAttribute('tabindex'), 10);
		// node with tabindex >= 0 is in focus order even if the node isn't natively focusable
		// node with tabindex < 0 is not in focus order even if the node is natively focusable
		return (!isNaN(tabindex) && tabindex >= 0);
	}

	return axe.commons.dom.isNativelyFocusable(candidate));
}
```

### no-descendants-in-the-focus-order (none)

1. Every descendant of a given node must not in the focus order

Pseudo code:

```js
// returning true is error
// Note: Sync with axe.commons.dom.isNativelyFocusable when it is updated.
// Note: Exclude <area> from axe.commons.dom.isNativelyFocusable as its position in the focus order is different from other elements.
// TODO: Use aXe APIs and ES5
const candidates = node.querySelectorAll("a[href], input, textarea, select, summary, button, [tabindex]");
return candidates.some((candidate) => {
	return isInFocusOrder(candidate);
});
```

## Possible false positives

The position of `area` element in the focus order is different from other elements. The position is calculated from the position of `img` element instead of `area` element ([Chrome has an exception](https://bugs.chromium.org/p/chromium/issues/detail?id=447289)). Following is legal although it looks unnatural.

```html
<img src="" alt="Map" usemap="#map">
<div tabindex="0">
  <map id="map" name="map">
   <area href="#" alt="Headquarter" shape="rect" coords="0 0 50 50">
  </map>
  <p>...</p>
</div>
```

Note: Above pseudo code of "no-descendants-in-the-focus-order" excludes `area` element from querySelectorAll.

## Further work

Checking [restrictions of ARIA in HTML (disallowing `<span role="link">` inside `<span role="link">`)](https://github.com/w3c/html-aria/issues/54) would help developers though I believe that should be another rule.

**Comment by WilcoFiers** [comment]
I don't think nested tabindex elements in itself is a bad thing. For instance for scrollable regions it's fine to have them contain focusable elements. I think what this rule should be about is not allowing nested widget roles, which is what https://github.com/dequelabs/axe-core/issues/601 is designed to address. Please continue any discussion there. I'm closing this as a duplicate.
