### ISSUE TITLE
Caption files embedded inside the media wrapper should not fail

### ISSUE THREAD

**Issue by johnfoliot** [dequelabs/axe-core#816]
Currently it appears that aXe-core is only looking for the presence of the <track> element to deliver caption files, but there is a second method of doing so: place the h.265 encoded video and the AAC encoded audio AND the Vtt/TTML file all inside of the media wrapper (traditionally either .mp4 or .mkv files). 

There is an existing API that "looks inside" the wrapper when being rendered onscreen, which looks for those files to deliver the captioning. Ideally, aXe-core would use a similar method to detect whether the time-stamped file is bundled inside of the media wrapper, as a second test (after checking for the presence of <track> as it does today)

**Comment by marcysutton** [comment]
@johnfoliot what is this "existing API" – do you have any examples or references? Can we even look inside of those media wrappers with client-side Javascript? 

Also IIRC that rule is marked as "needs review", and can be marked as "not an issue". Not that it solves y/our use case, but it does explain why we don't mark it as a clear violation (it's too hard to tell for certain).

**Comment by johnfoliot** [comment]
I believe what you seek can be found here: www.w3.org/TR/media-source.

> This specification was designed with the following goals in mind:
> - Allow JavaScript to construct media streams independent of how the media is fetched.

At this point, it is operating a a level higher than my tech skills allow, but if the right info you seek isn't there, let me know and I can reach out to some folks who may have a clearer indication.

**Comment by WilcoFiers** [comment]
@johnfoliot Do you have any cases where we've seen this get used?

**Comment by WilcoFiers** [comment]
As for the false positive, I believe you're right. It looks like both for caption and description we make it needs review if there are no track elements at all, and we fail it if there are track elements but none of them are description (or caption). Given how many ways there are to provide a caption / description, this probably should never fail. At best we can tell that we couldn't figure out where you put it.

**Comment by johnfoliot** [comment]
Wilco, sorry i didn't see your questions earlier...

Is this of any use?
https://www.w3.org/TR/2011/WD-html5-20110113/video.html#sourcing-in-band-text-tracks

**Comment by WilcoFiers** [comment]
Thanks John. I think we've got it covered :)
