### ISSUE TITLE
False positive: Angular hasbang links are being treated as in-page anchor links

### ISSUE THREAD

**Issue by ackleyk** [dequelabs/axe-core#824]
The new aXe plugin for Chrome displays a violation that says “the skip-link target should exist and be focusable” for any Angular links with a hashbang. I am proposing that Angular hashbang links should be excluded. 

The false positive can be tested on the Angular bootstrap page: 
https://ng-bootstrap.github.io/#/getting-started

**Element source**
<a class="navbar-brand" href="#/">ng-bootstrap</a>

**Issue description**
Ensure all skip links have a focusable target

Note: this issue occurs within HTML_CodeSniffer as well and it is one of the main reasons our team  moved away from CodeSniffer and started using aXe.

**Comment by WilcoFiers** [comment]
Fair point. Thanks for reporting!

**Comment by englishextra** [comment]
@WilcoFiers And...?

How am I gonna deal with that?

It's not only Angular - it's a hashrouting thing. 
having a href = #/home  can aXe be able to recognize that as routing stuff and not bookmark of existing block in the markup?

**Comment by WilcoFiers** [comment]
@englishextra Both have been addressed. We're finishing up a few more things for a new release. Should be out within the next week or two.

**Comment by englishextra** [comment]
@WilcoFiers Very nice thanks

**Comment by ackleyk** [comment]
Thank you for fixing this issue so quickly!
