### ISSUE TITLE
false positive for checkbox and radio group label rules

### ISSUE THREAD

**Issue by dylanb** [dequelabs/axe-core#834]
On this page

https://www.lightningdesignsystem.com/components/data-tables/

The groups have an `<h3>` as a group name. We could detect this and pass it if:

All inputs in the group are between two headings with no other widgets between those same headings

**Comment by WilcoFiers** [comment]
That doesn't work when you're in JAWS's forms mode, does it?

**Comment by devarshipant** [comment]
Are you referring to heading containers (Variants etc.)? If so, JAWS 18 and NVDA do not associate heading (also a button and a group label) with the first radio button.

<img width="773" alt="variants heading" src="https://user-images.githubusercontent.com/7377040/38567235-323256e4-3cd5-11e8-84b0-f453cf1163d9.PNG">

**Comment by dylanb** [comment]
ok, I agree, closing
