### ISSUE TITLE
Unable to axe analyze

### ISSUE THREAD

**Issue by ppandian-7494** [dequelabs/axe-core#841]
getting error
Error: [object Object]

**Comment by marcysutton** [comment]
Sorry, this is not enough details for us to debug your issue. Please read the instructions in the issue template and open a new one.

**Comment by ppandian-liaison-intl** [comment]
Hi 
I am using chrome extension axe. 
When I analyze a web page I get an error
Error: [object Object]

What are the additional information you might need to investigate further.

Thanks
Pushpa

**Comment by WilcoFiers** [comment]
https://github.com/dequelabs/axe-core/blob/develop/.github/ISSUE_TEMPLATE.md
