### ISSUE TITLE
Chrome extension does not work with local html files

### ISSUE THREAD

**Issue by josehilera** [dequelabs/axe-core#843]
The aXe extension for Chrome does not work with local html files. But the same extension for Firefox works very well with local files. Please review the Chrome version.

An example testing a file named "Google.html" with Firefox extension (ok):
![withfirefox](https://user-images.githubusercontent.com/13155126/38729505-7b24d576-3f13-11e8-9aa9-4f096d22796d.JPG)

An example testing the same file named "Google.html" with Chrome (error):
![withchrome](https://user-images.githubusercontent.com/13155126/38729506-7b3e3034-3f13-11e8-9547-aa52a9f96c3d.JPG)

**Comment by WilcoFiers** [comment]
Hi @josehilera There is no official support for testing local files today. I would recommend you use a local server if you need to test files on your machine. I'm going to close the issue here since it is not directly related to axe-core. We have an issue open internally to track this issue.

**Comment by josehilera** [comment]
Thanks.

**Comment by marcysutton** [comment]
Perhaps we could look into better error-handling for this? You can enable local files with chrome://extensions. There might be some way to detect if a URL is local and show a different message.
