### ISSUE TITLE
When injected into a page, the axe script can override other anonymous modules loaded via requireJS

### ISSUE THREAD

**Issue by noead01** [dequelabs/axe-core#849]
I am using AXE.java to inject the axe script into the pages during execution of my selenium automated tests.

The script seems to have a side effect on the application javascript code, and when accessing certain functions of my application, I see:

<pre><code>
Error: Mismatched anonymous define() module: function ()
{"use strict”; return axe}
</code></pre>

This seems to be linked to the fact that because the script is injected, the required module should not be anonymous. If I change axe.js to name the injected module as per:
<pre><code>
  if (typeof define === 'function' && define.amd) {
      define('axe', [], function() {
      'use strict';
      return axe;
    });
  }
</code></pre>

Then everything works as expected.

<pre><code>
axe-core version: 2.6.1
browser: chrome (all versions)
</code></pre>

**Comment by WilcoFiers** [comment]
This seems to be a problem in `lib/core/index.js`. Would you like to put in a PR for this?

**Comment by noead01** [comment]
Yes, please
