### ISSUE TITLE
Error Error: [object Object]

### ISSUE THREAD

**Issue by camerontok715** [dequelabs/axe-core#860]
error reported as soon as I clicked analyze

Error: [object Object]

- Link to live demo:

<pre><code>
axe-core version: X.Y.Z
axe-webdriver, extension or other integration version: X.Y.Z

Browser and Assistive Technology versions

For Tooling issues:
- Node version: XX  
- Platform:  
</code></pre>

**Comment by WilcoFiers** [comment]
Missing all information to reproduce the issue.

**Comment by WilcoFiers** [comment]
Have a look here: https://github.com/dequelabs/axe-core/issues/885

**Comment by atdiff** [comment]
Thanks @WilcoFiers. Just had to refresh the page.
