### ISSUE TITLE
Skip links and landmark regions

### ISSUE THREAD

**Issue by digitala11y** [dequelabs/axe-core#863]
Ensures all content is contained within a landmark region
 <html lang="en-US" prefix="og: http://ogp.me/ns#">
 URL:https://www.digitala11y.com

Lang attribute cannot  be wrapped inside a landmark region.

**Comment by marcysutton** [comment]
Have a look at the related nodes. Those are the elements that aXe is saying should be wrapped in a landmark region. In this case they're skip links, which we've talked about making exempt.

**Comment by WilcoFiers** [comment]
Our skiplink ignore part of this rule should account for multiple skip links in a page. I think that's the fix here.
