### ISSUE TITLE
Create a list of unsupported ARIA features

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#868]
Right now its pretty difficult to figure out what is and isn't supported in axe-core. A first step would be to create a markdown file in `docs` that lists all ARIA roles, attributes and attribute values that aren't supported in axe-core today. Most of those should be ARIA 1.1 features, but I'm not sure if there are any 1.0 features we don't support. We should look into that as well.

One way we could go about creating such a list would be to pull in aria-query and compare it to the list that is in axe-core. That way we can generate it dynamically, and we can get familiar with the aria-query API, which we may want if we switch over to ARIA blacklisting attributes/values in the future (instead of whitelisting them, as we do now).

**Comment by jkodu** [comment]
PR - https://github.com/dequelabs/axe-core/pull/900 addresses this issue.
