### ISSUE TITLE
I can't use about parent.document

### ISSUE THREAD

**Issue by jinkyun** [dequelabs/axe-core#872]
- Link to live demo:

<pre><code>

I can't use in parent.document because isContext function return false;
I want to use about parent.document.

example)
axe.run( parent.document , function(err, results){
        	
 });

axe-core version: 3.0.2
axe-webdriver, extension or other integration version: X.Y.Z

Browser and Assistive Technology versions

For Tooling issues:
- Node version: XX  
- Platform:  
</code></pre>

**Comment by WilcoFiers** [comment]
Thanks for reporting. This is effectively the same issue as #755. Axe-core expects to run in a context that has `document` and `window` globally available. If it doesn't have that, it won't work. This is something I do intend to change at some point, but there is no way to do this today. I suggest that as a workaround you make `document` and `window` available as global variables before you load axe-core. That should solve the issue.

I'm going to close this as a duplicate.
