### ISSUE TITLE
Uses of background video without controls not listed as a concern in Lighthouse report

### ISSUE THREAD

**Issue by jenstrickland** [dequelabs/axe-core#879]
Using Lighthouse, tested two sites with multiple uses of background video without controls and the report didn't mention anything about this. Inspecting the code, it appears it might be possible to set rules for the video element and whether or not controls are hidden or accessible. As a UX designer and front-end dev I am not as savvy about exactly what can be done, but hoped to help by submitting an issue. Happy to help, (bridgingtechnologies dot us and mopro dot com), in whatever way I can. Thanks so much for Lighthouse — I'm a huge fan!

I initially submitted this issue on Lighthouse's github and Paul Irish referred me to submit it here (https://github.com/GoogleChrome/lighthouse/issues/5104#issuecomment-386476204).

**Comment by WilcoFiers** [comment]
Hey Jen. I'm intrigued by the idea, but I'm not entirely sure what to do with this... Video elements without controls aren't in themselves inaccessible. There is also the possibility of the video having custom controls, which would be pretty difficult to detect. Do you have any suggestion of what we might be able to test for this?

**Comment by WilcoFiers** [comment]
Closing the ticket because of inactivity

**Comment by jenstrickland** [comment]
Sorry, I didn’t see the original email asking for ideas. 

I thought it might be possible to rest if there is a background video, as there are tests for background images, and treat them similarly. For background images, the test prompts to ensure legibility is sufficient. For video, the same concerns exist, plus the consideration for those with vestibular and cognitive issues, so providing information about that seems reasonable.
