### ISSUE TITLE
Chrome Browser extension - "Analyze" button - Error: [object Object]

### ISSUE THREAD

**Issue by chai-jay** [dequelabs/axe-core#885]
Using the current latest download of aXe Chrome Browser extension version and encountering these issues:

- Clicking on Analyze button yields "An error occurred" with "Error details" field showing: `Error: [object Object]`. 
- Clicking on the "i" info icon shows "fetching..." indefinitely.

Debugging the Chrome extension frame with Chrome Dev Tools shows both actions above outputs into the console an error object with `message` property with value `"Could not establish connection. Receiving end does not exist."`

```
OS: Windows 10 Enterprise Version 1709 Build 16299.334 64-bit
Chrome Browser version: Version 66.0.3359.139 (Official Build) (64-bit)
Chrome Extension aXe version: 3.3.0
axe-core version: 3.0.0
axe-webdriver, extension or other integration version: 3.3.0
```

- Link to live demo: Tested on some local HTML files and a dummy HTML file with `<html><head></head><body>Testing</body></html>` in Chrome browser.

**Comment by WilcoFiers** [comment]
This is commonly caused by the extension not loading entirely. Make sure the page is refreshed with the devtools panel closed. If that doesn't work, you may want to just remove it and reinstall.

**Comment by chai-jay** [comment]
@WilcoFiers I tried the following but issue still persists:

1. Wait for loading
    - Closing Chrome Dev Tools completely
    - Refresh page
    - Wait 10 second after HTML is loaded
    - Open Chrome Dev Tools (defaults to Elements pane)
    - Wait 10 seconds
    - Open "aXe" panel
    - Wait 10 seconds
    - Click on "i" info icon (Shows "fetching..." indefinitely)
    - Click on "Analyze" button (Shows error)

2. Reinstall the Chrome extension
    - Remove aXe Chrome extension
    - Close all Chrome browser windows/tabs
    - Reopen Chrome browser tabs
    - Install aXe Chrome extension from Chrome Web Store
    - Refresh the HTML file in browser
    - Repeat steps in 1

I just tried to use the Chrome extension on my Mac's Chrome and it worked on the first try. However, after I refresh the page (with the aXe Dev Tools panel open) and click on the Analyze/the "i" info icon again, I encounter the same issue again. 

To rule out network issues, I will try again later tonight when I'm not inside my work's network.

**Comment by chai-jay** [comment]
Yes I am. Just doing it on local files.

**Comment by WilcoFiers** [comment]
Ahh. In that case, go to chrome://extensions, find the extension and click "details" There's an "Allow access to file URLs" option there that you need to enable.

**Comment by chai-jay** [comment]
That fixed the issue for me. Thanks!
