### ISSUE TITLE
Support usage of fallback ARIA roles

### ISSUE THREAD

**Issue by iamrafan** [dequelabs/axe-core#887]
Allow using multiple space separated valid tokens on ```role``` attribute (https://www.w3.org/TR/core-aam-1.1/#mapping_role)

<pre><code>axe-core version: 3.0.0-beta.3
axe-Coconut version: 3.3.0-beta.0
</code></pre>

**Comment by WilcoFiers** [comment]
There is a ticket open for this already, #724. We likely won't be supporting this for some time now, given that the latest version of JAWS does not support this. I'm closing this issue as a duplicate.
