### ISSUE TITLE
:before & :after psuedo-element support for commons.text.accessibleText

### ISSUE THREAD

**Issue by dsturley** [dequelabs/axe-core#90]

**Comment by marcysutton** [comment]
This would be an expensive calculation. Perhaps we could try to put it in an experimental rule?

For the scenario where an element is about to be flagged for missing accessible text, we'd already have a node in mind so we could do an extra step of checking for content in `:before:` and `:after`.

Something like this:
```
var text = window.getComputedStyle(
	node, ':before'
)
```

**Comment by WilcoFiers** [comment]
I'm going to close this. For the time being, `:before` and `:after` content is not included in the accessible names in IE. As long as axe-core targets IE, we're going to leave it out of the accessible name computation.
