### ISSUE TITLE
Error occuring with details [object Object]

### ISSUE THREAD

**Issue by JoshingYou1** [dequelabs/axe-core#909]
Whenever I try to use analyze my code using aXe on a local file (file:///), I keep running into this error message: 

An error occurred

Please try again. If the error persists, pleasereport the issue  to Deque Systems

Error Details:

Error: [object Object]

I've tried refreshing the page multiple times and running aXe after about 15 seconds, but to no avail.

I saw a post similar to this and someone said go to the details section of the extension and enable the option: "Allow access to file URLs". However, I cannot find the "details" link anywhere. Any help would be greatly appreciated.

**Comment by iamrafan** [comment]
Go to chrome://extensions/?id=iobddmbdndbbbfjopjdgadphaoihpojp and enable the "Allow access to file URLs" toggle 
![image](https://user-images.githubusercontent.com/22068434/40454541-0d78c186-5e9e-11e8-8d9c-10432bd64fe5.png)

**Comment by JoshingYou1** [comment]
Thank you! This fixed it!
