### ISSUE TITLE
ARIA 1.1 States and Properties

### ISSUE THREAD

**Issue by dsturley** [dequelabs/axe-core#91]
We currently support all ARIA 1.1 roles; but we may have missed some of the new states and properties.

**Comment by dsturley** [comment]
## New Attributes
aria-modal
http://www.w3.org/TR/wai-aria-1.1/#aria-modal

aria-placeholder
http://www.w3.org/TR/wai-aria-1.1/#aria-placeholder

aria-colcount
http://www.w3.org/TR/wai-aria-1.1/#aria-colcount

aria-colindex
http://www.w3.org/TR/wai-aria-1.1/#aria-colindex

aria-colspan
http://www.w3.org/TR/wai-aria-1.1/#aria-colspan

aria-rowcount
http://www.w3.org/TR/wai-aria-1.1/#aria-rowcount

aria-rowspan
http://www.w3.org/TR/wai-aria-1.1/#aria-rowspan

aria-describedat
http://www.w3.org/TR/wai-aria-1.1/#aria-describedat

aria-current
http://www.w3.org/TR/wai-aria-1.1/#aria-current

### Check the change log
http://www.w3.org/TR/wai-aria-1.1/#h-changelog

**Comment by marcysutton** [comment]
The more current list was written out in https://github.com/dequelabs/axe-core/issues/350.
