### ISSUE TITLE
Document how to override DqElement

### ISSUE THREAD

**Issue by dylanb** [dequelabs/axe-core#93]

**Comment by dsturley** [comment]
Do we actually want to document it?  Assumption would be if we document it, we would need to support it.  I'd rather leave this as an edge-case; allow it to be overridden but not explicitly support it.

**Comment by dylanb** [comment]
If we are allowing this - and in particular if it starts to get used, we will de-facto have to support it. Perhaps the way we do this is to document how to override all of the utils. WDYT?

**Comment by dylanb** [comment]
This has been implemented in the new plugin architecture documentation
