### ISSUE TITLE
axe.d.ts should use `boolean` form, not `Boolean`

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [dequelabs/axe-core#938]
Minor nitpick: `Boolean` implies it was created like `new Boolean(true)`, whereas `boolean` is just the literal primitive. It doesn't make much of a difference in user land but it is a bit unusual.

**Comment by jkodu** [comment]
PR - https://github.com/dequelabs/axe-core/pull/939#pullrequestreview-126040475
