### ISSUE TITLE
Getting an error message when trying to use aXe

### ISSUE THREAD

**Issue by sarahhufstetler** [dequelabs/axe-core#940]
Getting the following error message when selecting "Analyze" button in aXe. This occurs on any page I try.

Steps to reproduce:

1. Log into any website (ie. www.google.com)
2. Right click page: Inspect Element
3. Open aXe
4. Select "Analyze" button

Current Result:  Getting error message (see screenshot)

When selecting the 'Error Details' link, getting the following:
Error: [object Object]

Expected Result: Should be able to use aXe

![screen shot 2018-06-05 at 11 45 27 am](https://user-images.githubusercontent.com/39961556/40987371-5a042a28-68b6-11e8-9798-b99ef953ab8c.png)

**Comment by jkodu** [comment]
@sarahhufstetler 
Thanks for raising this. Will be in touch as soon as a patch is in place.

**Comment by WilcoFiers** [comment]
In the mean time. It sometimes helps to restart the browser. :)

**Comment by isner** [comment]
@sarahhufstetler If you close the devtools panel, refresh the page, and reopen the devtools panel does this issue resolve itself? Knowing this will help us troubleshoot.

At the moment, we suspect this error only occurs when the devtools panel is remains open while the extension is installed, updated, or refreshed. If this isn't consistent with your experience, please let us know!

**Comment by sarahhufstetler** [comment]
Yes,

Actually it resolves itself if I just close the browser completely and re-open the browser and then aXe.

**Comment by jkodu** [comment]
@sarahhufstetler 
A newer version of axe extension has been released which handles this scenario & provides better user feedback and experience. Please update the extension (https://chrome.google.com/webstore/detail/axe/lhdoppojpmngadmnindnejefpokejbdd)
