### ISSUE TITLE
Refactor: To accommodate namespace for tagName determination (PR#1219)

### ISSUE THREAD

**Issue by jkodu** [dequelabs/axe-core#942]
Based on discussion:
- https://github.com/dequelabs/axe-core/pull/623#discussion_r159419441

**Comment by jkodu** [comment]
@WilcoFiers 
I have gone through this, and need your opinion before any work is done.

See comment put in description. It looks like in some places we use `node.tagName` and other `node.nodeName`. Further, in some places it is `toLowerCase()`, whilst others are `toUpperCase()`.

Question based on the discussion though, there seems to agreement on 2 things.

1) Implement a new `getTagName` function which returns preferably an `uppercased` string, also considering `namespace` eg: `HTML:ARTICLE` or `SVG:A` based on the usage of the node.

2) We simply just walk away from `node.tagName` usage to `node.nodeName.toUpperCase()`

Which route would you like to go with this?

**Comment by jkodu** [comment]
@WilcoFiers - assigning this to you, to get above Q answered.

**Comment by WilcoFiers** [comment]
We should always use `node.nodeName.toUpperCase()`.

**Comment by jkodu** [comment]
PR Merged. Closing issue.
