### ISSUE TITLE
Disable color-contrast check when aria-disabled=true

### ISSUE THREAD

**Issue by dsturley** [dequelabs/axe-core#95]
Needs confirmation that aria-disabled=true satisifies the WCAG 1.4.3 requirement

**Comment by dylanb** [comment]
Dave, as long as it is not used on an element supported by the "disabled" attribute, and as long as that element has a widget role, this attribute is sufficient for the WCAG 1.4.3 requirement

**Comment by dsturley** [comment]
@dylanb What about readonly?

**Comment by dylanb** [comment]
When working on this issue, look at the above pull request and close it if the issues raised in the pull request have not been addressed. If they have been addressed, please use the PR as a basis for completing this issue.

**Comment by WilcoFiers** [comment]
Issue has been resolved for the next release.
