### ISSUE TITLE
`utils.matchesSelector()` failing on page where the Element prototype has been modified

### ISSUE THREAD

**Issue by zkf** [dequelabs/axe-core#953]
While testing https://educationaboveall.org/, I encountered an at first mysterious error. I am running axe-core in a headless browser (Chromium, using axe-webdriverjs). The tests would not complete before the configured script timeout. This error is reported in the browser log: `Uncaught (in promise) TypeError: node[method] is not a function at Object.matchesSelector`.

On this particular page, the `Element.prototype` has been modified. But `utils.matchesSelector()` depends on the Element prototype in order to function. Hence the error.

I appreciate that this is likely to be a problem that arises at few Web pages; after all, messing with the prototypes of built-in objects is usually a bad idea.

I’ve created a small patch which fixes the issue. It modifies `matchesSelector()` to look for the method directly on a supplied node instead of the Element prototype. I hope it is okay to do it this way. AFAICT, `grunt test` reports no new test failures after applying this change.

```patch
diff --git a/lib/core/utils/element-matches.js b/lib/core/utils/element-matches.js                                                                
index 432109cf..2e56877d 100644
--- a/lib/core/utils/element-matches.js
+++ b/lib/core/utils/element-matches.js
@@ -9,10 +9,9 @@ axe.utils.matchesSelector = (function () {

        var method;

-       function getMethod(win) {
+       function getMethod(node) {

                var index, candidate,
-                       elProto = win.Element.prototype,
                        candidates = [
                                'matches',
                                'matchesSelector',
@@ -24,7 +23,7 @@ axe.utils.matchesSelector = (function () {

                for (index = 0; index < length; index++) {
                        candidate = candidates[index];
-                       if (elProto[candidate]) {
+                       if (node[candidate]) {
                                return candidate;
                        }
                }
@@ -34,7 +33,7 @@ axe.utils.matchesSelector = (function () {
        return function (node, selector) {

                if (!method || !node[method]) {
-                       method = getMethod(node.ownerDocument.defaultView);
+                       method = getMethod(node);
                }

                return node[method](selector);
```

**Comment by WilcoFiers** [comment]
Well you're just asking for trouble! ;-) Patch looks fine to me, can  you put it in a PR so we can give proper credit?

**Comment by zkf** [comment]
Okay, I’ll send you the PR next week.
