### ISSUE TITLE
Extension hangs up

### ISSUE THREAD

**Issue by dylanb** [dequelabs/axe-core#954]
If you try to analyze this URL https://html5-sandbox.glitch.me/ with the Chrome extension, it just hangs. According to @AutoSponge this is due to a missing `allow-scripts` option

<pre><code>
axe-webdriver, extension or other integration version: 3.3.0
Mac OS X
</code></pre>

**Comment by jkodu** [comment]
Soma, has confirmed that this issue does not exist in the latest version of axe extension. 

Excerpt from email thread:
<blockquote>
Not reproducible this issue on latest axe chrome extension 3.5.0.
</blockquote>

![gitbug_954](https://user-images.githubusercontent.com/20978252/45422120-345ab480-b687-11e8-9ce4-82b73cbba4a7.PNG)

Closing the issue.
