### ISSUE TITLE
Recursive function with no exit

### ISSUE THREAD

**Issue by DavidMacDonald** [dequelabs/axe-core#959]
Using Axe Core with  Axe Selenium JAVA crawled this page
https://www.ascensiadiabetes.ca/products/contour-next/

Caused the process to hang. Other pages on the site were fine with the same test. 

Stepping through the process found us in a recursive function called injectIntoFrames 

![image](https://user-images.githubusercontent.com/2365411/41682516-eead2cec-74a5-11e8-9062-9d2aae127f85.png)

WIN 10
Eclipse Oxygen
Selenium Chrome Driver 3.12.0
Axe Selenium 2.0
Axe Core 2.6.1
Chrome (latest) both headless and regular

**Note**: manual test with the browser plugin (axe-devtools 3.4.0-alpha 2 with axe-core 3.0.3) had no problem with the page.

**Comment by marcysutton** [comment]
@DavidMacDonald this issue should be opened in the [axe-selenium-java](https://github.com/dequelabs/axe-selenium-java) repository, as it is specific to that project and that's where the fix will go. The Java integration code is doing the injecting into iframes, not axe-core itself. Similarly, the browser extensions and axe-webdriverjs do their own injecting into iframes–not axe-core.

**Comment by stephenmathieson** [comment]
@marcysutton IIRC that's not the correct repository. It's severely behind what has been published to Maven and is lacking vital features.

**Comment by marcysutton** [comment]
@stephenmathieson that's something we'll have to sort out internally, but given our impending move to Github I believe that will still be the correct repository for the issue.

**Comment by dylanb** [comment]
@stephenmathieson beware - the two repositories are completely different things

The current Bitbucket one is not open source and is not supposed to be free. It is supposed to only be published to Agora, not Maven.

The current Github one is free and open source and can be published to Maven. We need to find a way to manage the name clash in our move to Github
