### ISSUE TITLE
getFlattenedTree can crash with <slot> elements without shadowDOM support

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#965]
https://github.com/dequelabs/axe-core/blob/f13ad3651d2ebee10625e4c8299791f020d9430a/lib/core/utils/flattened-tree.js#L92-L98

Line 93 here throws in Firefox, because `assignedNodes` isn't defined here. I think L92 should check that that function exists and otherwise just move on. @dylanb WDYT?

**Comment by dylanb** [comment]
@WilcoFiers Do you have an example of a page that fails on FF? I would like to validate that what FF is doing is correct before building in this workaround.

**Comment by WilcoFiers** [comment]
This probably crashes on everything except Chrome. Updating the name.
