### ISSUE TITLE
Incorrect typings for `axe.RunOnly`

### ISSUE THREAD

**Issue by stephenmathieson** [dequelabs/axe-core#972]
The TS definitions for `axe.RunOnly` are incorrect. As suggested by [axe-core.org](https://www.axe-core.org/docs/#options-parameter), the `runOnly` option should have a property `values` which is an Array of rule IDs. However, in the TS definition, [`RunOnly`](https://github.com/dequelabs/axe-core/blob/v3.0.3/axe.d.ts#L28) is either an Array of `TagValue`s or a `RunOnlyObject` (which has properties `include` and `exclude`, making it look like it belongs to `ElementContext`, not `RunOnly`).

It looks like these definitions are built by hand, so if you're all on-board, I'd  be happy to fix it.

**Comment by dylanb** [comment]
yep, it should always be an `Array` of `String`s which are either tags or rule IDs

**Comment by jkodu** [comment]
PR - https://github.com/dequelabs/axe-core/pull/973

**Comment by marcysutton** [comment]
Shouldn't the issue stay open until the PR is merged?
