### ISSUE TITLE
Incorrect typings for `Check.evaluate` and `Check.after`

### ISSUE THREAD

**Issue by stephenmathieson** [dequelabs/axe-core#974]
When we pass custom "checks" into `axe-core`, they're expected to be strings, not functions. [In `createExecutionContext`, we explicitly support casting strings (via `eval`) to a function](https://github.com/dequelabs/axe-core/blob/v3.0.3/lib/core/base/check.js#L6).

However, the [TypeScript definition](https://github.com/dequelabs/axe-core/blob/v3.0.3/axe.d.ts#L86) suggests only functions are allowed.

I do not know if _both_ functions and strings are supported. If they are, adding a type union (`evaluate: Function | string`) should work. If they're not supported, then replacing `Function` with `string` will solve this.

**Comment by WilcoFiers** [comment]
@stephenmathieson Yes, this can be either a function or a string, so your suggestion sounds correct. Please put in a PR to fix it.
