### ISSUE TITLE
Validate axe.d.ts type definitions

### ISSUE THREAD

**Issue by jkodu** [dequelabs/axe-core#979]
To verify if the current `d.ts` interfaces are correct

**Comment by marcysutton** [comment]
Have you seen the Typescript definition tests? These should probably be run as part of the automated test suite: https://github.com/dequelabs/axe-core/blob/develop/CONTRIBUTING.md#using-axe-with-typescript

**Comment by jkodu** [comment]
@marcysutton - thanks for the heads up. I will have a look.
