### ISSUE TITLE
Set up tests to regularly run with nightly builds

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core#980]
A problem we had a little while ago is that Chrome introduced a change to getElementsFromPoint, which caused Axe to crash. This was only picked up when that browser was released. We should set up regular testing with canary/nightly versions of browsers so that we can catch these things before they become a problem.

**Comment by WilcoFiers** [comment]
We can do this when we have Karma set up for testing, see #1805.

**Comment by straker** [comment]
Confirmed that this is working https://app.circleci.com/pipelines/github/dequelabs/axe-core/1646/workflows/57f6376f-a577-4dc1-b74d-e4281f92752a/jobs/26520
