### ISSUE TITLE
Add rule to check if the `<label>`'s `for` attribute has an associated field?

### ISSUE THREAD

**Issue by joelhsmith** [dequelabs/axe-core#987]
Can we check if the `<label>`'s `for` attribute has an associated field?

Example of label with no associated form field:
https://jhc36-duke-edu.github.io/a11y-fails/a11y-fail-label-for-attr.html

In the wild, I saw `<label>`s being used as main menu items.

I know there is already a rule checking if a form element has a label, but it does not catch this scenario because it is not meant to. 

Proposed rule:

1. If `<label>` has no `<input>` or `<button>` inside it
2. and If `<label>`'s `for` attribute is not associated with a field
Fail

Chrome version 67.0.3396.87 running aXe extension version3.4.0.2

**Comment by AutoSponge** [comment]
Other tools detect this (e.g., [HTML_Codesniffer](https://squizlabs.github.io/HTML_CodeSniffer/Standards/WCAG2/1_3_1#ensuring-label-targets-exist-in-the-document)) but it's not rooted in any WCAG violations ([old thread](https://webaim.org/discussion/mail_thread?thread=5448)).

**Comment by joelhsmith** [comment]
Fair enough :-)
