### ISSUE TITLE
Ensures all elements with a role attribute use a valid value  Impact: critical(Axe audit fails)

### ISSUE THREAD

**Issue by sripalreddyadamala** [dequelabs/axe-core#995]
Hi all,
                Hi All,
I am using ngx popover in my application and I am getting above role="popover" as critical error when I run audit reports with axe and google accessibility. This attribute is generated dynamically from 
 ng x bootstrap popover content.  I am just  @curious is this an issue with axe audit findings or this is something should handled by bootstrap team.

Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap:1.8.1
Angular:4.0.0
ngx-popover:0.0.16

![image](https://user-images.githubusercontent.com/17653691/42456673-7aa082b4-8363-11e8-93b5-407c62a6e834.png)

**Comment by WilcoFiers** [comment]
Howdy! Thanks for the report. This is definitely a bug in the application. "popover" is not a valid role, and so it will be ignored by the browser and by assistive technologies:
https://www.w3.org/TR/wai-aria-1.1/#role_definitions

I suggest reaching out to the author and ask them to update this to something appropriate. (Not sure what, missing a little too much context to make a recommendation.)
