### ISSUE TITLE
Reorganise axe rule description page

### ISSUE THREAD

**Issue by Wildebrew** [dequelabs/axe-core#998]
The [aXe 3.0 list of rules support page](https://dequeuniversity.com/rules/axe/3.0/) needs better organization and context.

1. There is no way to tell rules that produce violations from rules that are experimental/best practice or need manual verification.
`<html>` elementn without a `lang` attrbute is always a violation whereas [using bold elements to create headings](https://dequeuniversity.com/rules/axe/3.0/p-as-heading) is an experimental rule. The only way to tell the difference is to read the rule documentation.

2. Related rules should be grouped together into logical categories rather than simply listed alphabetically.

- Link to live demo:

<pre><code>
axe-core version: X.Y.Z
axe-webdriver, extension or other integration version: X.Y.Z

Browser and Assistive Technology versions

For Tooling issues:
- Node version: XX  
- Platform:  
</code></pre>

**Comment by WilcoFiers** [comment]
Good idea Birkir. Maybe we can have something like the following table instead:
https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md

We could see about updating this table to include links and to include if rules return incomplete, that'd be a worthwhile addition IMO.

**Comment by marcysutton** [comment]
I'm hearing that page wasn't intended to be used by the general public. @Wildebrew how did you happen to find that one–by modifying the URL to show the whole list?

**Comment by Wildebrew** [comment]
@Wilco, I like where you are going with this idea.
I think the table needs a separate rule type column that states
"violation" or "best practice". indicating best practice rules using
tags is not sufficient in my opinion.
The impact column is not a reliable indicator since best practice
rules can have serious impact.



@marcy I got the link from one of my Deque contacts in response to an
inquiry about Attest. My understanding was that the page was public. I
don't see why it shouldn't be public, but that's not my call.




On 7/16/18, Marcy Sutton <notifications@github.com> wrote:
> I'm hearing that page wasn't intended to be used by the general public.
> @Wildebrew how did you happen to find that one–by modifying the URL to show
> the whole list?
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/dequelabs/axe-core/issues/998#issuecomment-405402964


-- 
Work hard. Have fun. Make history.
